// Слова корзины заказа.
//
// 🔒 ВСЕ 82 ЯЗЫКА (решение владельца 2026-08-11). Сначала я написал два и
// рассуждал так: корзина — возможность магазина, а сайт услуг или портфолио на
// этом же стартере её удалит. Признак оказался не тот. Решает не «кому она
// нужна», а ГДЕ ОНА ЖИВЁТ: значок заказа стоит в ШАПКЕ, на каждой странице,
// рядом с ящиком аккаунта, у которого 82 языка. Владелец включает французский —
// заголовки слоёв заговорят сами, а корзина рядом осталась бы английской. Это
// читается как поломка, а не как решение.
//
// Правило, выведенное отсюда: удалить лишнее — разовое действие того, кому оно
// не нужно; молчащий на новом языке элемент шапки бьёт по всем, кто язык включил.

export type CartUi = {
  /** Значок в шапке. */
  open: string
  title: string
  empty: string
  /** Строка подтверждения: `{name}`. */
  confirmAdd: string
  confirmAddNote: string
  yes: string
  cancel: string
  added: string
  /** Кнопка в строке таблицы. */
  addToCart: string
  increase: string
  decrease: string
  remove: string
  quantity: string
  total: string
  checkout: string
  reset: string
  resetConfirm: string
  /** Тост оформления — заголовок и мелкая подпись. */
  checkoutToast: string
  checkoutNote: string
  toAdminPanel: string
}

const UI: Record<string, CartUi> = {
  en: { open: "Order cart", title: "Your order", empty: "The cart is empty. Add a product from the catalogue.", confirmAdd: "Add {name} to the order?", confirmAddNote: "You can change the quantity or remove it in the cart at any time.", yes: "Add", cancel: "Cancel", added: "Added to the order", addToCart: "Add to order", increase: "One more", decrease: "One fewer", remove: "Remove from order", quantity: "Quantity", total: "Total", checkout: "Place the order", reset: "Clear the order", resetConfirm: "Remove everything from the order?", checkoutToast: "Next you would go to checkout", checkoutNote: "Not implemented in this demo. Take the project to your own machine and build the checkout you need with AI.", toAdminPanel: "Open the control panel" },
  fr: { open: "Panier de commande", title: "Votre commande", empty: "Le panier est vide. Ajoutez un produit depuis le catalogue.", confirmAdd: "Ajouter {name} à la commande ?", confirmAddNote: "Vous pourrez modifier la quantité ou le retirer dans le panier à tout moment.", yes: "Ajouter", cancel: "Annuler", added: "Ajouté à la commande", addToCart: "Ajouter à la commande", increase: "Un de plus", decrease: "Un de moins", remove: "Retirer de la commande", quantity: "Quantité", total: "Total", checkout: "Passer la commande", reset: "Vider la commande", resetConfirm: "Tout retirer de la commande ?", checkoutToast: "Vous passeriez ensuite à la validation", checkoutNote: "Non implémenté dans cette démo. Reprenez le projet sur votre machine et construisez la validation dont vous avez besoin avec l’IA.", toAdminPanel: "Ouvrir le panneau de contrôle" },
  es: { open: "Carrito del pedido", title: "Su pedido", empty: "El carrito está vacío. Añada un producto del catálogo.", confirmAdd: "¿Añadir {name} al pedido?", confirmAddNote: "Podrá cambiar la cantidad o quitarlo del carrito en cualquier momento.", yes: "Añadir", cancel: "Cancelar", added: "Añadido al pedido", addToCart: "Añadir al pedido", increase: "Uno más", decrease: "Uno menos", remove: "Quitar del pedido", quantity: "Cantidad", total: "Total", checkout: "Realizar el pedido", reset: "Vaciar el pedido", resetConfirm: "¿Quitar todo del pedido?", checkoutToast: "A continuación pasaría a la confirmación", checkoutNote: "No implementado en esta demostración. Lleve el proyecto a su máquina y construya con IA la confirmación que necesite.", toAdminPanel: "Abrir el panel de control" },
  pt: { open: "Carrinho do pedido", title: "Seu pedido", empty: "O carrinho está vazio. Adicione um produto do catálogo.", confirmAdd: "Adicionar {name} ao pedido?", confirmAddNote: "Você pode mudar a quantidade ou remover no carrinho a qualquer momento.", yes: "Adicionar", cancel: "Cancelar", added: "Adicionado ao pedido", addToCart: "Adicionar ao pedido", increase: "Mais um", decrease: "Menos um", remove: "Remover do pedido", quantity: "Quantidade", total: "Total", checkout: "Fazer o pedido", reset: "Limpar o pedido", resetConfirm: "Remover tudo do pedido?", checkoutToast: "Em seguida você iria para a finalização", checkoutNote: "Não implementado nesta demonstração. Leve o projeto para a sua máquina e construa a finalização que precisar com IA.", toAdminPanel: "Abrir o painel de controle" },
  de: { open: "Bestellkorb", title: "Ihre Bestellung", empty: "Der Korb ist leer. Fügen Sie ein Produkt aus dem Katalog hinzu.", confirmAdd: "{name} zur Bestellung hinzufügen?", confirmAddNote: "Menge lässt sich jederzeit im Korb ändern oder das Produkt entfernen.", yes: "Hinzufügen", cancel: "Abbrechen", added: "Zur Bestellung hinzugefügt", addToCart: "Zur Bestellung", increase: "Eins mehr", decrease: "Eins weniger", remove: "Aus der Bestellung entfernen", quantity: "Menge", total: "Summe", checkout: "Bestellung aufgeben", reset: "Bestellung leeren", resetConfirm: "Alles aus der Bestellung entfernen?", checkoutToast: "Als Nächstes ginge es zur Kasse", checkoutNote: "In dieser Demo nicht umgesetzt. Holen Sie das Projekt auf Ihren Rechner und bauen Sie die Kasse mit KI so, wie Sie sie brauchen.", toAdminPanel: "Steuerungspanel öffnen" },
  it: { open: "Carrello dell’ordine", title: "Il tuo ordine", empty: "Il carrello è vuoto. Aggiungi un prodotto dal catalogo.", confirmAdd: "Aggiungere {name} all’ordine?", confirmAddNote: "Potrai cambiare la quantità o rimuoverlo dal carrello in qualsiasi momento.", yes: "Aggiungi", cancel: "Annulla", added: "Aggiunto all’ordine", addToCart: "Aggiungi all’ordine", increase: "Uno in più", decrease: "Uno in meno", remove: "Rimuovi dall’ordine", quantity: "Quantità", total: "Totale", checkout: "Effettua l’ordine", reset: "Svuota l’ordine", resetConfirm: "Rimuovere tutto dall’ordine?", checkoutToast: "Poi passeresti alla conferma", checkoutNote: "Non implementato in questa demo. Porta il progetto sulla tua macchina e costruisci con l’IA la conferma che ti serve.", toAdminPanel: "Apri il pannello di controllo" },
  nl: { open: "Winkelmandje", title: "Uw bestelling", empty: "Het mandje is leeg. Voeg een product uit de catalogus toe.", confirmAdd: "{name} aan de bestelling toevoegen?", confirmAddNote: "U kunt het aantal wijzigen of het artikel later uit het mandje halen.", yes: "Toevoegen", cancel: "Annuleren", added: "Toegevoegd aan de bestelling", addToCart: "Aan bestelling toevoegen", increase: "Eén meer", decrease: "Eén minder", remove: "Uit de bestelling halen", quantity: "Aantal", total: "Totaal", checkout: "Bestelling plaatsen", reset: "Bestelling wissen", resetConfirm: "Alles uit de bestelling verwijderen?", checkoutToast: "Hierna zou u afrekenen", checkoutNote: "Niet gebouwd in deze demo. Neem het project mee naar uw eigen machine en bouw het afrekenen met AI zoals u het nodig hebt.", toAdminPanel: "Bedieningspaneel openen" },
  sv: { open: "Beställningskorg", title: "Din beställning", empty: "Korgen är tom. Lägg till en produkt från katalogen.", confirmAdd: "Lägga {name} i beställningen?", confirmAddNote: "Du kan ändra antalet eller ta bort produkten i korgen när som helst.", yes: "Lägg till", cancel: "Avbryt", added: "Tillagd i beställningen", addToCart: "Lägg i beställningen", increase: "En till", decrease: "En färre", remove: "Ta bort från beställningen", quantity: "Antal", total: "Summa", checkout: "Lägg beställningen", reset: "Töm beställningen", resetConfirm: "Ta bort allt ur beställningen?", checkoutToast: "Härnäst skulle du gå till kassan", checkoutNote: "Inte byggt i den här demon. Ta projektet till din egen maskin och bygg kassan du behöver med AI.", toAdminPanel: "Öppna kontrollpanelen" },
  no: { open: "Bestillingskurv", title: "Din bestilling", empty: "Kurven er tom. Legg til et produkt fra katalogen.", confirmAdd: "Legge {name} i bestillingen?", confirmAddNote: "Du kan endre antallet eller fjerne produktet i kurven når som helst.", yes: "Legg til", cancel: "Avbryt", added: "Lagt i bestillingen", addToCart: "Legg i bestillingen", increase: "Én til", decrease: "Én færre", remove: "Fjern fra bestillingen", quantity: "Antall", total: "Sum", checkout: "Legg inn bestillingen", reset: "Tøm bestillingen", resetConfirm: "Fjerne alt fra bestillingen?", checkoutToast: "Deretter ville du gå til kassen", checkoutNote: "Ikke bygget i denne demoen. Ta prosjektet til din egen maskin og bygg kassen du trenger med KI.", toAdminPanel: "Åpne kontrollpanelet" },
  da: { open: "Bestillingskurv", title: "Din bestilling", empty: "Kurven er tom. Tilføj et produkt fra kataloget.", confirmAdd: "Læg {name} i bestillingen?", confirmAddNote: "Du kan ændre antallet eller fjerne varen i kurven når som helst.", yes: "Tilføj", cancel: "Annullér", added: "Lagt i bestillingen", addToCart: "Læg i bestillingen", increase: "Én mere", decrease: "Én færre", remove: "Fjern fra bestillingen", quantity: "Antal", total: "I alt", checkout: "Afgiv bestillingen", reset: "Tøm bestillingen", resetConfirm: "Fjern alt fra bestillingen?", checkoutToast: "Derefter ville du gå til kassen", checkoutNote: "Ikke bygget i denne demo. Tag projektet med på din egen maskine og byg den kasse, du har brug for, med AI.", toAdminPanel: "Åbn kontrolpanelet" },
  fi: { open: "Tilauskori", title: "Tilauksesi", empty: "Kori on tyhjä. Lisää tuote luettelosta.", confirmAdd: "Lisätäänkö {name} tilaukseen?", confirmAddNote: "Voit muuttaa määrää tai poistaa tuotteen korista milloin tahansa.", yes: "Lisää", cancel: "Peruuta", added: "Lisätty tilaukseen", addToCart: "Lisää tilaukseen", increase: "Yksi lisää", decrease: "Yksi vähemmän", remove: "Poista tilauksesta", quantity: "Määrä", total: "Yhteensä", checkout: "Tee tilaus", reset: "Tyhjennä tilaus", resetConfirm: "Poistetaanko kaikki tilauksesta?", checkoutToast: "Seuraavaksi siirtyisit kassalle", checkoutNote: "Ei toteutettu tässä esittelyssä. Vie projekti omalle koneellesi ja rakenna tarvitsemasi kassa tekoälyn avulla.", toAdminPanel: "Avaa hallintapaneeli" },
  is: { open: "Pöntunarkarfa", title: "Pöntunin þín", empty: "Karfan er tóm. Bættu vöru við úr vörulistanum.", confirmAdd: "Bæta {name} við pöntunina?", confirmAddNote: "Þú getur breytt fjöldanum eða fjarlægt vöruna í körfunni hvenær sem er.", yes: "Bæta við", cancel: "Hætta við", added: "Bætt við pöntunina", addToCart: "Bæta í pöntun", increase: "Einum fleira", decrease: "Einum færra", remove: "Fjarlægja úr pöntun", quantity: "Fjöldi", total: "Samtals", checkout: "Ganga frá pöntun", reset: "Tæma pöntunina", resetConfirm: "Fjarlægja allt úr pöntuninni?", checkoutToast: "Næst færirðu í greiðslu", checkoutNote: "Ekki útfært í þessari sýningu. Taktu verkefnið á þína eigin vél og smíðaðu greiðsluferlið sem þú þarft með gervigreind.", toAdminPanel: "Opna stjórnborðið" },
  el: { open: "Καλάθι παραγγελίας", title: "Η παραγγελία σας", empty: "Το καλάθι είναι άδειο. Προσθέστε ένα προϊόν από τον κατάλογο.", confirmAdd: "Προσθήκη {name} στην παραγγελία;", confirmAddNote: "Μπορείτε να αλλάξετε την ποσότητα ή να το αφαιρέσετε από το καλάθι ανά πάσα στιγμή.", yes: "Προσθήκη", cancel: "Άκυρο", added: "Προστέθηκε στην παραγγελία", addToCart: "Προσθήκη στην παραγγελία", increase: "Ένα ακόμη", decrease: "Ένα λιγότερο", remove: "Αφαίρεση από την παραγγελία", quantity: "Ποσότητα", total: "Σύνολο", checkout: "Υποβολή παραγγελίας", reset: "Εκκαθάριση παραγγελίας", resetConfirm: "Αφαίρεση όλων από την παραγγελία;", checkoutToast: "Στη συνέχεια θα πηγαίνατε στην ολοκλήρωση", checkoutNote: "Δεν υλοποιήθηκε σε αυτήν την επίδειξη. Πάρτε το έργο στον υπολογιστή σας και φτιάξτε την ολοκλήρωση που χρειάζεστε με τεχνητή νοημοσύνη.", toAdminPanel: "Άνοιγμα πίνακα ελέγχου" },
  pl: { open: "Koszyk zamówienia", title: "Twoje zamówienie", empty: "Koszyk jest pusty. Dodaj produkt z katalogu.", confirmAdd: "Dodać {name} do zamówienia?", confirmAddNote: "Ilość możesz zmienić, a produkt usunąć w koszyku w każdej chwili.", yes: "Dodaj", cancel: "Anuluj", added: "Dodano do zamówienia", addToCart: "Dodaj do zamówienia", increase: "O jeden więcej", decrease: "O jeden mniej", remove: "Usuń z zamówienia", quantity: "Ilość", total: "Razem", checkout: "Złóż zamówienie", reset: "Wyczyść zamówienie", resetConfirm: "Usunąć wszystko z zamówienia?", checkoutToast: "Następnie przeszedłbyś do finalizacji", checkoutNote: "Nie zaimplementowano w tej wersji demonstracyjnej. Zabierz projekt na własny komputer i zbuduj potrzebną finalizację z pomocą SI.", toAdminPanel: "Otwórz panel sterowania" },
  cs: { open: "Košík objednávky", title: "Vaše objednávka", empty: "Košík je prázdný. Přidejte produkt z katalogu.", confirmAdd: "Přidat {name} do objednávky?", confirmAddNote: "Množství můžete kdykoli změnit a produkt z košíku odebrat.", yes: "Přidat", cancel: "Zrušit", added: "Přidáno do objednávky", addToCart: "Přidat do objednávky", increase: "O jeden více", decrease: "O jeden méně", remove: "Odebrat z objednávky", quantity: "Množství", total: "Celkem", checkout: "Odeslat objednávku", reset: "Vyprázdnit objednávku", resetConfirm: "Odebrat z objednávky vše?", checkoutToast: "Dál byste pokračovali k pokladně", checkoutNote: "V této ukázce neimplementováno. Vezměte projekt na svůj počítač a postavte si potřebnou pokladnu pomocí AI.", toAdminPanel: "Otevřít ovládací panel" },
  sk: { open: "Košík objednávky", title: "Vaša objednávka", empty: "Košík je prázdny. Pridajte produkt z katalógu.", confirmAdd: "Pridať {name} do objednávky?", confirmAddNote: "Množstvo môžete kedykoľvek zmeniť a produkt z košíka odobrať.", yes: "Pridať", cancel: "Zrušiť", added: "Pridané do objednávky", addToCart: "Pridať do objednávky", increase: "O jeden viac", decrease: "O jeden menej", remove: "Odobrať z objednávky", quantity: "Množstvo", total: "Spolu", checkout: "Odoslať objednávku", reset: "Vyprázdniť objednávku", resetConfirm: "Odobrať z objednávky všetko?", checkoutToast: "Ďalej by ste pokračovali k pokladni", checkoutNote: "V tejto ukážke neimplementované. Vezmite projekt na svoj počítač a postavte si potrebnú pokladňu pomocou AI.", toAdminPanel: "Otvoriť ovládací panel" },
  hu: { open: "Rendelési kosár", title: "Az Ön rendelése", empty: "A kosár üres. Adjon hozzá terméket a katalógusból.", confirmAdd: "Hozzáadja a(z) {name} terméket a rendeléshez?", confirmAddNote: "A mennyiséget bármikor módosíthatja, a terméket a kosárból eltávolíthatja.", yes: "Hozzáadás", cancel: "Mégse", added: "Hozzáadva a rendeléshez", addToCart: "Rendeléshez ad", increase: "Eggyel több", decrease: "Eggyel kevesebb", remove: "Eltávolítás a rendelésből", quantity: "Mennyiség", total: "Összesen", checkout: "Rendelés leadása", reset: "Rendelés ürítése", resetConfirm: "Eltávolít mindent a rendelésből?", checkoutToast: "Ezután a pénztárhoz jutna", checkoutNote: "Ebben a bemutatóban nincs megvalósítva. Vigye a projektet a saját gépére, és építse meg a szükséges pénztárat MI segítségével.", toAdminPanel: "Vezérlőpult megnyitása" },
  ro: { open: "Coșul comenzii", title: "Comanda dumneavoastră", empty: "Coșul este gol. Adăugați un produs din catalog.", confirmAdd: "Adăugați {name} în comandă?", confirmAddNote: "Puteți schimba cantitatea sau elimina produsul din coș oricând.", yes: "Adaugă", cancel: "Anulează", added: "Adăugat în comandă", addToCart: "Adaugă în comandă", increase: "Unul în plus", decrease: "Unul în minus", remove: "Elimină din comandă", quantity: "Cantitate", total: "Total", checkout: "Plasează comanda", reset: "Golește comanda", resetConfirm: "Eliminați tot din comandă?", checkoutToast: "În continuare ați merge la finalizare", checkoutNote: "Neimplementat în această demonstrație. Luați proiectul pe propria mașină și construiți finalizarea de care aveți nevoie cu ajutorul IA.", toAdminPanel: "Deschide panoul de control" },
  hr: { open: "Košarica narudžbe", title: "Vaša narudžba", empty: "Košarica je prazna. Dodajte proizvod iz kataloga.", confirmAdd: "Dodati {name} u narudžbu?", confirmAddNote: "Količinu možete promijeniti, a proizvod ukloniti iz košarice u svakom trenutku.", yes: "Dodaj", cancel: "Odustani", added: "Dodano u narudžbu", addToCart: "Dodaj u narudžbu", increase: "Jedan više", decrease: "Jedan manje", remove: "Ukloni iz narudžbe", quantity: "Količina", total: "Ukupno", checkout: "Pošalji narudžbu", reset: "Isprazni narudžbu", resetConfirm: "Ukloniti sve iz narudžbe?", checkoutToast: "Zatim biste prešli na plaćanje", checkoutNote: "Nije izvedeno u ovoj demonstraciji. Prenesite projekt na svoje računalo i izgradite potrebno plaćanje uz pomoć UI.", toAdminPanel: "Otvori upravljačku ploču" },
  sl: { open: "Košarica naročila", title: "Vaše naročilo", empty: "Košarica je prazna. Dodajte izdelek iz kataloga.", confirmAdd: "Dodam {name} v naročilo?", confirmAddNote: "Količino lahko kadar koli spremenite, izdelek pa odstranite iz košarice.", yes: "Dodaj", cancel: "Prekliči", added: "Dodano v naročilo", addToCart: "Dodaj v naročilo", increase: "Enega več", decrease: "Enega manj", remove: "Odstrani iz naročila", quantity: "Količina", total: "Skupaj", checkout: "Oddaj naročilo", reset: "Izprazni naročilo", resetConfirm: "Odstranim vse iz naročila?", checkoutToast: "Nato bi šli na zaključek nakupa", checkoutNote: "V tej predstavitvi ni izvedeno. Vzemite projekt na svoj računalnik in z UI zgradite zaključek nakupa, kakršnega potrebujete.", toAdminPanel: "Odpri nadzorno ploščo" },
  et: { open: "Tellimuskorv", title: "Teie tellimus", empty: "Korv on tühi. Lisage toode kataloogist.", confirmAdd: "Kas lisada {name} tellimusse?", confirmAddNote: "Kogust saab igal ajal muuta ja toote korvist eemaldada.", yes: "Lisa", cancel: "Loobu", added: "Lisatud tellimusse", addToCart: "Lisa tellimusse", increase: "Üks rohkem", decrease: "Üks vähem", remove: "Eemalda tellimusest", quantity: "Kogus", total: "Kokku", checkout: "Esita tellimus", reset: "Tühjenda tellimus", resetConfirm: "Kas eemaldada tellimusest kõik?", checkoutToast: "Järgmisena läheksite kassasse", checkoutNote: "Selles näidises pole teostatud. Võtke projekt oma masinasse ja ehitage vajalik kassa tehisintellekti abil.", toAdminPanel: "Ava juhtpaneel" },
  lv: { open: "Pasūtījuma grozs", title: "Jūsu pasūtījums", empty: "Grozs ir tukšs. Pievienojiet preci no kataloga.", confirmAdd: "Pievienot {name} pasūtījumam?", confirmAddNote: "Daudzumu var mainīt un preci no groza izņemt jebkurā brīdī.", yes: "Pievienot", cancel: "Atcelt", added: "Pievienots pasūtījumam", addToCart: "Pievienot pasūtījumam", increase: "Par vienu vairāk", decrease: "Par vienu mazāk", remove: "Izņemt no pasūtījuma", quantity: "Daudzums", total: "Kopā", checkout: "Noformēt pasūtījumu", reset: "Iztukšot pasūtījumu", resetConfirm: "Izņemt no pasūtījuma visu?", checkoutToast: "Tālāk jūs dotos uz apmaksu", checkoutNote: "Šajā demonstrācijā nav realizēts. Paņemiet projektu savā datorā un izveidojiet nepieciešamo apmaksu ar mākslīgā intelekta palīdzību.", toAdminPanel: "Atvērt vadības paneli" },
  lt: { open: "Užsakymo krepšelis", title: "Jūsų užsakymas", empty: "Krepšelis tuščias. Pridėkite prekę iš katalogo.", confirmAdd: "Pridėti {name} į užsakymą?", confirmAddNote: "Kiekį galite pakeisti, o prekę iš krepšelio pašalinti bet kada.", yes: "Pridėti", cancel: "Atšaukti", added: "Pridėta į užsakymą", addToCart: "Pridėti į užsakymą", increase: "Vienu daugiau", decrease: "Vienu mažiau", remove: "Pašalinti iš užsakymo", quantity: "Kiekis", total: "Iš viso", checkout: "Pateikti užsakymą", reset: "Išvalyti užsakymą", resetConfirm: "Pašalinti iš užsakymo viską?", checkoutToast: "Toliau eitumėte į apmokėjimą", checkoutNote: "Šioje demonstracijoje neįgyvendinta. Parsineškite projektą į savo kompiuterį ir su dirbtiniu intelektu sukurkite reikiamą apmokėjimą.", toAdminPanel: "Atverti valdymo skydelį" },
  mt: { open: "Karrettun tal-ordni", title: "L-ordni tiegħek", empty: "Il-karrettun huwa vojt. Żid prodott mill-katalgu.", confirmAdd: "Iżżid {name} mal-ordni?", confirmAddNote: "Tista’ tibdel il-kwantità jew tneħħih mill-karrettun f’kull ħin.", yes: "Żid", cancel: "Ikkanċella", added: "Miżjud mal-ordni", addToCart: "Żid mal-ordni", increase: "Wieħed aktar", decrease: "Wieħed inqas", remove: "Neħħi mill-ordni", quantity: "Kwantità", total: "Total", checkout: "Agħmel l-ordni", reset: "Battal l-ordni", resetConfirm: "Tneħħi kollox mill-ordni?", checkoutToast: "Imbagħad tgħaddi għall-ħlas", checkoutNote: "Mhux implimentat f’din id-dimostrazzjoni. Ħu l-proġett fuq il-magna tiegħek u ibni l-ħlas li teħtieġ bl-IA.", toAdminPanel: "Iftaħ il-pannell tal-kontroll" },
  ca: { open: "Cistella de la comanda", title: "La vostra comanda", empty: "La cistella és buida. Afegiu un producte del catàleg.", confirmAdd: "Voleu afegir {name} a la comanda?", confirmAddNote: "Podreu canviar la quantitat o treure’l de la cistella en qualsevol moment.", yes: "Afegeix", cancel: "Cancel·la", added: "Afegit a la comanda", addToCart: "Afegeix a la comanda", increase: "Un més", decrease: "Un menys", remove: "Treu de la comanda", quantity: "Quantitat", total: "Total", checkout: "Fes la comanda", reset: "Buida la comanda", resetConfirm: "Voleu treure-ho tot de la comanda?", checkoutToast: "Tot seguit passaríeu a la confirmació", checkoutNote: "No implementat en aquesta demostració. Emporteu-vos el projecte a la vostra màquina i construïu amb IA la confirmació que necessiteu.", toAdminPanel: "Obre el tauler de control" },
  gl: { open: "Carriño do pedido", title: "O seu pedido", empty: "O carriño está baleiro. Engada un produto do catálogo.", confirmAdd: "Engadir {name} ao pedido?", confirmAddNote: "Pode cambiar a cantidade ou retiralo do carriño en calquera momento.", yes: "Engadir", cancel: "Cancelar", added: "Engadido ao pedido", addToCart: "Engadir ao pedido", increase: "Un máis", decrease: "Un menos", remove: "Retirar do pedido", quantity: "Cantidade", total: "Total", checkout: "Facer o pedido", reset: "Baleirar o pedido", resetConfirm: "Retirar todo do pedido?", checkoutToast: "A seguir pasaría á confirmación", checkoutNote: "Non implementado nesta demostración. Leve o proxecto á súa máquina e constrúa con IA a confirmación que precise.", toAdminPanel: "Abrir o panel de control" },
  cy: { open: "Basged archeb", title: "Eich archeb", empty: "Mae’r fasged yn wag. Ychwanegwch gynnyrch o’r catalog.", confirmAdd: "Ychwanegu {name} at yr archeb?", confirmAddNote: "Gallwch newid y nifer neu ei dynnu o’r fasged unrhyw bryd.", yes: "Ychwanegu", cancel: "Canslo", added: "Wedi’i ychwanegu at yr archeb", addToCart: "Ychwanegu at yr archeb", increase: "Un yn fwy", decrease: "Un yn llai", remove: "Tynnu o’r archeb", quantity: "Nifer", total: "Cyfanswm", checkout: "Gosod yr archeb", reset: "Clirio’r archeb", resetConfirm: "Tynnu popeth o’r archeb?", checkoutToast: "Nesaf byddech yn mynd i’r ddesg dalu", checkoutNote: "Heb ei adeiladu yn y demo hwn. Ewch â’r prosiect i’ch peiriant eich hun ac adeiladwch y ddesg dalu sydd ei hangen arnoch gyda DA.", toAdminPanel: "Agor y panel rheoli" },
  ga: { open: "Ciseán an ordaithe", title: "D’ordú", empty: "Tá an ciseán folamh. Cuir táirge leis ón gcatalóg.", confirmAdd: "{name} a chur leis an ordú?", confirmAddNote: "Is féidir an méid a athrú nó é a bhaint as an gciseán am ar bith.", yes: "Cuir leis", cancel: "Cealaigh", added: "Curtha leis an ordú", addToCart: "Cuir leis an ordú", increase: "Ceann amháin níos mó", decrease: "Ceann amháin níos lú", remove: "Bain as an ordú", quantity: "Méid", total: "Iomlán", checkout: "Cuir an t-ordú isteach", reset: "Folmhaigh an t-ordú", resetConfirm: "An bhfuil gach rud le baint as an ordú?", checkoutToast: "Ansin rachfá chuig an tseiceáil amach", checkoutNote: "Níl sé curtha i bhfeidhm sa taispeántas seo. Tabhair an tionscadal chuig do ríomhaire féin agus tóg an tseiceáil amach a theastaíonn uait le IS.", toAdminPanel: "Oscail an painéal rialaithe" },
  eu: { open: "Eskariaren saskia", title: "Zure eskaria", empty: "Saskia hutsik dago. Gehitu produktu bat katalogotik.", confirmAdd: "{name} eskariari gehitu?", confirmAddNote: "Kopurua alda dezakezu edo saskitik kendu edozein unetan.", yes: "Gehitu", cancel: "Utzi", added: "Eskariari gehituta", addToCart: "Eskariari gehitu", increase: "Bat gehiago", decrease: "Bat gutxiago", remove: "Kendu eskaritik", quantity: "Kopurua", total: "Guztira", checkout: "Egin eskaria", reset: "Hustu eskaria", resetConfirm: "Dena kendu eskaritik?", checkoutToast: "Ondoren ordainketara joango zinateke", checkoutNote: "Erakusgarri honetan ez dago eginda. Eraman proiektua zure ordenagailura eta eraiki behar duzun ordainketa AAren laguntzaz.", toAdminPanel: "Ireki kontrol panela" },
  ru: { open: "Корзина заказа", title: "Ваш заказ", empty: "Корзина пуста. Добавьте товар из каталога.", confirmAdd: "Добавить «{name}» в заказ?", confirmAddNote: "Количество можно изменить, а товар убрать — в корзине, в любой момент.", yes: "Добавить", cancel: "Отмена", added: "Добавлено в заказ", addToCart: "В заказ", increase: "На один больше", decrease: "На один меньше", remove: "Убрать из заказа", quantity: "Количество", total: "Итого", checkout: "Оформить заказ", reset: "Сбросить весь заказ", resetConfirm: "Убрать из заказа всё?", checkoutToast: "Далее вы переходите к оформлению заказа", checkoutNote: "В демонстрационном режиме это не реализовано. Заберите проект на свою машину и соберите нужное вам оформление с помощью искусственного интеллекта.", toAdminPanel: "Перейти в панель управления" },
  uk: { open: "Кошик замовлення", title: "Ваше замовлення", empty: "Кошик порожній. Додайте товар із каталогу.", confirmAdd: "Додати «{name}» до замовлення?", confirmAddNote: "Кількість можна змінити, а товар прибрати — у кошику, будь-коли.", yes: "Додати", cancel: "Скасувати", added: "Додано до замовлення", addToCart: "До замовлення", increase: "На один більше", decrease: "На один менше", remove: "Прибрати із замовлення", quantity: "Кількість", total: "Разом", checkout: "Оформити замовлення", reset: "Скинути все замовлення", resetConfirm: "Прибрати із замовлення все?", checkoutToast: "Далі ви переходите до оформлення", checkoutNote: "У демонстраційному режимі це не реалізовано. Заберіть проєкт на свою машину й зберіть потрібне вам оформлення за допомогою штучного інтелекту.", toAdminPanel: "Перейти до панелі керування" },
  be: { open: "Кошык замовы", title: "Ваша замова", empty: "Кошык пусты. Дадайце тавар з каталога.", confirmAdd: "Дадаць «{name}» у замову?", confirmAddNote: "Колькасць можна змяніць, а тавар прыбраць — у кошыку, у любы момант.", yes: "Дадаць", cancel: "Скасаваць", added: "Дададзена ў замову", addToCart: "У замову", increase: "На адзін больш", decrease: "На адзін менш", remove: "Прыбраць з замовы", quantity: "Колькасць", total: "Разам", checkout: "Аформіць замову", reset: "Скінуць усю замову", resetConfirm: "Прыбраць з замовы ўсё?", checkoutToast: "Далей вы пераходзіце да афармлення", checkoutNote: "У дэманстрацыйным рэжыме гэта не рэалізавана. Забярыце праект на сваю машыну і збярыце патрэбнае вам афармленне з дапамогай штучнага інтэлекту.", toAdminPanel: "Перайсці ў панэль кіравання" },
  bg: { open: "Количка за поръчка", title: "Вашата поръчка", empty: "Количката е празна. Добавете продукт от каталога.", confirmAdd: "Да се добави ли {name} към поръчката?", confirmAddNote: "Количеството може да се промени, а продуктът да се премахне от количката по всяко време.", yes: "Добави", cancel: "Отказ", added: "Добавено към поръчката", addToCart: "Към поръчката", increase: "С едно повече", decrease: "С едно по-малко", remove: "Премахни от поръчката", quantity: "Количество", total: "Общо", checkout: "Направи поръчката", reset: "Изчисти поръчката", resetConfirm: "Да се премахне ли всичко от поръчката?", checkoutToast: "След това щяхте да преминете към плащане", checkoutNote: "В тази демонстрация не е реализирано. Вземете проекта на своята машина и изградете нужното плащане с помощта на изкуствен интелект.", toAdminPanel: "Отвори контролния панел" },
  sr: { open: "Корпа поруџбине", title: "Ваша поруџбина", empty: "Корпа је празна. Додајте производ из каталога.", confirmAdd: "Додати {name} у поруџбину?", confirmAddNote: "Количину можете променити, а производ уклонити из корпе у сваком тренутку.", yes: "Додај", cancel: "Откажи", added: "Додато у поруџбину", addToCart: "Додај у поруџбину", increase: "Један више", decrease: "Један мање", remove: "Уклони из поруџбине", quantity: "Количина", total: "Укупно", checkout: "Пошаљи поруџбину", reset: "Испразни поруџбину", resetConfirm: "Уклонити све из поруџбине?", checkoutToast: "Затим бисте прешли на плаћање", checkoutNote: "У овој демонстрацији није изведено. Пренесите пројекат на свој рачунар и изградите потребно плаћање уз помоћ вештачке интелигенције.", toAdminPanel: "Отвори управљачку таблу" },
  bs: { open: "Korpa narudžbe", title: "Vaša narudžba", empty: "Korpa je prazna. Dodajte proizvod iz kataloga.", confirmAdd: "Dodati {name} u narudžbu?", confirmAddNote: "Količinu možete promijeniti, a proizvod ukloniti iz korpe u svakom trenutku.", yes: "Dodaj", cancel: "Otkaži", added: "Dodato u narudžbu", addToCart: "Dodaj u narudžbu", increase: "Jedan više", decrease: "Jedan manje", remove: "Ukloni iz narudžbe", quantity: "Količina", total: "Ukupno", checkout: "Pošalji narudžbu", reset: "Isprazni narudžbu", resetConfirm: "Ukloniti sve iz narudžbe?", checkoutToast: "Zatim biste prešli na plaćanje", checkoutNote: "U ovoj demonstraciji nije izvedeno. Prenesite projekat na svoj računar i izgradite potrebno plaćanje uz pomoć vještačke inteligencije.", toAdminPanel: "Otvori upravljačku ploču" },
  mk: { open: "Кошничка за нарачка", title: "Вашата нарачка", empty: "Кошничката е празна. Додајте производ од каталогот.", confirmAdd: "Да се додаде {name} во нарачката?", confirmAddNote: "Количината може да се промени, а производот да се отстрани од кошничката во секое време.", yes: "Додај", cancel: "Откажи", added: "Додадено во нарачката", addToCart: "Додај во нарачката", increase: "Еден повеќе", decrease: "Еден помалку", remove: "Отстрани од нарачката", quantity: "Количина", total: "Вкупно", checkout: "Испрати нарачка", reset: "Испразни ја нарачката", resetConfirm: "Да се отстрани сè од нарачката?", checkoutToast: "Потоа ќе поминевте на плаќање", checkoutNote: "Во оваа демонстрација не е изведено. Земете го проектот на својата машина и изградете го потребното плаќање со помош на вештачка интелигенција.", toAdminPanel: "Отвори го контролниот панел" },
  sq: { open: "Shporta e porosisë", title: "Porosia juaj", empty: "Shporta është bosh. Shtoni një produkt nga katalogu.", confirmAdd: "Të shtohet {name} në porosi?", confirmAddNote: "Sasinë mund ta ndryshoni ose ta hiqni produktin nga shporta në çdo moment.", yes: "Shto", cancel: "Anulo", added: "U shtua në porosi", addToCart: "Shto në porosi", increase: "Një më shumë", decrease: "Një më pak", remove: "Hiq nga porosia", quantity: "Sasia", total: "Gjithsej", checkout: "Bëj porosinë", reset: "Pastro porosinë", resetConfirm: "Të hiqet gjithçka nga porosia?", checkoutToast: "Më pas do të kalonit te pagesa", checkoutNote: "Nuk është realizuar në këtë demonstrim. Merreni projektin në makinën tuaj dhe ndërtoni pagesën që ju nevojitet me IA.", toAdminPanel: "Hap panelin e kontrollit" },
  kk: { open: "Тапсырыс себеті", title: "Сіздің тапсырысыңыз", empty: "Себет бос. Каталогтан тауар қосыңыз.", confirmAdd: "«{name}» тапсырысқа қосылсын ба?", confirmAddNote: "Санын өзгертуге, тауарды себеттен алып тастауға кез келген уақытта болады.", yes: "Қосу", cancel: "Бас тарту", added: "Тапсырысқа қосылды", addToCart: "Тапсырысқа", increase: "Бірге көп", decrease: "Бірге аз", remove: "Тапсырыстан алып тастау", quantity: "Саны", total: "Барлығы", checkout: "Тапсырысты рәсімдеу", reset: "Тапсырысты тазалау", resetConfirm: "Тапсырыстан барлығы алынсын ба?", checkoutToast: "Одан әрі сіз рәсімдеуге өтесіз", checkoutNote: "Демонстрациялық режимде бұл жүзеге асырылмаған. Жобаны өз құрылғыңызға алып, қажет рәсімдеуді жасанды интеллект көмегімен жинаңыз.", toAdminPanel: "Басқару тақтасына өту" },
  uz: { open: "Buyurtma savati", title: "Sizning buyurtmangiz", empty: "Savat bo‘sh. Katalogdan mahsulot qo‘shing.", confirmAdd: "«{name}» buyurtmaga qo‘shilsinmi?", confirmAddNote: "Miqdorni o‘zgartirish va mahsulotni savatdan olib tashlash istalgan vaqtda mumkin.", yes: "Qo‘shish", cancel: "Bekor qilish", added: "Buyurtmaga qo‘shildi", addToCart: "Buyurtmaga", increase: "Bittaga ko‘p", decrease: "Bittaga kam", remove: "Buyurtmadan olib tashlash", quantity: "Miqdor", total: "Jami", checkout: "Buyurtmani rasmiylashtirish", reset: "Buyurtmani tozalash", resetConfirm: "Buyurtmadan hammasi olib tashlansinmi?", checkoutToast: "Keyin siz rasmiylashtirishga o‘tasiz", checkoutNote: "Namoyish rejimida bu amalga oshirilmagan. Loyihani o‘z kompyuteringizga olib, kerakli rasmiylashtirishni sun’iy intellekt yordamida quring.", toAdminPanel: "Boshqaruv paneliga o‘tish" },
  ky: { open: "Заказ себети", title: "Сиздин заказыңыз", empty: "Себет бош. Каталогдон товар кошуңуз.", confirmAdd: "«{name}» заказга кошулсунбу?", confirmAddNote: "Санын өзгөртүүгө, товарды себеттен алып салууга каалаган убакта болот.", yes: "Кошуу", cancel: "Жокко чыгаруу", added: "Заказга кошулду", addToCart: "Заказга", increase: "Бирге көп", decrease: "Бирге аз", remove: "Заказдан алып салуу", quantity: "Саны", total: "Баары", checkout: "Заказды таштоо", reset: "Заказды тазалоо", resetConfirm: "Заказдан баары алынсынбы?", checkoutToast: "Андан ары сиз таштоого өтөсүз", checkoutNote: "Демонстрациялык режимде бул ишке ашырылган эмес. Долбоорду өз машинаңызга алып, керектүү таштоону жасалма интеллекттин жардамы менен куруңуз.", toAdminPanel: "Башкаруу панелине өтүү" },
  tg: { open: "Сабади фармоиш", title: "Фармоиши шумо", empty: "Сабад холӣ аст. Аз феҳрист мол илова кунед.", confirmAdd: "«{name}» ба фармоиш илова шавад?", confirmAddNote: "Миқдорро тағйир додан ва молро аз сабад бардоштан ҳар вақт мумкин аст.", yes: "Илова", cancel: "Бекор", added: "Ба фармоиш илова шуд", addToCart: "Ба фармоиш", increase: "Як зиёдтар", decrease: "Як камтар", remove: "Аз фармоиш бардоштан", quantity: "Миқдор", total: "Ҳамагӣ", checkout: "Фармоиш додан", reset: "Фармоишро тоза кардан", resetConfirm: "Ҳама аз фармоиш бардошта шавад?", checkoutToast: "Сипас шумо ба расмиёт мегузаред", checkoutNote: "Дар реҷаи намоишӣ ин амалӣ нашудааст. Лоиҳаро ба мошини худ баред ва расмиёти лозимиро бо ёрии зеҳни сунъӣ созед.", toAdminPanel: "Ба лавҳаи идора гузаштан" },
  tk: { open: "Sargyt sebedi", title: "Siziň sargydyňyz", empty: "Sebet boş. Katalogdan haryt goşuň.", confirmAdd: "«{name}» sargyda goşulsynmy?", confirmAddNote: "Sanyny üýtgetmek we haryt sebetden aýyrmak islendik wagtda mümkin.", yes: "Goş", cancel: "Ýatyr", added: "Sargyda goşuldy", addToCart: "Sargyda", increase: "Bir köp", decrease: "Bir az", remove: "Sargytdan aýyr", quantity: "Sany", total: "Jemi", checkout: "Sargydy resmileşdir", reset: "Sargydy arassala", resetConfirm: "Sargytdan ählisi aýrylsynmy?", checkoutToast: "Soňra siz resmileşdirmä geçersiňiz", checkoutNote: "Görkeziş tertibinde bu amala aşyrylmady. Taslamany öz enjamyňyza alyň we gerekli resmileşdirmäni emeli aň bilen guruň.", toAdminPanel: "Dolandyryş paneline geç" },
  az: { open: "Sifariş səbəti", title: "Sifarişiniz", empty: "Səbət boşdur. Kataloqdan məhsul əlavə edin.", confirmAdd: "«{name}» sifarişə əlavə olunsun?", confirmAddNote: "Miqdarı dəyişmək və məhsulu səbətdən çıxarmaq istənilən vaxt mümkündür.", yes: "Əlavə et", cancel: "Ləğv et", added: "Sifarişə əlavə edildi", addToCart: "Sifarişə", increase: "Bir çox", decrease: "Bir az", remove: "Sifarişdən çıxar", quantity: "Miqdar", total: "Cəmi", checkout: "Sifarişi rəsmiləşdir", reset: "Sifarişi təmizlə", resetConfirm: "Sifarişdən hər şey çıxarılsın?", checkoutToast: "Sonra rəsmiləşdirməyə keçərdiniz", checkoutNote: "Nümayiş rejimində bu həyata keçirilməyib. Layihəni öz kompüterinizə aparın və lazımi rəsmiləşdirməni süni intellektlə qurun.", toAdminPanel: "İdarəetmə panelinə keç" },
  hy: { open: "Պատվերի զամբյուղ", title: "Ձեր պատվերը", empty: "Զամբյուղը դատարկ է։ Ավելացրեք ապրանք ցանկից։", confirmAdd: "Ավելացնե՞լ «{name}»-ը պատվերին։", confirmAddNote: "Քանակը կարելի է փոխել, իսկ ապրանքը հանել զամբյուղից ցանկացած պահի։", yes: "Ավելացնել", cancel: "Չեղարկել", added: "Ավելացվեց պատվերին", addToCart: "Պատվերին", increase: "Մեկով ավելի", decrease: "Մեկով պակաս", remove: "Հանել պատվերից", quantity: "Քանակ", total: "Ընդամենը", checkout: "Ձևակերպել պատվերը", reset: "Մաքրել պատվերը", resetConfirm: "Հանե՞լ պատվերից ամեն ինչ։", checkoutToast: "Այնուհետև կանցնեիք ձևակերպմանը", checkoutNote: "Ցուցադրական ռեժիմում սա իրականացված չէ։ Վերցրեք նախագիծը ձեր համակարգիչ և արհեստական բանականությամբ կառուցեք ձեզ անհրաժեշտ ձևակերպումը։", toAdminPanel: "Անցնել կառավարման վահանակ" },
  ka: { open: "შეკვეთის კალათა", title: "თქვენი შეკვეთა", empty: "კალათა ცარიელია. დაამატეთ პროდუქტი კატალოგიდან.", confirmAdd: "დაემატოს {name} შეკვეთას?", confirmAddNote: "რაოდენობის შეცვლა და პროდუქტის კალათიდან ამოღება ნებისმიერ დროს შეიძლება.", yes: "დამატება", cancel: "გაუქმება", added: "დაემატა შეკვეთას", addToCart: "შეკვეთაში", increase: "ერთით მეტი", decrease: "ერთით ნაკლები", remove: "შეკვეთიდან ამოღება", quantity: "რაოდენობა", total: "ჯამი", checkout: "შეკვეთის გაფორმება", reset: "შეკვეთის გასუფთავება", resetConfirm: "ამოღებულ იქნას ყველაფერი შეკვეთიდან?", checkoutToast: "შემდეგ გადახვიდოდით გაფორმებაზე", checkoutNote: "სადემონსტრაციო რეჟიმში ეს არ არის რეალიზებული. წაიღეთ პროექტი თქვენს კომპიუტერზე და ხელოვნური ინტელექტით ააგეთ საჭირო გაფორმება.", toAdminPanel: "მართვის პანელზე გადასვლა" },
  mn: { open: "Захиалгын сагс", title: "Таны захиалга", empty: "Сагс хоосон байна. Каталогоос бараа нэмнэ үү.", confirmAdd: "«{name}»-г захиалгад нэмэх үү?", confirmAddNote: "Тоог өөрчлөх, барааг сагснаас хасах нь ямар ч үед боломжтой.", yes: "Нэмэх", cancel: "Цуцлах", added: "Захиалгад нэмэгдлээ", addToCart: "Захиалгад", increase: "Нэгээр илүү", decrease: "Нэгээр бага", remove: "Захиалгаас хасах", quantity: "Тоо", total: "Нийт", checkout: "Захиалга өгөх", reset: "Захиалгыг цэвэрлэх", resetConfirm: "Захиалгаас бүгдийг хасах уу?", checkoutToast: "Дараа нь та захиалга баталгаажуулах руу очно", checkoutNote: "Үзүүлэн горимд үүнийг хийгээгүй. Төслөө өөрийн компьютерт аваад хиймэл оюунаар шаардлагатай баталгаажуулалтаа бүтээгээрэй.", toAdminPanel: "Удирдлагын самбар руу очих" },
  ar: { open: "سلة الطلب", title: "طلبك", empty: "السلة فارغة. أضف منتجًا من الكتالوج.", confirmAdd: "إضافة {name} إلى الطلب؟", confirmAddNote: "يمكنك تغيير الكمية أو إزالته من السلة في أي وقت.", yes: "إضافة", cancel: "إلغاء", added: "أُضيف إلى الطلب", addToCart: "إضافة إلى الطلب", increase: "واحد أكثر", decrease: "واحد أقل", remove: "إزالة من الطلب", quantity: "الكمية", total: "الإجمالي", checkout: "إتمام الطلب", reset: "تفريغ الطلب", resetConfirm: "إزالة كل شيء من الطلب؟", checkoutToast: "بعد ذلك تنتقل إلى إتمام الشراء", checkoutNote: "غير منفَّذ في هذا العرض التوضيحي. خذ المشروع إلى جهازك وابنِ إتمام الشراء الذي تحتاجه بمساعدة الذكاء الاصطناعي.", toAdminPanel: "فتح لوحة التحكم" },
  tr: { open: "Sipariş sepeti", title: "Siparişiniz", empty: "Sepet boş. Katalogdan bir ürün ekleyin.", confirmAdd: "{name} siparişe eklensin mi?", confirmAddNote: "Miktarı değiştirebilir ya da ürünü sepetten istediğiniz zaman çıkarabilirsiniz.", yes: "Ekle", cancel: "Vazgeç", added: "Siparişe eklendi", addToCart: "Siparişe ekle", increase: "Bir fazla", decrease: "Bir az", remove: "Siparişten çıkar", quantity: "Miktar", total: "Toplam", checkout: "Siparişi ver", reset: "Siparişi temizle", resetConfirm: "Siparişten her şey çıkarılsın mı?", checkoutToast: "Ardından ödemeye geçerdiniz", checkoutNote: "Bu tanıtımda uygulanmadı. Projeyi kendi makinenize alın ve ihtiyacınız olan ödeme akışını yapay zekâ ile kurun.", toAdminPanel: "Kontrol paneline git" },
  he: { open: "סל ההזמנה", title: "ההזמנה שלך", empty: "הסל ריק. הוסיפו מוצר מהקטלוג.", confirmAdd: "להוסיף את {name} להזמנה?", confirmAddNote: "אפשר לשנות את הכמות או להסיר את המוצר מהסל בכל רגע.", yes: "הוספה", cancel: "ביטול", added: "נוסף להזמנה", addToCart: "הוספה להזמנה", increase: "אחד יותר", decrease: "אחד פחות", remove: "הסרה מההזמנה", quantity: "כמות", total: "סה\"כ", checkout: "ביצוע ההזמנה", reset: "ניקוי ההזמנה", resetConfirm: "להסיר הכול מההזמנה?", checkoutToast: "בשלב הבא הייתם עוברים לתשלום", checkoutNote: "לא מומש בהדגמה הזו. קחו את הפרויקט למחשב שלכם ובנו את התשלום שאתם צריכים בעזרת בינה מלאכותית.", toAdminPanel: "פתיחת לוח הבקרה" },
  fa: { open: "سبد سفارش", title: "سفارش شما", empty: "سبد خالی است. محصولی از فهرست اضافه کنید.", confirmAdd: "{name} به سفارش افزوده شود؟", confirmAddNote: "تعداد را می‌توانید تغییر دهید و محصول را هر زمان از سبد بردارید.", yes: "افزودن", cancel: "انصراف", added: "به سفارش افزوده شد", addToCart: "افزودن به سفارش", increase: "یکی بیشتر", decrease: "یکی کمتر", remove: "حذف از سفارش", quantity: "تعداد", total: "جمع", checkout: "ثبت سفارش", reset: "پاک کردن سفارش", resetConfirm: "همه‌چیز از سفارش حذف شود؟", checkoutToast: "سپس به مرحله پرداخت می‌رفتید", checkoutNote: "در این نسخه نمایشی پیاده‌سازی نشده است. پروژه را به رایانه خود ببرید و پرداخت مورد نیاز را با هوش مصنوعی بسازید.", toAdminPanel: "رفتن به پنل مدیریت" },
  ku: { open: "Selika siparîşê", title: "Siparîşa te", empty: "Selik vala ye. Ji katalogê berhemekê zêde bike.", confirmAdd: "{name} li siparîşê were zêdekirin?", confirmAddNote: "Hejmarê dikarî biguherînî an berhemê her dem ji selikê rakî.", yes: "Zêde bike", cancel: "Betal", added: "Li siparîşê hate zêdekirin", addToCart: "Li siparîşê zêde bike", increase: "Yek zêdetir", decrease: "Yek kêmtir", remove: "Ji siparîşê rake", quantity: "Hejmar", total: "Bi giştî", checkout: "Siparîşê bide", reset: "Siparîşê paqij bike", resetConfirm: "Her tişt ji siparîşê were rakirin?", checkoutToast: "Piştre tû diçûyî dayînê", checkoutNote: "Di vê nîşandanê de nehatiye çêkirin. Projeyê bibe ser makîneya xwe û dayîna ku hewce dikî bi ZŞ ava bike.", toAdminPanel: "Panela kontrolê veke" },
  af: { open: "Bestellingsmandjie", title: "Jou bestelling", empty: "Die mandjie is leeg. Voeg ’n produk uit die katalogus by.", confirmAdd: "Voeg {name} by die bestelling?", confirmAddNote: "Jy kan die hoeveelheid enige tyd verander of dit uit die mandjie verwyder.", yes: "Voeg by", cancel: "Kanselleer", added: "By die bestelling gevoeg", addToCart: "Voeg by bestelling", increase: "Een meer", decrease: "Een minder", remove: "Verwyder uit bestelling", quantity: "Hoeveelheid", total: "Totaal", checkout: "Plaas die bestelling", reset: "Maak bestelling leeg", resetConfirm: "Verwyder alles uit die bestelling?", checkoutToast: "Daarna sou jy na betaling gaan", checkoutNote: "Nie in hierdie demo gebou nie. Neem die projek na jou eie masjien en bou die betaling wat jy nodig het met KI.", toAdminPanel: "Open die beheerpaneel" },
  sw: { open: "Kikapu cha oda", title: "Oda yako", empty: "Kikapu ki tupu. Ongeza bidhaa kutoka katalogi.", confirmAdd: "Ongeza {name} kwenye oda?", confirmAddNote: "Unaweza kubadilisha idadi au kuiondoa kikapuni wakati wowote.", yes: "Ongeza", cancel: "Ghairi", added: "Imeongezwa kwenye oda", addToCart: "Ongeza kwenye oda", increase: "Moja zaidi", decrease: "Moja pungufu", remove: "Ondoa kwenye oda", quantity: "Idadi", total: "Jumla", checkout: "Weka oda", reset: "Futa oda", resetConfirm: "Ondoa kila kitu kwenye oda?", checkoutToast: "Kisha ungeenda kwenye malipo", checkoutNote: "Haijatengenezwa katika onyesho hili. Chukua mradi kwenye kompyuta yako na ujenge malipo unayohitaji kwa msaada wa AI.", toAdminPanel: "Fungua paneli ya udhibiti" },
  ha: { open: "Kwandon oda", title: "Odarka", empty: "Kwandon babu komai. Ƙara kaya daga katalog.", confirmAdd: "A ƙara {name} cikin oda?", confirmAddNote: "Za ka iya canza yawa ko cire shi daga kwando a kowane lokaci.", yes: "Ƙara", cancel: "Soke", added: "An ƙara cikin oda", addToCart: "Ƙara cikin oda", increase: "Ɗaya ƙari", decrease: "Ɗaya ƙasa", remove: "Cire daga oda", quantity: "Yawa", total: "Jimla", checkout: "Yi odar", reset: "Share odar", resetConfirm: "A cire komai daga oda?", checkoutToast: "Sannan za ka je biya", checkoutNote: "Ba a gina shi ba a wannan nunin. Ɗauki aikin zuwa na’urarka ka gina biyan da kake buƙata da AI.", toAdminPanel: "Buɗe kwamitin sarrafawa" },
  yo: { open: "Agbọ̀n àṣẹ", title: "Àṣẹ rẹ", empty: "Agbọ̀n ṣofo. Fi ọjà kún un láti inú àkójọ.", confirmAdd: "Fi {name} kún àṣẹ?", confirmAddNote: "O lè yí iye padà tàbí mú un kúrò nínú agbọ̀n nígbàkúgbà.", yes: "Fi kún", cancel: "Fagilé", added: "A fi kún àṣẹ", addToCart: "Fi kún àṣẹ", increase: "Ọ̀kan sí i", decrease: "Ọ̀kan kù", remove: "Mú kúrò nínú àṣẹ", quantity: "Iye", total: "Àpapọ̀", checkout: "Fi àṣẹ ránṣẹ́", reset: "Nu àṣẹ nù", resetConfirm: "Mú gbogbo rẹ̀ kúrò nínú àṣẹ?", checkoutToast: "Lẹ́yìn náà o máa lọ sí ìsanwó", checkoutNote: "Kò sí nínú àfihàn yìí. Mú iṣẹ́ náà lọ sí ẹ̀rọ rẹ, kí o sì kọ́ ìsanwó tí o nílò pẹ̀lú AI.", toAdminPanel: "Ṣí pátákó ìdarí" },
  ig: { open: "Nkata iwu", title: "Iwu gị", empty: "Nkata tọgbọrọ chakoo. Tinye ngwaahịa site na katalọgụ.", confirmAdd: "Tinye {name} n’iwu?", confirmAddNote: "Ị nwere ike ịgbanwe ọnụọgụ ma ọ bụ wepụ ya na nkata mgbe ọ bụla.", yes: "Tinye", cancel: "Kagbuo", added: "Etinyela n’iwu", addToCart: "Tinye n’iwu", increase: "Otu ọzọ", decrease: "Otu belata", remove: "Wepụ n’iwu", quantity: "Ọnụọgụ", total: "Mkpokọta", checkout: "Nye iwu", reset: "Hichapụ iwu", resetConfirm: "Wepụ ihe niile n’iwu?", checkoutToast: "Ị ga-agakwuru ịkwụ ụgwọ", checkoutNote: "Emeghị ya na ngosi a. Buru ọrụ gaa n’igwe gị wee jiri AI wuo ụzọ ịkwụ ụgwọ ị chọrọ.", toAdminPanel: "Mepee panel njikwa" },
  am: { open: "የትዕዛዝ ቅርጫት", title: "ትዕዛዝዎ", empty: "ቅርጫቱ ባዶ ነው። ከዝርዝሩ ምርት ያክሉ።", confirmAdd: "{name} ወደ ትዕዛዝ ይታከል?", confirmAddNote: "ብዛቱን መቀየር ወይም ከቅርጫቱ ማውጣት በማንኛውም ጊዜ ይቻላል።", yes: "አክል", cancel: "ተወው", added: "ወደ ትዕዛዝ ታክሏል", addToCart: "ወደ ትዕዛዝ", increase: "አንድ ተጨማሪ", decrease: "አንድ ያነሰ", remove: "ከትዕዛዝ አውጣ", quantity: "ብዛት", total: "ጠቅላላ", checkout: "ትዕዛዝ አስገባ", reset: "ትዕዛዙን አጽዳ", resetConfirm: "ሁሉንም ከትዕዛዝ ይውጣ?", checkoutToast: "ቀጥሎ ወደ ክፍያ ይሄዱ ነበር", checkoutNote: "በዚህ ማሳያ አልተተገበረም። ፕሮጀክቱን ወደ የራስዎ ማሽን ወስደው የሚያስፈልግዎትን ክፍያ በአርቴፊሻል ኢንተለጀንስ ይገንቡ።", toAdminPanel: "የቁጥጥር ፓነል ክፈት" },
  zu: { open: "Ibhasikidi le-oda", title: "I-oda yakho", empty: "Ibhasikidi lingenalutho. Engeza umkhiqizo ohlwini.", confirmAdd: "Yengeza u-{name} kwi-oda?", confirmAddNote: "Ungashintsha inani noma uwukhiphe ebhasikidini noma nini.", yes: "Engeza", cancel: "Khansela", added: "Kwengeziwe kwi-oda", addToCart: "Engeza kwi-oda", increase: "Okukodwa okwengeziwe", decrease: "Okukodwa okuncane", remove: "Susa kwi-oda", quantity: "Inani", total: "Isamba", checkout: "Faka i-oda", reset: "Sula i-oda", resetConfirm: "Susa konke kwi-oda?", checkoutToast: "Ube usuya ekukhokheni", checkoutNote: "Akwakhiwanga kule demo. Thatha iphrojekthi uyise emshinini wakho bese wakha ukukhokha okudingayo nge-AI.", toAdminPanel: "Vula iphaneli yokulawula" },
  xh: { open: "Ingobozi yeodolo", title: "Iodolo yakho", empty: "Ingobozi ize. Yongeza imveliso kuluhlu.", confirmAdd: "Yongeza u-{name} kwiodolo?", confirmAddNote: "Unokutshintsha inani okanye uyisuse engobozini nanini na.", yes: "Yongeza", cancel: "Rhoxisa", added: "Yongeziwe kwiodolo", addToCart: "Yongeza kwiodolo", increase: "Enye ngaphezulu", decrease: "Enye ngaphantsi", remove: "Susa kwiodolo", quantity: "Inani", total: "Iyonke", checkout: "Faka iodolo", reset: "Cima iodolo", resetConfirm: "Susa konke kwiodolo?", checkoutToast: "Ubuya kuya kwintlawulo", checkoutNote: "Ayakhiwanga kule demo. Thabatha iprojekthi kumatshini wakho uze wakhe intlawulo oyifunayo nge-AI.", toAdminPanel: "Vula iphaneli yolawulo" },
  rw: { open: "Agatebo k’ubutumwa", title: "Ikimenyetso cyawe", empty: "Agatebo ni ubusa. Ongeraho igicuruzwa mu rutonde.", confirmAdd: "Kongeraho {name} mu bicuruzwa byatumijwe?", confirmAddNote: "Ushobora guhindura umubare cyangwa ukayikuramo igihe icyo ari cyo cyose.", yes: "Ongeraho", cancel: "Kureka", added: "Byongewe", addToCart: "Ongeraho", increase: "Kimwe cyiyongera", decrease: "Kimwe kigabanuka", remove: "Kuraho", quantity: "Umubare", total: "Igiteranyo", checkout: "Tumiza", reset: "Gusiba byose", resetConfirm: "Gukuraho byose?", checkoutToast: "Hanyuma wajya mu kwishyura", checkoutNote: "Ntibyakozwe muri iyi mbonerahamwe. Jyana umushinga kuri mudasobwa yawe hanyuma wubake uburyo bwo kwishyura ukoresheje AI.", toAdminPanel: "Fungura urubuga rw’ubuyobozi" },
  so: { open: "Dambiisha dalabka", title: "Dalabkaaga", empty: "Dambiishu waa madhan yahay. Kaga dar alaab liiska.", confirmAdd: "{name} ma lagu daraa dalabka?", confirmAddNote: "Tirada waad beddeli kartaa ama alaabta dambiisha ka saari kartaa wakhti kasta.", yes: "Kudar", cancel: "Jooji", added: "Waa lagu daray dalabka", addToCart: "Ku dar dalabka", increase: "Mid dheeraad ah", decrease: "Mid ka yar", remove: "Ka saar dalabka", quantity: "Tirada", total: "Wadarta", checkout: "Dalbo", reset: "Nadiifi dalabka", resetConfirm: "Ma ka saaraa wax walba dalabka?", checkoutToast: "Kadibna waxaad u gudbi lahayd bixinta", checkoutNote: "Bandhiggan laguma dhisin. Mashruuca u qaado kombiyuutarkaaga oo ku dhis bixinta aad u baahan tahay adigoo isticmaalaya AI.", toAdminPanel: "Fur guddiga xakamaynta" },
  zh: { open: "订单购物车", title: "您的订单", empty: "购物车是空的。请从目录中添加商品。", confirmAdd: "将「{name}」加入订单？", confirmAddNote: "数量随时可以更改，商品也可以从购物车中移除。", yes: "加入", cancel: "取消", added: "已加入订单", addToCart: "加入订单", increase: "多一件", decrease: "少一件", remove: "从订单中移除", quantity: "数量", total: "合计", checkout: "提交订单", reset: "清空订单", resetConfirm: "从订单中移除全部？", checkoutToast: "接下来将进入结算", checkoutNote: "演示模式未实现。把项目带到自己的机器上，用人工智能构建你需要的结算流程。", toAdminPanel: "前往控制面板" },
  ja: { open: "注文カート", title: "あなたの注文", empty: "カートは空です。カタログから商品を追加してください。", confirmAdd: "「{name}」を注文に追加しますか？", confirmAddNote: "数量の変更も、カートからの削除も、いつでもできます。", yes: "追加", cancel: "キャンセル", added: "注文に追加しました", addToCart: "注文に追加", increase: "1つ増やす", decrease: "1つ減らす", remove: "注文から削除", quantity: "数量", total: "合計", checkout: "注文する", reset: "注文を空にする", resetConfirm: "注文からすべて削除しますか？", checkoutToast: "この先は決済に進みます", checkoutNote: "デモでは未実装です。プロジェクトをご自身のマシンに持ち帰り、必要な決済をAIで組み立ててください。", toAdminPanel: "コントロールパネルを開く" },
  ko: { open: "주문 장바구니", title: "내 주문", empty: "장바구니가 비어 있습니다. 카탈로그에서 상품을 추가하세요.", confirmAdd: "「{name}」을(를) 주문에 추가할까요?", confirmAddNote: "수량 변경과 장바구니에서의 삭제는 언제든지 가능합니다.", yes: "추가", cancel: "취소", added: "주문에 추가되었습니다", addToCart: "주문에 추가", increase: "하나 더", decrease: "하나 줄이기", remove: "주문에서 삭제", quantity: "수량", total: "합계", checkout: "주문하기", reset: "주문 비우기", resetConfirm: "주문에서 전부 삭제할까요?", checkoutToast: "다음은 결제 단계입니다", checkoutNote: "데모에서는 구현되어 있지 않습니다. 프로젝트를 자신의 컴퓨터로 가져가 필요한 결제를 AI로 만드세요.", toAdminPanel: "제어판 열기" },
  hi: { open: "ऑर्डर की टोकरी", title: "आपका ऑर्डर", empty: "टोकरी खाली है। सूची से उत्पाद जोड़ें।", confirmAdd: "{name} को ऑर्डर में जोड़ें?", confirmAddNote: "मात्रा बदलना या उत्पाद को टोकरी से हटाना कभी भी संभव है।", yes: "जोड़ें", cancel: "रद्द करें", added: "ऑर्डर में जोड़ा गया", addToCart: "ऑर्डर में जोड़ें", increase: "एक और", decrease: "एक कम", remove: "ऑर्डर से हटाएँ", quantity: "मात्रा", total: "कुल", checkout: "ऑर्डर करें", reset: "ऑर्डर खाली करें", resetConfirm: "ऑर्डर से सब कुछ हटाएँ?", checkoutToast: "आगे आप भुगतान पर जाते", checkoutNote: "इस डेमो में लागू नहीं है। परियोजना अपनी मशीन पर ले जाएँ और आवश्यक भुगतान एआई की मदद से बनाएँ।", toAdminPanel: "नियंत्रण पैनल खोलें" },
  ur: { open: "آرڈر کی ٹوکری", title: "آپ کا آرڈر", empty: "ٹوکری خالی ہے۔ فہرست سے مصنوعات شامل کریں۔", confirmAdd: "کیا {name} آرڈر میں شامل کریں؟", confirmAddNote: "مقدار بدلنا یا مصنوعات کو ٹوکری سے نکالنا کسی بھی وقت ممکن ہے۔", yes: "شامل کریں", cancel: "منسوخ", added: "آرڈر میں شامل ہو گیا", addToCart: "آرڈر میں شامل کریں", increase: "ایک زیادہ", decrease: "ایک کم", remove: "آرڈر سے نکالیں", quantity: "مقدار", total: "کل", checkout: "آرڈر دیں", reset: "آرڈر خالی کریں", resetConfirm: "آرڈر سے سب کچھ نکال دیں؟", checkoutToast: "اس کے بعد آپ ادائیگی پر جاتے", checkoutNote: "اس ڈیمو میں نافذ نہیں۔ منصوبہ اپنی مشین پر لے جائیں اور مطلوبہ ادائیگی مصنوعی ذہانت سے بنائیں۔", toAdminPanel: "کنٹرول پینل کھولیں" },
  bn: { open: "অর্ডারের ঝুড়ি", title: "আপনার অর্ডার", empty: "ঝুড়ি খালি। তালিকা থেকে পণ্য যোগ করুন।", confirmAdd: "{name} অর্ডারে যোগ করবেন?", confirmAddNote: "পরিমাণ বদলানো বা পণ্যটি ঝুড়ি থেকে সরানো যেকোনো সময় সম্ভব।", yes: "যোগ করুন", cancel: "বাতিল", added: "অর্ডারে যোগ হয়েছে", addToCart: "অর্ডারে যোগ", increase: "একটি বেশি", decrease: "একটি কম", remove: "অর্ডার থেকে সরান", quantity: "পরিমাণ", total: "মোট", checkout: "অর্ডার করুন", reset: "অর্ডার খালি করুন", resetConfirm: "অর্ডার থেকে সব সরাবেন?", checkoutToast: "এরপর আপনি পরিশোধে যেতেন", checkoutNote: "এই ডেমোতে বাস্তবায়িত নয়। প্রকল্পটি নিজের মেশিনে নিয়ে যান এবং প্রয়োজনীয় পরিশোধ কৃত্রিম বুদ্ধিমত্তা দিয়ে তৈরি করুন।", toAdminPanel: "নিয়ন্ত্রণ প্যানেল খুলুন" },
  te: { open: "ఆర్డర్ బుట్ట", title: "మీ ఆర్డర్", empty: "బుట్ట ఖాళీగా ఉంది. జాబితా నుండి ఉత్పత్తిని జోడించండి.", confirmAdd: "{name}ని ఆర్డర్‌కు జోడించాలా?", confirmAddNote: "పరిమాణం మార్చడం లేదా బుట్ట నుండి తీసివేయడం ఎప్పుడైనా సాధ్యమే.", yes: "జోడించు", cancel: "రద్దు", added: "ఆర్డర్‌కు జోడించబడింది", addToCart: "ఆర్డర్‌కు జోడించు", increase: "ఒకటి ఎక్కువ", decrease: "ఒకటి తక్కువ", remove: "ఆర్డర్ నుండి తీసివేయి", quantity: "పరిమాణం", total: "మొత్తం", checkout: "ఆర్డర్ చేయి", reset: "ఆర్డర్ ఖాళీ చేయి", resetConfirm: "ఆర్డర్ నుండి అన్నీ తీసివేయాలా?", checkoutToast: "తర్వాత మీరు చెల్లింపునకు వెళ్తారు", checkoutNote: "ఈ ప్రదర్శనలో అమలు చేయలేదు. ప్రాజెక్టును మీ మెషీన్‌కు తీసుకెళ్లి అవసరమైన చెల్లింపును కృత్రిమ మేధతో నిర్మించండి.", toAdminPanel: "నియంత్రణ ప్యానెల్ తెరువు" },
  mr: { open: "ऑर्डरची टोपली", title: "तुमची ऑर्डर", empty: "टोपली रिकामी आहे. सूचीतून उत्पादन जोडा.", confirmAdd: "{name} ऑर्डरमध्ये जोडायचे?", confirmAddNote: "प्रमाण बदलणे किंवा उत्पादन टोपलीतून काढणे कधीही शक्य आहे.", yes: "जोडा", cancel: "रद्द करा", added: "ऑर्डरमध्ये जोडले", addToCart: "ऑर्डरमध्ये जोडा", increase: "एक अधिक", decrease: "एक कमी", remove: "ऑर्डरमधून काढा", quantity: "प्रमाण", total: "एकूण", checkout: "ऑर्डर द्या", reset: "ऑर्डर रिकामी करा", resetConfirm: "ऑर्डरमधून सर्व काढायचे?", checkoutToast: "पुढे तुम्ही देयकाकडे जाल", checkoutNote: "या प्रात्यक्षिकात लागू केलेले नाही. प्रकल्प आपल्या संगणकावर न्या आणि आवश्यक देयक कृत्रिम बुद्धिमत्तेने तयार करा.", toAdminPanel: "नियंत्रण पॅनेल उघडा" },
  kn: { open: "ಆರ್ಡರ್ ಬುಟ್ಟಿ", title: "ನಿಮ್ಮ ಆರ್ಡರ್", empty: "ಬುಟ್ಟಿ ಖಾಲಿಯಿದೆ. ಪಟ್ಟಿಯಿಂದ ಉತ್ಪನ್ನ ಸೇರಿಸಿ.", confirmAdd: "{name} ಅನ್ನು ಆರ್ಡರ್‌ಗೆ ಸೇರಿಸಬೇಕೆ?", confirmAddNote: "ಪ್ರಮಾಣ ಬದಲಾಯಿಸುವುದು ಅಥವಾ ಬುಟ್ಟಿಯಿಂದ ತೆಗೆಯುವುದು ಯಾವಾಗ ಬೇಕಾದರೂ ಸಾಧ್ಯ.", yes: "ಸೇರಿಸಿ", cancel: "ರದ್ದು", added: "ಆರ್ಡರ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ", addToCart: "ಆರ್ಡರ್‌ಗೆ ಸೇರಿಸಿ", increase: "ಒಂದು ಹೆಚ್ಚು", decrease: "ಒಂದು ಕಡಿಮೆ", remove: "ಆರ್ಡರ್‌ನಿಂದ ತೆಗೆಯಿರಿ", quantity: "ಪ್ರಮಾಣ", total: "ಒಟ್ಟು", checkout: "ಆರ್ಡರ್ ಮಾಡಿ", reset: "ಆರ್ಡರ್ ಖಾಲಿ ಮಾಡಿ", resetConfirm: "ಆರ್ಡರ್‌ನಿಂದ ಎಲ್ಲವನ್ನೂ ತೆಗೆಯಬೇಕೆ?", checkoutToast: "ಮುಂದೆ ನೀವು ಪಾವತಿಗೆ ಹೋಗುತ್ತಿದ್ದಿರಿ", checkoutNote: "ಈ ಪ್ರದರ್ಶನದಲ್ಲಿ ಅಳವಡಿಸಿಲ್ಲ. ಯೋಜನೆಯನ್ನು ನಿಮ್ಮ ಯಂತ್ರಕ್ಕೆ ಒಯ್ದು ಬೇಕಾದ ಪಾವತಿಯನ್ನು ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆಯಿಂದ ನಿರ್ಮಿಸಿ.", toAdminPanel: "ನಿಯಂತ್ರಣ ಫಲಕ ತೆರೆಯಿರಿ" },
  gu: { open: "ઓર્ડરની ટોપલી", title: "તમારો ઓર્ડર", empty: "ટોપલી ખાલી છે. યાદીમાંથી ઉત્પાદન ઉમેરો.", confirmAdd: "{name} ઓર્ડરમાં ઉમેરવું?", confirmAddNote: "જથ્થો બદલવો કે ઉત્પાદન ટોપલીમાંથી કાઢવું કોઈપણ સમયે શક્ય છે.", yes: "ઉમેરો", cancel: "રદ કરો", added: "ઓર્ડરમાં ઉમેરાયું", addToCart: "ઓર્ડરમાં ઉમેરો", increase: "એક વધુ", decrease: "એક ઓછું", remove: "ઓર્ડરમાંથી કાઢો", quantity: "જથ્થો", total: "કુલ", checkout: "ઓર્ડર કરો", reset: "ઓર્ડર ખાલી કરો", resetConfirm: "ઓર્ડરમાંથી બધું કાઢવું?", checkoutToast: "પછી તમે ચુકવણી પર જાત", checkoutNote: "આ પ્રદર્શનમાં અમલમાં નથી. પ્રોજેક્ટ તમારા મશીન પર લઈ જાઓ અને જરૂરી ચુકવણી કૃત્રિમ બુદ્ધિથી બનાવો.", toAdminPanel: "નિયંત્રણ પેનલ ખોલો" },
  ml: { open: "ഓർഡർ കൊട്ട", title: "നിങ്ങളുടെ ഓർഡർ", empty: "കൊട്ട ശൂന്യമാണ്. പട്ടികയിൽ നിന്ന് ഉൽപ്പന്നം ചേർക്കുക.", confirmAdd: "{name} ഓർഡറിൽ ചേർക്കണോ?", confirmAddNote: "അളവ് മാറ്റാനും കൊട്ടയിൽ നിന്ന് നീക്കാനും എപ്പോൾ വേണമെങ്കിലും കഴിയും.", yes: "ചേർക്കുക", cancel: "റദ്ദാക്കുക", added: "ഓർഡറിൽ ചേർത്തു", addToCart: "ഓർഡറിൽ ചേർക്കുക", increase: "ഒന്ന് കൂടുതൽ", decrease: "ഒന്ന് കുറവ്", remove: "ഓർഡറിൽ നിന്ന് നീക്കുക", quantity: "അളവ്", total: "ആകെ", checkout: "ഓർഡർ ചെയ്യുക", reset: "ഓർഡർ ശൂന്യമാക്കുക", resetConfirm: "ഓർഡറിൽ നിന്ന് എല്ലാം നീക്കണോ?", checkoutToast: "അടുത്തതായി പണമടയ്ക്കലിലേക്ക് പോകുമായിരുന്നു", checkoutNote: "ഈ പ്രദർശനത്തിൽ നടപ്പാക്കിയിട്ടില്ല. പദ്ധതി സ്വന്തം യന്ത്രത്തിലേക്ക് കൊണ്ടുപോയി ആവശ്യമുള്ള പണമടയ്ക്കൽ നിർമ്മിത ബുദ്ധി ഉപയോഗിച്ച് നിർമ്മിക്കുക.", toAdminPanel: "നിയന്ത്രണ പാനൽ തുറക്കുക" },
  ta: { open: "ஆர்டர் கூடை", title: "உங்கள் ஆர்டர்", empty: "கூடை காலியாக உள்ளது. பட்டியலிலிருந்து பொருளைச் சேர்க்கவும்.", confirmAdd: "{name} ஆர்டரில் சேர்க்கவா?", confirmAddNote: "அளவை மாற்றுவதும் கூடையிலிருந்து நீக்குவதும் எப்போது வேண்டுமானாலும் முடியும்.", yes: "சேர்", cancel: "ரத்து", added: "ஆர்டரில் சேர்க்கப்பட்டது", addToCart: "ஆர்டரில் சேர்", increase: "ஒன்று அதிகம்", decrease: "ஒன்று குறைவு", remove: "ஆர்டரிலிருந்து நீக்கு", quantity: "அளவு", total: "மொத்தம்", checkout: "ஆர்டர் செய்", reset: "ஆர்டரை காலி செய்", resetConfirm: "ஆர்டரிலிருந்து அனைத்தையும் நீக்கவா?", checkoutToast: "அடுத்து நீங்கள் கட்டணத்திற்குச் செல்வீர்கள்", checkoutNote: "இந்த விளக்கக்காட்சியில் செயல்படுத்தப்படவில்லை. திட்டத்தை உங்கள் கணினிக்கு எடுத்துச் சென்று தேவையான கட்டணத்தை செயற்கை நுண்ணறிவால் உருவாக்குங்கள்.", toAdminPanel: "கட்டுப்பாட்டு பலகத்தைத் திற" },
  ne: { open: "अर्डरको टोकरी", title: "तपाईंको अर्डर", empty: "टोकरी खाली छ। सूचीबाट उत्पादन थप्नुहोस्।", confirmAdd: "{name} अर्डरमा थप्ने?", confirmAddNote: "परिमाण बदल्न वा टोकरीबाट हटाउन जुनसुकै बेला सकिन्छ।", yes: "थप्नुहोस्", cancel: "रद्द", added: "अर्डरमा थपियो", addToCart: "अर्डरमा थप्नुहोस्", increase: "एक बढी", decrease: "एक कम", remove: "अर्डरबाट हटाउनुहोस्", quantity: "परिमाण", total: "जम्मा", checkout: "अर्डर गर्नुहोस्", reset: "अर्डर खाली गर्नुहोस्", resetConfirm: "अर्डरबाट सबै हटाउने?", checkoutToast: "त्यसपछि तपाईं भुक्तानीमा जानुहुन्थ्यो", checkoutNote: "यो प्रदर्शनमा लागू गरिएको छैन। परियोजना आफ्नै मेसिनमा लैजानुहोस् र आवश्यक भुक्तानी कृत्रिम बुद्धिमत्ताले बनाउनुहोस्।", toAdminPanel: "नियन्त्रण प्यानल खोल्नुहोस्" },
  vi: { open: "Giỏ đơn hàng", title: "Đơn hàng của bạn", empty: "Giỏ trống. Hãy thêm sản phẩm từ danh mục.", confirmAdd: "Thêm {name} vào đơn hàng?", confirmAddNote: "Bạn có thể đổi số lượng hoặc bỏ sản phẩm khỏi giỏ bất cứ lúc nào.", yes: "Thêm", cancel: "Hủy", added: "Đã thêm vào đơn hàng", addToCart: "Thêm vào đơn hàng", increase: "Thêm một", decrease: "Bớt một", remove: "Bỏ khỏi đơn hàng", quantity: "Số lượng", total: "Tổng cộng", checkout: "Đặt hàng", reset: "Xóa đơn hàng", resetConfirm: "Bỏ tất cả khỏi đơn hàng?", checkoutToast: "Tiếp theo bạn sẽ sang bước thanh toán", checkoutNote: "Chưa dựng trong bản demo này. Hãy đưa dự án về máy của bạn và dựng bước thanh toán bạn cần với AI.", toAdminPanel: "Mở bảng điều khiển" },
  th: { open: "ตะกร้าคำสั่งซื้อ", title: "คำสั่งซื้อของคุณ", empty: "ตะกร้าว่างเปล่า เพิ่มสินค้าจากรายการ", confirmAdd: "เพิ่ม {name} ลงในคำสั่งซื้อ?", confirmAddNote: "เปลี่ยนจำนวนหรือนำออกจากตะกร้าได้ทุกเมื่อ", yes: "เพิ่ม", cancel: "ยกเลิก", added: "เพิ่มลงคำสั่งซื้อแล้ว", addToCart: "เพิ่มลงคำสั่งซื้อ", increase: "เพิ่มหนึ่ง", decrease: "ลดหนึ่ง", remove: "นำออกจากคำสั่งซื้อ", quantity: "จำนวน", total: "รวม", checkout: "สั่งซื้อ", reset: "ล้างคำสั่งซื้อ", resetConfirm: "นำทุกอย่างออกจากคำสั่งซื้อ?", checkoutToast: "ขั้นถัดไปคือการชำระเงิน", checkoutNote: "ไม่ได้สร้างไว้ในเดโมนี้ นำโปรเจกต์ไปยังเครื่องของคุณแล้วสร้างขั้นตอนชำระเงินที่ต้องการด้วย AI", toAdminPanel: "เปิดแผงควบคุม" },
  id: { open: "Keranjang pesanan", title: "Pesanan Anda", empty: "Keranjang kosong. Tambahkan produk dari katalog.", confirmAdd: "Tambahkan {name} ke pesanan?", confirmAddNote: "Jumlah bisa diubah dan produk bisa dikeluarkan dari keranjang kapan saja.", yes: "Tambah", cancel: "Batal", added: "Ditambahkan ke pesanan", addToCart: "Tambah ke pesanan", increase: "Satu lagi", decrease: "Satu kurang", remove: "Keluarkan dari pesanan", quantity: "Jumlah", total: "Total", checkout: "Buat pesanan", reset: "Kosongkan pesanan", resetConfirm: "Keluarkan semua dari pesanan?", checkoutToast: "Selanjutnya Anda akan menuju pembayaran", checkoutNote: "Tidak dibangun dalam demo ini. Bawa proyek ke mesin Anda sendiri dan bangun pembayaran yang Anda butuhkan dengan AI.", toAdminPanel: "Buka panel kontrol" },
  ms: { open: "Bakul pesanan", title: "Pesanan anda", empty: "Bakul kosong. Tambah produk daripada katalog.", confirmAdd: "Tambah {name} ke pesanan?", confirmAddNote: "Kuantiti boleh diubah dan produk dikeluarkan daripada bakul bila-bila masa.", yes: "Tambah", cancel: "Batal", added: "Ditambah ke pesanan", addToCart: "Tambah ke pesanan", increase: "Satu lagi", decrease: "Satu kurang", remove: "Keluarkan daripada pesanan", quantity: "Kuantiti", total: "Jumlah", checkout: "Buat pesanan", reset: "Kosongkan pesanan", resetConfirm: "Keluarkan semua daripada pesanan?", checkoutToast: "Seterusnya anda akan ke pembayaran", checkoutNote: "Tidak dibina dalam demo ini. Bawa projek ke mesin anda sendiri dan bina pembayaran yang anda perlukan dengan AI.", toAdminPanel: "Buka panel kawalan" },
  tl: { open: "Basket ng order", title: "Ang iyong order", empty: "Walang laman ang basket. Magdagdag ng produkto mula sa katalogo.", confirmAdd: "Idagdag ang {name} sa order?", confirmAddNote: "Maaaring baguhin ang dami o alisin ito sa basket anumang oras.", yes: "Idagdag", cancel: "Kanselahin", added: "Naidagdag sa order", addToCart: "Idagdag sa order", increase: "Isa pa", decrease: "Isa nang mas kaunti", remove: "Alisin sa order", quantity: "Dami", total: "Kabuuan", checkout: "Ilagay ang order", reset: "Linisin ang order", resetConfirm: "Alisin ang lahat sa order?", checkoutToast: "Susunod ay pupunta ka sa bayaran", checkoutNote: "Hindi ginawa sa demo na ito. Dalhin ang proyekto sa sarili mong makina at buuin ang kailangan mong bayaran gamit ang AI.", toAdminPanel: "Buksan ang control panel" },
  my: { open: "အော်ဒါ ခြင်းတောင်း", title: "သင့်အော်ဒါ", empty: "ခြင်းတောင်း ဗလာဖြစ်နေသည်။ စာရင်းမှ ကုန်ပစ္စည်း ထည့်ပါ။", confirmAdd: "{name} ကို အော်ဒါထဲ ထည့်မလား။", confirmAddNote: "အရေအတွက် ပြောင်းခြင်း၊ ခြင်းတောင်းမှ ဖယ်ခြင်း အချိန်မရွေး ပြုလုပ်နိုင်သည်။", yes: "ထည့်ရန်", cancel: "ပယ်ဖျက်", added: "အော်ဒါထဲ ထည့်ပြီး", addToCart: "အော်ဒါထဲ ထည့်", increase: "တစ်ခု ပိုထည့်", decrease: "တစ်ခု လျှော့", remove: "အော်ဒါမှ ဖယ်ရန်", quantity: "အရေအတွက်", total: "စုစုပေါင်း", checkout: "အော်ဒါတင်ရန်", reset: "အော်ဒါ ရှင်းရန်", resetConfirm: "အော်ဒါမှ အားလုံး ဖယ်မလား။", checkoutToast: "ထို့နောက် ငွေပေးချေမှုသို့ သွားမည်", checkoutNote: "ဤသရုပ်ပြတွင် မတည်ဆောက်ရသေးပါ။ ပရောဂျက်ကို ကိုယ့်စက်သို့ ယူသွားပြီး လိုအပ်သော ငွေပေးချေမှုကို AI ဖြင့် တည်ဆောက်ပါ။", toAdminPanel: "ထိန်းချုပ်မှု ပန်နယ် ဖွင့်ရန်" },
  km: { open: "កន្ត្រកបញ្ជាទិញ", title: "ការបញ្ជាទិញរបស់អ្នក", empty: "កន្ត្រកទទេ។ បន្ថែមផលិតផលពីបញ្ជី។", confirmAdd: "បន្ថែម {name} ទៅការបញ្ជាទិញ?", confirmAddNote: "អាចប្តូរចំនួន ឬដកចេញពីកន្ត្រកបានគ្រប់ពេល។", yes: "បន្ថែម", cancel: "បោះបង់", added: "បានបន្ថែមទៅការបញ្ជាទិញ", addToCart: "បន្ថែមទៅការបញ្ជាទិញ", increase: "មួយបន្ថែម", decrease: "មួយតិច", remove: "ដកចេញពីការបញ្ជាទិញ", quantity: "ចំនួន", total: "សរុប", checkout: "ធ្វើការបញ្ជាទិញ", reset: "សម្អាតការបញ្ជាទិញ", resetConfirm: "ដកអ្វីៗទាំងអស់ចេញពីការបញ្ជាទិញ?", checkoutToast: "បន្ទាប់មកអ្នកនឹងទៅកាន់ការទូទាត់", checkoutNote: "មិនបានសាងសង់ក្នុងការបង្ហាញនេះទេ។ យកគម្រោងទៅម៉ាស៊ីនរបស់អ្នក ហើយសាងសង់ការទូទាត់ដែលអ្នកត្រូវការដោយប្រើបញ្ញាសិប្បនិម្មិត។", toAdminPanel: "បើកផ្ទាំងគ្រប់គ្រង" },
  lo: { open: "ກະຕ່າສັ່ງຊື້", title: "ການສັ່ງຊື້ຂອງທ່ານ", empty: "ກະຕ່າວ່າງເປົ່າ. ເພີ່ມສິນຄ້າຈາກລາຍການ.", confirmAdd: "ເພີ່ມ {name} ເຂົ້າການສັ່ງຊື້?", confirmAddNote: "ສາມາດປ່ຽນຈຳນວນ ຫຼື ເອົາອອກຈາກກະຕ່າໄດ້ທຸກເວລາ.", yes: "ເພີ່ມ", cancel: "ຍົກເລີກ", added: "ເພີ່ມເຂົ້າການສັ່ງຊື້ແລ້ວ", addToCart: "ເພີ່ມເຂົ້າການສັ່ງຊື້", increase: "ຫນຶ່ງເພີ່ມ", decrease: "ຫນຶ່ງຫຼຸດ", remove: "ເອົາອອກຈາກການສັ່ງຊື້", quantity: "ຈຳນວນ", total: "ລວມ", checkout: "ສັ່ງຊື້", reset: "ລ້າງການສັ່ງຊື້", resetConfirm: "ເອົາທັງໝົດອອກຈາກການສັ່ງຊື້?", checkoutToast: "ຕໍ່ໄປທ່ານຈະໄປສູ່ການຊຳລະ", checkoutNote: "ບໍ່ໄດ້ສ້າງໃນການສາທິດນີ້. ເອົາໂຄງການໄປເຄື່ອງຂອງທ່ານ ແລະ ສ້າງການຊຳລະທີ່ຕ້ອງການດ້ວຍ AI.", toAdminPanel: "ເປີດແຜງຄວບຄຸມ" },
}

export function cartUi(lang: string): CartUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
