// Слова страницы товаров БУХГАЛТЕРИИ.
//
// Форма пути повторяет слой персонала: `<раздел>/products`. Сущность одна и та
// же, страницы разные ролью, а не сущностью, — и это должно быть видно в адресе
// прежде, чем откроешь файл: `/manage/products` ведёт менеджер, `/accounting/products`
// ведёт бухгалтер.
//
// 🔒 ЯЗЫКОВ СТОЛЬКО, СКОЛЬКО ВКЛЮЧЕНО В ПАНЕЛИ (`NEXT_PUBLIC_SUPPORTED_LANGUAGES`,
// сейчас `en,ru`). Это строки ОДНОЙ страницы: они рождаются вместе с ней и умрут
// вместе с ней. Не путать с заголовками слоёв прав в ящике аккаунта — те
// переиспользуются в каждом проекте и потому написаны на всех 82 языках.

export type AccountingProductsUi = {
  title: string
  subtitle: string
  /** Подсказка над таблицей: почему правится только цена. */
  priceOnly: string
  saved: string
  invalidPrice: string
  save: string
  cancel: string
}

const UI: Record<string, AccountingProductsUi> = {
  en: { title: "Pricing", subtitle: "The money layer: one column and full responsibility for it. You set prices — the number a customer will see and pay. Everything descriptive stays with staff, and that is the point of the separation: a price is changed often and by different people, so it must not travel together with the text of the card. Nothing else on this page can be edited, and the server enforces that rather than the interface hiding it.", priceOnly: "You may change the price. The name, description and photo are edited by the staff layer — the server refuses anything else from this page.", saved: "Price updated", invalidPrice: "Price must be a number, zero or greater.", save: "Save", cancel: "Cancel" },
  fr: { title: "Produits", subtitle: "Le même catalogue, vu côté prix. Tout le reste du produit relève de la couche personnel.", priceOnly: "Vous pouvez modifier le prix. Le nom, la description et la photo sont édités par la couche personnel — le serveur refuse tout autre champ depuis cette page.", saved: "Prix mis à jour", invalidPrice: "Le prix doit être un nombre supérieur ou égal à zéro.", save: "Enregistrer", cancel: "Annuler" },
  es: { title: "Productos", subtitle: "El mismo catálogo, visto desde el precio. Todo lo demás del producto pertenece a la capa de personal.", priceOnly: "Puede modificar el precio. El nombre, la descripción y la foto los edita la capa de personal — el servidor rechazará cualquier otro campo desde esta página.", saved: "Precio actualizado", invalidPrice: "El precio debe ser un número mayor o igual a cero.", save: "Guardar", cancel: "Cancelar" },
  pt: { title: "Produtos", subtitle: "O mesmo catálogo, visto pelo preço. Tudo o mais sobre o produto pertence à camada de equipe.", priceOnly: "Você pode alterar o preço. O nome, a descrição e a foto são editados pela camada de equipe — o servidor recusará qualquer outro campo vindo desta página.", saved: "Preço atualizado", invalidPrice: "O preço deve ser um número maior ou igual a zero.", save: "Salvar", cancel: "Cancelar" },
  de: { title: "Produkte", subtitle: "Derselbe Katalog, aus Sicht des Preises. Alles andere am Produkt gehört zur Personal-Ebene.", priceOnly: "Sie dürfen den Preis ändern. Name, Beschreibung und Foto werden von der Personal-Ebene bearbeitet — der Server lehnt jedes andere Feld von dieser Seite ab.", saved: "Preis aktualisiert", invalidPrice: "Der Preis muss eine Zahl größer oder gleich null sein.", save: "Speichern", cancel: "Abbrechen" },
  it: { title: "Prodotti", subtitle: "Lo stesso catalogo, visto dal lato del prezzo. Tutto il resto del prodotto appartiene al livello del personale.", priceOnly: "Puoi modificare il prezzo. Nome, descrizione e foto vengono modificati dal livello del personale — il server rifiuterà qualsiasi altro campo da questa pagina.", saved: "Prezzo aggiornato", invalidPrice: "Il prezzo deve essere un numero maggiore o uguale a zero.", save: "Salva", cancel: "Annulla" },
  nl: { title: "Producten", subtitle: "Dezelfde catalogus, bekeken vanuit de prijs. Al het overige aan een product hoort bij de personeelslaag.", priceOnly: "U mag de prijs wijzigen. Naam, beschrijving en foto worden bewerkt door de personeelslaag — de server weigert elk ander veld vanaf deze pagina.", saved: "Prijs bijgewerkt", invalidPrice: "De prijs moet een getal zijn dat nul of groter is.", save: "Opslaan", cancel: "Annuleren" },
  sv: { title: "Produkter", subtitle: "Samma katalog, sedd från prissidan. Allt annat om en produkt hör till personallagret.", priceOnly: "Du får ändra priset. Namn, beskrivning och foto redigeras av personallagret — servern nekar allt annat fält från den här sidan.", saved: "Priset uppdaterat", invalidPrice: "Priset måste vara ett tal, noll eller större.", save: "Spara", cancel: "Avbryt" },
  no: { title: "Produkter", subtitle: "Samme katalog, sett fra prisen. Alt annet ved produktet hører til personallaget.", priceOnly: "Du kan endre prisen. Navn, beskrivelse og bilde redigeres av personallaget — serveren avviser ethvert annet felt fra denne siden.", saved: "Pris oppdatert", invalidPrice: "Prisen må være et tall, null eller høyere.", save: "Lagre", cancel: "Avbryt" },
  da: { title: "Produkter", subtitle: "Samme katalog, set fra prisen. Alt andet ved produktet hører til personalelaget.", priceOnly: "Du kan ændre prisen. Navn, beskrivelse og foto redigeres af personalelaget — serveren afviser ethvert andet felt fra denne side.", saved: "Pris opdateret", invalidPrice: "Prisen skal være et tal, nul eller derover.", save: "Gem", cancel: "Annuller" },
  fi: { title: "Tuotteet", subtitle: "Sama luettelo, hinnan näkökulmasta. Kaikki muu tuotteesta kuuluu henkilöstökerrokselle.", priceOnly: "Voit muuttaa hintaa. Nimen, kuvauksen ja kuvan muokkaa henkilöstökerros — palvelin hylkää minkä tahansa muun kentän tältä sivulta.", saved: "Hinta päivitetty", invalidPrice: "Hinnan on oltava luku, nolla tai suurempi.", save: "Tallenna", cancel: "Peruuta" },
  is: { title: "Vörur", subtitle: "Sami vörulistinn, séður út frá verðinu. Allt annað um vöruna tilheyrir starfsfólkslaginu.", priceOnly: "Þú mátt breyta verðinu. Nafn, lýsing og mynd eru ritstýrð af starfsfólkslaginu — netþjónninn hafnar öllum öðrum reitum frá þessari síðu.", saved: "Verð uppfært", invalidPrice: "Verðið verður að vera tala, núll eða hærri.", save: "Vista", cancel: "Hætta við" },
  el: { title: "Προϊόντα", subtitle: "Ο ίδιος κατάλογος, από την πλευρά της τιμής. Οτιδήποτε άλλο αφορά το προϊόν ανήκει στο επίπεδο προσωπικού.", priceOnly: "Μπορείτε να αλλάξετε την τιμή. Το όνομα, η περιγραφή και η φωτογραφία επεξεργάζονται από το επίπεδο προσωπικού — ο διακομιστής θα απορρίψει οποιοδήποτε άλλο πεδίο από αυτήν τη σελίδα.", saved: "Η τιμή ενημερώθηκε", invalidPrice: "Η τιμή πρέπει να είναι αριθμός, μηδέν ή μεγαλύτερος.", save: "Αποθήκευση", cancel: "Άκυρο" },
  pl: { title: "Produkty", subtitle: "Ten sam katalog, widziany od strony ceny. Wszystko inne w produkcie należy do warstwy personelu.", priceOnly: "Możesz zmienić cenę. Nazwę, opis i zdjęcie edytuje warstwa personelu — serwer odrzuci każde inne pole z tej strony.", saved: "Cena zaktualizowana", invalidPrice: "Cena musi być liczbą równą zero lub większą.", save: "Zapisz", cancel: "Anuluj" },
  cs: { title: "Produkty", subtitle: "Stejný katalog, viděný ze strany ceny. Vše ostatní na produktu patří vrstvě personálu.", priceOnly: "Můžete měnit cenu. Název, popis a fotku upravuje vrstva personálu — server odmítne jakékoli jiné pole z této stránky.", saved: "Cena aktualizována", invalidPrice: "Cena musí být číslo rovné nule nebo větší.", save: "Uložit", cancel: "Zrušit" },
  sk: { title: "Produkty", subtitle: "Ten istý katalóg, videný zo strany ceny. Všetko ostatné na produkte patrí vrstve personálu.", priceOnly: "Môžete meniť cenu. Názov, popis a fotku upravuje vrstva personálu — server odmietne akékoľvek iné pole z tejto stránky.", saved: "Cena aktualizovaná", invalidPrice: "Cena musí byť číslo rovné nule alebo väčšie.", save: "Uložiť", cancel: "Zrušiť" },
  hu: { title: "Termékek", subtitle: "Ugyanaz a katalógus, az ár oldaláról nézve. A termék minden más adata a személyzeti réteghez tartozik.", priceOnly: "Az árat módosíthatja. A nevet, a leírást és a fotót a személyzeti réteg szerkeszti — a szerver bármely más mezőt elutasít erről az oldalról.", saved: "Ár frissítve", invalidPrice: "Az árnak nullával egyenlő vagy annál nagyobb számnak kell lennie.", save: "Mentés", cancel: "Mégse" },
  ro: { title: "Produse", subtitle: "Același catalog, văzut din partea prețului. Tot restul despre produs aparține stratului de personal.", priceOnly: "Puteți modifica prețul. Numele, descrierea și fotografia sunt editate de stratul de personal — serverul va refuza orice alt câmp de pe această pagină.", saved: "Preț actualizat", invalidPrice: "Prețul trebuie să fie un număr egal cu zero sau mai mare.", save: "Salvează", cancel: "Anulează" },
  hr: { title: "Proizvodi", subtitle: "Isti katalog, gledan sa strane cijene. Sve ostalo o proizvodu pripada sloju osoblja.", priceOnly: "Možete promijeniti cijenu. Naziv, opis i fotografiju uređuje sloj osoblja — poslužitelj će odbiti svako drugo polje s ove stranice.", saved: "Cijena ažurirana", invalidPrice: "Cijena mora biti broj jednak nuli ili veći.", save: "Spremi", cancel: "Odustani" },
  sl: { title: "Izdelki", subtitle: "Isti katalog, viden s strani cene. Vse drugo o izdelku pripada plasti osebja.", priceOnly: "Cena je edino, kar lahko spremenite. Ime, opis in fotografijo ureja plast osebja — strežnik zavrne vsako drugo polje s te strani.", saved: "Cena posodobljena", invalidPrice: "Cena mora biti število, enako nič ali večje.", save: "Shrani", cancel: "Prekliči" },
  et: { title: "Tooted", subtitle: "Sama kataloog, hinna vaatepunktist. Kõik muu toote juures kuulub personalikihile.", priceOnly: "Te tohite muuta hinda. Nime, kirjeldust ja fotot muudab personalikiht — server lükkab sellelt lehelt tagasi iga muu välja.", saved: "Hind uuendatud", invalidPrice: "Hind peab olema arv, mis on null või suurem.", save: "Salvesta", cancel: "Loobu" },
  lv: { title: "Preces", subtitle: "Tas pats katalogs, skatīts no cenas puses. Viss pārējais par preci pieder personāla slānim.", priceOnly: "Jūs varat mainīt cenu. Nosaukumu, aprakstu un fotoattēlu rediģē personāla slānis — serveris atteiks jebkuru citu lauku no šīs lapas.", saved: "Cena atjaunināta", invalidPrice: "Cenai jābūt skaitlim, kas ir nulle vai lielāks.", save: "Saglabāt", cancel: "Atcelt" },
  lt: { title: "Prekės", subtitle: "Tas pats katalogas, matomas iš kainos pusės. Visa kita apie prekę priklauso personalo sluoksniui.", priceOnly: "Jūs galite keisti kainą. Pavadinimą, aprašymą ir nuotrauką redaguoja personalo sluoksnis — serveris atmes bet kokį kitą lauką iš šio puslapio.", saved: "Kaina atnaujinta", invalidPrice: "Kaina turi būti skaičius, lygus nuliui arba didesnis.", save: "Išsaugoti", cancel: "Atšaukti" },
  mt: { title: "Prodotti", subtitle: "L-istess katalgu, mħares mil-lat tal-prezz. Kull ħaġa oħra dwar il-prodott tappartjeni għal-saff tal-persunal.", priceOnly: "Tista' tibdel il-prezz. L-isem, id-deskrizzjoni u r-ritratt jiġu editjati mis-saff tal-persunal — is-server jirrifjuta kwalunkwe qasam ieħor minn din il-paġna.", saved: "Il-prezz ġie aġġornat", invalidPrice: "Il-prezz irid ikun numru daqs żero jew akbar.", save: "Issejvja", cancel: "Ikkanċella" },
  ca: { title: "Productes", subtitle: "El mateix catàleg, vist des del preu. Tota la resta del producte pertany a la capa de personal.", priceOnly: "Podeu modificar el preu. El nom, la descripció i la foto els edita la capa de personal — el servidor rebutjarà qualsevol altre camp des d'aquesta pàgina.", saved: "Preu actualitzat", invalidPrice: "El preu ha de ser un nombre igual o superior a zero.", save: "Desa", cancel: "Cancel·la" },
  gl: { title: "Produtos", subtitle: "O mesmo catálogo, visto desde o prezo. Todo o demais do produto pertence á capa de persoal.", priceOnly: "Podes modificar o prezo. O nome, a descrición e a foto edítaos a capa de persoal — o servidor rexeitará calquera outro campo desde esta páxina.", saved: "Prezo actualizado", invalidPrice: "O prezo debe ser un número igual ou maior que cero.", save: "Gardar", cancel: "Cancelar" },
  cy: { title: "Cynhyrchion", subtitle: "Yr un catalog, o safbwynt y pris. Mae popeth arall am gynnyrch yn perthyn i haen y staff.", priceOnly: "Cewch newid y pris. Golygir yr enw, y disgrifiad a'r llun gan haen y staff — bydd y gweinydd yn gwrthod unrhyw faes arall o'r dudalen hon.", saved: "Pris wedi'i ddiweddaru", invalidPrice: "Rhaid i'r pris fod yn rif, sero neu fwy.", save: "Cadw", cancel: "Canslo" },
  ga: { title: "Táirgí", subtitle: "An catalóg chéanna, feicthe ó thaobh an phraghais. Baineann gach rud eile faoin táirge le sraith na foirne.", priceOnly: "Is féidir leat an praghas a athrú. Cuireann sraith na foirne an t-ainm, an cur síos agus an ghrianghraf in eagar — diúltóidh an freastalaí d'aon réimse eile ón leathanach seo.", saved: "Praghas nuashonraithe", invalidPrice: "Caithfidh an praghas a bheith ina uimhir atá cothrom le nialas nó níos mó.", save: "Sábháil", cancel: "Cealaigh" },
  eu: { title: "Produktuak", subtitle: "Katalogo bera, prezioaren aldetik ikusita. Produktuari buruzko gainerako guztia langile-geruzarena da.", priceOnly: "Prezioa alda dezakezu. Izena, deskribapena eta argazkia langile-geruzak editatzen ditu — zerbitzariak orri honetatik beste edozein eremu ukatuko du.", saved: "Prezioa eguneratuta", invalidPrice: "Prezioak zero edo handiagoa den zenbakia izan behar du.", save: "Gorde", cancel: "Utzi" },
  ru: { title: "Цены", subtitle: "Денежный слой: одна колонка и полная ответственность за неё. Вы назначаете цены — то число, которое покупатель увидит и заплатит. Всё описательное остаётся за персоналом, и в этом смысл разделения: цена меняется часто и разными людьми, поэтому она не должна ездить вместе с текстом карточки. Больше на этой странице править нечего, и следит за этим сервер, а не спрятанная кнопка.", priceOnly: "Вам доступна цена. Название, описание и фотографию правит слой персонала — сервер откажет этой странице в любом другом поле.", saved: "Цена изменена", invalidPrice: "Цена — число не меньше нуля.", save: "Сохранить", cancel: "Отмена" },
  uk: { title: "Товари", subtitle: "Той самий каталог, вигляд із боку грошей. Усе інше про товар — шар персоналу.", priceOnly: "Вам доступна ціна. Назву, опис і фотографію редагує шар персоналу — сервер відмовить цій сторінці в будь-якому іншому полі.", saved: "Ціну змінено", invalidPrice: "Ціна — число не менше нуля.", save: "Зберегти", cancel: "Скасувати" },
  be: { title: "Тавары", subtitle: "Той жа каталог, від з боку грошай. Усё астатняе пра тавар — слой персаналу.", priceOnly: "Вам даступная цана. Назву, апісанне і фатаграфію рэдагуе слой персаналу — сервер адмовіць гэтай старонцы ў любым іншым полі.", saved: "Цана зменена", invalidPrice: "Цана — лік не менш за нуль.", save: "Захаваць", cancel: "Скасаваць" },
  bg: { title: "Продукти", subtitle: "Същият каталог, погледнат откъм цената. Всичко останало за продукта принадлежи на слоя на персонала.", priceOnly: "Можете да променяте цената. Името, описанието и снимката се редактират от слоя на персонала — сървърът ще откаже всяко друго поле от тази страница.", saved: "Цената е обновена", invalidPrice: "Цената трябва да е число, равно на нула или по-голямо.", save: "Запази", cancel: "Отказ" },
  sr: { title: "Производи", subtitle: "Исти каталог, гледан са стране цене. Све остало о производу припада слоју особља.", priceOnly: "Можете мењати цену. Назив, опис и фотографију уређује слој особља — сервер ће одбити свако друго поље са ове странице.", saved: "Цена ажурирана", invalidPrice: "Цена мора бити број једнак нули или већи.", save: "Сачувај", cancel: "Откажи" },
  bs: { title: "Proizvodi", subtitle: "Isti katalog, gledan sa strane cijene. Sve ostalo o proizvodu pripada sloju osoblja.", priceOnly: "Možete mijenjati cijenu. Naziv, opis i fotografiju uređuje sloj osoblja — server će odbiti svako drugo polje sa ove stranice.", saved: "Cijena ažurirana", invalidPrice: "Cijena mora biti broj jednak nuli ili veći.", save: "Sačuvaj", cancel: "Otkaži" },
  mk: { title: "Производи", subtitle: "Истиот каталог, гледан од страна на цената. Сè останато за производот припаѓа на слојот на персоналот.", priceOnly: "Можете да ја менувате цената. Името, описот и фотографијата ги уредува слојот на персоналот — серверот ќе одбие секое друго поле од оваа страница.", saved: "Цената е ажурирана", invalidPrice: "Цената мора да биде број еднаков на нула или поголем.", save: "Зачувај", cancel: "Откажи" },
  sq: { title: "Produktet", subtitle: "I njëjti katalog, parë nga ana e çmimit. Gjithçka tjetër rreth produktit i përket shtresës së personelit.", priceOnly: "Mund të ndryshoni çmimin. Emrin, përshkrimin dhe foton i redakton shtresa e personelit — serveri do të refuzojë çdo fushë tjetër nga kjo faqe.", saved: "Çmimi u përditësua", invalidPrice: "Çmimi duhet të jetë një numër zero ose më i madh.", save: "Ruaj", cancel: "Anulo" },
  kk: { title: "Тауарлар", subtitle: "Сол каталог, баға жағынан қаралған. Тауар туралы қалғанның бәрі — персонал қабатының ісі.", priceOnly: "Сізге баға қолжетімді. Атауын, сипаттамасын және фотосуретін персонал қабаты өңдейді — сервер бұл беттен басқа кез келген өрісті қабылдамайды.", saved: "Баға өзгертілді", invalidPrice: "Баға — нөлден кем емес сан.", save: "Сақтау", cancel: "Бас тарту" },
  uz: { title: "Mahsulotlar", subtitle: "Xuddi shu katalog, narx tomonidan qaralgan. Mahsulot haqidagi qolgan hamma narsa xodimlar qatlamiga tegishli.", priceOnly: "Sizga narxni o‘zgartirish mumkin. Nomi, tavsifi va fotosuratini xodimlar qatlami tahrirlaydi — server bu sahifadan boshqa har qanday maydonni rad etadi.", saved: "Narx yangilandi", invalidPrice: "Narx nolga teng yoki undan katta son bo‘lishi kerak.", save: "Saqlash", cancel: "Bekor qilish" },
  ky: { title: "Товарлар", subtitle: "Ошол эле каталог, баа жагынан каралган. Товар жөнүндөгү калгандын баары — персонал катмарынын иши.", priceOnly: "Сизге баа жеткиликтүү. Атын, сүрөттөлүшүн жана сүрөтүн персонал катмары түзөтөт — сервер бул беттен башка кайсы болбосун талааны кабыл албайт.", saved: "Баа өзгөртүлдү", invalidPrice: "Баа — нөлдөн кем эмес сан.", save: "Сактоо", cancel: "Жокко чыгаруу" },
  tg: { title: "Молҳо", subtitle: "Ҳамон феҳрист, аз тарафи нарх дида шудааст. Ҳама чизи дигар дар бораи мол ба қабати кормандон тааллуқ дорад.", priceOnly: "Ба шумо нарх дастрас аст. Номро, тавсифро ва суратро қабати кормандон таҳрир мекунад — сервер ҳар майдони дигарро аз ин саҳифа рад мекунад.", saved: "Нарх тағйир ёфт", invalidPrice: "Нарх бояд рақами баробар ба сифр ё бузургтар бошад.", save: "Захира кардан", cancel: "Бекор" },
  tk: { title: "Harytlar", subtitle: "Şol bir katalog, baha tarapyndan seredilen. Haryt barada galan zadyň hemmesi işgärler gatlamyna degişli.", priceOnly: "Size baha üýtgetmäge rugsat bar. Ady, beýany we suraty işgärler gatlamy redaktirleýär — server bu sahypadan başga islendik meýdany ret eder.", saved: "Baha täzelendi", invalidPrice: "Baha nola deň ýa-da ondan uly san bolmaly.", save: "Ýatda sakla", cancel: "Ýatyr" },
  az: { title: "Məhsullar", subtitle: "Eyni kataloq, qiymət tərəfindən baxılmış. Məhsul haqqında qalan hər şey heyət qatına aiddir.", priceOnly: "Siz qiyməti dəyişə bilərsiniz. Adı, təsviri və fotonu heyət qatı redaktə edir — server bu səhifədən başqa hər hansı sahəni rədd edəcək.", saved: "Qiymət yeniləndi", invalidPrice: "Qiymət sıfıra bərabər və ya ondan böyük ədəd olmalıdır.", save: "Yadda saxla", cancel: "Ləğv et" },
  hy: { title: "Ապրանքներ", subtitle: "Նույն ցանկը, գնի կողմից դիտված։ Ապրանքի մասին մնացած ամեն ինչ պատկանում է անձնակազմի շերտին։", priceOnly: "Դուք կարող եք փոխել գինը։ Անվանումը, նկարագրությունը և լուսանկարը խմբագրում է անձնակազմի շերտը — սերվերը կմերժի այս էջից ցանկացած այլ դաշտ։", saved: "Գինը թարմացվեց", invalidPrice: "Գինը պետք է լինի զրոյին հավասար կամ մեծ թիվ։", save: "Պահպանել", cancel: "Չեղարկել" },
  ka: { title: "პროდუქტები", subtitle: "იგივე კატალოგი, ფასის მხრიდან დანახული. ყველაფერი დანარჩენი პროდუქტის შესახებ ეკუთვნის პერსონალის შრეს.", priceOnly: "თქვენ შეგიძლიათ შეცვალოთ ფასი. სახელს, აღწერას და ფოტოს არედაქტირებს პერსონალის შრე — სერვერი უარყოფს ნებისმიერ სხვა ველს ამ გვერდიდან.", saved: "ფასი განახლდა", invalidPrice: "ფასი უნდა იყოს რიცხვი, ნულის ტოლი ან მეტი.", save: "შენახვა", cancel: "გაუქმება" },
  mn: { title: "Бүтээгдэхүүнүүд", subtitle: "Ижил каталог, үнийн талаас харсан. Бүтээгдэхүүний талаарх бусад бүх зүйл нь ажилтны давхаргад хамаарна.", priceOnly: "Та үнийг өөрчлөх боломжтой. Нэр, тодорхойлолт, зургийг ажилтны давхарга засварладаг — сервер энэ хуудаснаас өөр ямар ч талбарыг татгалзана.", saved: "Үнэ шинэчлэгдлээ", invalidPrice: "Үнэ нь тэгтэй тэнцүү эсвэл түүнээс их тоо байх ёстой.", save: "Хадгалах", cancel: "Цуцлах" },
  ar: { title: "المنتجات", subtitle: "نفس الكتالوج، من جهة السعر. كل شيء آخر عن المنتج يخص طبقة الموظفين.", priceOnly: "يمكنك تعديل السعر فقط. الاسم والوصف والصورة يحررها طبقة الموظفين — سيرفض الخادم أي حقل آخر من هذه الصفحة.", saved: "تم تحديث السعر", invalidPrice: "يجب أن يكون السعر رقمًا يساوي صفرًا أو أكبر.", save: "حفظ", cancel: "إلغاء" },
  tr: { title: "Ürünler", subtitle: "Aynı katalog, fiyat tarafından görülen. Ürünle ilgili geri kalan her şey personel katmanına aittir.", priceOnly: "Fiyatı değiştirebilirsiniz. Adı, açıklamayı ve fotoğrafı personel katmanı düzenler — sunucu bu sayfadan gelen başka her alanı reddeder.", saved: "Fiyat güncellendi", invalidPrice: "Fiyat sıfıra eşit veya ondan büyük bir sayı olmalıdır.", save: "Kaydet", cancel: "Vazgeç" },
  he: { title: "מוצרים", subtitle: "אותו קטלוג, נראה מצד המחיר. כל השאר לגבי המוצר שייך לשכבת הצוות.", priceOnly: "מותר לכם לשנות רק את המחיר. השם, התיאור והתמונה נערכים על ידי שכבת הצוות — השרת ידחה כל שדה אחר מדף זה.", saved: "המחיר עודכן", invalidPrice: "המחיר חייב להיות מספר השווה לאפס או גדול ממנו.", save: "שמירה", cancel: "ביטול" },
  fa: { title: "محصولات", subtitle: "همان فهرست، از سمت قیمت دیده‌شده. هر چیز دیگری درباره محصول به لایه کارکنان تعلق دارد.", priceOnly: "شما فقط می‌توانید قیمت را تغییر دهید. نام، توضیحات و عکس را لایه کارکنان ویرایش می‌کند — سرور هر فیلد دیگری را از این صفحه رد می‌کند.", saved: "قیمت به‌روزرسانی شد", invalidPrice: "قیمت باید عددی برابر با صفر یا بزرگ‌تر باشد.", save: "ذخیره", cancel: "انصراف" },
  ku: { title: "Berhem", subtitle: "Heman katalog e, ji aliyê bihayê ve tê dîtin. Her tiştê din ê berhemê yê çîna karmendan e.", priceOnly: "Tenê bihayê dikarî biguherînî. Nav, daxuyanî û wêneyê ji aliyê çîna karmendan ve tê sererastkirin — servera vê rûpelê her qadeke din red dike.", saved: "Biha hate nûkirin", invalidPrice: "Biha divê hejmarek wekhevî sifir an mezintir be.", save: "Tomar bike", cancel: "Betal bike" },
  af: { title: "Produkte", subtitle: "Dieselfde katalogus, van die prys se kant beskou. Al die res oor 'n produk behoort aan die personeellaag.", priceOnly: "U mag slegs die prys verander. Die naam, beskrywing en foto word deur die personeellaag geredigeer — die bediener sal enige ander veld vanaf hierdie bladsy weier.", saved: "Prys opgedateer", invalidPrice: "Die prys moet 'n getal wees, nul of groter.", save: "Stoor", cancel: "Kanselleer" },
  sw: { title: "Bidhaa", subtitle: "Katalogi ile ile, ikiangaliwa kwa upande wa bei. Kila kitu kingine kuhusu bidhaa ni cha safu ya wafanyakazi.", priceOnly: "Unaweza kubadilisha bei tu. Jina, maelezo na picha hurekebishwa na safu ya wafanyakazi — seva itakataa uwanja mwingine wowote kutoka ukurasa huu.", saved: "Bei imesasishwa", invalidPrice: "Bei lazima iwe nambari sawa na sifuri au zaidi.", save: "Hifadhi", cancel: "Ghairi" },
  ha: { title: "Kayayyaki", subtitle: "Katalog iri ɗaya, wanda aka duba daga ɓangaren farashi. Duk sauran abin da ya shafi kayan yana na matakin ma'aikata.", priceOnly: "Za ka iya canza farashi kawai. Suna, bayani, da hoto matakin ma'aikata ne ke gyara su — sabar za ta ƙi kowane fanni na daban daga wannan shafin.", saved: "An sabunta farashi", invalidPrice: "Farashi dole ya zama lamba daidai da sifili ko fiye.", save: "Ajiye", cancel: "Soke" },
  yo: { title: "Àwọn ọjà", subtitle: "Àkójọ kan náà, tí a wò láti ẹ̀gbẹ́ owó. Gbogbo ohun mìíràn nípa ọjà náà jẹ́ ti ipele òṣìṣẹ́.", priceOnly: "O lè yí owó padà nìkan. Ipele òṣìṣẹ́ ni ó ń ṣàtúnṣe orúkọ, àpèjúwe àti fọ́tò — sáfà yóò kọ̀ eyíkéyìí pápá mìíràn láti ojú-ìwé yìí.", saved: "Owó ti di dídójú", invalidPrice: "Owó gbọ́dọ̀ jẹ́ nọ́mbà tí ó dọ́gba pẹ̀lú odo tàbí tí ó tóbi jù.", save: "Fi pamọ́", cancel: "Fagilé" },
  ig: { title: "Ngwaahịa", subtitle: "Otu katalọgụ ahụ, na-ele anya n'akụkụ ọnụahịa. Ihe ọzọ niile gbasara ngwaahịa bụ nke oyi akwa ndị ọrụ.", priceOnly: "Ị nwere ike ịgbanwe naanị ọnụahịa. Oyi akwa ndị ọrụ na-edezi aha, nkọwa na foto — ihe nkesa ga-ajụ ubi ọ bụla ọzọ site na peeji a.", saved: "Emelitela ọnụahịa", invalidPrice: "Ọnụahịa aghaghị ịbụ nọmba nha ọtụtụ efu ma ọ bụ karịa.", save: "Chekwaa", cancel: "Kagbuo" },
  am: { title: "ምርቶች", subtitle: "ተመሳሳይ ዝርዝር፣ ከዋጋ ጎን ታይቷል። ስለ ምርቱ የቀሩት ነገሮች ሁሉ የሠራተኞች ንብርብር ናቸው።", priceOnly: "ዋጋውን ብቻ መቀየር ይችላሉ። ስም፣ መግለጫ እና ፎቶ የሚስተካከሉት በሠራተኞች ንብርብር ነው — አገልጋዩ ከዚህ ገጽ ማንኛውንም ሌላ መስክ ይክዳል።", saved: "ዋጋ ተዘምኗል", invalidPrice: "ዋጋው ከዜሮ ጋር እኩል ወይም የበለጠ ቁጥር መሆን አለበት።", save: "አስቀምጥ", cancel: "ተወው" },
  zu: { title: "Imikhiqizo", subtitle: "Ikhathalogi efanayo, ibukwa ngasohlangothini lwentengo. Konke okunye ngomkhiqizo kungokwesendlalelo sabasebenzi.", priceOnly: "Ungashintsha intengo kuphela. Igama, incazelo nesithombe kuhlelwa yisendlalelo sabasebenzi — iseva izokwenqaba noma iyiphi enye ifomu kule khasi.", saved: "Intengo ibuyekeziwe", invalidPrice: "Intengo kufanele ibe yinombolo elingana no-zero noma engaphezulu.", save: "Londoloza", cancel: "Khansela" },
  xh: { title: "Iimveliso", subtitle: "Uludwe olufanayo, lubonwa ngecala lexabiso. Yonke enye into ngemveliso ikwiseti yabasebenzi.", priceOnly: "Ungatshintsha ixabiso kuphela. Igama, inkcazelo nomfanekiso kuhlelwa liseti labasebenzi — iseva iya kwala nayiphi na enye indawo kule phepha.", saved: "Ixabiso lihlaziyiwe", invalidPrice: "Ixabiso kufuneka libe yinani elilingana noziro okanye ngaphezulu.", save: "Gcina", cancel: "Rhoxisa" },
  rw: { title: "Ibicuruzwa", subtitle: "Urutonde rumwe, rurebwa ku ruhande rw'igiciro. Ibindi byose ku bijyanye n'igicuruzwa ni iby'urwego rw'abakozi.", priceOnly: "Ushobora guhindura igiciro gusa. Izina, ibisobanuro n'ifoto bihindurwa n'urwego rw'abakozi — seriveri izanga ikindi kibanza icyo ari cyo cyose kuri iyi paji.", saved: "Igiciro cyavuguruwe", invalidPrice: "Igiciro kigomba kuba umubare ungana na zeru cyangwa urenga.", save: "Bika", cancel: "Kureka" },
  so: { title: "Alaabta", subtitle: "Isla liiskan oo laga eegayo dhinaca qiimaha. Wax kasta oo kale ee ku saabsan alaabta waa kuwa lakabka shaqaalaha.", priceOnly: "Qiimaha uun baad bedeli kartaa. Magaca, sharraxaadda, iyo sawirka waxaa tafatira lakabka shaqaalaha — sarverku wuu diidayaa goob kasta oo kale oo bogga ka timaada.", saved: "Qiimaha waa la cusboonaysiiyay", invalidPrice: "Qiimuhu waa inuu ahaadaa tiro la mid ah eber ama ka weyn.", save: "Kaydi", cancel: "Jooji" },
  zh: { title: "商品", subtitle: "同一份目录，从价格的角度呈现。商品的其余部分属于员工层。", priceOnly: "您只能修改价格。名称、描述和照片由员工层编辑——服务器会拒绝本页面提交的其他任何字段。", saved: "价格已更新", invalidPrice: "价格必须是不小于零的数字。", save: "保存", cancel: "取消" },
  ja: { title: "商品", subtitle: "同じカタログを、価格の側から見たもの。商品に関するそれ以外の情報はスタッフ層のものです。", priceOnly: "変更できるのは価格のみです。名前、説明、写真はスタッフ層が編集します——サーバーはこのページからの他のフィールドをすべて拒否します。", saved: "価格を更新しました", invalidPrice: "価格は0以上の数値である必要があります。", save: "保存", cancel: "キャンセル" },
  ko: { title: "상품", subtitle: "같은 카탈로그를 가격 쪽에서 본 것입니다. 상품에 관한 나머지 모든 것은 직원 계층의 몫입니다.", priceOnly: "가격만 변경할 수 있습니다. 이름, 설명, 사진은 직원 계층에서 편집하며, 서버는 이 페이지에서 그 외 필드를 거부합니다.", saved: "가격이 업데이트되었습니다", invalidPrice: "가격은 0 이상의 숫자여야 합니다.", save: "저장", cancel: "취소" },
  hi: { title: "उत्पाद", subtitle: "वही सूची, कीमत की ओर से देखी गई। उत्पाद के बारे में बाकी सब कुछ स्टाफ़ लेयर का है।", priceOnly: "आप केवल कीमत बदल सकते हैं। नाम, विवरण और फ़ोटो स्टाफ़ लेयर द्वारा संपादित होते हैं — सर्वर इस पेज से किसी भी अन्य फ़ील्ड को अस्वीकार कर देगा।", saved: "कीमत अपडेट हो गई", invalidPrice: "कीमत शून्य के बराबर या उससे बड़ी संख्या होनी चाहिए।", save: "सहेजें", cancel: "रद्द करें" },
  ur: { title: "مصنوعات", subtitle: "وہی فہرست، قیمت کے پہلو سے دیکھی گئی۔ مصنوعات کے بارے میں باقی سب کچھ عملے کی سطح کا ہے۔", priceOnly: "آپ صرف قیمت تبدیل کر سکتے ہیں۔ نام، تفصیل اور تصویر عملے کی سطح ترمیم کرتی ہے — سرور اس صفحے سے کسی بھی دوسرے فیلڈ کو مسترد کر دے گا۔", saved: "قیمت اپ ڈیٹ ہو گئی", invalidPrice: "قیمت صفر کے برابر یا اس سے بڑا عدد ہونی چاہیے۔", save: "محفوظ کریں", cancel: "منسوخ کریں" },
  bn: { title: "পণ্য", subtitle: "একই তালিকা, দামের দিক থেকে দেখা। পণ্য সম্পর্কে বাকি সবকিছু স্টাফ স্তরের।", priceOnly: "আপনি শুধু দাম পরিবর্তন করতে পারেন। নাম, বিবরণ এবং ছবি স্টাফ স্তর সম্পাদনা করে — সার্ভার এই পৃষ্ঠা থেকে অন্য যেকোনো ক্ষেত্র প্রত্যাখ্যান করবে।", saved: "দাম আপডেট হয়েছে", invalidPrice: "দাম শূন্যের সমান বা তার চেয়ে বড় সংখ্যা হতে হবে।", save: "সংরক্ষণ করুন", cancel: "বাতিল" },
  te: { title: "ఉత్పత్తులు", subtitle: "అదే జాబితా, ధర వైపు నుండి చూసినది. ఉత్పత్తి గురించి మిగతా అన్నీ సిబ్బంది పొర సొంతం.", priceOnly: "మీరు కేవలం ధరను మార్చవచ్చు. పేరు, వివరణ మరియు ఫోటోను సిబ్బంది పొర సవరిస్తుంది — ఈ పేజీ నుండి వేరే ఏ ఫీల్డ్‌నైనా సర్వర్ తిరస్కరిస్తుంది.", saved: "ధర నవీకరించబడింది", invalidPrice: "ధర సున్నాకు సమానం లేదా అంతకంటే ఎక్కువ సంఖ్య అయి ఉండాలి.", save: "సేవ్ చేయి", cancel: "రద్దు" },
  mr: { title: "उत्पादने", subtitle: "तीच यादी, किमतीच्या बाजूने पाहिलेली. उत्पादनाबद्दल बाकी सर्व काही कर्मचारी थराचे आहे.", priceOnly: "तुम्ही फक्त किंमत बदलू शकता. नाव, वर्णन आणि फोटो कर्मचारी थर संपादित करतो — सर्व्हर या पानावरून इतर कोणतेही क्षेत्र नाकारेल.", saved: "किंमत अद्ययावत केली", invalidPrice: "किंमत शून्याच्या बरोबरीची किंवा त्यापेक्षा मोठी संख्या असावी.", save: "जतन करा", cancel: "रद्द करा" },
  kn: { title: "ಉತ್ಪನ್ನಗಳು", subtitle: "ಅದೇ ಪಟ್ಟಿ, ಬೆಲೆಯ ಕಡೆಯಿಂದ ನೋಡಿದಂತೆ. ಉತ್ಪನ್ನದ ಬಗ್ಗೆ ಉಳಿದೆಲ್ಲವೂ ಸಿಬ್ಬಂದಿ ಪದರಕ್ಕೆ ಸೇರಿದ್ದು.", priceOnly: "ನೀವು ಕೇವಲ ಬೆಲೆಯನ್ನು ಬದಲಾಯಿಸಬಹುದು. ಹೆಸರು, ವಿವರಣೆ ಮತ್ತು ಫೋಟೋವನ್ನು ಸಿಬ್ಬಂದಿ ಪದರ ಸಂಪಾದಿಸುತ್ತದೆ — ಈ ಪುಟದಿಂದ ಬೇರೆ ಯಾವುದೇ ಕ್ಷೇತ್ರವನ್ನು ಸರ್ವರ್ ತಿರಸ್ಕರಿಸುತ್ತದೆ.", saved: "ಬೆಲೆ ನವೀಕರಿಸಲಾಗಿದೆ", invalidPrice: "ಬೆಲೆ ಸೊನ್ನೆಗೆ ಸಮ ಅಥವಾ ಅದಕ್ಕಿಂತ ದೊಡ್ಡ ಸಂಖ್ಯೆ ಆಗಿರಬೇಕು.", save: "ಉಳಿಸಿ", cancel: "ರದ್ದು" },
  gu: { title: "ઉત્પાદનો", subtitle: "એ જ યાદી, કિંમતની બાજુથી જોવાયેલી. ઉત્પાદન વિશે બાકીનું બધું સ્ટાફ સ્તરનું છે.", priceOnly: "તમે ફક્ત કિંમત બદલી શકો છો. નામ, વર્ણન અને ફોટો સ્ટાફ સ્તર સંપાદિત કરે છે — સર્વર આ પેજ પરથી અન્ય કોઈપણ ફીલ્ડને નકારશે.", saved: "કિંમત અપડેટ થઈ", invalidPrice: "કિંમત શૂન્યની બરાબર અથવા તેનાથી મોટી સંખ્યા હોવી જોઈએ.", save: "સાચવો", cancel: "રદ કરો" },
  ml: { title: "ഉൽപ്പന്നങ്ങൾ", subtitle: "അതേ പട്ടിക, വിലയുടെ വശത്ത് നിന്ന് കാണുന്നത്. ഉൽപ്പന്നത്തെക്കുറിച്ചുള്ള ബാക്കിയെല്ലാം സ്റ്റാഫ് പാളിയുടേതാണ്.", priceOnly: "നിങ്ങൾക്ക് വില മാത്രമേ മാറ്റാനാകൂ. പേര്, വിവരണം, ഫോട്ടോ എന്നിവ സ്റ്റാഫ് പാളി എഡിറ്റ് ചെയ്യുന്നു — ഈ പേജിൽ നിന്ന് മറ്റേതൊരു ഫീൽഡും സെർവർ നിരസിക്കും.", saved: "വില പുതുക്കി", invalidPrice: "വില പൂജ്യത്തിന് തുല്യമോ അതിലധികമോ ആയ സംഖ്യയായിരിക്കണം.", save: "സേവ് ചെയ്യുക", cancel: "റദ്ദാക്കുക" },
  ta: { title: "தயாரிப்புகள்", subtitle: "அதே பட்டியல், விலையின் பக்கத்திலிருந்து பார்க்கப்பட்டது. தயாரிப்பு பற்றிய மற்ற அனைத்தும் பணியாளர் அடுக்குக்கு உரியது.", priceOnly: "நீங்கள் விலையை மட்டுமே மாற்றலாம். பெயர், விவரம் மற்றும் புகைப்படத்தை பணியாளர் அடுக்கு திருத்துகிறது — இந்தப் பக்கத்திலிருந்து வேறு எந்தத் துறையையும் சர்வர் நிராகரிக்கும்.", saved: "விலை புதுப்பிக்கப்பட்டது", invalidPrice: "விலை பூஜ்ஜியத்திற்கு சமமான அல்லது அதற்கு மேற்பட்ட எண்ணாக இருக்க வேண்டும்.", save: "சேமி", cancel: "ரத்து" },
  ne: { title: "उत्पादनहरू", subtitle: "उही सूची, मूल्यको पक्षबाट हेरिएको। उत्पादनको बारेमा बाँकी सबै कुरा कर्मचारी तहको हो।", priceOnly: "तपाईंले मूल्य मात्र परिवर्तन गर्न सक्नुहुन्छ। नाम, विवरण र फोटो कर्मचारी तहले सम्पादन गर्छ — यो पृष्ठबाट अन्य कुनै पनि क्षेत्र सर्भरले अस्वीकार गर्नेछ।", saved: "मूल्य अद्यावधिक भयो", invalidPrice: "मूल्य शून्यको बराबर वा त्यो भन्दा ठूलो संख्या हुनुपर्छ।", save: "सुरक्षित गर्नुहोस्", cancel: "रद्द गर्नुहोस्" },
  vi: { title: "Sản phẩm", subtitle: "Cùng một danh mục, nhìn từ phía giá. Mọi thứ khác về sản phẩm thuộc về lớp nhân viên.", priceOnly: "Bạn chỉ có thể thay đổi giá. Tên, mô tả và ảnh do lớp nhân viên chỉnh sửa — máy chủ sẽ từ chối bất kỳ trường nào khác từ trang này.", saved: "Đã cập nhật giá", invalidPrice: "Giá phải là một số bằng không hoặc lớn hơn.", save: "Lưu", cancel: "Hủy" },
  th: { title: "สินค้า", subtitle: "แคตตาล็อกเดียวกัน มองจากด้านราคา ทุกอย่างอื่นเกี่ยวกับสินค้าเป็นของชั้นพนักงาน", priceOnly: "คุณสามารถเปลี่ยนได้เฉพาะราคาเท่านั้น ชื่อ คำอธิบาย และรูปภาพจะแก้ไขโดยชั้นพนักงาน — เซิร์ฟเวอร์จะปฏิเสธฟิลด์อื่นใดจากหน้านี้", saved: "อัปเดตราคาแล้ว", invalidPrice: "ราคาต้องเป็นตัวเลขที่เท่ากับศูนย์หรือมากกว่า", save: "บันทึก", cancel: "ยกเลิก" },
  id: { title: "Produk", subtitle: "Katalog yang sama, dilihat dari sisi harga. Semua hal lain tentang produk adalah milik lapisan staf.", priceOnly: "Anda hanya dapat mengubah harga. Nama, deskripsi, dan foto diedit oleh lapisan staf — server akan menolak bidang lain apa pun dari halaman ini.", saved: "Harga diperbarui", invalidPrice: "Harga harus berupa angka sama dengan nol atau lebih besar.", save: "Simpan", cancel: "Batal" },
  ms: { title: "Produk", subtitle: "Katalog yang sama, dilihat dari sudut harga. Semua yang lain tentang produk adalah milik lapisan kakitangan.", priceOnly: "Anda hanya boleh menukar harga. Nama, penerangan dan foto disunting oleh lapisan kakitangan — pelayan akan menolak mana-mana medan lain daripada halaman ini.", saved: "Harga dikemas kini", invalidPrice: "Harga mesti nombor sama dengan sifar atau lebih besar.", save: "Simpan", cancel: "Batal" },
  tl: { title: "Mga Produkto", subtitle: "Parehong katalogo, tinitingnan mula sa panig ng presyo. Ang lahat ng iba pa tungkol sa produkto ay pag-aari ng layer ng kawani.", priceOnly: "Maaari mo lang baguhin ang presyo. Ang pangalan, paglalarawan, at larawan ay ineedit ng layer ng kawani — tatanggihan ng server ang anumang ibang field mula sa pahinang ito.", saved: "Na-update ang presyo", invalidPrice: "Ang presyo ay dapat na numerong katumbas ng zero o mas malaki.", save: "I-save", cancel: "Kanselahin" },
  my: { title: "ကုန်ပစ္စည်းများ", subtitle: "ထပ်တူဖြစ်သော ကတလောက်ကို ဈေးနှုန်းဘက်မှ ကြည့်ထားသည်။ ကုန်ပစ္စည်းနှင့်ပတ်သက်သော ကျန်အားလုံးမှာ ဝန်ထမ်းအလွှာပိုင်ဖြစ်သည်။", priceOnly: "ဈေးနှုန်းကိုသာ ပြောင်းလဲနိုင်သည်။ အမည်၊ ဖော်ပြချက်နှင့် ဓာတ်ပုံကို ဝန်ထမ်းအလွှာက တည်းဖြတ်သည် — ဤစာမျက်နှာမှ အခြားမည်သည့်အကွက်ကိုမဆို ဆာဗာက ငြင်းပယ်မည်။", saved: "ဈေးနှုန်း အပ်ဒိတ်ပြီးပါပြီ", invalidPrice: "ဈေးနှုန်းသည် သုညနှင့်ညီမျှသော သို့မဟုတ် ပိုကြီးသော ဂဏန်းဖြစ်ရမည်။", save: "သိမ်းဆည်းရန်", cancel: "ပယ်ဖျက်ရန်" },
  km: { title: "ផលិតផល", subtitle: "កាតាឡុកដដែល ដែលមើលពីជ្រុងតម្លៃ។ អ្វីៗផ្សេងទៀតអំពីផលិតផលជាកម្មសិទ្ធិរបស់ស្រទាប់បុគ្គលិក។", priceOnly: "អ្នកអាចផ្លាស់ប្តូរតែតម្លៃប៉ុណ្ណោះ។ ឈ្មោះ ការពិពណ៌នា និងរូបថតត្រូវបានកែសម្រួលដោយស្រទាប់បុគ្គលិក — ម៉ាស៊ីនមេនឹងបដិសេធវាលផ្សេងទៀតណាមួយពីទំព័រនេះ។", saved: "តម្លៃត្រូវបានធ្វើបច្ចុប្បន្នភាព", invalidPrice: "តម្លៃត្រូវតែជាលេខស្មើសូន្យ ឬធំជាងសូន្យ។", save: "រក្សាទុក", cancel: "បោះបង់" },
  lo: { title: "ສິນຄ້າ", subtitle: "ບັນຊີລາຍການດຽວກັນ, ເບິ່ງຈາກດ້ານລາຄາ. ທຸກຢ່າງອື່ນກ່ຽວກັບສິນຄ້າແມ່ນຂອງຊັ້ນພະນັກງານ.", priceOnly: "ທ່ານສາມາດປ່ຽນໄດ້ພຽງແຕ່ລາຄາເທົ່ານັ້ນ. ຊື່, ຄຳອະທິບາຍ ແລະ ຮູບພາບຖືກແກ້ໄຂໂດຍຊັ້ນພະນັກງານ — ເຊີບເວີຈະປະຕິເສດຊ່ອງອື່ນໆຈາກໜ້ານີ້.", saved: "ອັບເດດລາຄາແລ້ວ", invalidPrice: "ລາຄາຕ້ອງເປັນຕົວເລກເທົ່າກັບສູນ ຫຼື ຫຼາຍກວ່ານັ້ນ.", save: "ບັນທຶກ", cancel: "ຍົກເລີກ" },
}

export function accountingProductsUi(lang: string): AccountingProductsUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
