// СЛОВАРЬ ГОЛОСОВОГО ВВОДА — десять языков (en, es, fr, it, ru, de, pt, pl, tr, nl), англ. фолбэк (закон 4г).
// Тексты перенесены из v1 (`_shared/components/voice-input.client.tsx`) — фидбэк владельца «переноси
// один-в-один». Живёт в папке автоматизации: наружу не ходим (закон 0).
export type VoiceStrings = {
  hold: string;
  recording: string;
  transcribing: string;
  tipOk: string;
  tipInsecure: string;
  micDenied: string;
  micNoDevice: string;
  frame: string; // микрофон в окне предпросмотра — открыть страницу отдельной вкладкой
  failed: string;
  nothing: string;
  noKey: string;
  /** Расшифровка показана и ждёт решения — вставлять её или выбросить. */
  draftTitle: string;
  accept: string;
  discard: string;
};

export const VOICE_I18N: Record<string, VoiceStrings> = {
  en: { hold: "Hold to speak", recording: "Recording…", transcribing: "Transcribing…", tipOk: "Hold to speak — release to transcribe. The text lands where your cursor is.", tipInsecure: "Voice input needs HTTPS (or localhost). Connect your domain to enable it — or dictate with your system keyboard.", micDenied: "Microphone access is blocked — allow it for this site and hold the button again.", micNoDevice: "No microphone was found on this device.", frame: "The browser blocks the microphone inside the preview — open this page in its own tab to record.", failed: "Could not transcribe the recording.", nothing: "Nothing was recognised — try again, closer to the microphone.", noKey: "Voice input needs the OpenAI key — add it in the workspace settings.", draftTitle: "Transcribed — insert at the cursor?", accept: "Insert", discard: "Discard" },
  es: { hold: "Mantén para hablar", recording: "Grabando…", transcribing: "Transcribiendo…", tipOk: "Mantén pulsado para hablar; suelta para transcribir. El texto va donde está el cursor.", tipInsecure: "La entrada de voz necesita HTTPS (o localhost). Conecta tu dominio para activarla — o dicta con el teclado del sistema.", micDenied: "El acceso al micrófono está bloqueado: permítelo para este sitio y vuelve a mantener el botón.", micNoDevice: "No se encontró ningún micrófono en este dispositivo.", frame: "El navegador bloquea el micrófono dentro de la vista previa: abre esta página en su propia pestaña para grabar.", failed: "No se pudo transcribir la grabación.", nothing: "No se reconoció nada — inténtalo de nuevo, más cerca del micrófono.", noKey: "La entrada de voz necesita la clave de OpenAI — añádela en los ajustes del espacio de trabajo.", draftTitle: "Transcrito: ¿insertar en el cursor?", accept: "Insertar", discard: "Descartar" },
  fr: { hold: "Maintenez pour parler", recording: "Enregistrement…", transcribing: "Transcription…", tipOk: "Maintenez pour parler ; relâchez pour transcrire. Le texte arrive à l'emplacement du curseur.", tipInsecure: "La saisie vocale nécessite HTTPS (ou localhost). Connectez votre domaine pour l'activer — ou dictez avec le clavier du système.", micDenied: "L'accès au microphone est bloqué : autorisez-le pour ce site puis maintenez à nouveau le bouton.", micNoDevice: "Aucun microphone n'a été trouvé sur cet appareil.", frame: "Le navigateur bloque le micro dans l'aperçu : ouvrez cette page dans son propre onglet pour enregistrer.", failed: "Impossible de transcrire l'enregistrement.", nothing: "Rien n'a été reconnu — réessayez, plus près du micro.", noKey: "La saisie vocale nécessite la clé OpenAI — ajoutez-la dans les paramètres de l'espace de travail.", draftTitle: "Transcrit — insérer au curseur ?", accept: "Insérer", discard: "Abandonner" },
  it: { hold: "Tieni premuto per parlare", recording: "Registrazione…", transcribing: "Trascrizione…", tipOk: "Tieni premuto per parlare; rilascia per trascrivere. Il testo va dove si trova il cursore.", tipInsecure: "L'input vocale richiede HTTPS (o localhost). Collega il tuo dominio per abilitarlo — oppure detta con la tastiera di sistema.", micDenied: "L'accesso al microfono è bloccato: consentilo per questo sito e tieni premuto di nuovo.", micNoDevice: "Nessun microfono trovato su questo dispositivo.", frame: "Il browser blocca il microfono nell'anteprima: apri questa pagina in una scheda propria per registrare.", failed: "Impossibile trascrivere la registrazione.", nothing: "Non è stato riconosciuto nulla — riprova, più vicino al microfono.", noKey: "L'input vocale richiede la chiave OpenAI — aggiungila nelle impostazioni dello spazio di lavoro.", draftTitle: "Trascritto — inserire al cursore?", accept: "Inserisci", discard: "Scarta" },
  ru: { hold: "Удерживайте для речи", recording: "Идёт запись…", transcribing: "Расшифровка…", tipOk: "Удерживайте, чтобы говорить; отпустите — расшифрую. Текст встанет туда, где курсор.", tipInsecure: "Голосовому вводу нужен HTTPS (или localhost). Подключите домен — или диктуйте системной клавиатурой.", micDenied: "Доступ к микрофону заблокирован — разрешите его для этого сайта и снова удерживайте кнопку.", micNoDevice: "На этом устройстве не найден микрофон.", frame: "В окне предпросмотра браузер блокирует микрофон — откройте эту страницу отдельной вкладкой, чтобы записать голос.", failed: "Не удалось расшифровать запись.", nothing: "Ничего не распознано — попробуйте ещё раз, ближе к микрофону.", noKey: "Для голосового ввода нужен ключ OpenAI — добавьте его в настройках рабочего пространства.", draftTitle: "Расшифровано — вставить туда, где курсор?", accept: "Вставить", discard: "Отменить" },
  de: { hold: "Zum Sprechen halten", recording: "Aufnahme…", transcribing: "Transkription…", tipOk: "Zum Sprechen gedrückt halten; loslassen zum Transkribieren. Der Text landet an der Cursorposition.", tipInsecure: "Spracheingabe braucht HTTPS (oder localhost). Verbinde deine Domain, um sie zu aktivieren — oder diktiere mit der Systemtastatur.", micDenied: "Der Mikrofonzugriff ist blockiert — erlaube ihn für diese Seite und halte die Taste erneut.", micNoDevice: "Auf diesem Gerät wurde kein Mikrofon gefunden.", frame: "In der Vorschau blockiert der Browser das Mikrofon — öffne diese Seite in einem eigenen Tab, um aufzunehmen.", failed: "Die Aufnahme konnte nicht transkribiert werden.", nothing: "Nichts erkannt — versuch es erneut, näher am Mikrofon.", noKey: "Spracheingabe braucht den OpenAI-Schlüssel — füge ihn in den Workspace-Einstellungen hinzu.", draftTitle: "Transkribiert — an der Cursorposition einfügen?", accept: "Einfügen", discard: "Verwerfen" },
  pt: { hold: "Mantenha pressionado para falar", recording: "A gravar…", transcribing: "A transcrever…", tipOk: "Mantenha pressionado para falar — solte para transcrever. O texto surge onde está o cursor.", tipInsecure: "A entrada de voz precisa de HTTPS (ou localhost). Ligue o seu domínio para a ativar — ou dite com o teclado do sistema.", micDenied: "O acesso ao microfone está bloqueado — permita-o para este site e mantenha o botão novamente.", micNoDevice: "Não foi encontrado nenhum microfone neste dispositivo.", frame: "O navegador bloqueia o microfone na pré-visualização — abra esta página no seu próprio separador para gravar.", failed: "Não foi possível transcrever a gravação.", nothing: "Nada foi reconhecido — tente novamente, mais perto do microfone.", noKey: "A entrada de voz precisa da chave OpenAI — adicione-a nas definições do espaço de trabalho.", draftTitle: "Transcrito — inserir no cursor?", accept: "Inserir", discard: "Descartar" },
  pl: { hold: "Przytrzymaj, aby mówić", recording: "Nagrywanie…", transcribing: "Transkrypcja…", tipOk: "Przytrzymaj, aby mówić — puść, aby przepisać. Tekst trafia tam, gdzie jest kursor.", tipInsecure: "Wprowadzanie głosowe wymaga HTTPS (lub localhost). Podłącz swoją domenę, aby je włączyć — lub dyktuj klawiaturą systemową.", micDenied: "Dostęp do mikrofonu jest zablokowany — zezwól na niego dla tej witryny i przytrzymaj przycisk ponownie.", micNoDevice: "Na tym urządzeniu nie znaleziono mikrofonu.", frame: "W podglądzie przeglądarka blokuje mikrofon — otwórz tę stronę we własnej karcie, aby nagrywać.", failed: "Nie udało się przepisać nagrania.", nothing: "Nic nie rozpoznano — spróbuj ponownie, bliżej mikrofonu.", noKey: "Wprowadzanie głosowe wymaga klucza OpenAI — dodaj go w ustawieniach przestrzeni roboczej.", draftTitle: "Przepisano — wstawić w miejscu kursora?", accept: "Wstaw", discard: "Odrzuć" },
  tr: { hold: "Konuşmak için basılı tutun", recording: "Kaydediliyor…", transcribing: "Metne dönüştürülüyor…", tipOk: "Konuşmak için basılı tutun — bırakınca metne dönüştürülür. Metin imlecin olduğu yere gelir.", tipInsecure: "Sesli giriş HTTPS (veya localhost) gerektirir. Etkinleştirmek için alan adınızı bağlayın — ya da sistem klavyenizle dikte edin.", micDenied: "Mikrofon erişimi engellendi — bu site için izin verin ve düğmeyi tekrar basılı tutun.", micNoDevice: "Bu cihazda mikrofon bulunamadı.", frame: "Önizleme içinde tarayıcı mikrofonu engeller — kaydetmek için bu sayfayı kendi sekmesinde açın.", failed: "Kayıt metne dönüştürülemedi.", nothing: "Hiçbir şey tanınmadı — mikrofona daha yakın olarak tekrar deneyin.", noKey: "Sesli giriş OpenAI anahtarı gerektirir — çalışma alanı ayarlarından ekleyin.", draftTitle: "Metne dönüştürüldü — imlecin olduğu yere eklensin mi?", accept: "Ekle", discard: "Vazgeç" },
  nl: { hold: "Ingedrukt houden om te spreken", recording: "Opname…", transcribing: "Transcriberen…", tipOk: "Houd ingedrukt om te spreken — laat los om te transcriberen. De tekst komt waar de cursor staat.", tipInsecure: "Spraakinvoer heeft HTTPS (of localhost) nodig. Koppel je domein om het in te schakelen — of dicteer met je systeemtoetsenbord.", micDenied: "Microfoontoegang is geblokkeerd — sta het toe voor deze site en houd de knop opnieuw ingedrukt.", micNoDevice: "Er is geen microfoon gevonden op dit apparaat.", frame: "In de voorvertoning blokkeert de browser de microfoon — open deze pagina in een eigen tabblad om op te nemen.", failed: "Kon de opname niet transcriberen.", nothing: "Er is niets herkend — probeer het opnieuw, dichter bij de microfoon.", noKey: "Spraakinvoer heeft de OpenAI-sleutel nodig — voeg deze toe in de werkruimte-instellingen.", draftTitle: "Getranscribeerd — invoegen bij de cursor?", accept: "Invoegen", discard: "Verwerpen" },
};

export const voiceStrings = (lang: string): VoiceStrings => VOICE_I18N[lang.slice(0, 2)] ?? VOICE_I18N.en;
