// AUTO-GENERATED by lib/parser-fs.mjs — DO NOT EDIT.
// Regenerated on every build/dev (npm prebuild/predev). Gitignored.
// Lists every post folder under this collection that has _data/index.ts.
import type { BlogData } from './_lib/post'
import { data as p0 } from './the-end-of-prompt-engineering/_data'
import { data as p1 } from './trillion-dollar-service-opportunity/_data'

export const POSTS: BlogData[] = [p0, p1]
