// Слова страницы товаров ПОКУПАТЕЛЯ.
//
// Четвёртый слой той же сущности; форма пути та же, что у соседей:
// `<раздел>/products`. Различает страницы роль, а не сущность.
//
// 🔒 ЯЗЫКОВ СТОЛЬКО, СКОЛЬКО ВКЛЮЧЕНО В ПАНЕЛИ — это строки одной страницы.
// Слова самой корзины лежат отдельно (`components/cart/cart.i18n.ts`): корзина
// показывается ещё и в шапке, то есть у неё двое потребителей, и общий предок им
// не эта папка.

export type ShoppingProductsUi = {
  title: string
  subtitle: string
  /** Полоса над таблицей: что здесь можно, чего нельзя. */
  buyOnly: string
}

const UI: Record<string, ShoppingProductsUi> = {
  en: {
    title: "Shopping",
    subtitle: "Your personal layer: here you are the customer. Pick quantities and collect an order — the cart travels with you across the site and survives a page reload. Everything else about a product is somebody else's job: names, prices, photographs and the catalogue itself are edited in the staff, finance and administration layers, and the server refuses those changes from this page even if the request is forged.",
    buyOnly: "You may add products to your order. Names, prices and the catalogue itself belong to the staff, finance and administration layers — the server refuses any change from this page.",
  },
  fr: { title: "Produits", subtitle: "Le catalogue tel que le voit un client : choisissez une quantité et ajoutez-la à la commande.", buyOnly: "Vous pouvez ajouter des produits à votre commande. Les noms, les prix et le catalogue lui-même appartiennent aux niveaux personnel, finances et administration — le serveur refuse toute modification depuis cette page." },
  es: { title: "Productos", subtitle: "El catálogo tal como lo ve un cliente: elija una cantidad y añádala al pedido.", buyOnly: "Puede añadir productos a su pedido. Los nombres, los precios y el propio catálogo pertenecen a las capas de personal, finanzas y administración: el servidor rechaza cualquier cambio desde esta página." },
  pt: { title: "Produtos", subtitle: "O catálogo como o cliente o vê: escolha uma quantidade e adicione-a ao pedido.", buyOnly: "Você pode adicionar produtos ao seu pedido. Os nomes, os preços e o próprio catálogo pertencem às camadas de equipe, finanças e administração — o servidor recusa qualquer alteração vinda desta página." },
  de: { title: "Produkte", subtitle: "Der Katalog aus Sicht des Kunden: Menge wählen und der Bestellung hinzufügen.", buyOnly: "Sie können Produkte zu Ihrer Bestellung hinzufügen. Namen, Preise und der Katalog selbst gehören den Ebenen Personal, Finanzen und Verwaltung — der Server lehnt jede Änderung von dieser Seite ab." },
  it: { title: "Prodotti", subtitle: "Il catalogo come lo vede un cliente: scegli una quantità e aggiungila all’ordine.", buyOnly: "Puoi aggiungere prodotti al tuo ordine. I nomi, i prezzi e il catalogo stesso appartengono ai livelli personale, finanza e amministrazione — il server rifiuta qualsiasi modifica da questa pagina." },
  nl: { title: "Producten", subtitle: "De catalogus zoals een klant hem ziet: kies een aantal en voeg het toe aan de bestelling.", buyOnly: "U kunt producten aan uw bestelling toevoegen. Namen, prijzen en de catalogus zelf horen bij de lagen personeel, financiën en administratie — de server weigert elke wijziging vanaf deze pagina." },
  sv: { title: "Produkter", subtitle: "Katalogen som kunden ser den: välj ett antal och lägg det i beställningen.", buyOnly: "Du kan lägga till produkter i din beställning. Namn, priser och själva katalogen tillhör personal-, ekonomi- och administrationsnivåerna — servern avvisar alla ändringar från den här sidan." },
  no: { title: "Produkter", subtitle: "Katalogen slik kunden ser den: velg et antall og legg det i bestillingen.", buyOnly: "Du kan legge produkter til bestillingen din. Navn, priser og selve katalogen tilhører personal-, økonomi- og administrasjonsnivåene — serveren avviser enhver endring fra denne siden." },
  da: { title: "Produkter", subtitle: "Kataloget, som kunden ser det: vælg et antal og læg det i bestillingen.", buyOnly: "Du kan tilføje produkter til din bestilling. Navne, priser og selve kataloget tilhører personale-, finans- og administrationslagene — serveren afviser enhver ændring fra denne side." },
  fi: { title: "Tuotteet", subtitle: "Luettelo asiakkaan silmin: valitse määrä ja lisää se tilaukseen.", buyOnly: "Voit lisätä tuotteita tilaukseesi. Nimet, hinnat ja itse luettelo kuuluvat henkilöstön, talouden ja hallinnon tasoille — palvelin hylkää kaikki muutokset tältä sivulta." },
  is: { title: "Vörur", subtitle: "Vörulistinn eins og viðskiptavinur sér hann: veldu magn og settu í pöntunina.", buyOnly: "Þú getur bætt vörum við pöntunina þína. Heiti, verð og vörulistinn sjálfur tilheyra starfsfólks-, fjármála- og stjórnunarlögunum — netþjónninn hafnar öllum breytingum frá þessari síðu." },
  el: { title: "Προϊόντα", subtitle: "Ο κατάλογος όπως τον βλέπει ο πελάτης: επιλέξτε ποσότητα και προσθέστε την στην παραγγελία.", buyOnly: "Μπορείτε να προσθέτετε προϊόντα στην παραγγελία σας. Τα ονόματα, οι τιμές και ο ίδιος ο κατάλογος ανήκουν στα επίπεδα προσωπικού, οικονομικών και διαχείρισης — ο διακομιστής απορρίπτει κάθε αλλαγή από αυτήν τη σελίδα." },
  pl: { title: "Produkty", subtitle: "Katalog oczami klienta: wybierz ilość i dodaj do zamówienia.", buyOnly: "Możesz dodawać produkty do swojego zamówienia. Nazwy, ceny i sam katalog należą do warstw personelu, finansów i administracji — serwer odrzuca każdą zmianę z tej strony." },
  cs: { title: "Produkty", subtitle: "Katalog očima zákazníka: zvolte množství a přidejte je do objednávky.", buyOnly: "Můžete přidávat produkty do své objednávky. Názvy, ceny a samotný katalog patří vrstvám personálu, financí a administrace — server odmítá jakoukoli změnu z této stránky." },
  sk: { title: "Produkty", subtitle: "Katalóg očami zákazníka: zvoľte množstvo a pridajte ho do objednávky.", buyOnly: "Môžete pridávať produkty do svojej objednávky. Názvy, ceny a samotný katalóg patria vrstvám personálu, financií a administrácie — server odmieta akúkoľvek zmenu z tejto stránky." },
  hu: { title: "Termékek", subtitle: "A katalógus úgy, ahogy a vásárló látja: válasszon mennyiséget, és tegye a rendelésbe.", buyOnly: "Termékeket adhat a rendeléséhez. A nevek, az árak és maga a katalógus a személyzeti, pénzügyi és adminisztrációs rétegekhez tartozik — a szerver minden erről az oldalról érkező módosítást elutasít." },
  ro: { title: "Produse", subtitle: "Catalogul așa cum îl vede clientul: alegeți o cantitate și adăugați-o în comandă.", buyOnly: "Puteți adăuga produse în comanda dumneavoastră. Numele, prețurile și catalogul însuși aparțin nivelurilor de personal, finanțe și administrare — serverul refuză orice modificare de pe această pagină." },
  hr: { title: "Proizvodi", subtitle: "Katalog očima kupca: odaberite količinu i dodajte je u narudžbu.", buyOnly: "Možete dodavati proizvode u svoju narudžbu. Nazivi, cijene i sam katalog pripadaju slojevima osoblja, financija i administracije — poslužitelj odbija svaku promjenu s ove stranice." },
  sl: { title: "Izdelki", subtitle: "Katalog z očmi kupca: izberite količino in jo dodajte v naročilo.", buyOnly: "Izdelke lahko dodajate v svoje naročilo. Imena, cene in sam katalog pripadajo plastem osebja, financ in administracije — strežnik zavrne vsako spremembo s te strani." },
  et: { title: "Tooted", subtitle: "Kataloog kliendi pilgu läbi: valige kogus ja lisage tellimusse.", buyOnly: "Saate lisada tooteid oma tellimusse. Nimed, hinnad ja kataloog ise kuuluvad personali-, rahandus- ja haldustasandile — server keeldub igasugusest muudatusest sellelt lehelt." },
  lv: { title: "Preces", subtitle: "Katalogs pircēja acīm: izvēlieties daudzumu un pievienojiet to pasūtījumam.", buyOnly: "Jūs varat pievienot preces savam pasūtījumam. Nosaukumi, cenas un pats katalogs pieder personāla, finanšu un administrācijas slāņiem — serveris atsakās no jebkādām izmaiņām šajā lapā." },
  lt: { title: "Prekės", subtitle: "Katalogas pirkėjo akimis: pasirinkite kiekį ir pridėkite jį prie užsakymo.", buyOnly: "Galite pridėti prekių prie savo užsakymo. Pavadinimai, kainos ir pats katalogas priklauso personalo, finansų ir administravimo lygmenims — serveris atsisako bet kokio pakeitimo iš šio puslapio." },
  mt: { title: "Prodotti", subtitle: "Il-katalgu kif jarah il-klijent: agħżel kwantità u żidha mal-ordni.", buyOnly: "Tista’ żżid prodotti mal-ordni tiegħek. L-ismijiet, il-prezzijiet u l-katalgu nnifsu jappartjenu għal-saffi tal-persunal, il-finanzi u l-amministrazzjoni — is-server jirrifjuta kwalunkwe bidla minn din il-paġna." },
  ca: { title: "Productes", subtitle: "El catàleg tal com el veu un client: trieu una quantitat i afegiu-la a la comanda.", buyOnly: "Podeu afegir productes a la vostra comanda. Els noms, els preus i el catàleg mateix pertanyen a les capes de personal, finances i administració — el servidor rebutja qualsevol canvi des d’aquesta pàgina." },
  gl: { title: "Produtos", subtitle: "O catálogo tal como o ve un cliente: escolla unha cantidade e engádaa ao pedido.", buyOnly: "Pode engadir produtos ao seu pedido. Os nomes, os prezos e o propio catálogo pertencen ás capas de persoal, finanzas e administración — o servidor rexeita calquera cambio desde esta páxina." },
  cy: { title: "Cynnyrch", subtitle: "Y catalog fel y mae cwsmer yn ei weld: dewiswch nifer ac ychwanegwch ef at yr archeb.", buyOnly: "Cewch ychwanegu cynnyrch at eich archeb. Mae enwau, prisiau a’r catalog ei hun yn perthyn i haenau staff, cyllid a gweinyddu — mae’r gweinydd yn gwrthod unrhyw newid o’r dudalen hon." },
  ga: { title: "Táirgí", subtitle: "An catalóg mar a fheiceann custaiméir í: roghnaigh méid agus cuir san ordú é.", buyOnly: "Is féidir leat táirgí a chur le d’ordú. Baineann na hainmneacha, na praghsanna agus an catalóg féin le sraitheanna na foirne, an airgeadais agus an riaracháin — diúltaíonn an freastalaí d’aon athrú ón leathanach seo." },
  eu: { title: "Produktuak", subtitle: "Katalogoa bezeroaren begiekin: aukeratu kopurua eta gehitu eskarian.", buyOnly: "Produktuak zure eskariari gehi diezazkiokezu. Izenak, prezioak eta katalogoa bera langile-, finantza- eta administrazio-geruzenak dira — zerbitzariak orri honetatik datorren edozein aldaketa ukatzen du." },
  ru: {
    title: "Покупка",
    subtitle: "Ваш личный слой: здесь вы покупатель. Выбирайте количество и собирайте заказ — корзина ходит с вами по сайту и переживает перезагрузку страницы. Всё остальное о товаре — не ваша забота: названия, цены, фотографии и сам каталог правятся в слоях персонала, финансов и администрирования, и сервер отклонит такое изменение с этой страницы, даже если запрос подделать.",
    buyOnly: "Вам доступно добавление товаров в заказ. Названия, цены и сам каталог принадлежат слоям персонала, финансов и администрирования — серверу этой страницы любое изменение запрещено.",
  },
  uk: { title: "Товари", subtitle: "Каталог очима покупця: виберіть кількість і додайте до замовлення.", buyOnly: "Вам доступне додавання товарів до замовлення. Назви, ціни та сам каталог належать шарам персоналу, фінансів та адміністрування — сервер цієї сторінки відхиляє будь-яку зміну." },
  be: { title: "Тавары", subtitle: "Каталог вачыма пакупніка: выберыце колькасць і дадайце ў замову.", buyOnly: "Вам даступна дадаванне тавараў у замову. Назвы, цэны і сам каталог належаць пластам персаналу, фінансаў і адміністравання — сервер гэтай старонкі адхіляе любую змену." },
  bg: { title: "Продукти", subtitle: "Каталогът през очите на купувача: изберете количество и го добавете в поръчката.", buyOnly: "Можете да добавяте продукти към поръчката си. Имената, цените и самият каталог принадлежат на слоевете персонал, финанси и администрация — сървърът отхвърля всяка промяна от тази страница." },
  sr: { title: "Производи", subtitle: "Каталог очима купца: изаберите количину и додајте је у поруџбину.", buyOnly: "Можете да додајете производе у своју поруџбину. Називи, цене и сам каталог припадају слојевима особља, финансија и администрације — сервер одбија сваку измену са ове странице." },
  bs: { title: "Proizvodi", subtitle: "Katalog očima kupca: odaberite količinu i dodajte je u narudžbu.", buyOnly: "Možete dodavati proizvode u svoju narudžbu. Nazivi, cijene i sam katalog pripadaju slojevima osoblja, finansija i administracije — server odbija svaku izmjenu s ove stranice." },
  mk: { title: "Производи", subtitle: "Каталогот низ очите на купувачот: изберете количина и додадете ја во нарачката.", buyOnly: "Можете да додавате производи во нарачката. Имињата, цените и самиот каталог припаѓаат на слоевите на персоналот, финансиите и администрацијата — серверот одбива секаква промена од оваа страница." },
  sq: { title: "Produktet", subtitle: "Katalogu siç e sheh blerësi: zgjidhni një sasi dhe shtojeni në porosi.", buyOnly: "Mund të shtoni produkte në porosinë tuaj. Emrat, çmimet dhe vetë katalogu i përkasin shtresave të stafit, financave dhe administratës — serveri refuzon çdo ndryshim nga kjo faqe." },
  kk: { title: "Тауарлар", subtitle: "Каталог сатып алушы көзімен: мөлшерін таңдап, тапсырысқа қосыңыз.", buyOnly: "Сіз тауарларды тапсырысыңызға қоса аласыз. Атаулар, бағалар және каталогтың өзі персонал, қаржы және әкімшілік қабаттарына тиесілі — сервер осы беттен келетін кез келген өзгертуден бас тартады." },
  uz: { title: "Mahsulotlar", subtitle: "Katalog xaridor ko‘zi bilan: miqdorni tanlang va buyurtmaga qo‘shing.", buyOnly: "Siz mahsulotlarni buyurtmangizga qo‘sha olasiz. Nomlar, narxlar va katalogning o‘zi xodimlar, moliya va boshqaruv qatlamlariga tegishli — server bu sahifadan kelgan har qanday o‘zgarishni rad etadi." },
  ky: { title: "Товарлар", subtitle: "Каталог сатып алуучунун көзү менен: санын тандап, буйрутмага кошуңуз.", buyOnly: "Сиз товарларды буйрутмаңызга кошо аласыз. Аттар, баалар жана каталогдун өзү персонал, каржы жана башкаруу катмарларына таандык — сервер бул беттен келген ар кандай өзгөртүүдөн баш тартат." },
  tg: { title: "Маҳсулот", subtitle: "Феҳрист аз назари харидор: миқдорро интихоб карда, ба фармоиш илова кунед.", buyOnly: "Шумо метавонед маҳсулотро ба фармоиши худ илова кунед. Номҳо, нархҳо ва худи феҳрист ба қабатҳои кормандон, молия ва маъмурият тааллуқ доранд — сервер ҳар гуна тағйиротро аз ин саҳифа рад мекунад." },
  tk: { title: "Harytlar", subtitle: "Katalog müşderiniň gözi bilen: mukdary saýlaň we sargyda goşuň.", buyOnly: "Siz harytlary sargydyňyza goşup bilersiňiz. Atlar, bahalar we katalogyň özi işgärler, maliýe we dolandyryş gatlaklaryna degişlidir — server bu sahypadan gelen islendik üýtgetmäni ret edýär." },
  az: { title: "Məhsullar", subtitle: "Kataloq alıcının gözü ilə: miqdarı seçin və sifarişə əlavə edin.", buyOnly: "Siz məhsulları sifarişinizə əlavə edə bilərsiniz. Adlar, qiymətlər və kataloqun özü heyət, maliyyə və inzibati qatlara aiddir — server bu səhifədən gələn hər hansı dəyişikliyi rədd edir." },
  hy: { title: "Ապրանքներ", subtitle: "Կատալոգը հաճախորդի աչքերով. ընտրեք քանակը և ավելացրեք պատվերին։", buyOnly: "Դուք կարող եք ապրանքներ ավելացնել ձեր պատվերին։ Անունները, գները և ինքնին կատալոգը պատկանում են անձնակազմի, ֆինանսների և վարչարարության շերտերին — սերվերը մերժում է այս էջից եկող ցանկացած փոփոխություն։" },
  ka: { title: "პროდუქტები", subtitle: "კატალოგი მყიდველის თვალით: აირჩიეთ რაოდენობა და დაამატეთ შეკვეთას.", buyOnly: "თქვენ შეგიძლიათ პროდუქტების დამატება თქვენს შეკვეთაში. სახელები, ფასები და თავად კატალოგი ეკუთვნის პერსონალის, ფინანსების და ადმინისტრირების შრეებს — სერვერი უარყოფს ამ გვერდიდან ნებისმიერ ცვლილებას." },
  mn: { title: "Бүтээгдэхүүнүүд", subtitle: "Худалдан авагчийн нүдээр харсан каталог: тоо ширхгийг сонгоод захиалгад нэмнэ үү.", buyOnly: "Та бүтээгдэхүүнийг захиалгадаа нэмж болно. Нэр, үнэ болон каталог өөрөө ажилтан, санхүү, удирдлагын давхаргад хамаарна — сервер энэ хуудаснаас ирсэн ямар ч өөрчлөлтийг татгалздаг." },
  ar: { title: "المنتجات", subtitle: "الكتالوج كما يراه الزبون: اختر الكمية وأضفها إلى الطلب.", buyOnly: "يمكنك إضافة منتجات إلى طلبك. الأسماء والأسعار والكتالوج نفسه ملك لطبقات الموظفين والمالية والإدارة — يرفض الخادم أي تغيير من هذه الصفحة." },
  tr: { title: "Ürünler", subtitle: "Katalog müşterinin gözüyle: bir miktar seçin ve siparişe ekleyin.", buyOnly: "Siparişinize ürün ekleyebilirsiniz. Adlar, fiyatlar ve katalogun kendisi personel, finans ve yönetim katmanlarına aittir — sunucu bu sayfadan gelen her türlü değişikliği reddeder." },
  he: { title: "מוצרים", subtitle: "הקטלוג כפי שהלקוח רואה אותו: בחרו כמות והוסיפו אותה להזמנה.", buyOnly: "ניתן להוסיף מוצרים להזמנה שלכם. השמות, המחירים והקטלוג עצמו שייכים לשכבות הצוות, הכספים והניהול — השרת דוחה כל שינוי המגיע מדף זה." },
  fa: { title: "محصولات", subtitle: "کاتالوگ از دید مشتری: مقدار را انتخاب کنید و به سفارش اضافه کنید.", buyOnly: "شما می‌توانید محصولات را به سفارش خود اضافه کنید. نام‌ها، قیمت‌ها و خود کاتالوگ متعلق به لایه‌های کارکنان، مالی و مدیریت است — سرور هر تغییری را از این صفحه رد می‌کند." },
  ku: { title: "Berhem", subtitle: "Katalog wek ku kirryar dibîne: hejmarê hilbijêrin û têxin nav siparîşê.", buyOnly: "Hûn dikarin berheman li siparîşa xwe zêde bikin. Nav, biha û katalog bi xwe yên qatên personel, darayî û rêveberiyê ne — server her guherîna ji vê rûpelê red dike." },
  af: { title: "Produkte", subtitle: "Die katalogus soos ’n klant dit sien: kies ’n hoeveelheid en voeg dit by die bestelling.", buyOnly: "U kan produkte by u bestelling voeg. Name, pryse en die katalogus self behoort aan die personeel-, finansies- en administrasielae — die bediener weier enige verandering vanaf hierdie bladsy." },
  sw: { title: "Bidhaa", subtitle: "Katalogi jinsi mteja anavyoiona: chagua idadi na uongeze kwenye agizo.", buyOnly: "Unaweza kuongeza bidhaa kwenye agizo lako. Majina, bei na katalogi yenyewe ni mali ya tabaka za wafanyakazi, fedha na utawala — seva inakataa mabadiliko yoyote kutoka kwenye ukurasa huu." },
  ha: { title: "Kayayyaki", subtitle: "Kundin kayayyaki kamar yadda mai siye yake gani: zaɓi adadi ka saka a cikin oda.", buyOnly: "Kana iya ƙara kayayyaki cikin odar ka. Sunaye, farashi da kundin kansa mallakar matakan ma’aikata, kuɗi da gudanarwa ne — sabar tana ƙin duk wani canji daga wannan shafi." },
  yo: { title: "Àwọn Ọjà", subtitle: "Àkójọ ọjà bí oníbàárà ṣe rí i: yan iye tí ó fẹ́ kí o sì fi kún àṣẹ ìbéèrè.", buyOnly: "O lè fi àwọn ọjà kún àṣẹ ìbéèrè rẹ. Orúkọ, owó àti àkójọ fúnra rẹ jẹ́ ti àwọn ẹ̀ka òṣìṣẹ́, owó àti àkóso — sáfà kọ̀ láti gba àyípadà kankan láti ojú-ìwé yìí." },
  ig: { title: "Ngwaahịa", subtitle: "Katalọgụ dịka onye ahịa hụrụ ya: họrọ ọnụọgụgụ ma tinye ya n'iwu.", buyOnly: "Ị nwere ike ịgbakwunye ngwaahịa n'iwu gị. Aha, ọnụahịa na katalọgụ n'onwe ya bụ nke akwaba ndị ọrụ, ego, na nchịkwa — ihe nkesa na-ajụ mgbanwe ọ bụla site na peeji a." },
  am: { title: "ምርቶች", subtitle: "ካታሎጉ በደንበኛ ዓይን፡ መጠን ይምረጡ እና ወደ ትዕዛዙ ያክሉት።", buyOnly: "ምርቶችን ወደ ትዕዛዝዎ ማከል ይችላሉ። ስሞች፣ ዋጋዎች እና ካታሎጉ ራሱ የሰራተኞች፣ የገንዘብ እና የአስተዳደር ንብርብሮች ንብረት ናቸው — አገልጋዩ ከዚህ ገጽ የሚመጣ ማንኛውንም ለውጥ ውድቅ ያደርጋል።" },
  zu: { title: "Imikhiqizo", subtitle: "Ikhathalogi njengoba ibonwa umthengi: khetha inani bese uyifaka ku-oda.", buyOnly: "Ungangeza imikhiqizo ku-oda lwakho. Amagama, amanani nekhathalogi ngokwayo kungokwezingqimba zabasebenzi, ezezimali nezokuphatha — iseva iyala noma yiluphi ushintsho oluvela kuleli khasi." },
  xh: { title: "Iimveliso", subtitle: "Ikhathalogu njengoko ibonwa ngumthengi: khetha inani bese uyongeza kwi-oda.", buyOnly: "Ungongeza iimveliso kwi-oda lwakho. Amagama, amaxabiso kunye nekhathalogu ngokwayo zezabasebenzi, ezemali nezolawulo — iseva iyakwala nayiphi na utshintsho oluvela kweli phepha." },
  rw: { title: "Ibicuruzwa", subtitle: "Katalogi nk'uko umuguzi ayibona: hitamo umubare uwushyire mu itumizo.", buyOnly: "Ushobora kongeramo ibicuruzwa mu itumizo ryawe. Amazina, ibiciro n'ikatalogi ubwayo ni iby'inzego z'abakozi, imari n'ubuyobozi — seriveri yanga impinduka izava kuri iyi paji." },
  so: { title: "Alaabta", subtitle: "Liiska sida macmiilku u arko: dooro tirada oo ku dar dalabka.", buyOnly: "Waxaad ku dari kartaa alaabta dalabkaaga. Magacyada, qiimaha, iyo liiska laftiisa waxay ka mid yihiin lakabyada shaqaalaha, maaliyadda iyo maamulka — server-ku wuu diidayaa isbeddel kasta oo ka yimaada boggan." },
  zh: { title: "商品", subtitle: "以顾客视角呈现的商品目录：选择数量并加入订单。", buyOnly: "您可以将商品添加到订单中。名称、价格及目录本身属于员工、财务和管理层，本页面的服务器拒绝任何修改。" },
  ja: { title: "商品", subtitle: "顧客の視点から見たカタログ：数量を選んで注文に追加します。", buyOnly: "商品を注文に追加することができます。名称、価格、カタログそのものはスタッフ・財務・管理の各層に属しており、このページからの変更はサーバーが拒否します。" },
  ko: { title: "상품", subtitle: "고객의 시선으로 본 카탈로그: 수량을 선택해 주문에 담으세요.", buyOnly: "상품을 주문에 추가할 수 있습니다. 이름, 가격, 카탈로그 자체는 직원·재무·관리 계층에 속하며, 이 페이지에서의 변경은 서버가 거부합니다." },
  hi: { title: "उत्पाद", subtitle: "ग्राहक की नज़र से कैटलॉग: मात्रा चुनें और उसे ऑर्डर में डालें।", buyOnly: "आप अपने ऑर्डर में उत्पाद जोड़ सकते हैं। नाम, कीमतें और स्वयं कैटलॉग स्टाफ़, वित्त और प्रशासन परतों के हैं — सर्वर इस पेज से आने वाले किसी भी बदलाव को अस्वीकार करता है।" },
  ur: { title: "مصنوعات", subtitle: "کیٹلاگ گاہک کی نظر سے: مقدار منتخب کریں اور اسے آرڈر میں شامل کریں۔", buyOnly: "آپ اپنے آرڈر میں مصنوعات شامل کر سکتے ہیں۔ نام، قیمتیں اور خود کیٹلاگ عملے، مالیات اور انتظامیہ کی سطحوں سے تعلق رکھتے ہیں — سرور اس صفحے سے آنے والی کسی بھی تبدیلی کو مسترد کرتا ہے۔" },
  bn: { title: "পণ্য", subtitle: "ক্রেতার দৃষ্টিতে ক্যাটালগ: পরিমাণ বেছে নিন এবং অর্ডারে যোগ করুন।", buyOnly: "আপনি আপনার অর্ডারে পণ্য যোগ করতে পারেন। নাম, দাম এবং ক্যাটালগ নিজেই স্টাফ, অর্থ এবং প্রশাসন স্তরের অন্তর্গত — সার্ভার এই পৃষ্ঠা থেকে আসা যেকোনো পরিবর্তন প্রত্যাখ্যান করে।" },
  te: { title: "ఉత్పత్తులు", subtitle: "కస్టమర్ దృష్టిలో కేటలాగ్: పరిమాణాన్ని ఎంచుకుని ఆర్డర్‌లో చేర్చండి.", buyOnly: "మీరు మీ ఆర్డర్‌కు ఉత్పత్తులను జోడించవచ్చు. పేర్లు, ధరలు మరియు కేటలాగ్ స్వయంగా సిబ్బంది, ఆర్థిక మరియు నిర్వహణ పొరలకు చెందినవి — ఈ పేజీ నుండి వచ్చే ఏ మార్పునైనా సర్వర్ తిరస్కరిస్తుంది." },
  mr: { title: "उत्पादने", subtitle: "ग्राहकाच्या नजरेतून कॅटलॉग: प्रमाण निवडा आणि ऑर्डरमध्ये टाका.", buyOnly: "तुम्ही तुमच्या ऑर्डरमध्ये उत्पादने जोडू शकता. नावे, किमती आणि कॅटलॉग स्वतः कर्मचारी, वित्त आणि प्रशासन स्तरांचे आहेत — या पानावरून येणारा कोणताही बदल सर्व्हर नाकारतो." },
  kn: { title: "ಉತ್ಪನ್ನಗಳು", subtitle: "ಗ್ರಾಹಕನ ದೃಷ್ಟಿಯಲ್ಲಿ ಕ್ಯಾಟಲಾಗ್: ಪ್ರಮಾಣವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಆರ್ಡರ್‌ಗೆ ಸೇರಿಸಿ.", buyOnly: "ನೀವು ನಿಮ್ಮ ಆರ್ಡರ್‌ಗೆ ಉತ್ಪನ್ನಗಳನ್ನು ಸೇರಿಸಬಹುದು. ಹೆಸರುಗಳು, ಬೆಲೆಗಳು ಮತ್ತು ಕ್ಯಾಟಲಾಗ್ ಸ್ವತಃ ಸಿಬ್ಬಂದಿ, ಹಣಕಾಸು ಮತ್ತು ಆಡಳಿತ ಪದರಗಳಿಗೆ ಸೇರಿವೆ — ಈ ಪುಟದಿಂದ ಬರುವ ಯಾವುದೇ ಬದಲಾವಣೆಯನ್ನು ಸರ್ವರ್ ತಿರಸ್ಕರಿಸುತ್ತದೆ." },
  gu: { title: "ઉત્પાદનો", subtitle: "ગ્રાહકની નજરે કેટલોગ: જથ્થો પસંદ કરો અને ઓર્ડરમાં ઉમેરો.", buyOnly: "તમે તમારા ઓર્ડરમાં ઉત્પાદનો ઉમેરી શકો છો. નામો, ભાવો અને કેટલોગ પોતે સ્ટાફ, નાણાં અને વહીવટ સ્તરોના છે — આ પાનાં પરથી આવતો કોઈપણ ફેરફાર સર્વર નકારે છે." },
  ml: { title: "ഉൽപ്പന്നങ്ങൾ", subtitle: "ഉപഭോക്താവിന്റെ കണ്ണിലൂടെ കാറ്റലോഗ്: അളവ് തിരഞ്ഞെടുത്ത് ഓർഡറിൽ ചേർക്കുക.", buyOnly: "നിങ്ങൾക്ക് ഉൽപ്പന്നങ്ങൾ നിങ്ങളുടെ ഓർഡറിൽ ചേർക്കാം. പേരുകൾ, വിലകൾ, കാറ്റലോഗ് തന്നെ ജീവനക്കാർ, ധനകാര്യം, ഭരണ നിർവഹണ പാളികളുടേതാണ് — ഈ പേജിൽ നിന്നുള്ള ഏതൊരു മാറ്റവും സെർവർ നിരസിക്കുന്നു." },
  ta: { title: "பொருட்கள்", subtitle: "வாடிக்கையாளர் பார்வையில் பட்டியல்: அளவைத் தேர்ந்தெடுத்து ஆர்டரில் சேர்க்கவும்.", buyOnly: "நீங்கள் உங்கள் ஆர்டரில் பொருட்களைச் சேர்க்கலாம். பெயர்கள், விலைகள் மற்றும் பட்டியல் தானே பணியாளர், நிதி மற்றும் நிர்வாக அடுக்குகளுக்கு சொந்தமானது — இந்தப் பக்கத்திலிருந்து வரும் எந்த மாற்றத்தையும் சேவையகம் நிராகரிக்கிறது." },
  ne: { title: "उत्पादनहरू", subtitle: "ग्राहकको दृष्टिमा क्याटलग: परिमाण छान्नुहोस् र अर्डरमा राख्नुहोस्।", buyOnly: "तपाईं आफ्नो अर्डरमा उत्पादनहरू थप्न सक्नुहुन्छ। नामहरू, मूल्यहरू र क्याटलग आफैं कर्मचारी, वित्त र प्रशासन तहका हुन् — यो पृष्ठबाट आउने कुनै पनि परिवर्तनलाई सर्भरले अस्वीकार गर्छ।" },
  vi: { title: "Sản phẩm", subtitle: "Danh mục dưới góc nhìn của khách hàng: chọn số lượng và thêm vào đơn hàng.", buyOnly: "Bạn có thể thêm sản phẩm vào đơn hàng của mình. Tên gọi, giá cả và bản thân danh mục thuộc về các lớp nhân sự, tài chính và quản trị — máy chủ từ chối mọi thay đổi từ trang này." },
  th: { title: "สินค้า", subtitle: "แคตตาล็อกในสายตาของลูกค้า: เลือกจำนวนแล้วใส่ลงในคำสั่งซื้อ", buyOnly: "คุณสามารถเพิ่มสินค้าลงในคำสั่งซื้อของคุณได้ ชื่อ ราคา และตัวแคตตาล็อกเองเป็นของชั้นพนักงาน การเงิน และการบริหาร — เซิร์ฟเวอร์ปฏิเสธการเปลี่ยนแปลงใด ๆ จากหน้านี้" },
  id: { title: "Produk", subtitle: "Katalog dari sudut pandang pelanggan: pilih jumlah dan masukkan ke pesanan.", buyOnly: "Anda dapat menambahkan produk ke pesanan Anda. Nama, harga, dan katalog itu sendiri milik lapisan staf, keuangan, dan administrasi — server menolak setiap perubahan dari halaman ini." },
  ms: { title: "Produk", subtitle: "Katalog dari sudut pandang pelanggan: pilih kuantiti dan masukkan ke dalam pesanan.", buyOnly: "Anda boleh menambah produk ke dalam pesanan anda. Nama, harga dan katalog itu sendiri adalah milik lapisan kakitangan, kewangan dan pentadbiran — pelayan menolak sebarang perubahan dari halaman ini." },
  tl: { title: "Mga Produkto", subtitle: "Ang katalogo sa mata ng customer: pumili ng dami at idagdag ito sa order.", buyOnly: "Maaari kang magdagdag ng mga produkto sa iyong order. Ang mga pangalan, presyo, at ang katalogo mismo ay pag-aari ng mga layer ng staff, pananalapi, at administrasyon — tinatanggihan ng server ang anumang pagbabago mula sa pahinang ito." },
  my: { title: "ကုန်ပစ္စည်းများ", subtitle: "ဖောက်သည်၏ရှုထောင့်မှကတ်တလောက်: အရေအတွက်ရွေးချယ်ပြီး အော်ဒါထဲသို့ထည့်ပါ။", buyOnly: "သင်သည် သင့်အော်ဒါထဲသို့ ကုန်ပစ္စည်းများထည့်နိုင်သည်။ အမည်များ၊ ဈေးနှုန်းများနှင့် ကတ်တလောက်ကိုယ်တိုင်သည် ဝန်ထမ်း၊ ဘဏ္ဍာရေးနှင့် စီမံခန့်ခွဲမှုအလွှာများပိုင်ဆိုင်သည် — ဤစာမျက်နှာမှလာသောမည်သည့်ပြောင်းလဲမှုကိုမဆို ဆာဗာကငြင်းပယ်သည်။" },
  km: { title: "ផលិតផល", subtitle: "កាតាឡុកតាមទស្សនៈអតិថិជន៖ ជ្រើសរើសបរិមាណ ហើយដាក់ចូលក្នុងការបញ្ជាទិញ។", buyOnly: "អ្នកអាចបន្ថែមផលិតផលទៅក្នុងការបញ្ជាទិញរបស់អ្នក។ ឈ្មោះ តម្លៃ និងកាតាឡុកខ្លួនឯងជាកម្មសិទ្ធិរបស់ស្រទាប់បុគ្គលិក ហិរញ្ញវត្ថុ និងរដ្ឋបាល — ម៉ាស៊ីនមេបដិសេធការផ្លាស់ប្តូរណាមួយពីទំព័រនេះ។" },
  lo: { title: "ສິນຄ້າ", subtitle: "ລາຍການສິນຄ້າໃນສາຍຕາຂອງລູກຄ້າ: ເລືອກຈຳນວນແລ້ວໃສ່ໃນຄຳສັ່ງຊື້.", buyOnly: "ທ່ານສາມາດເພີ່ມສິນຄ້າໃສ່ຄຳສັ່ງຊື້ຂອງທ່ານໄດ້. ຊື່, ລາຄາ ແລະ ລາຍການສິນຄ້າເອງເປັນຂອງຊັ້ນພະນັກງານ, ການເງິນ ແລະ ການບໍລິຫານ — ເຊີບເວີປະຕິເສດການປ່ຽນແປງໃດໆຈາກໜ້ານີ້." },
}

export function shoppingProductsUi(lang: string): ShoppingProductsUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
