// Слова страницы товаров АДМИНИСТРИРОВАНИЯ.
//
// Форма пути повторяет соседние слои: `<раздел>/products`. Сущность одна и та
// же во всех трёх, страницы различаются РОЛЬЮ: `/manage/products` ведёт
// менеджер, `/accounting/products` — бухгалтер, `/administration/products` —
// администратор.
//
// 🔒 ЯЗЫКОВ СТОЛЬКО, СКОЛЬКО ВКЛЮЧЕНО В ПАНЕЛИ (`NEXT_PUBLIC_SUPPORTED_LANGUAGES`,
// сейчас `en,ru`). Это строки одной страницы; заголовки слоёв прав в ящике
// аккаунта — другое дело, они переиспользуются в каждом проекте и написаны на 82.

export type AdministrationProductsUi = {
  title: string
  subtitle: string
  /** Полоса над таблицей: чем это право отличается от соседних. */
  deleteOnly: string
  confirm: string
  deleted: string
}

const UI: Record<string, AdministrationProductsUi> = {
  en: {
    title: "Administration",
    subtitle: "The administrative layer: one action, and it is irreversible. You delete products — there is no undo, no bin and no restore, which is exactly why deletion lives in its own role rather than beside editing. Everything else is read-only here: names, descriptions and prices belong to staff and finance. A layer whose only power is destruction is given out to few people on purpose.",
    deleteOnly: "You may delete a product — and nothing else: the name, price and description are edited by the staff and finance layers, and the server refuses any edit from this page. Deleting has no undo, which is why it is a separate role.",
    confirm: "Delete this product? This cannot be undone.",
    deleted: "Product deleted",
  },
  fr: { title: "Produits", subtitle: "Le catalogue tel que le voit l'administrateur : une seule action, et c'est l'irréversible.", deleteOnly: "Vous pouvez supprimer un produit — et rien d'autre : le nom, le prix et la description sont modifiés par les équipes du personnel et des finances, et le serveur refuse toute modification depuis cette page. La suppression est sans annulation possible, c'est pourquoi elle est confiée à un rôle à part.", confirm: "Supprimer ce produit ? Cette action est irréversible.", deleted: "Produit supprimé" },
  es: { title: "Productos", subtitle: "El catálogo tal como lo ve el administrador: una sola acción, y es la irreversible.", deleteOnly: "Puede eliminar un producto —y nada más—: el nombre, el precio y la descripción los edita el personal y las finanzas, y el servidor rechaza cualquier edición desde esta página. Eliminar no tiene deshacer, por eso está reservado a un rol aparte.", confirm: "¿Eliminar este producto? No se puede deshacer.", deleted: "Producto eliminado" },
  pt: { title: "Produtos", subtitle: "O catálogo como o administrador o vê: uma única ação, e é a irreversível.", deleteOnly: "Você pode excluir um produto — e mais nada: o nome, o preço e a descrição são editados pelas camadas de equipe e financeiro, e o servidor recusa qualquer edição a partir desta página. Excluir não tem desfazer, por isso está reservado a uma função à parte.", confirm: "Excluir este produto? Isso não pode ser desfeito.", deleted: "Produto excluído" },
  de: { title: "Produkte", subtitle: "Der Katalog aus Sicht des Administrators: eine einzige Aktion, und es ist die unwiderrufliche.", deleteOnly: "Sie dürfen ein Produkt löschen — und sonst nichts: Name, Preis und Beschreibung werden von den Ebenen Personal und Finanzen bearbeitet, und der Server lehnt jede Bearbeitung von dieser Seite aus ab. Löschen kennt kein Rückgängig, deshalb ist es einer eigenen Rolle vorbehalten.", confirm: "Dieses Produkt löschen? Das lässt sich nicht rückgängig machen.", deleted: "Produkt gelöscht" },
  it: { title: "Prodotti", subtitle: "Il catalogo come lo vede l'amministratore: un'unica azione, ed è quella irreversibile.", deleteOnly: "Puoi eliminare un prodotto — e nient'altro: nome, prezzo e descrizione vengono modificati dai livelli del personale e della finanza, e il server rifiuta qualsiasi modifica da questa pagina. L'eliminazione non ha annullamento, per questo è affidata a un ruolo separato.", confirm: "Eliminare questo prodotto? L'operazione non può essere annullata.", deleted: "Prodotto eliminato" },
  nl: { title: "Producten", subtitle: "De catalogus zoals de beheerder die ziet: één actie, en dat is de onomkeerbare.", deleteOnly: "U mag een product verwijderen — en verder niets: naam, prijs en beschrijving worden bewerkt door de personeels- en financiënlagen, en de server weigert elke bewerking vanaf deze pagina. Verwijderen kan niet ongedaan worden gemaakt, daarom is het een aparte rol.", confirm: "Dit product verwijderen? Dit kan niet ongedaan worden gemaakt.", deleted: "Product verwijderd" },
  sv: { title: "Produkter", subtitle: "Katalogen som administratören ser den: en enda åtgärd, och det är den oåterkalleliga.", deleteOnly: "Du får ta bort en produkt — och inget annat: namn, pris och beskrivning redigeras av personal- och ekonomiskikten, och servern nekar all redigering från denna sida. Borttagning kan inte ångras, därför är den en egen roll.", confirm: "Ta bort den här produkten? Det går inte att ångra.", deleted: "Produkten borttagen" },
  no: { title: "Produkter", subtitle: "Katalogen slik administratoren ser den: én handling, og det er den ugjenkallelige.", deleteOnly: "Du kan slette et produkt — og ikke noe annet: navn, pris og beskrivelse redigeres av personal- og økonomilagene, og serveren avviser all redigering fra denne siden. Sletting kan ikke angres, derfor er den en egen rolle.", confirm: "Slette dette produktet? Dette kan ikke angres.", deleted: "Produktet slettet" },
  da: { title: "Produkter", subtitle: "Kataloget som administratoren ser det: én handling, og det er den uigenkaldelige.", deleteOnly: "Du kan slette et produkt — og intet andet: navn, pris og beskrivelse redigeres af personale- og økonomilagene, og serveren afviser al redigering fra denne side. Sletning kan ikke fortrydes, derfor er den en separat rolle.", confirm: "Slet dette produkt? Det kan ikke fortrydes.", deleted: "Produkt slettet" },
  fi: { title: "Tuotteet", subtitle: "Luettelo pääkäyttäjän silmin: yksi toiminto, ja se on peruuttamaton.", deleteOnly: "Voit poistaa tuotteen — etkä muuta: nimeä, hintaa ja kuvausta muokkaavat henkilöstö- ja talouskerrokset, ja palvelin kieltää kaiken muokkauksen tältä sivulta. Poistolla ei ole kumoamista, siksi se on eriytetty omaan rooliin.", confirm: "Poistetaanko tämä tuote? Toimintoa ei voi perua.", deleted: "Tuote poistettu" },
  is: { title: "Vörur", subtitle: "Vörulistinn eins og stjórnandinn sér hann: ein aðgerð, og hún er óafturkræf.", deleteOnly: "Þú mátt eyða vöru — og ekkert annað: heiti, verð og lýsingu breyta starfsfólks- og fjármálalögin, og þjónninn hafnar allri breytingu frá þessari síðu. Eyðing hefur enga afturköllun, þess vegna er hún sér hlutverk.", confirm: "Eyða þessari vöru? Ekki er hægt að afturkalla þetta.", deleted: "Vöru eytt" },
  el: { title: "Προϊόντα", subtitle: "Ο κατάλογος όπως τον βλέπει ο διαχειριστής: μία ενέργεια, και είναι η μη αναστρέψιμη.", deleteOnly: "Μπορείτε να διαγράψετε ένα προϊόν — και τίποτα άλλο: το όνομα, την τιμή και την περιγραφή τα επεξεργάζονται τα επίπεδα προσωπικού και οικονομικών, και ο διακομιστής απορρίπτει κάθε επεξεργασία από αυτή τη σελίδα. Η διαγραφή δεν έχει αναίρεση, γι' αυτό αποτελεί ξεχωριστό ρόλο.", confirm: "Διαγραφή αυτού του προϊόντος; Δεν μπορεί να αναιρεθεί.", deleted: "Το προϊόν διαγράφηκε" },
  pl: { title: "Produkty", subtitle: "Katalog oczami administratora: jedna czynność, i to ta nieodwracalna.", deleteOnly: "Możesz usunąć produkt — i nic więcej: nazwę, cenę i opis edytują warstwy personelu i finansów, a serwer odrzuca każdą edycję z tej strony. Usuwanie nie ma cofnięcia, dlatego jest wydzielone do osobnej roli.", confirm: "Usunąć ten produkt? Nie da się tego cofnąć.", deleted: "Produkt usunięty" },
  cs: { title: "Produkty", subtitle: "Katalog očima administrátora: jedna akce, a je to ta nevratná.", deleteOnly: "Můžete produkt smazat — a nic víc: název, cenu a popis upravují vrstvy personálu a financí a server odmítá jakoukoli úpravu z této stránky. Smazání nelze vzít zpět, proto je vyčleněno do samostatné role.", confirm: "Smazat tento produkt? Nelze to vrátit zpět.", deleted: "Produkt smazán" },
  sk: { title: "Produkty", subtitle: "Katalóg očami administrátora: jedna akcia, a je to tá nevratná.", deleteOnly: "Môžete produkt vymazať — a nič iné: názov, cenu a popis upravujú vrstvy personálu a financií a server odmieta akúkoľvek úpravu z tejto stránky. Vymazanie nemá spätné vzatie, preto je vyčlenené do samostatnej role.", confirm: "Vymazať tento produkt? Toto nie je možné vrátiť späť.", deleted: "Produkt vymazaný" },
  hu: { title: "Termékek", subtitle: "A katalógus úgy, ahogy az adminisztrátor látja: egyetlen művelet, és az a visszavonhatatlan.", deleteOnly: "Ön törölhet egy terméket — és semmi mást: a nevet, az árat és a leírást a személyzeti és pénzügyi rétegek szerkesztik, a szerver pedig elutasít minden szerkesztést erről az oldalról. A törlésnek nincs visszavonása, ezért külön szerepkörbe van kiszervezve.", confirm: "Törli ezt a terméket? Ez nem vonható vissza.", deleted: "Termék törölve" },
  ro: { title: "Produse", subtitle: "Catalogul așa cum îl vede administratorul: o singură acțiune, și este cea ireversibilă.", deleteOnly: "Puteți șterge un produs — și nimic altceva: numele, prețul și descrierea sunt editate de straturile de personal și finanțe, iar serverul refuză orice editare de pe această pagină. Ștergerea nu are anulare, de aceea este separată într-un rol distinct.", confirm: "Ștergeți acest produs? Această acțiune nu poate fi anulată.", deleted: "Produs șters" },
  hr: { title: "Proizvodi", subtitle: "Katalog očima administratora: jedna radnja, i to je ona nepovratna.", deleteOnly: "Možete izbrisati proizvod — i ništa drugo: naziv, cijenu i opis uređuju slojevi osoblja i financija, a poslužitelj odbija svaku izmjenu s ove stranice. Brisanje nema opoziv, zato je izdvojeno u posebnu ulogu.", confirm: "Izbrisati ovaj proizvod? To se ne može poništiti.", deleted: "Proizvod izbrisan" },
  sl: { title: "Izdelki", subtitle: "Katalog, kot ga vidi skrbnik: eno dejanje, in to je tisto nepovratno.", deleteOnly: "Izdelek lahko izbrišete — in nič drugega: ime, ceno in opis urejata plast osebja in financ, strežnik pa zavrne vsako urejanje s te strani. Brisanje nima razveljavitve, zato je izločeno v ločeno vlogo.", confirm: "Izbrišem ta izdelek? Tega ni mogoče razveljaviti.", deleted: "Izdelek izbrisan" },
  et: { title: "Tooted", subtitle: "Kataloog administraatori pilgu läbi: üks toiming, ja see on pöördumatu.", deleteOnly: "Te tohite toote kustutada — ja mitte midagi muud: nime, hinda ja kirjeldust muudavad personali- ja finantskihid ning server keeldub sellelt lehelt igasugusest muutmisest. Kustutamisel puudub tagasivõtmine, seepärast on see eraldi rolliks eraldatud.", confirm: "Kas kustutada see toode? Seda ei saa tagasi võtta.", deleted: "Toode kustutatud" },
  lv: { title: "Preces", subtitle: "Katalogs administratora acīm: viena darbība, un tā ir neatgriezeniska.", deleteOnly: "Jūs varat dzēst preci — un neko citu: nosaukumu, cenu un aprakstu rediģē personāla un finanšu slāņi, un serveris atsakās no jebkuras rediģēšanas šajā lapā. Dzēšanai nav atsaukšanas, tāpēc tā ir izdalīta atsevišķā lomā.", confirm: "Dzēst šo preci? To nevar atsaukt.", deleted: "Prece dzēsta" },
  lt: { title: "Prekės", subtitle: "Katalogas administratoriaus akimis: vienas veiksmas, ir jis negrįžtamas.", deleteOnly: "Galite ištrinti prekę — ir nieko daugiau: pavadinimą, kainą ir aprašymą redaguoja personalo ir finansų sluoksniai, o serveris atsisako bet kokio redagavimo iš šio puslapio. Trynimas neturi atšaukimo, todėl jis išskirtas į atskirą vaidmenį.", confirm: "Ištrinti šią prekę? Šio veiksmo atšaukti negalima.", deleted: "Prekė ištrinta" },
  mt: { title: "Prodotti", subtitle: "Il-katalgu kif jarah l-amministratur: azzjoni waħda, u hija dik li ma tistax titreġġa' lura.", deleteOnly: "Tista' tħassar prodott — u xejn aktar: l-isem, il-prezz u d-deskrizzjoni jiġu editjati mil-livelli tal-persunal u tal-finanzi, u s-server jirrifjuta kwalunkwe editjar minn din il-paġna. It-tħassir ma għandux disfar, għalhekk huwa maqtugħ f'rwol separat.", confirm: "Tħassar dan il-prodott? Dan ma jistax jitreġġa' lura.", deleted: "Prodott imħassar" },
  ca: { title: "Productes", subtitle: "El catàleg tal com el veu l'administrador: una sola acció, i és la irreversible.", deleteOnly: "Podeu suprimir un producte — i res més: el nom, el preu i la descripció els editen les capes de personal i finances, i el servidor rebutja qualsevol edició des d'aquesta pàgina. Suprimir no té desfer, per això és un rol a part.", confirm: "Suprimir aquest producte? Això no es pot desfer.", deleted: "Producte suprimit" },
  gl: { title: "Produtos", subtitle: "O catálogo tal e como o ve o administrador: unha soa acción, e é a irreversible.", deleteOnly: "Podes eliminar un produto — e nada máis: o nome, o prezo e a descrición edítanas as capas de persoal e finanzas, e o servidor rexeita calquera edición desde esta páxina. Eliminar non ten desfacer, por iso está reservado a un rol á parte.", confirm: "Eliminar este produto? Isto non se pode desfacer.", deleted: "Produto eliminado" },
  cy: { title: "Cynhyrchion", subtitle: "Y catalog fel y mae'r gweinyddwr yn ei weld: un weithred, a honno yw'r un na ellir ei dadwneud.", deleteOnly: "Cewch ddileu cynnyrch — a dim byd arall: mae'r enw, y pris a'r disgrifiad yn cael eu golygu gan haenau'r staff a'r cyllid, ac mae'r gweinydd yn gwrthod unrhyw olygiad o'r dudalen hon. Nid oes dadwneud i ddileu, a dyna pam mae'n rôl ar wahân.", confirm: "Dileu'r cynnyrch hwn? Ni ellir dadwneud hyn.", deleted: "Cynnyrch wedi'i ddileu" },
  ga: { title: "Táirgí", subtitle: "An catalóg mar a fheiceann an riarthóir í: gníomh amháin, agus is é an ceann do-aisiompaithe é.", deleteOnly: "Is féidir leat táirge a scriosadh — agus dada eile: an t-ainm, an praghas agus an cur síos, cuireann na sraitheanna foirne agus airgeadais in eagar iad, agus diúltaíonn an freastalaí d'aon eagarthóireacht ón leathanach seo. Níl aon chealú ag scriosadh, agus sin an fáth a bhfuil sé scartha ina ról ar leith.", confirm: "An táirge seo a scriosadh? Ní féidir é seo a chealú.", deleted: "Táirge scriosta" },
  eu: { title: "Produktuak", subtitle: "Katalogoa administratzaileak ikusten duen bezala: ekintza bakarra, eta atzeraezina da.", deleteOnly: "Produktu bat ezaba dezakezu — eta besterik ez: izena, prezioa eta deskribapena langile eta finantza geruzek editatzen dituzte, eta zerbitzariak orri honetatik edozein edizio ukatzen du. Ezabatzeak ez du desegiterik, horregatik dago rol bereizi batean.", confirm: "Produktu hau ezabatu? Hau ezin da desegin.", deleted: "Produktua ezabatuta" },
  ru: {
    title: "Администрирование",
    subtitle: "Административный слой: одно действие, и оно необратимое. Вы удаляете товары — без «отменить», без корзины и без восстановления, и именно поэтому удаление вынесено в отдельную роль, а не поставлено рядом с правкой. Всё прочее здесь только для чтения: названия, описания и цены принадлежат персоналу и финансам. Слой, единственная сила которого — разрушение, раздаётся немногим намеренно.",
    deleteOnly: "Вам доступно удаление товара — и больше ничего: название, цену и описание правят слои персонала и финансов, а серверу этой страницы правка запрещена. У удаления нет «отменить», поэтому оно и вынесено в отдельную роль.",
    confirm: "Удалить товар? Отменить это будет нельзя.",
    deleted: "Товар удалён",
  },
  uk: { title: "Товари", subtitle: "Каталог очима адміністратора: одна дія, і вона незворотна.", deleteOnly: "Вам доступне видалення товару — і більше нічого: назву, ціну та опис редагують шари персоналу й фінансів, а серверу цієї сторінки редагування заборонено. У видалення немає «скасувати», тому воно винесене в окрему роль.", confirm: "Видалити товар? Скасувати це буде неможливо.", deleted: "Товар видалено" },
  be: { title: "Тавары", subtitle: "Каталог вачыма адміністратара: адно дзеянне, і яно незваротнае.", deleteOnly: "Вам даступна выдаленне тавару — і больш нічога: назву, цану і апісанне рэдагуюць слаі персаналу і фінансаў, а серверу гэтай старонкі рэдагаванне забаронена. У выдалення няма «адрабіць назад», таму яно вынесена ў асобную ролю.", confirm: "Выдаліць тавар? Адрабіць гэта будзе немагчыма.", deleted: "Тавар выдалены" },
  bg: { title: "Продукти", subtitle: "Каталогът през очите на администратора: едно действие, и то е необратимото.", deleteOnly: "Разполагате само с изтриване на продукт — и нищо друго: името, цената и описанието се редактират от слоевете на персонала и финансите, а сървърът отказва всяко редактиране от тази страница. Изтриването няма отмяна, затова е обособено в отделна роля.", confirm: "Да се изтрие ли този продукт? Това не може да бъде отменено.", deleted: "Продуктът е изтрит" },
  sr: { title: "Производи", subtitle: "Каталог очима администратора: једна радња, и то она неповратна.", deleteOnly: "Можете само да обришете производ — и ништа друго: назив, цену и опис уређују слојеви особља и финансија, а сервер одбија сваку измену са ове странице. Брисање нема опозив, зато је издвојено у посебну улогу.", confirm: "Обрисати овај производ? Ово се не може поништити.", deleted: "Производ обрисан" },
  bs: { title: "Proizvodi", subtitle: "Katalog očima administratora: jedna radnja, i to ona nepovratna.", deleteOnly: "Možete samo obrisati proizvod — i ništa drugo: naziv, cijenu i opis uređuju slojevi osoblja i finansija, a server odbija svaku izmjenu sa ove stranice. Brisanje nema opoziv, zato je izdvojeno u posebnu ulogu.", confirm: "Obrisati ovaj proizvod? Ovo se ne može poništiti.", deleted: "Proizvod obrisan" },
  mk: { title: "Производи", subtitle: "Каталогот преку очите на администраторот: едно дејство, и тоа е неповратното.", deleteOnly: "Ви е достапно само бришење производ — и ништо друго: името, цената и описот ги уредуваат слоевите на персоналот и финансиите, а серверот одбива секое уредување од оваа страница. Бришењето нема отповикување, затоа е издвоено во посебна улога.", confirm: "Да се избрише овој производ? Ова не може да се врати.", deleted: "Производот е избришан" },
  sq: { title: "Produktet", subtitle: "Katalogu siç e sheh administratori: një veprim i vetëm, dhe ai është i pakthyeshmi.", deleteOnly: "Ju mund të fshini vetëm një produkt — dhe asgjë tjetër: emrin, çmimin dhe përshkrimin i editojnë shtresat e stafit dhe të financave, dhe serveri refuzon çdo editim nga kjo faqe. Fshirja nuk ka zhbërje, prandaj është veçuar në një rol të ndarë.", confirm: "Ta fshij këtë produkt? Kjo nuk mund të zhbëhet.", deleted: "Produkti u fshi" },
  kk: { title: "Тауарлар", subtitle: "Каталог әкімші көзімен: бір ғана әрекет, және ол — қайтарылмайтын әрекет.", deleteOnly: "Сізге тек тауарды жоюға ғана рұқсат бар — басқа ештеңеге жоқ: атауын, бағасын және сипаттамасын персонал мен қаржы қабаттары өзгертеді, ал бұл беттен серверге ешбір өзгерту жасауға болмайды. Жоюдың «болдырмау» опциясы жоқ, сондықтан ол бөлек рөлге бөлінген.", confirm: "Бұл тауарды жою керек пе? Мұны болдырмау мүмкін емес.", deleted: "Тауар жойылды" },
  uz: { title: "Mahsulotlar", subtitle: "Katalog administrator ko'zi bilan: bitta amal, va u — qaytarib bo'lmaydigan amal.", deleteOnly: "Sizga faqat mahsulotni o'chirish mumkin — boshqa hech narsa emas: nomi, narxi va tavsifini xodimlar va moliya qatlamlari tahrirlaydi, bu sahifadan esa serverga hech qanday tahrir kiritish taqiqlangan. O'chirishning «bekor qilish»i yo'q, shuning uchun u alohida rolga ajratilgan.", confirm: "Ushbu mahsulot o'chirilsinmi? Buni bekor qilib bo'lmaydi.", deleted: "Mahsulot o'chirildi" },
  ky: { title: "Товарлар", subtitle: "Каталог администратордун көзү менен: бир гана аракет, жана ал — кайтарылгыс аракет.", deleteOnly: "Сизге товарды жок кылуу гана мүмкүн — башка эч нерсе эмес: атын, баасын жана сүрөттөлүшүн персонал жана каржы катмарлары түзөтөт, ал эми бул беттен серверге эч кандай түзөтүү жасоого болбойт. Жок кылуунун «жокко чыгаруу» мүмкүнчүлүгү жок, ошондуктан ал өзүнчө ролго бөлүнгөн.", confirm: "Бул товар жок кылынсынбы? Муну жокко чыгарууга болбойт.", deleted: "Товар жок кылынды" },
  tg: { title: "Молҳо", subtitle: "Феҳрист аз назари маъмур: як амал, ва он бебозгашт аст.", deleteOnly: "Ба шумо танҳо нест кардани мол дастрас аст — ва дигар ҳеҷ чиз: номро, нархро ва тавсифро қабатҳои кормандон ва молия таҳрир мекунанд, ва сервер ба ин саҳифа ҳар гуна таҳрирро рад мекунад. Несткунӣ бекоркунӣ надорад, аз ин рӯ он ба нақши алоҳида ҷудо шудааст.", confirm: "Ин мол нест карда шавад? Инро бозгардонидан мумкин нест.", deleted: "Мол нест карда шуд" },
  tk: { title: "Harytlar", subtitle: "Katalog administratoryň gözi bilen: ýeke-täk hereket, we ol — yzyna gaýtarylmajak hereket.", deleteOnly: "Size diňe haryt öçürmek elýeterli — başga hiç zat däl: ady, bahasy we beýany işgärler we maliýe gatlaklary tarapyndan üýtgedilýär, bu sahypadan bolsa serwer islendik üýtgetmäni ret edýär. Öçürmegiň «yzyna almak» ýok, şoňa görä-de ol aýratyn rola bölünen.", confirm: "Bu haryt öçürilsinmi? Muny yzyna almak mümkin däl.", deleted: "Haryt öçürildi" },
  az: { title: "Məhsullar", subtitle: "Kataloq administratorun gözü ilə: yalnız bir hərəkət, və o geri qaytarılmazdır.", deleteOnly: "Sizə yalnız məhsulu silmək əlçatandır — başqa heç nə: adını, qiymətini və təsvirini heyət və maliyyə qatları redaktə edir, bu səhifədən isə serverə heç bir redaktə etməyə icazə verilmir. Silmənin «geri qaytar»ı yoxdur, buna görə də o ayrıca rola bölünüb.", confirm: "Bu məhsul silinsin? Bunu geri qaytarmaq mümkün olmayacaq.", deleted: "Məhsul silindi" },
  hy: { title: "Ապրանքներ", subtitle: "Ցանկը ադմինիստրատորի աչքերով. մեկ գործողություն, և այն անդառնալի է։", deleteOnly: "Ձեզ հասանելի է միայն ապրանքի ջնջումը — և ուրիշ ոչինչ. անվանումը, գինը և նկարագրությունը խմբագրում են անձնակազմի և ֆինանսների շերտերը, և սերվերն այս էջից մերժում է ցանկացած խմբագրում։ Ջնջումը «հետ վերադարձնել» չունի, հենց դրա համար այն առանձնացված է առանձին դերի մեջ։", confirm: "Ջնջե՞լ այս ապրանքը։ Սա հետ վերադարձնել հնարավոր չէ։", deleted: "Ապրանքը ջնջվեց" },
  ka: { title: "პროდუქტები", subtitle: "კატალოგი ადმინისტრატორის თვალით: ერთი მოქმედება, და ის შეუქცევადია.", deleteOnly: "თქვენთვის ხელმისაწვდომია მხოლოდ პროდუქტის წაშლა — და სხვა არაფერი: სახელს, ფასს და აღწერას ცვლის პერსონალისა და ფინანსების შრეები, ხოლო სერვერი უარყოფს ნებისმიერ რედაქტირებას ამ გვერდიდან. წაშლას არ აქვს გაუქმება, სწორედ ამიტომ ის გამოყოფილია ცალკე როლში.", confirm: "წავშალო ეს პროდუქტი? ამის გაუქმება შეუძლებელი იქნება.", deleted: "პროდუქტი წაშლილია" },
  mn: { title: "Бүтээгдэхүүнүүд", subtitle: "Каталогийг администратор хэрхэн харах вэ: ганцхан үйлдэл, тэр нь буцаагдашгүй үйлдэл юм.", deleteOnly: "Танд зөвхөн бүтээгдэхүүнийг устгах боломжтой — өөр юу ч биш: нэр, үнэ, тайлбарыг ажилтан болон санхүүгийн давхаргууд засварладаг бөгөөд серверт энэ хуудаснаас засвар хийхийг хориглодог. Устгахад «буцаах» гэж байхгүй, тиймээс энэ нь тусдаа эрхэд оноогдсон.", confirm: "Энэ бүтээгдэхүүнийг устгах уу? Үүнийг буцаах боломжгүй.", deleted: "Бүтээгдэхүүн устгагдлаа" },
  ar: { title: "المنتجات", subtitle: "الكتالوج كما يراه المسؤول: إجراء واحد، وهو الإجراء الذي لا رجعة فيه.", deleteOnly: "المتاح لك هو حذف المنتج فقط — ولا شيء غيره: الاسم والسعر والوصف تحررها طبقتا الموظفين والمالية، ويرفض الخادم أي تعديل من هذه الصفحة. الحذف لا رجعة فيه، ولهذا خُصّص له دور منفصل.", confirm: "هل تريد حذف هذا المنتج؟ لا يمكن التراجع عن هذا.", deleted: "تم حذف المنتج" },
  tr: { title: "Ürünler", subtitle: "Katalog yöneticinin gözünden: tek bir işlem, ve o geri alınamaz olandır.", deleteOnly: "Yalnızca ürünü silme yetkiniz var — başka hiçbir şey değil: adını, fiyatını ve açıklamasını personel ve finans katmanları düzenler, sunucu ise bu sayfadan gelen her türlü düzenlemeyi reddeder. Silmenin geri alması yoktur, bu yüzden ayrı bir role ayrılmıştır.", confirm: "Bu ürün silinsin mi? Bu işlem geri alınamaz.", deleted: "Ürün silindi" },
  he: { title: "מוצרים", subtitle: "הקטלוג בעיני המנהל: פעולה אחת, וזו הבלתי הפיכה.", deleteOnly: "העומד לרשותכם הוא רק מחיקת מוצר — ולא יותר מכך: את השם, המחיר והתיאור עורכות שכבות הצוות והכספים, והשרת דוחה כל עריכה מדף זה. למחיקה אין ביטול, ולכן היא הופרדה לתפקיד נפרד.", confirm: "למחוק את המוצר הזה? לא ניתן לבטל פעולה זו.", deleted: "המוצר נמחק" },
  fa: { title: "محصولات", subtitle: "کاتالوگ از دید مدیر: یک اقدام، و همان اقدام برگشت‌ناپذیر است.", deleteOnly: "تنها حذف محصول در اختیار شماست — و نه چیز دیگری: نام، قیمت و توضیحات را لایه‌های کارکنان و مالی ویرایش می‌کنند و سرور هرگونه ویرایش از این صفحه را رد می‌کند. حذف بازگشتی ندارد، به همین دلیل به نقشی جداگانه اختصاص یافته است.", confirm: "این محصول حذف شود؟ این کار قابل بازگشت نیست.", deleted: "محصول حذف شد" },
  ku: { title: "Berhem", subtitle: "Katalog ji çavê rêveberê ve: tenê kirinek, û ew kirina venegerî ye.", deleteOnly: "Tenê rakirina berhemê li ba te vekirî ye — û tiştek din na: nav, biha û şirovekirin ji aliyê qatên karmend û darayî ve tê guhertin, û pêşkêşkar her guherînek ji vê rûpelê red dike. Rakirin venegerî ye, ji ber vê yekê ew ji bo rolek cuda hatiye veqetandin.", confirm: "Ev berhem were rakirin? Ev kar venagere.", deleted: "Berhem hate rakirin" },
  af: { title: "Produkte", subtitle: "Die katalogus soos die administrateur dit sien: een aksie, en dit is die onomkeerbare een.", deleteOnly: "U mag slegs 'n produk verwyder — en niks anders nie: die naam, prys en beskrywing word deur die personeel- en finansiële lae geredigeer, en die bediener weier enige redigering vanaf hierdie bladsy. Verwydering het geen ontdoen nie, en daarom is dit in 'n aparte rol geplaas.", confirm: "Hierdie produk verwyder? Dit kan nie ontdoen word nie.", deleted: "Produk verwyder" },
  sw: { title: "Bidhaa", subtitle: "Katalogi kama anavyoiona msimamizi: kitendo kimoja, nacho ndicho kisichoweza kutenduliwa.", deleteOnly: "Unaruhusiwa tu kufuta bidhaa — na hakuna kingine: jina, bei na maelezo yanahaririwa na tabaka za wafanyakazi na fedha, na seva inakataa uhariri wowote kutoka ukurasa huu. Kufuta hakuna kutendua, ndiyo maana kumetengwa kuwa jukumu tofauti.", confirm: "Ufute bidhaa hii? Hii haiwezi kutenduliwa.", deleted: "Bidhaa imefutwa" },
  ha: { title: "Kayayyaki", subtitle: "Jerin abubuwa kamar yadda manaja ke gani: aiki ɗaya kaɗai, kuma shi ne wanda ba za a iya sokewa ba.", deleteOnly: "Abin da kake da izinin yi shi ne share kaya kawai — babu wani abu: suna, farashi da bayani ma'aikata da matakan kuɗi ne ke gyara su, kuma sabar ta ƙi duk wani gyara daga wannan shafi. Sharewa ba ta da mayarwa, don haka an keɓe ta ga wata rawar dabam.", confirm: "A share wannan kayan? Ba za a iya mayar da wannan ba.", deleted: "An share kayan" },
  yo: { title: "Àwọn ọjà", subtitle: "Àkójọ bí alábòójútó ṣe rí i: iṣe kan ṣoṣo, ó sì ni èyí tí kò ṣeé yí padà.", deleteOnly: "Ìparẹ́ ọjà nìkan ni o ní àǹfààní sí — kò sí ohunkóhun mìíràn: orúkọ, iye owó, àti àpèjúwe ni àwọn ìpele òṣìṣẹ́ àti ti owó ń ṣàtúnṣe, olùṣàkóso yóò sì kọ èyíkéyìí àtúnṣe láti ojú ìwé yìí sílẹ̀. Ìparẹ́ kò ní ìdásẹ́yìn, ìdí nìyí tí a fi yà á sọ́tọ̀ sí ipò ọ̀tọ̀.", confirm: "Pa ọjà yìí rẹ́? A kò lè dá èyí padà.", deleted: "A ti pa ọjà náà rẹ́" },
  ig: { title: "Ngwaahịa", subtitle: "Katalọgụ dịka onye nchịkwa hụrụ ya: otu omume, ọ bụkwa nke a na-agaghị eme ọzọ.", deleteOnly: "Naanị ihe ị nwere ike ime bụ ihichapụ ngwaahịa — ọ dịghị ihe ọzọ: aha, ọnụahịa na nkọwa ka ndị ọrụ na ndị akụ na ụba na-edezi, sava na-ajụkwa mgbanwe ọ bụla site na peeji a. Ihichapụ enweghị ịkwụghachi azụ, ọ bụ ya mere e ji hazie ya ka ọ bụrụ ọrụ dị iche.", confirm: "Hichapụ ngwaahịa a? Enweghị ike ịkwụghachi nke a azụ.", deleted: "E hichapụla ngwaahịa" },
  am: { title: "ምርቶች", subtitle: "ካታሎጉ በአስተዳዳሪው ዓይን፦ አንድ ተግባር ብቻ ነው ያለ፣ እሱም የማይመለስ ተግባር ነው።", deleteOnly: "የሚፈቀድልዎት የምርት ስረዛ ብቻ ነው — ሌላ ምንም አይደለም፦ ስም፣ ዋጋ እና መግለጫ በሠራተኞችና በፋይናንስ ንብርብሮች ይስተካከላሉ፣ አገልጋዩም ከዚህ ገጽ የሚደረግ ማንኛውንም ማስተካከያ ውድቅ ያደርጋል። ስረዛ መልሶ የማይመለስ በመሆኑ ለተለየ ሚና ተመድቧል።", confirm: "ይህን ምርት መሰረዝ ይፈልጋሉ? ይህን መመለስ አይቻልም።", deleted: "ምርቱ ተሰርዟል" },
  zu: { title: "Imikhiqizo", subtitle: "Ikhathalogu njengoba umqondisi eyibona: isenzo esisodwa, futhi yiso esingenakuguqulwa.", deleteOnly: "Okuvunyelwe kuwe ukususa umkhiqizo kuphela — akukho okunye: igama, intengo nencazelo kuhlelwa izingqimba zabasebenzi nezezimali, futhi iseva iyala noma yiluphi uhlelo oluvela kuleli khasi. Ukususa akunakuhlehliswa, yingakho kwahlukaniswe kwaba yindima ehlukile.", confirm: "Susa lo mkhiqizo? Lokhu ngeke kuguqulwe.", deleted: "Umkhiqizo ususiwe" },
  xh: { title: "Iimveliso", subtitle: "Ikhathalogu njengoko umlawuli eyibona: isenzo esinye, kwaye sesona singenakuguqulwa.", deleteOnly: "Okuvumelekileyo kuwe kukucima imveliso kuphela — akukho nto yimbi: igama, ixabiso nenkcazelo kuhlelwa ngamanqanaba abasebenzi nezemali, kwaye iseva iyala nayiphi na uhlengahlengiso oluvela kweli phepha. Ukucima akunakuguqulwa, yiyo loo nto kwahlulwe kwaba yindima eyahlukileyo.", confirm: "Cima le mveliso? Oku akunakuguqulwa.", deleted: "Imveliso icinyiwe" },
  rw: { title: "Ibicuruzwa", subtitle: "Urutonde nk'uko umuyobozi arubona: igikorwa kimwe, kandi ni cyo kidasubizwa inyuma.", deleteOnly: "Icyo wemerewe ni ugusiba igicuruzwa gusa — nta kindi: izina, igiciro n'ibisobanuro bihindurwa n'inzego z'abakozi n'iz'imari, kandi seriveri irabuza ihinduka iryo ari ryo ryose riturutse kuri iyi paji. Gusiba nta gusubira inyuma bifite, ni yo mpamvu byatandukanijwe bishyirwa mu ruhare rwihariye.", confirm: "Gusiba iki gicuruzwa? Ibi ntibishobora gusubizwa inyuma.", deleted: "Igicuruzwa cyasibwe" },
  so: { title: "Alaabta", subtitle: "Liiska sida maamulaha u arko: hal falal, waana kan aan la soo celin karin.", deleteOnly: "Waxa kaliya ee kuu furan waa tirtiridda alaabta — waxba kale ma jiraan: magaca, qiimaha iyo sharraxaadda waxaa wax ka beddela lakabyada shaqaalaha iyo maaliyadda, serverkuna wuu diidayaa wax kasta oo laga soo saxo boggan. Tirtiridu ma laha soo celin, sidaas darteed waxaa loo qaybiyay door gooni ah.", confirm: "Ma tirtirayaa alaabtan? Tan lama soo celin karo.", deleted: "Alaabta waa la tirtiray" },
  zh: { title: "商品", subtitle: "管理员视角下的目录：只有一个操作，而且是不可撤销的那个。", deleteOnly: "您只能删除商品——仅此而已：名称、价格和描述由员工层和财务层编辑，服务器拒绝来自本页面的任何修改。删除没有撤销，所以它被单独划成了一个角色。", confirm: "删除该商品？此操作无法撤销。", deleted: "商品已删除" },
  ja: { title: "商品", subtitle: "管理者の目に映るカタログ：できる操作はひとつだけ、しかもそれは取り消せない操作です。", deleteOnly: "許可されているのは商品の削除だけです——それ以外は何もできません。名前、価格、説明はスタッフ層と財務層が編集し、このページからのサーバーへの編集は一切拒否されます。削除には元に戻す機能がないため、独立したロールとして切り分けられています。", confirm: "この商品を削除しますか？この操作は取り消せません。", deleted: "商品を削除しました" },
  ko: { title: "상품", subtitle: "관리자의 눈으로 본 카탈로그: 할 수 있는 작업은 오직 하나, 되돌릴 수 없는 그 작업입니다.", deleteOnly: "이 페이지에서 허용되는 것은 상품 삭제뿐입니다 — 그 외에는 아무것도 없습니다. 이름, 가격, 설명은 직원 계층과 재무 계층이 편집하며, 서버는 이 페이지에서의 어떤 편집도 거부합니다. 삭제에는 되돌리기가 없기 때문에 별도의 역할로 분리되어 있습니다.", confirm: "이 상품을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.", deleted: "상품이 삭제되었습니다" },
  hi: { title: "उत्पाद", subtitle: "प्रशासक की नज़र से कैटलॉग: केवल एक ही क्रिया, और वह अपरिवर्तनीय है।", deleteOnly: "आपके पास केवल उत्पाद हटाने की अनुमति है — और कुछ नहीं: नाम, कीमत और विवरण को स्टाफ और वित्त परतें संपादित करती हैं, और सर्वर इस पेज से किसी भी संपादन को अस्वीकार करता है। हटाने को पूर्ववत नहीं किया जा सकता, इसीलिए इसे एक अलग भूमिका में रखा गया है।", confirm: "क्या यह उत्पाद हटाना है? इसे पूर्ववत नहीं किया जा सकता।", deleted: "उत्पाद हटा दिया गया" },
  ur: { title: "مصنوعات", subtitle: "کیٹلاگ منتظم کی نظر سے: صرف ایک عمل، اور وہ ناقابلِ واپسی عمل ہے۔", deleteOnly: "آپ کو صرف مصنوعات حذف کرنے کی اجازت ہے — اور کچھ نہیں: نام، قیمت اور تفصیل کو عملہ اور مالیات کی سطحیں ترمیم کرتی ہیں، اور سرور اس صفحے سے کسی بھی ترمیم کو مسترد کر دیتا ہے۔ حذف کرنے کو واپس نہیں کیا جا سکتا، اسی لیے اسے ایک الگ کردار میں رکھا گیا ہے۔", confirm: "کیا یہ مصنوعہ حذف کریں؟ اسے واپس نہیں کیا جا سکتا۔", deleted: "مصنوعہ حذف کر دیا گیا" },
  bn: { title: "পণ্য", subtitle: "প্রশাসকের চোখে ক্যাটালগ: একটিমাত্র কাজ, আর সেটিই অপরিবর্তনীয়।", deleteOnly: "আপনার জন্য শুধু পণ্য মুছে ফেলাই উপলব্ধ — আর কিছু নয়: নাম, দাম এবং বিবরণ স্টাফ ও অর্থ স্তর সম্পাদনা করে, আর সার্ভার এই পাতা থেকে যেকোনো সম্পাদনা প্রত্যাখ্যান করে। মুছে ফেলার কোনো পূর্বাবস্থা নেই, তাই এটিকে আলাদা ভূমিকায় রাখা হয়েছে।", confirm: "এই পণ্যটি মুছে ফেলবেন? এটি পূর্বাবস্থায় ফেরানো যাবে না।", deleted: "পণ্য মুছে ফেলা হয়েছে" },
  te: { title: "ఉత్పత్తులు", subtitle: "నిర్వాహకుడి దృష్టిలో కేటలాగ్: ఒకే ఒక చర్య, అదే తిరిగి మార్చలేనిది.", deleteOnly: "మీకు అనుమతి ఉన్నది ఉత్పత్తిని తొలగించడం మాత్రమే — వేరే ఏమీ కాదు: పేరు, ధర మరియు వివరణను సిబ్బంది మరియు ఆర్థిక పొరలు సవరిస్తాయి, ఈ పేజీ నుండి ఏ సవరణనైనా సర్వర్ తిరస్కరిస్తుంది. తొలగింపుకు తిరిగి తీసుకురావడం లేదు, అందుకే దీన్ని ప్రత్యేక పాత్రగా వేరు చేశారు.", confirm: "ఈ ఉత్పత్తిని తొలగించాలా? దీన్ని వెనక్కి తీసుకోలేరు.", deleted: "ఉత్పత్తి తొలగించబడింది" },
  mr: { title: "उत्पादने", subtitle: "प्रशासकाच्या नजरेतून कॅटलॉग: एकच कृती, आणि तीच परत न करता येणारी आहे.", deleteOnly: "तुम्हाला फक्त उत्पादन हटवण्याची परवानगी आहे — आणखी काहीही नाही: नाव, किंमत आणि वर्णन कर्मचारी आणि आर्थिक स्तर संपादित करतात, आणि सर्व्हर या पानावरून कोणतेही संपादन नाकारतो. हटवण्याला पूर्ववत करणे नाही, म्हणूनच ते वेगळ्या भूमिकेत विभागले आहे.", confirm: "हे उत्पादन हटवायचे? हे पूर्ववत करता येणार नाही.", deleted: "उत्पादन हटवले" },
  kn: { title: "ಉತ್ಪನ್ನಗಳು", subtitle: "ನಿರ್ವಾಹಕರ ಕಣ್ಣಿನಲ್ಲಿ ಕ್ಯಾಟಲಾಗ್: ಒಂದೇ ಕ್ರಿಯೆ, ಮತ್ತು ಅದು ಹಿಂತಿರುಗಿಸಲಾಗದ್ದು.", deleteOnly: "ನಿಮಗೆ ಲಭ್ಯವಿರುವುದು ಉತ್ಪನ್ನ ಅಳಿಸುವಿಕೆ ಮಾತ್ರ — ಬೇರೇನೂ ಇಲ್ಲ: ಹೆಸರು, ಬೆಲೆ ಮತ್ತು ವಿವರಣೆಯನ್ನು ಸಿಬ್ಬಂದಿ ಮತ್ತು ಹಣಕಾಸು ಪದರಗಳು ಸಂಪಾದಿಸುತ್ತವೆ, ಮತ್ತು ಈ ಪುಟದಿಂದ ಯಾವುದೇ ಸಂಪಾದನೆಯನ್ನು ಸರ್ವರ್ ತಿರಸ್ಕರಿಸುತ್ತದೆ. ಅಳಿಸುವಿಕೆಗೆ ಹಿಂದಕ್ಕೆ ಪಡೆಯುವಿಕೆ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಅದನ್ನು ಪ್ರತ್ಯೇಕ ಪಾತ್ರಕ್ಕೆ ಬೇರ್ಪಡಿಸಲಾಗಿದೆ.", confirm: "ಈ ಉತ್ಪನ್ನವನ್ನು ಅಳಿಸುವುದೇ? ಇದನ್ನು ಹಿಂತಿರುಗಿಸಲಾಗುವುದಿಲ್ಲ.", deleted: "ಉತ್ಪನ್ನ ಅಳಿಸಲಾಗಿದೆ" },
  gu: { title: "ઉત્પાદનો", subtitle: "એડમિનિસ્ટ્રેટરની નજરે કેટલોગ: ફક્ત એક જ ક્રિયા, અને તે જ ઉલટાવી ન શકાય તેવી છે.", deleteOnly: "તમને ફક્ત ઉત્પાદન કાઢી નાખવાની જ પરવાનગી છે — બીજું કંઈ નહીં: નામ, ભાવ અને વર્ણન સ્ટાફ અને ફાઇનાન્સ સ્તરો સંપાદિત કરે છે, અને સર્વર આ પેજ પરથી કોઈપણ સંપાદનનો અસ્વીકાર કરે છે. કાઢી નાખવાનું પાછું લઈ શકાતું નથી, એટલે જ તેને અલગ ભૂમિકામાં અલગ કરવામાં આવ્યું છે.", confirm: "આ ઉત્પાદન કાઢી નાખવું છે? આ પાછું લઈ શકાશે નહીં.", deleted: "ઉત્પાદન કાઢી નાખવામાં આવ્યું" },
  ml: { title: "ഉൽപ്പന്നങ്ങൾ", subtitle: "അഡ്മിനിസ്ട്രേറ്ററുടെ കണ്ണിലൂടെ കാറ്റലോഗ്: ഒരൊറ്റ പ്രവർത്തി, അതും തിരിച്ചെടുക്കാനാവാത്തത്.", deleteOnly: "നിങ്ങൾക്ക് ലഭ്യമായത് ഉൽപ്പന്നം ഇല്ലാതാക്കൽ മാത്രമാണ് — മറ്റൊന്നുമില്ല: പേര്, വില, വിവരണം എന്നിവ സ്റ്റാഫ്, ഫിനാൻസ് പാളികളാണ് എഡിറ്റ് ചെയ്യുന്നത്, ഈ പേജിൽ നിന്നുള്ള ഏത് എഡിറ്റും സെർവർ നിരസിക്കുന്നു. ഇല്ലാതാക്കലിന് തിരിച്ചെടുക്കൽ ഇല്ല, അതുകൊണ്ടാണ് ഇത് പ്രത്യേക റോളായി വേർതിരിച്ചിരിക്കുന്നത്.", confirm: "ഈ ഉൽപ്പന്നം ഇല്ലാതാക്കണോ? ഇത് തിരിച്ചെടുക്കാനാവില്ല.", deleted: "ഉൽപ്പന്നം ഇല്ലാതാക്കി" },
  ta: { title: "தயாரிப்புகள்", subtitle: "நிர்வாகியின் பார்வையில் பட்டியல்: ஒரே ஒரு செயல், அதுவே திரும்பப் பெற முடியாதது.", deleteOnly: "உங்களுக்குக் கிடைப்பது தயாரிப்பை நீக்குவது மட்டுமே — வேறு எதுவும் இல்லை: பெயர், விலை, விளக்கம் ஆகியவற்றை ஊழியர் மற்றும் நிதி அடுக்குகள் திருத்துகின்றன, இந்தப் பக்கத்திலிருந்து எந்தத் திருத்தத்தையும் சேவையகம் நிராகரிக்கிறது. நீக்குதலுக்குத் திரும்பப் பெறுதல் இல்லை, அதனால்தான் இது தனி பாத்திரமாகப் பிரிக்கப்பட்டுள்ளது.", confirm: "இந்தத் தயாரிப்பை நீக்கவா? இதைத் திரும்பப் பெற முடியாது.", deleted: "தயாரிப்பு நீக்கப்பட்டது" },
  ne: { title: "उत्पादनहरू", subtitle: "प्रशासकको दृष्टिमा सूची: एउटै मात्र कार्य, र त्यो नै फर्काउन नसकिने हो।", deleteOnly: "तपाईंलाई उपलब्ध भएको उत्पादन मेटाउने मात्र हो — अरू केही होइन: नाम, मूल्य र विवरण कर्मचारी र वित्त तहहरूले सम्पादन गर्छन्, र यो पृष्ठबाट कुनै पनि सम्पादनलाई सर्भरले अस्वीकार गर्छ। मेटाउनुको पूर्ववत हुँदैन, त्यसैले यसलाई छुट्टै भूमिकामा छुट्याइएको छ।", confirm: "यो उत्पादन मेटाउने? यसलाई फर्काउन सकिँदैन।", deleted: "उत्पादन मेटाइयो" },
  vi: { title: "Sản phẩm", subtitle: "Danh mục qua con mắt của quản trị viên: chỉ một hành động duy nhất, và đó là hành động không thể hoàn tác.", deleteOnly: "Bạn chỉ được phép xóa sản phẩm — không gì khác: tên, giá và mô tả do các lớp nhân sự và tài chính chỉnh sửa, còn máy chủ từ chối mọi chỉnh sửa từ trang này. Xóa không có hoàn tác, vì vậy nó được tách thành một vai trò riêng.", confirm: "Xóa sản phẩm này? Không thể hoàn tác thao tác này.", deleted: "Đã xóa sản phẩm" },
  th: { title: "สินค้า", subtitle: "แคตตาล็อกในสายตาของผู้ดูแลระบบ: มีเพียงการกระทำเดียว และนั่นคือการกระทำที่ย้อนกลับไม่ได้", deleteOnly: "สิ่งที่คุณทำได้มีเพียงการลบสินค้า — ไม่มีอย่างอื่น ชื่อ ราคา และคำอธิบายถูกแก้ไขโดยชั้นของทีมงานและการเงิน และเซิร์ฟเวอร์ปฏิเสธการแก้ไขใดๆ จากหน้านี้ การลบไม่มีการยกเลิก จึงถูกแยกออกเป็นบทบาทต่างหาก", confirm: "ลบสินค้านี้หรือไม่? การกระทำนี้ไม่สามารถย้อนกลับได้", deleted: "ลบสินค้าแล้ว" },
  id: { title: "Produk", subtitle: "Katalog dari sudut pandang administrator: satu-satunya tindakan, dan itu adalah tindakan yang tidak dapat dibatalkan.", deleteOnly: "Yang tersedia bagi Anda hanyalah menghapus produk — tidak ada yang lain: nama, harga, dan deskripsi diedit oleh lapisan staf dan keuangan, dan server menolak setiap pengeditan dari halaman ini. Penghapusan tidak memiliki pembatalan, itulah sebabnya dipisahkan menjadi peran tersendiri.", confirm: "Hapus produk ini? Tindakan ini tidak dapat dibatalkan.", deleted: "Produk dihapus" },
  ms: { title: "Produk", subtitle: "Katalog dari sudut pandang pentadbir: satu tindakan sahaja, dan itulah yang tidak boleh dibuat asal.", deleteOnly: "Yang tersedia untuk anda hanyalah memadam produk — tiada apa-apa lagi: nama, harga dan penerangan disunting oleh lapisan kakitangan dan kewangan, dan pelayan menolak sebarang suntingan daripada halaman ini. Pemadaman tidak boleh dibuat asal, itulah sebabnya ia diasingkan kepada peranan berasingan.", confirm: "Padam produk ini? Tindakan ini tidak boleh dibuat asal.", deleted: "Produk dipadam" },
  tl: { title: "Mga Produkto", subtitle: "Ang katalogo sa mata ng administrator: iisang aksyon lamang, at iyon ang hindi na maibabalik.", deleteOnly: "Ang pinapayagan lamang sa iyo ay ang pagtanggal ng produkto — wala nang iba: ang pangalan, presyo, at deskripsyon ay ini-edit ng mga layer ng staff at pinansya, at tinatanggihan ng server ang anumang pag-edit mula sa pahinang ito. Ang pagtanggal ay walang pagbabalik, kaya't ito ay inilagay sa hiwalay na tungkulin.", confirm: "Tanggalin ang produktong ito? Hindi na ito maibabalik.", deleted: "Natanggal ang produkto" },
  my: { title: "ကုန်ပစ္စည်းများ", subtitle: "စီမံခန့်ခွဲသူ၏ မျက်စိဖြင့် ကတလောက်: လုပ်ဆောင်ချက်တစ်ခုတည်း၊ ၎င်းမှာ ပြန်မလှည့်နိုင်သော လုပ်ဆောင်ချက်ဖြစ်သည်။", deleteOnly: "သင့်အတွက် ရရှိနိုင်သည်မှာ ကုန်ပစ္စည်းဖျက်ခြင်းသာ ဖြစ်သည် — အခြားမည်သည့်အရာမျှ မရှိပါ။ အမည်၊ စျေးနှုန်းနှင့် ဖော်ပြချက်ကို ဝန်ထမ်းနှင့် ဘဏ္ဍာရေးအလွှာများက တည်းဖြတ်ကြပြီး၊ ဤစာမျက်နှာမှ မည်သည့်တည်းဖြတ်မှုကိုမဆို ဆာဗာက ငြင်းပယ်ပါသည်။ ဖျက်ခြင်းတွင် ပြန်ဖျက်ခြင်း မရှိသဖြင့် ၎င်းကို သီးခြားအခန်းကဏ္ဍအဖြစ် ခွဲထားခြင်း ဖြစ်သည်။", confirm: "ဤကုန်ပစ္စည်းကို ဖျက်မလား။ ၎င်းကို ပြန်ပြင်၍ မရပါ။", deleted: "ကုန်ပစ္စည်း ဖျက်ပြီးပါပြီ" },
  km: { title: "ផលិតផល", subtitle: "កាតាឡុកតាមទស្សនៈអ្នកគ្រប់គ្រង៖ សកម្មភាពតែមួយ ហើយវាជាសកម្មភាពដែលមិនអាចត្រឡប់វិញបាន។", deleteOnly: "អ្វីដែលអ្នកអាចធ្វើបានគឺគ្រាន់តែលុបផលិតផលប៉ុណ្ណោះ — គ្មានអ្វីផ្សេងទៀតទេ៖ ឈ្មោះ តម្លៃ និងការពិពណ៌នា ត្រូវបានកែសម្រួលដោយស្រទាប់បុគ្គលិក និងហិរញ្ញវត្ថុ ហើយម៉ាស៊ីនមេបដិសេធការកែសម្រួលណាមួយពីទំព័រនេះ។ ការលុបគ្មានការមិនធ្វើវិញទេ ដូច្នេះវាត្រូវបានញែកទៅជាតួនាទីដាច់ដោយឡែក។", confirm: "លុបផលិតផលនេះមែនទេ? វាមិនអាចត្រឡប់វិញបានទេ។", deleted: "ផលិតផលត្រូវបានលុប" },
  lo: { title: "ສິນຄ້າ", subtitle: "ບັນຊີລາຍການໃນສາຍຕາຂອງຜູ້ບໍລິຫານ: ມີພຽງການກະທຳດຽວ, ແລະນັ້ນຄືການກະທຳທີ່ບໍ່ສາມາດຍ້ອນກັບໄດ້.", deleteOnly: "ສິ່ງທີ່ທ່ານສາມາດເຮັດໄດ້ແມ່ນການລຶບສິນຄ້າເທົ່ານັ້ນ — ບໍ່ມີຢ່າງອື່ນ: ຊື່, ລາຄາ ແລະ ຄຳອະທິບາຍຖືກແກ້ໄຂໂດຍຊັ້ນຂອງພະນັກງານ ແລະການເງິນ, ແລະເຊີບເວີປະຕິເສດການແກ້ໄຂໃດໆຈາກໜ້ານີ້. ການລຶບບໍ່ມີການຍົກເລີກ, ນັ້ນຄືເຫດຜົນທີ່ມັນຖືກແຍກອອກເປັນບົດບາດຕ່າງຫາກ.", confirm: "ລຶບສິນຄ້ານີ້ບໍ? ການກະທຳນີ້ບໍ່ສາມາດຍ້ອນກັບໄດ້.", deleted: "ລຶບສິນຄ້າແລ້ວ" },
}

export function administrationProductsUi(lang: string): AdministrationProductsUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
