// Слова диалога переводов — 82 языка (`/code/CLAUDE.md` §4д).
//
// Строки интерфейса живут в коде и едут со сборкой; сообщения об ОТКАЗАХ сюда не
// входят — они общие для голоса, перевода и любой думающей части и лежат один
// раз в `lib/i18n/platform-errors.ts`.
//
// 🔒 СЕРВЕРНЫЙ РЕЗОЛВ. 82 языка × словарь — сотни килобайт; клиентский компонент
// не имеет права импортировать этот файл. Серверная страница зовёт
// `translationsUi(lang)` и передаёт строки островку пропсами.
//
// Языки, кроме английского, переведены моделью 2026-08-11 одним прогоном на
// язык — все ключи разом, чтобы перевод был согласован внутри себя. Правку
// отдельной строки вносите руками: перегонять весь словарь ради одного слова
// дороже и рискованнее.

export type TranslationsUi = {
  title: string
  intro: string
  translateTab: string
  translateAllTabs: string
  translating: string
  saveOne: string
  saving: string
  savedMark: string
  skip: string
  close: string
  /** Текст у вопросика — почему пропуск это нормально. */
  hint: string
  saved: string
}

const UI: Record<string, TranslationsUi> = {
  en: { title: 'Add translations', intro: 'Fill the languages your app ships in. Nothing is translated until you ask.', translateTab: 'Translate this tab', translateAllTabs: 'Translate all tabs', translating: 'Translating…', saveOne: 'Save this translation', saving: 'Saving…', savedMark: 'saved', skip: 'Skip for now', close: 'Close', hint: 'Designing a page and not sure it is final? Skip the translations. The record lives in the language you are working in, and you add the rest when the wording settles — translating a draft spends time and tokens on text you are about to rewrite.', saved: 'Translation saved' },
  fr: { title: 'Ajouter des traductions', intro: 'Indiquez les langues dans lesquelles votre application est livrée. Rien n’est traduit tant que vous ne le demandez pas.', translateTab: 'Traduire cet onglet', translateAllTabs: 'Traduire tous les onglets', translating: 'Traduction…', saveOne: 'Enregistrer cette traduction', saving: 'Enregistrement…', savedMark: 'enregistré', skip: 'Ignorer pour l’instant', close: 'Fermer', hint: 'Vous concevez une page et n’êtes pas sûr qu’elle soit définitive ? Ignorez les traductions. L’enregistrement reste dans la langue dans laquelle vous travaillez, et vous ajouterez le reste quand la formulation sera stabilisée — traduire un brouillon consomme du temps et des jetons pour un texte que vous allez réécrire.', saved: 'Traduction enregistrée' },
  es: { title: 'Añadir traducciones', intro: 'Añade los idiomas en los que tu app se distribuye. Nada se traduce hasta que lo pidas.', translateTab: 'Traducir esta pestaña', translateAllTabs: 'Traducir todas las pestañas', translating: 'Traduciendo…', saveOne: 'Guardar esta traducción', saving: 'Guardando…', savedMark: 'guardado', skip: 'Omitir por ahora', close: 'Cerrar', hint: '¿Diseñando una página y no estás seguro de que sea la versión final? Omite las traducciones. El registro queda en el idioma en el que trabajas y podrás añadir el resto cuando el texto esté definido — traducir un borrador consume tiempo y tokens en un texto que vas a reescribir.', saved: 'Traducción guardada' },
  pt: { title: 'Adicionar traduções', intro: 'Informe os idiomas em que seu app está disponível. Nada é traduzido até você pedir.', translateTab: 'Traduzir esta aba', translateAllTabs: 'Traduzir todas as abas', translating: 'Traduzindo…', saveOne: 'Salvar esta tradução', saving: 'Salvando…', savedMark: 'salvo', skip: 'Ignorar por enquanto', close: 'Fechar', hint: 'Projetando uma página e não tem certeza se é a versão final? Ignore as traduções. O registro fica no idioma em que você está trabalhando, e você adiciona o resto quando o texto estiver definido — traduzir um rascunho gasta tempo e tokens com algo que você ainda vai reescrever.', saved: 'Tradução salva' },
  de: { title: 'Übersetzungen hinzufügen', intro: 'Füge die Sprachen hinzu, in denen deine App ausgeliefert wird. Nichts wird übersetzt, bis du es anforderst.', translateTab: 'Diesen Tab übersetzen', translateAllTabs: 'Alle Tabs übersetzen', translating: 'Wird übersetzt…', saveOne: 'Diese Übersetzung speichern', saving: 'Speichern…', savedMark: 'gespeichert', skip: 'Jetzt überspringen', close: 'Schließen', hint: 'Du gestaltest gerade eine Seite und weißt noch nicht, ob sie final ist? Überspringe die Übersetzungen. Der Datensatz liegt in der Sprache vor, in der du arbeitest; den Rest fügst du hinzu, wenn die Formulierungen feststehen — einen Entwurf zu übersetzen kostet Zeit und Tokens für Text, den du gleich wieder umschreibst.', saved: 'Übersetzung gespeichert' },
  it: { title: 'Aggiungi traduzioni', intro: 'Imposta le lingue in cui la tua app è disponibile. Nulla viene tradotto finché non lo richiedi.', translateTab: 'Traduci questa scheda', translateAllTabs: 'Traduci tutte le schede', translating: 'Traduzione in corso…', saveOne: 'Salva questa traduzione', saving: 'Salvataggio in corso…', savedMark: 'salvato', skip: 'Salta per ora', close: 'Chiudi', hint: 'Stai progettando una pagina e non sei sicuro che sia definitiva? Salta le traduzioni. Il record resta nella lingua in cui stai lavorando e aggiungerai le altre quando il testo si assesta — tradurre una bozza fa perdere tempo e token su un testo che stai per riscrivere.', saved: 'Traduzione salvata' },
  nl: { title: 'Vertalingen toevoegen', intro: 'Voeg de talen toe waarin je app wordt geleverd. Er wordt niets vertaald totdat je het vraagt.', translateTab: 'Vertaal dit tabblad', translateAllTabs: 'Vertaal alle tabbladen', translating: 'Vertalen…', saveOne: 'Sla deze vertaling op', saving: 'Opslaan…', savedMark: 'opgeslagen', skip: 'Nu overslaan', close: 'Sluiten', hint: 'Ben je een pagina aan het ontwerpen en niet zeker of die al definitief is? Sla de vertalingen over. Het record bestaat in de taal waarin je werkt, en je voegt de rest toe zodra de tekst vaststaat — een concept vertalen kost tijd en tokens aan tekst die je toch gaat herschrijven.', saved: 'Vertaling opgeslagen' },
  sv: { title: 'Lägg till översättningar', intro: 'Lägg till språken din app levereras med. Inget översätts förrän du ber om det.', translateTab: 'Översätt den här fliken', translateAllTabs: 'Översätt alla flikar', translating: 'Översätter…', saveOne: 'Spara den här översättningen', saving: 'Sparar…', savedMark: 'sparad', skip: 'Hoppa över för tillfället', close: 'Stäng', hint: 'Designar du en sida och är osäker på om den är klar? Hoppa över översättningarna. Posten sparas på språket du arbetar i och du kan lägga till resten när texten har satt sig — att översätta ett utkast kostar tid och tokens på text du ändå kommer att skriva om.', saved: 'Översättning sparad' },
  no: { title: 'Legg til oversettelser', intro: 'Legg inn språkene appen din leveres i. Ingenting blir oversatt før du ber om det.', translateTab: 'Oversett denne fanen', translateAllTabs: 'Oversett alle faner', translating: 'Oversetter…', saveOne: 'Lagre denne oversettelsen', saving: 'Lagrer…', savedMark: 'lagret', skip: 'Hopp over foreløpig', close: 'Lukk', hint: 'Designer du en side og usikker på om den er endelig? Hopp over oversettelsene. Posten ligger i språket du jobber i, og du kan legge til resten når teksten er spikret — å oversette et utkast bruker tid og tokens på tekst du snart skriver om.', saved: 'Oversettelse lagret' },
  da: { title: 'Tilføj oversættelser', intro: 'Angiv de sprog, din app leveres i. Intet oversættes, før du beder om det.', translateTab: 'Oversæt denne fane', translateAllTabs: 'Oversæt alle faner', translating: 'Oversætter…', saveOne: 'Gem denne oversættelse', saving: 'Gemmer…', savedMark: 'gemt', skip: 'Spring over for nu', close: 'Luk', hint: 'Designer du en side og er du ikke sikker på, at den er færdig? Spring oversættelserne over. Elementet findes på det sprog, du arbejder i, og du kan tilføje resten, når formuleringerne er på plads — at oversætte et udkast bruger tid og tokens på tekst, du er ved at skrive om.', saved: 'Oversættelse gemt' },
  fi: { title: 'Lisää käännöksiä', intro: 'Lisää sovelluksesi julkaisukielet. Mitään ei käännetä ennen kuin pyydät.', translateTab: 'Käännä tämä välilehti', translateAllTabs: 'Käännä kaikki välilehdet', translating: 'Käännetään…', saveOne: 'Tallenna tämä käännös', saving: 'Tallennetaan…', savedMark: 'tallennettu', skip: 'Ohita toistaiseksi', close: 'Sulje', hint: 'Suunnitteletko sivua etkä ole varma, onko se lopullinen? Ohita käännökset. Tietue on sillä kielellä, jolla työskentelet, ja lisäät loput, kun sanamuodot vakiintuvat — luonnoksen kääntäminen kuluttaa aikaa ja tokeneita tekstiin, jonka aiot kirjoittaa uusiksi.', saved: 'Käännös tallennettu' },
  is: { title: 'Bæta við þýðingum', intro: 'Veldu tungumálin sem appið þitt styður. Ekkert er þýtt fyrr en þú biður um það.', translateTab: 'Þýða þennan flipa', translateAllTabs: 'Þýða alla flipa', translating: 'Er að þýða…', saveOne: 'Vista þessa þýðingu', saving: 'Er að vista…', savedMark: 'vistað', skip: 'Sleppa í bili', close: 'Loka', hint: 'Ertu að hanna síðu og ekki viss um að hún sé endanleg? Sleppdu þýðingunum. Færslan er á því tungumáli sem þú vinnur í og þú bætir við hinum þegar orðalagið hefur fest sig — að þýða drög eyðir tíma og einingum í texta sem þú ert líklega að endurskrifa.', saved: 'Þýðing vistuð' },
  el: { title: 'Προσθήκη μεταφράσεων', intro: 'Συμπληρώστε τις γλώσσες στις οποίες διατίθεται η εφαρμογή σας. Τίποτα δεν μεταφράζεται μέχρι να το ζητήσετε.', translateTab: 'Μετάφραση αυτής της καρτέλας', translateAllTabs: 'Μετάφραση όλων των καρτελών', translating: 'Μετάφραση…', saveOne: 'Αποθήκευση αυτής της μετάφρασης', saving: 'Αποθήκευση…', savedMark: 'αποθηκεύτηκε', skip: 'Παράλειψη προς το παρόν', close: 'Κλείσιμο', hint: 'Σχεδιάζετε μια σελίδα και δεν είστε σίγουροι ότι είναι τελική; Παραλείψτε τις μεταφράσεις. Η καταχώρηση παραμένει στη γλώσσα στην οποία δουλεύετε και προσθέτετε τις υπόλοιπες όταν οριστικοποιηθεί το κείμενο — η μετάφραση προσχεδίου σπαταλά χρόνο και tokens για κείμενο που θα ξαναγράψετε.', saved: 'Η μετάφραση αποθηκεύτηκε' },
  pl: { title: 'Dodaj tłumaczenia', intro: 'Określ języki, w których dostępna jest Twoja aplikacja. Nic nie zostanie przetłumaczone, dopóki o to nie poprosisz.', translateTab: 'Przetłumacz tę zakładkę', translateAllTabs: 'Przetłumacz wszystkie zakładki', translating: 'Tłumaczenie…', saveOne: 'Zapisz to tłumaczenie', saving: 'Zapisywanie…', savedMark: 'zapisano', skip: 'Pomiń na razie', close: 'Zamknij', hint: 'Projektujesz stronę i nie masz pewności, że to wersja ostateczna? Pomiń tłumaczenia. Wpis pozostanie w języku, w którym pracujesz, a resztę dodasz, gdy tekst się ustali — tłumaczenie szkicu zużywa czas i tokeny na tekst, który i tak zaraz przepiszesz.', saved: 'Tłumaczenie zapisane' },
  cs: { title: 'Přidat překlady', intro: 'Zadejte jazyky, ve kterých aplikaci dodáváte. Nic se nepřeloží, dokud o to nepožádáte.', translateTab: 'Přeložit tuto záložku', translateAllTabs: 'Přeložit všechny záložky', translating: 'Překládá se…', saveOne: 'Uložit tento překlad', saving: 'Ukládá se…', savedMark: 'uloženo', skip: 'Zatím přeskočit', close: 'Zavřít', hint: 'Navrhujete stránku a nejste si jistí, že je finální? Překlady přeskočte. Záznam zůstane v jazyce, ve kterém pracujete, a ostatní doplníte, až se text ustálí — překládat koncept zbytečně stojí čas a tokeny na text, který brzy přepíšete.', saved: 'Překlad uložen' },
  sk: { title: 'Pridať preklady', intro: 'Zadajte jazyky, v ktorých sa vaša aplikácia dodáva. Nič sa nepreloží, kým o to nepožiadate.', translateTab: 'Preložiť túto kartu', translateAllTabs: 'Preložiť všetky karty', translating: 'Prekladá sa…', saveOne: 'Uložiť tento preklad', saving: 'Ukladá sa…', savedMark: 'uložené', skip: 'Zatiaľ preskočiť', close: 'Zavrieť', hint: 'Navrhujete stránku a nie ste si istí, či je finálna? Preklady zatiaľ preskočte. Záznam zostáva v jazyku, v ktorom pracujete, a zvyšok pridáte, keď sa text ustáli — preklad rozpracovaného návrhu míňa čas a tokeny na text, ktorý aj tak prepisujete.', saved: 'Preklad uložený' },
  hu: { title: 'Fordítások hozzáadása', intro: 'Add meg, milyen nyelveken adod ki az alkalmazásod. Semmi sem fordul le, amíg nem kéred.', translateTab: 'Fordítsd ezt a fület', translateAllTabs: 'Fordítsd az összes fület', translating: 'Fordítás folyamatban…', saveOne: 'Fordítás mentése', saving: 'Mentés…', savedMark: 'elmentve', skip: 'Kihagyás egyelőre', close: 'Bezárás', hint: 'Oldalt tervezel, és nem vagy benne biztos, hogy ez a végleges? Hagyd ki a fordításokat. A bejegyzés azon a nyelven él, amelyiken dolgozol, a többit akkor adod hozzá, amikor a szöveg véglegesedik — egy piszkozat fordítása időt és tokeneket pazarol olyan szövegre, amit úgyis átírsz.', saved: 'Fordítás elmentve' },
  ro: { title: 'Adaugă traduceri', intro: 'Completează limbile în care aplicația ta este disponibilă. Nu se traduce nimic până nu ceri.', translateTab: 'Tradu această filă', translateAllTabs: 'Tradu toate filele', translating: 'Se traduce…', saveOne: 'Salvează această traducere', saving: 'Se salvează…', savedMark: 'salvat', skip: 'Omite deocamdată', close: 'Închide', hint: 'Proiectezi o pagină și nu știi dacă e finală? Omite traducerile. Înregistrarea rămâne în limba în care lucrezi și adaugi restul când formularea se definitivează — traducerea unei ciorne consumă timp și tokeni pe un text pe care urmează să-l rescrii.', saved: 'Traducere salvată' },
  hr: { title: 'Dodaj prijevode', intro: 'Dodajte jezike u kojima isporučujete aplikaciju. Ništa se ne prevodi dok ne zatražite.', translateTab: 'Prevedi ovu karticu', translateAllTabs: 'Prevedi sve kartice', translating: 'Prevođenje…', saveOne: 'Spremi ovaj prijevod', saving: 'Spremanje…', savedMark: 'spremljeno', skip: 'Preskoči zasad', close: 'Zatvori', hint: 'Dizajnirate stranicu i niste sigurni da je konačna? Preskočite prijevode. Zapis ostaje na jeziku na kojem radite, a ostalo dodajete kad se formulacija ustali — prevođenje nacrta troši vrijeme i tokene na tekst koji ćete ionako prepraviti.', saved: 'Prijevod spremljen' },
  sl: { title: 'Dodaj prevode', intro: 'Določite jezike, v katerih je vaša aplikacija na voljo. Nič ne bo prevedeno, dokler tega ne zahtevate.', translateTab: 'Prevedi ta zavihek', translateAllTabs: 'Prevedi vse zavihke', translating: 'Prevajanje…', saveOne: 'Shrani ta prevod', saving: 'Shranjevanje…', savedMark: 'shranjeno', skip: 'Preskoči za zdaj', close: 'Zapri', hint: 'Oblikujete stran in niste prepričani, da je končna? Preskočite prevode. Zapis ostane v jeziku, v katerem delate, ostale dodate, ko se besedilo ustali — prevajanje osnutka porablja čas in žetone za besedilo, ki ga boste verjetno še prepisali.', saved: 'Prevod shranjen' },
  et: { title: 'Lisa tõlked', intro: 'Lisa keeled, milles su rakendus on saadaval. Midagi ei tõlgita enne, kui seda palud.', translateTab: 'Tõlgi see vahekaart', translateAllTabs: 'Tõlgi kõik vahekaardid', translating: 'Tõlgin…', saveOne: 'Salvesta see tõlge', saving: 'Salvestan…', savedMark: 'salvestatud', skip: 'Jäta praegu vahele', close: 'Sulge', hint: 'Koostad lehte ega ole kindel, et see on lõplik? Jäta tõlked vahele. Kirje on keeles, milles töötad, ja teised keeled lisad siis, kui sõnastus on paigas — mustandi tõlkimine kulutab aega ja tokeneid tekstile, mida plaanid ümber kirjutada.', saved: 'Tõlge salvestatud' },
  lv: { title: 'Pievienot tulkojumus', intro: 'Pievienojiet valodas, kurās jūsu lietotne ir pieejama. Nekas netiks tulkots, līdz to pieprasīsiet.', translateTab: 'Tulkot šo cilni', translateAllTabs: 'Tulkot visas cilnes', translating: 'Tulkojam…', saveOne: 'Saglabāt šo tulkojumu', saving: 'Saglabājam…', savedMark: 'saglabāts', skip: 'Pagaidām izlaist', close: 'Aizvērt', hint: 'Veidojat lapu un neesat droši, ka tā ir galīga? Izlaidiet tulkojumus. Ieraksts paliek tajā valodā, kurā strādājat, un pārējās pievienosiet, kad teksts būs skaidrs — melnraksta tulkošana patērē laiku un tokenus tekstam, ko tāpat pārrakstīsiet.', saved: 'Tulkojums saglabāts' },
  lt: { title: 'Pridėti vertimus', intro: 'Pasirinkite kalbas, kuriomis tiekiama jūsų programa. Nieko neverčiame, kol neprašysite.', translateTab: 'Išversti šį skirtuką', translateAllTabs: 'Išversti visus skirtukus', translating: 'Verčiama…', saveOne: 'Išsaugoti šį vertimą', saving: 'Išsaugoma…', savedMark: 'išsaugota', skip: 'Kol kas praleisti', close: 'Uždaryti', hint: 'Kuriate puslapį ir nesate tikri, ar tai galutinis variantas? Praleiskite vertimus. Įrašas lieka ta kalba, kuria dabar dirbate, o kitus pridėsite, kai formuluotės nusistovės — juodraščio vertimas švaisto laiką ir žetonus tekstui, kurį vis tiek taisysite.', saved: 'Vertimas išsaugotas' },
  mt: { title: 'Żid traduzzjonijiet', intro: 'Imla l-lingwi li toħroġ fihom l-app tiegħek. Xejn jiġi tradott sakemm titlob.', translateTab: 'Ittraduċi din it-tab', translateAllTabs: 'Ittraduċi t-tabs kollha', translating: 'Qed nittraduċi…', saveOne: 'Issejvja din it-traduzzjoni', saving: 'Qed nissejvja…', savedMark: 'salvat', skip: 'Aqbeż għalissa', close: 'Agħlaq', hint: 'Qed tiddisinja paġna u m’intix ċert jekk hijiex finali? Aqbeż it-traduzzjonijiet. Ir-rekord jibqa’ fil-lingwa li qed taħdem fiha, u żżid il-bqija meta l-kliem jistabbilixxi ruħu — it-traduzzjoni ta’ abbozz tonfoq ħin u tokens fuq test li se terġa’ tikteb.', saved: 'Traduzzjoni salvata' },
  ca: { title: 'Afegeix traduccions', intro: 'Indica els idiomes en què la teva aplicació s’ofereix. No es tradueix res fins que ho demanis.', translateTab: 'Tradueix aquesta pestanya', translateAllTabs: 'Tradueix totes les pestanyes', translating: 'Traduint…', saveOne: 'Desa aquesta traducció', saving: 'Desant…', savedMark: 'desat', skip: 'Omet per ara', close: 'Tanca', hint: 'Dissenyant una pàgina i no tens clar si és definitiva? Omet les traduccions. El registre existeix en l’idioma en què estàs treballant, i afegiràs la resta quan el text es fixi — traduir un esborrany consumeix temps i tokens en un text que probablement reescriuràs.', saved: 'Traducció desada' },
  gl: { title: 'Engadir traducións', intro: 'Engade os idiomas nos que se distribúe a túa aplicación. Non se traduce nada ata que o pidas.', translateTab: 'Traducir esta lapela', translateAllTabs: 'Traducir todas as lapelas', translating: 'Traducindo…', saveOne: 'Gardar esta tradución', saving: 'Gardando…', savedMark: 'gardado', skip: 'Omitir por agora', close: 'Pechar', hint: 'Deseñando unha páxina e non tes claro se é definitiva? Omite as traducións. O rexistro queda no idioma no que estás a traballar, e engadirás o resto cando a redacción se estabilice — traducir un borrador gasta tempo e tokens nun texto que vas reescribir.', saved: 'Tradución gardada' },
  cy: { title: 'Ychwanegu cyfieithiadau', intro: 'Llenwch yr ieithoedd y darperir eich ap ynddynt. Ni chyfieithir dim nes i chi ofyn.', translateTab: 'Cyfieithu\'r tab hwn', translateAllTabs: 'Cyfieithu pob tab', translating: 'Yn cyfieithu…', saveOne: 'Cadw\'r cyfieithiad hwn', saving: 'Yn cadw…', savedMark: 'wedi\'i gadw', skip: 'Hepgor am y tro', close: 'Cau', hint: 'Yn dylunio tudalen ac yn ansicr a yw\'n derfynol? Hepgor y cyfieithiadau. Mae\'r cofnod yn yr iaith rydych yn gweithio ynddi, a gallwch ychwanegu\'r gweddill pan fydd y geiriad wedi setlo — mae cyfieithu drafft yn gwario amser a thocynnau ar destun rydych ar fin ei ailysgrifennu.', saved: 'Cadwyd y cyfieithiad' },
  ga: { title: 'Cuir aistriúcháin leis', intro: 'Líon isteach na teangacha ina gcuirtear d\'aip ar fáil. Ní aistrítear aon rud go dtí go n-iarrfaidh tú é.', translateTab: 'Aistrigh an cluaisín seo', translateAllTabs: 'Aistrigh na cluaisíní go léir', translating: 'Á aistriú…', saveOne: 'Sábháil an t-aistriúchán seo', saving: 'Á shábháil…', savedMark: 'sábháilte', skip: 'Ná bac leis faoi láthair', close: 'Dún', hint: 'Ag dearadh leathanaigh agus níl tú cinnte gur leagan deiridh é? Scipeáil na haistriúcháin. Fanfaidh an taifead sa teanga a bhfuil tú ag obair inti, agus cuirfidh tú an chuid eile leis nuair a mbeidh an téacs socraithe — caitheann aistriú dréachta am agus tóicinn ar théacs atá tú ar tí athscríobh.', saved: 'Sábháladh an t-aistriúchán' },
  eu: { title: 'Gehitu itzulpenak', intro: 'Zehaztu zure aplikazioak eskaintzen dituen hizkuntzak. Ez da ezer itzuliko zuk eskatu arte.', translateTab: 'Itzuli fitxa hau', translateAllTabs: 'Itzuli fitxa guztiak', translating: 'Itzultzen…', saveOne: 'Gorde itzulpen hau', saving: 'Gordetzen…', savedMark: 'gordeta', skip: 'Saltatu oraingoz', close: 'Itxi', hint: 'Orri bat diseinatzen ari zara eta ez zaude ziur azken bertsioa denik? Saltatu itzulpenak. Erregistroa lanean ari zaren hizkuntzan gordetzen da, eta gainerakoa gehituko duzu testua finkatzen denean — zirriborroa itzultzeak denbora eta tokenak xahutzen ditu berridatziko duzun testuan.', saved: 'Itzulpena gordeta' },
  ru: { title: 'Добавьте переводы', intro: 'Укажите языки, на которых доступно ваше приложение. Ничего не переводится, пока вы не попросите.', translateTab: 'Перевести эту вкладку', translateAllTabs: 'Перевести все вкладки', translating: 'Перевод…', saveOne: 'Сохранить этот перевод', saving: 'Сохранение…', savedMark: 'сохранено', skip: 'Пока пропустить', close: 'Закрыть', hint: 'Проектируете страницу и не уверены, что это финал? Пропустите переводы. Запись останется на языке, с которым вы работаете, а остальные добавите, когда формулировки определятся — перевод черновика тратит время и токены на текст, который вы всё равно перепишете.', saved: 'Перевод сохранён' },
  uk: { title: 'Додати переклади', intro: 'Додайте мови, з якими постачається ваш застосунок. Нічого не перекладено, доки ви не попросите.', translateTab: 'Перекласти цю вкладку', translateAllTabs: 'Перекласти всі вкладки', translating: 'Перекладаємо…', saveOne: 'Зберегти цей переклад', saving: 'Зберігаємо…', savedMark: 'збережено', skip: 'Поки що пропустити', close: 'Закрити', hint: 'Проєктуєте сторінку й не певні, що це фінал? Пропустіть переклади. Запис зберігається мовою, з якою ви працюєте, а решту додасте, коли формулювання усталяться — переклад чернетки витрачає час і токени на текст, який ви все одно перепишете.', saved: 'Переклад збережено' },
  be: { title: 'Дадаць пераклады', intro: 'Пазначце мовы, у якіх пастаўляецца ваша прыкладанне. Нічога не будзе перакладзена, пакуль вы не папросіце.', translateTab: 'Перакласці гэту ўкладку', translateAllTabs: 'Перакласці ўсе ўкладкі', translating: 'Перакладаем…', saveOne: 'Захаваць гэты пераклад', saving: 'Захоўваем…', savedMark: 'захавана', skip: 'Пакуль прапусціць', close: 'Закрыць', hint: 'Ствараеце старонку і не ўпэўнены, што гэта канчатковая версія? Прапусціце пераклады. Запіс існуе на мове, на якой вы працуеце; астатнія дадасце, калі фармулёўкі стануць канчатковымі — пераклад чарнавіка марнуе час і токены на тэкст, які вы ўсё роўна перапішаце.', saved: 'Пераклад захаваны' },
  bg: { title: 'Добавяне на преводи', intro: 'Добавете езиците, в които приложението ви се предлага. Нищо не се превежда, докато не поискате.', translateTab: 'Преведи този раздел', translateAllTabs: 'Преведи всички раздели', translating: 'Превеждане…', saveOne: 'Запази този превод', saving: 'Запазване…', savedMark: 'запазено', skip: 'Пропусни засега', close: 'Затвори', hint: 'Правите страница и не сте сигурни, че е финална? Пропуснете преводите. Записът е на езика, на който работите, а останалите ще добавите, когато формулировките се уточнят — преводът на чернова хаби време и токени за текст, който скоро ще пренапишете.', saved: 'Преводът е запазен' },
  sr: { title: 'Додајте преводе', intro: 'Унесите језике у којима се апликација испоручује. Ништа се не преводи док не затражите.', translateTab: 'Преведите ову картицу', translateAllTabs: 'Преведите све картице', translating: 'Превођење…', saveOne: 'Сачувајте овај превод', saving: 'Чување…', savedMark: 'сачувано', skip: 'Прескочите за сада', close: 'Затворите', hint: 'Правите страницу и нисте сигурни да је коначна? Прескочите превођење. Запис остаје на језику на ком радите, а остале ћете додати кад се формулације устале — превођење нацрта троши време и токене на текст који ћете вероватно преписати.', saved: 'Превод је сачуван' },
  bs: { title: 'Dodaj prijevode', intro: 'Odaberi jezike u kojima tvoja aplikacija dolazi. Ništa se ne prevodi dok ne zatražiš.', translateTab: 'Prevedi ovu karticu', translateAllTabs: 'Prevedi sve kartice', translating: 'Prevođenje…', saveOne: 'Sačuvaj ovaj prijevod', saving: 'Čuvanje…', savedMark: 'sačuvano', skip: 'Preskoči zasad', close: 'Zatvori', hint: 'Dizajniraš stranicu i još nije konačna? Preskoči prijevode. Zapis ostaje na jeziku na kojem radiš, a ostale dodaš kad se tekst ustali — prevođenje nacrta troši vrijeme i tokene na tekst koji ćeš ionako prepraviti.', saved: 'Prijevod sačuvan' },
  mk: { title: 'Додај преводи', intro: 'Додадете ги јазиците во кои вашата апликација се испорачува. Ништо нема да се преведе додека не побарате.', translateTab: 'Преведи го ова јазиче', translateAllTabs: 'Преведи ги сите јазичиња', translating: 'Преведување…', saveOne: 'Зачувај го овој превод', saving: 'Зачувување…', savedMark: 'зачувано', skip: 'Прескокни засега', close: 'Затвори', hint: 'Дизајнирате страница и не сте сигурни дека е финална? Прескокнете ги преводите. Записот е на јазикот на кој работите, а останатото ќе го додадете кога формулацијата ќе се утврди — преведувањето на нацрт троши време и токени на текст што веројатно ќе го преработите.', saved: 'Преводот е зачуван' },
  sq: { title: 'Shto përkthime', intro: 'Zgjidh gjuhët në të cilat shpërndahet aplikacioni yt. Asgjë nuk përkthehet derisa ta kërkosh.', translateTab: 'Përkthe këtë skedë', translateAllTabs: 'Përkthe të gjitha skedat', translating: 'Duke përkthyer…', saveOne: 'Ruaj këtë përkthim', saving: 'Duke ruajtur…', savedMark: 'ruajtur', skip: 'Kaloje për momentin', close: 'Mbyll', hint: 'Po dizajnon një faqe dhe s’je i/e sigurt që është përfundimtare? Kalo përkthimet. Regjistrimi mbetet në gjuhën në të cilën po punon, dhe të tjerat i shton kur formulimi të jetë vendosur — përkthimi i një skice shpenzon kohë dhe tokena për tekst që je gati ta rishkruash.', saved: 'Përkthimi u ruajt' },
  kk: { title: 'Аудармаларды қосу', intro: 'Қолданбаңыз қолдайтын тілдерді көрсетіңіз. Сұрағанға дейін ештеңе аударылмайды.', translateTab: 'Осы қойындыны аудару', translateAllTabs: 'Барлық қойындыларды аудару', translating: 'Аударылып жатыр…', saveOne: 'Осы аударманы сақтау', saving: 'Сақталып жатыр…', savedMark: 'сақталды', skip: 'Әзірге өткізу', close: 'Жабу', hint: 'Бет әзірлеп жатырсыз ба, соңғы нұсқа екеніне сенімді емессіз бе? Аудармаларды өткізе тұрыңыз. Жазба сіз жұмыс істеп жатқан тілде қалады, мәтін нақтыланған соң қалғандарын қосасыз — нобайды аудару қайта жазылатын мәтінге уақыт пен токендерді босқа жұмсайды.', saved: 'Аударма сақталды' },
  uz: { title: 'Tarjimalarni qo‘shish', intro: 'Ilovangiz qo‘llab-quvvatlaydigan tillarni kiriting. So‘ramaguncha hech narsa tarjima qilinmaydi.', translateTab: 'Ushbu ichki oynani tarjima qiling', translateAllTabs: 'Barcha ichki oynalarni tarjima qiling', translating: 'Tarjima qilinmoqda…', saveOne: 'Ushbu tarjimani saqlang', saving: 'Saqlanmoqda…', savedMark: 'saqlandi', skip: 'Hozircha o‘tkazib turing', close: 'Yopish', hint: 'Sahifa yaratmoqdasiz-u, hali yakuniyligiga ishonchingiz komil emasmi? Tarjimalarni hozircha o‘tkazib turing. Yozuv siz ishlayotgan tilda saqlanadi, matnni yakunlagach qolgan tillarni qo‘shasiz — qoralamani tarjima qilish baribir qayta yoziladigan matnga vaqt va tokenlarni sarflaydi.', saved: 'Tarjima saqlandi' },
  ky: { title: 'Котормолорду кош', intro: 'Тиркеме кайсы тилдерде чыгарын белгилеңиз. Сураганда гана которулат.', translateTab: 'Бул өтмөктү котор', translateAllTabs: 'Бардык өтмөктөрдү котор', translating: 'Которулууда…', saveOne: 'Бул котормону сакта', saving: 'Сакталууда…', savedMark: 'сакталды', skip: 'Азырынча өткөрүп жибер', close: 'Жабуу', hint: 'Баракты долбоорлоп, акыркы версия экенине ишенбейсизби? Котормолорду өткөрүп туруңуз. Жазуу сиз иштеп жаткан тилде калат, ал эми сөздөр такталганда калганын кошосуз — караламаны которуу баары бир кайра жазчу текстке убакыт менен токендерди коротот.', saved: 'Котормо сакталды' },
  tg: { title: 'Иловаи тарҷумаҳо', intro: 'Забонҳое, ки барномаатон дар онҳо пешниҳод мешавад, пур кунед. То дархост накунед, чизе тарҷума намешавад.', translateTab: 'Тарҷумаи ин лавҳа', translateAllTabs: 'Тарҷумаи ҳамаи лавҳаҳо', translating: 'Дар ҳоли тарҷума…', saveOne: 'Захира кардани ин тарҷума', saving: 'Дар ҳоли захира…', savedMark: 'захира шуд', skip: 'Ҳоло гузаред', close: 'Бастан', hint: 'Саҳифа месозед ва мутмаин нестед, ки ниҳоист? Тарҷумаҳоро гузаред. Сабт дар забоне боқӣ мемонад, ки дар он кор мекунед, ва чун матн ниҳоӣ шуд, боқимондаро илова мекунед — тарҷумаи лоиҳа вақт ва токенҳоро барои матне сарф мекунад, ки боз менависед.', saved: 'Тарҷума захира шуд' },
  tk: { title: 'Terjimeleri goş', intro: 'Programmaňyz hödürleýän dilleri belläň. Siz soramasaňyz, hiç zat terjime edilmez.', translateTab: 'Şu bölümçäni terjime et', translateAllTabs: 'Ähli bölümçeleri terjime et', translating: 'Terjime edilýär…', saveOne: 'Bu terjimäni sakla', saving: 'Saklanýar…', savedMark: 'saklandy', skip: 'Häzirlikçe geç', close: 'Ýap', hint: 'Sahypa dizaýn edýärsiňizmi, gutarnyklydygyna ynam ýokmy? Terjimeleri geçip goýuň. Ýazgy işleýän diliňizde saklanar, tekst berkänsoň galanlaryny goşarsyňyz — taslamany terjime etmek, golaýda täzeden ýazjak tekstiňize wagt we tokenleri sarp edýär.', saved: 'Terjime saklandy' },
  az: { title: 'Tərcümələri əlavə et', intro: 'Tətbiqinizin təqdim olunduğu dilləri göstərin. Siz istəməyincə heç nə tərcümə olunmur.', translateTab: 'Bu vərəqi tərcümə et', translateAllTabs: 'Bütün vərəqləri tərcümə et', translating: 'Tərcümə olunur…', saveOne: 'Bu tərcüməni saxla', saving: 'Saxlanılır…', savedMark: 'saxlanıldı', skip: 'Hələlik keç', close: 'Bağla', hint: 'Səhifə dizayn edirsiniz və son hal olduğuna əmin deyilsiniz? Tərcümələri keçin. Qeyd hazırda işlədiyiniz dildədir, mətn sabitləşəndən sonra qalanlarını əlavə edərsiniz — qaralamanı tərcümə etmək, az sonra yenidən yazacağınız mətnə vaxt və tokenlər sərf edir.', saved: 'Tərcümə saxlanıldı' },
  hy: { title: 'Ավելացնել թարգմանություններ', intro: 'Նշեք հավելվածի աջակցվող լեզուները։ Ոչինչ չի թարգմանվի, մինչև չհանձնարարեք։', translateTab: 'Թարգմանել այս ներդիրը', translateAllTabs: 'Թարգմանել բոլոր ներդիրները', translating: 'Թարգմանվում է…', saveOne: 'Պահել այս թարգմանությունը', saving: 'Պահպանվում է…', savedMark: 'պահպանված', skip: 'Առայժմ բաց թողնել', close: 'Փակել', hint: 'Էջ եք ձևավորում և վստահ չեք, որ վերջնական է? Թողեք թարգմանությունները հետո։ Գրառումը կմնա այն լեզվով, որով աշխատում եք, իսկ մնացածը կավելացնեք, երբ ձևակերպումները հաստատվեն — սևագրի թարգմանությունը պարզապես ժամանակ և թոքեններ է ծախսում այն տեքստի վրա, որը դեռ փոխելու եք։', saved: 'Թարգմանությունը պահպանվեց' },
  ka: { title: 'თარგმანების დამატება', intro: 'მიუთითეთ ენები, რომლებშიც თქვენი აპი გამოდის. სანამ არ მოითხოვთ, არაფერი ითარგმნება.', translateTab: 'ამ ჩანართის თარგმნა', translateAllTabs: 'ყველა ჩანართის თარგმნა', translating: 'ითარგმნება…', saveOne: 'შეინახეთ ეს თარგმანი', saving: 'ინახება…', savedMark: 'შენახულია', skip: 'ჯერჯერობით გამოტოვეთ', close: 'დახურვა', hint: 'აწყობთ გვერდს და არ ხართ დარწმუნებული, რომ ეს საბოლოოა? გამოტოვეთ თარგმანები. ჩანაწერი რჩება იმ ენაზე, რომელშიც მუშაობთ, დანარჩენს კი დაამატებთ, როცა ფორმულირება დაზუსტდება — მონახაზის თარგმნა ხარჯავს დროს და ტოკენებს ტექსტზე, რომლის გადაკეთებასაც ისედაც აპირებთ.', saved: 'თარგმანი შენახულია' },
  mn: { title: 'Орчуулга нэмэх', intro: 'Апп тань түгээх хэлүүдийг оруулна уу. Та хүсэх хүртэл юу ч орчуулагдахгүй.', translateTab: 'Энэ табыг орчуулах', translateAllTabs: 'Бүх табыг орчуулах', translating: 'Орчуулж байна…', saveOne: 'Энэ орчуулгыг хадгалах', saving: 'Хадгалж байна…', savedMark: 'хадгалагдсан', skip: 'Одоохондоо алгасах', close: 'Хаах', hint: 'Хуудсаа загварчилж байгаа ч эцсийн хувилбар эсэхдээ эргэлзэж байна уу? Орчуулгыг алгасаарай. Та одоо ажиллаж буй хэл дээрээ бичлэгээ хадгалж, үг хэллэг тогтсон хойно бусдыг нь нэмж болно — ноорогийг орчуулах нь удахгүй дахин засах текстэд цаг, токен үрнэ.', saved: 'Орчуулга хадгалагдлаа' },
  ar: { title: 'إضافة ترجمات', intro: 'حدّد اللغات التي يتوفر بها تطبيقك. لن تتم أي ترجمة حتى تطلبها.', translateTab: 'ترجمة علامة التبويب هذه', translateAllTabs: 'ترجمة كل علامات التبويب', translating: 'قيد الترجمة…', saveOne: 'احفظ هذه الترجمة', saving: 'قيد الحفظ…', savedMark: 'محفوظ', skip: 'تخطي الآن', close: 'إغلاق', hint: 'تصمم صفحة ولست متأكدًا أنها نهائية؟ تجاوز الترجمات. سيبقى السجل باللغة التي تعمل بها، وتضيف البقية عندما تستقر الصياغة — ترجمة مسودة تستهلك وقتًا ورموزًا على نص ستعيد كتابته.', saved: 'تم حفظ الترجمة' },
  tr: { title: 'Çeviri ekle', intro: 'Uygulamanızın sunacağı dilleri ekleyin. Siz istemeden hiçbir şey çevrilmez.', translateTab: 'Bu sekmeyi çevir', translateAllTabs: 'Tüm sekmeleri çevir', translating: 'Çevriliyor…', saveOne: 'Bu çeviriyi kaydet', saving: 'Kaydediliyor…', savedMark: 'kaydedildi', skip: 'Şimdilik atla', close: 'Kapat', hint: 'Bir sayfa tasarlıyor ve son halinden emin değil misiniz? Çevirileri atlayın. Kayıt, çalıştığınız dilde kalır; metin netleştiğinde diğerlerini eklersiniz — bir taslağı çevirmek, az sonra yeniden yazacağınız metin için zaman ve token harcar.', saved: 'Çeviri kaydedildi' },
  he: { title: 'הוספת תרגומים', intro: 'בחר את השפות שבהן האפליקציה מופצת. שום דבר לא יתורגם עד שתבקש.', translateTab: 'תרגם כרטיסייה זו', translateAllTabs: 'תרגם את כל הכרטיסיות', translating: 'מתרגם…', saveOne: 'שמור תרגום זה', saving: 'שומר…', savedMark: 'נשמר', skip: 'דלג בינתיים', close: 'סגור', hint: 'מעצב עמוד ולא בטוח שזה סופי? דלג על התרגומים. הרשומה נשמרת בשפה שבה אתה עובד, ותוכל להוסיף את השאר כשהנוסח יתייצב — תרגום טיוטה מבזבז זמן וטוקנים על טקסט שעומד להשתנות.', saved: 'התרגום נשמר' },
  fa: { title: 'افزودن ترجمه‌ها', intro: 'زبان‌های ارائه‌شده در اپ را مشخص کنید. تا زمانی که درخواست نکنید، چیزی ترجمه نمی‌شود.', translateTab: 'ترجمهٔ این زبانه', translateAllTabs: 'ترجمهٔ همه زبانه‌ها', translating: 'در حال ترجمه…', saveOne: 'ذخیره این ترجمه', saving: 'در حال ذخیره…', savedMark: 'ذخیره‌شده', skip: 'فعلاً صرف‌نظر کن', close: 'بستن', hint: 'در حال طراحی یک صفحه‌اید و مطمئن نیستید نهایی است؟ از ترجمه‌ها بگذرید. رکورد در زبانی که با آن کار می‌کنید ذخیره می‌شود و وقتی متن نهایی شد، بقیه زبان‌ها را اضافه می‌کنید — ترجمهٔ پیش‌نویس یعنی صرف زمان و توکن برای متنی که احتمالاً دوباره می‌نویسید.', saved: 'ترجمه ذخیره شد' },
  ku: { title: 'Wergeran zêde bike', intro: 'Zimanên ku sepanê te pêşkêş dike tije bike. Heta tu daxwaz bikî, tiştek nawergerin.', translateTab: 'Vê tabê wergerîne', translateAllTabs: 'Hemû taban wergerîne', translating: 'Di wergerandinê de…', saveOne: 'Ev wergerê tomar bike', saving: 'Di tomarkirinê de…', savedMark: 'tomarkirî', skip: 'Ji bo niha derbas bibe', close: 'Bigire', hint: 'Rûpeleke tê dizaynkirin û ne bawer î ku ew dawî ye? Wergeran bihêle. Tomar di zimanê ku tu li ser wê dixebitî de dimîne, û dema nivîsar sabît bibe yên din zêde dikî — wergerandina pêşnûse dem û tokên li ser nivîsarekî ku tu ê ji nû ve binivîsî di xerc dike.', saved: 'Werger hat tomarkirin' },
  af: { title: 'Voeg vertalings by', intro: 'Vul die tale in waarin jou app beskikbaar is. Niks word vertaal totdat jy vra nie.', translateTab: 'Vertaal hierdie oortjie', translateAllTabs: 'Vertaal alle oortjies', translating: 'Vertaal…', saveOne: 'Stoor hierdie vertaling', saving: 'Stoor…', savedMark: 'gestoor', skip: 'Slaan vir nou oor', close: 'Sluit', hint: 'Ontwerp jy \'n bladsy en is jy nie seker dit is finaal nie? Slaan die vertalings oor. Die rekord bly in die taal waarin jy werk, en jy voeg die res by wanneer die bewoording vas is — om \'n konsep te vertaal spandeer tyd en tokens op teks wat jy weer gaan herskryf.', saved: 'Vertaling gestoor' },
  sw: { title: 'Ongeza tafsiri', intro: 'Jaza lugha ambazo programu yako hutolewa nazo. Hakuna kinachotafsiriwa hadi uombe.', translateTab: 'Tafsiri kichupo hiki', translateAllTabs: 'Tafsiri vichupo vyote', translating: 'Inatafsiri…', saveOne: 'Hifadhi tafsiri hii', saving: 'Inahifadhi…', savedMark: 'imehifadhiwa', skip: 'Ruka kwa sasa', close: 'Funga', hint: 'Unaunda ukurasa na huna uhakika kama umekamilika? Ruka tafsiri. Rekodi hubaki katika lugha unayofanyia kazi, na utaongeza nyingine maneno yakikamilika — kutafsiri rasimu hutumia muda na tokeni kwa maandishi ambayo utaandika upya.', saved: 'Tafsiri imehifadhiwa' },
  ha: { title: 'Ƙara fassarori', intro: 'Zaɓi harsunan da manhajarka ke fitowa da su. Ba a fassara komai sai ka nema.', translateTab: 'Fassara wannan shafin', translateAllTabs: 'Fassara dukkan shafuka', translating: 'Ana fassara…', saveOne: 'Ajiye wannan fassarar', saving: 'Ana ajiye…', savedMark: 'an ajiye', skip: 'Tsallake yanzu', close: 'Rufe', hint: 'Kana tsara shafi ba ka tabbata ya kammala ba? Tsallake fassarori. Rajistar tana cikin harshen da kake aiki da shi, kuma za ka ƙara sauran idan kalmomi sun daidaita — fassarar tsarin farko tana ɓata lokaci da tokens a kan abin da za ka sake rubutawa.', saved: 'An ajiye fassarar' },
  yo: { title: 'Fi àwọn ìtumọ̀ kún', intro: 'Kún àwọn èdè tí app rẹ̀ ń pèsè. Kò sí ohun tí a túmọ̀ títí tí o bá béèrè.', translateTab: 'Túmọ̀ táàbù yìí', translateAllTabs: 'Túmọ̀ gbogbo àwọn táàbù', translating: 'Ń túmọ̀…', saveOne: 'Fipamọ́ ìtumọ̀ yìí', saving: 'Ń fipamọ́…', savedMark: 'ti fipamọ́', skip: 'Foju kọ fún báyìí', close: 'Pá', hint: 'Ṣe o ń ṣe àpẹrẹ ojú-ìwé kan, kò sì dájú pé ó ti pé? Foju kọ ìtumọ̀. Àkọsílẹ̀ náà wà ní èdè tí o ń ṣiṣẹ́ nínú, ìwọ á sì fi yòókù kún un nígbà tí ọ̀rọ̀ bá ti pé — títúmọ̀ ìkọ̀wé àdàkọ máa ń na àkókò àti tóókènì sí ọ̀rọ̀ tí o máa tún kọ.', saved: 'Ìtumọ̀ ti fipamọ́' },
  ig: { title: 'Tinye ntụgharị asụsụ', intro: 'Tinye asụsụ ndị ngwa gị na-abịa na ha. Enweghị ihe a tụgharịrị ruo mgbe ị rịọ ya.', translateTab: 'Tụgharịa taabụ a', translateAllTabs: 'Tụgharịa taabụ niile', translating: 'Na-atụgharị…', saveOne: 'Chekwaa ntụgharị a', saving: 'Na-echekwa…', savedMark: 'echekwara', skip: 'Hapụ ya ugbu a', close: 'Mechie', hint: 'Ị na-emepepụta ibe ma ị maghị ma ọ bụ nke ikpeazụ? Hapụ ntụgharị asụsụ. Ndekọ ahụ nọ n’asụsụ ị na-arụ ọrụ na ya, ị ga-agbakwunye ndị fọdụrụ mgbe okwu kwụsiri ike — ịtụgharị draft na-ewe oge na tokens na ederede ị ga-edegharịa.', saved: 'Echekwara ntụgharị' },
  am: { title: 'ትርጉሞችን ያክሉ', intro: 'መተግበሪያዎ የሚያቀርባቸውን ቋንቋዎች ይሙሉ። እርስዎ እስኪጠይቁ ድረስ ምንም አይተረጉምም።', translateTab: 'ይህን ታብ ይተርጉሙ', translateAllTabs: 'ሁሉንም ታቦች ይተርጉሙ', translating: 'በመተርጎም ላይ…', saveOne: 'ይህን ትርጉም ያስቀምጡ', saving: 'በማስቀመጥ ላይ…', savedMark: 'ተቀምጧል', skip: 'ለጊዜው ይዝለሉ', close: 'ዝጉ', hint: 'ገጽ እየነደፉ ነዎት እና መጨረሻ መሆኑን አታረጋግጡም? ትርጉሞቹን ዝለሉ። መዝገቡ በምትሠሩበት ቋንቋ ውስጥ ይኖራል፣ እና ቃላቱ ከተወሰኑ በኋላ ቀሪዎቹን ያክሉ — ረቂቅን መተርጎም ጊዜና ቶከኖችን ያጠቃልላል።', saved: 'ትርጉም ተቀምጧል' },
  zu: { title: 'Engeza izihumusho', intro: 'Faka izilimi i-app yakho efika ngazo. Akukho okuhumushiwe kuze ucele.', translateTab: 'Humusha le thebhu', translateAllTabs: 'Humusha onke amathebhu', translating: 'Kuhumushwa…', saveOne: 'Gcina lokhu kuhumusha', saving: 'Kugcinwa…', savedMark: 'kugcinwe', skip: 'Yeqa okwamanje', close: 'Vala', hint: 'Ukuklama ikhasi kodwa awuqiniseki ukuthi sesokugcina? Yeqa ukuhumusha. Irekhodi lihlala ngolimi osebenzayo, bese wengeza okunye uma umbhalo usulungile — ukuhumusha okusalungiswa kuchitha isikhathi namathokheni embhalweni ozowubhala kabusha.', saved: 'Ukuhumusha kugciniwe' },
  xh: { title: 'Yongeza iinguqulelo', intro: 'Ngenisa iilwimi apho i-app yakho ikhoyo. Akukho nto iguqulelweyo de ucele.', translateTab: 'Guqulela le thebhu', translateAllTabs: 'Guqulela zonke iithebhu', translating: 'Kuguqulelwa…', saveOne: 'Gcina le nguqulelo', saving: 'Kugcinwa…', savedMark: 'Kugcinwe', skip: 'Tsiba okwangoku', close: 'Vala', hint: 'Uyila iphepha ungakaqiniseki ukuba ligqityiwe? Tsiba iinguqulelo. Irekhodi lihlala kulwimi osebenza kulo, uze wongeze ezinye xa amagama esezinzile — ukuguqulela umbhalo ongagqitywanga kuchitha ixesha neetoken kumbhalo oza kuwuphinda ubhale.', saved: 'Inguqulelo igciniwe' },
  rw: { title: 'Ongeraho amasemura', intro: 'Uzuza indimi porogaramu yawe izatangiramo. Nta kintu gisemurwa keretse ubisabye.', translateTab: 'Semura iyi tab', translateAllTabs: 'Semura tab zose', translating: 'Birimo gusemurwa…', saveOne: 'Bika iri semura', saving: 'Birimo kubikwa…', savedMark: 'bibitswe', skip: 'Simbuka ubu', close: 'Funga', hint: 'Uri gutunganya urupapuro kandi ntuzi niba ari verisiyo ya nyuma? Simbuka isemura. Icyanditswe kibikwa mu rurimi urimo gukoreramo, hanyuma wongeraho izindi ndimi igihe amagambo yamaze kwemezwa — gusemura inyandiko y’agateganyo (draft) bitwara igihe na tokens ku magambo ugiye kongera kwandika.', saved: 'Isemura ribitswe' },
  so: { title: 'Ku dar turjumaado', intro: 'Dooro luqadaha uu app-kaagu la yimaado. Waxba lama turjumo ilaa aad codsato.', translateTab: 'Turjun tab-kan', translateAllTabs: 'Turjun dhammaan tab-yada', translating: 'Turjumayaa…', saveOne: 'Keydi turjumaaddan', saving: 'Keydinayaa…', savedMark: 'la keydiyay', skip: 'Ka bood hadda', close: 'Xir', hint: 'Bog ayaad naqshadaynaysaa oo ma hubtid inuu weli dhammaystiran yahay? Ka bood turjumaadaha. Diiwaanku waxa uu ku jiraa luqadda aad ka shaqaynayso, inta kalena ku dar marka qoraalku dego — turjumaadda qabyo waxay ku luminaysaa waqti iyo tokens qoraal aad dib u qori doonto.', saved: 'Turjumaadda waa la keydiyay' },
  zh: { title: '添加翻译', intro: '填写你的应用支持的语言。除非你请求，否则不会翻译任何内容。', translateTab: '翻译此标签页', translateAllTabs: '翻译所有标签页', translating: '正在翻译…', saveOne: '保存此翻译', saving: '正在保存…', savedMark: '已保存', skip: '暂时跳过', close: '关闭', hint: '在设计页面但不确定是否定稿？先跳过翻译。记录会以你当前使用的语言保存，等文案稳定后再补充其他语言——为草稿翻译只会把时间和 tokens 花在即将改写的文本上。', saved: '翻译已保存' },
  ja: { title: '翻訳を追加', intro: '対応言語を設定してください。依頼するまで翻訳は行われません。', translateTab: 'このタブを翻訳', translateAllTabs: 'すべてのタブを翻訳', translating: '翻訳中…', saveOne: 'この翻訳を保存', saving: '保存中…', savedMark: '保存済み', skip: '今はスキップ', close: '閉じる', hint: 'ページを設計中で、まだ最終ではない場合は、翻訳はスキップしましょう。レコードは作業中の言語で保持され、文言が固まってから残りを追加できます—下書きを翻訳すると、書き直すテキストに時間とトークンを費やすことになります。', saved: '翻訳を保存しました' },
  ko: { title: '번역 추가', intro: '앱에서 제공할 언어를 설정하세요. 요청하기 전까지는 아무것도 번역되지 않습니다.', translateTab: '이 탭 번역', translateAllTabs: '모든 탭 번역', translating: '번역 중…', saveOne: '이 번역 저장', saving: '저장 중…', savedMark: '저장됨', skip: '지금은 건너뛰기', close: '닫기', hint: '페이지를 디자인 중인데 최종이 아닐 수도 있나요? 번역은 건너뛰세요. 항목은 현재 작업 중인 언어로 저장되며, 문구가 확정되면 나머지 언어를 추가하세요 — 초안을 번역하면 곧 수정할 텍스트에 시간과 토큰을 쓰게 됩니다.', saved: '번역이 저장되었습니다' },
  hi: { title: 'अनुवाद जोड़ें', intro: 'ऐप किन भाषाओं में उपलब्ध है, उन्हें भरें। जब तक आप अनुरोध न करें, कुछ भी अनुवादित नहीं होगा।', translateTab: 'इस टैब का अनुवाद करें', translateAllTabs: 'सभी टैब्स का अनुवाद करें', translating: 'अनुवाद हो रहा है…', saveOne: 'यह अनुवाद सहेजें', saving: 'सहेजा जा रहा है…', savedMark: 'सहेजा गया', skip: 'अभी के लिए छोड़ें', close: 'बंद करें', hint: 'क्या आप पेज डिज़ाइन कर रहे हैं और यकीन नहीं कि यह अंतिम है? अनुवाद छोड़ दें। रिकॉर्ड उसी भाषा में रहता है जिसमें आप काम कर रहे हैं, और जब शब्द तय हो जाएँ तो बाकी जोड़ें — ड्राफ्ट का अनुवाद उस टेक्स्ट पर समय और टोकन खर्च करता है जिसे आप अभी फिर से लिखने वाले हैं।', saved: 'अनुवाद सहेजा गया' },
  ur: { title: 'ترجمے شامل کریں', intro: 'اپنی ایپ کی زبانیں منتخب کریں۔ جب تک آپ کہیں، کچھ بھی ترجمہ نہیں ہوگا۔', translateTab: 'اس ٹیب کا ترجمہ کریں', translateAllTabs: 'تمام ٹیبز کا ترجمہ کریں', translating: 'ترجمہ ہو رہا ہے…', saveOne: 'یہ ترجمہ محفوظ کریں', saving: 'محفوظ کیا جا رہا ہے…', savedMark: 'محفوظ', skip: 'ابھی کے لیے چھوڑیں', close: 'بند کریں', hint: 'صفحہ ڈیزائن کر رہے ہیں اور یقین نہیں کہ یہ حتمی ہے؟ ترجمے چھوڑ دیں۔ ریکارڈ اسی زبان میں رہتا ہے جس میں آپ کام کر رہے ہیں، اور جب الفاظ طے ہو جائیں تو باقی شامل کر دیں — مسودہ ترجمہ کرنا اس متن پر وقت اور ٹوکنز خرچ کرتا ہے جسے آپ ابھی دوبارہ لکھنے والے ہیں۔', saved: 'ترجمہ محفوظ ہو گیا' },
  bn: { title: 'অনুবাদ যোগ করুন', intro: 'আপনার অ্যাপ যেসব ভাষায় দেওয়া হয়, সেগুলো দিন। আপনি না বললে কিছুই অনুবাদ হবে না।', translateTab: 'এই ট্যাবটি অনুবাদ করুন', translateAllTabs: 'সব ট্যাব অনুবাদ করুন', translating: 'অনুবাদ হচ্ছে…', saveOne: 'এই অনুবাদ সংরক্ষণ করুন', saving: 'সংরক্ষণ হচ্ছে…', savedMark: 'সংরক্ষিত', skip: 'এখন এড়িয়ে যান', close: 'বন্ধ করুন', hint: 'পেজ ডিজাইন করছেন, চূড়ান্ত নয়? অনুবাদ এড়িয়ে যান। আপনি যে ভাষায় কাজ করছেন, রেকর্ডটি সেখানেই থাকে; শব্দচয়ন ঠিক হলে বাকি ভাষা যোগ করুন — খসড়া অনুবাদে সময় ও টোকেন নষ্ট হয়, যেটি আপনি আবারই লিখবেন।', saved: 'অনুবাদ সংরক্ষিত' },
  te: { title: 'అనువాదాలను జోడించండి', intro: 'మీ యాప్ అందించే భాషలను నమోదు చేయండి. మీరు కోరే వరకు ఏదీ అనువదించబడదు.', translateTab: 'ఈ ట్యాబ్‌ను అనువదించండి', translateAllTabs: 'అన్ని ట్యాబ్‌లను అనువదించండి', translating: 'అనువదిస్తోంది…', saveOne: 'ఈ అనువాదాన్ని సేవ్ చేయండి', saving: 'సేవ్ చేస్తోంది…', savedMark: 'సేవ్ అయింది', skip: 'ఇప్పటికైతే దాటవేయండి', close: 'మూసివేయండి', hint: 'ఒక పేజీని డిజైన్ చేస్తూ, ఇది ఫైనలైజ్ కాలేదా? అనువాదాలను స్కిప్ చేయండి. మీరు పనిచేస్తున్న భాషలోనే రికార్డు ఉంటుంది; పదాలు స్థిరపడిన తర్వాత మిగతావి జోడించండి — డ్రాఫ్ట్‌ను అనువదిస్తే, వెంటనే తిరిగి రాయబోయే టెక్స్ట్‌పైనే సమయం, టోకెన్లు ఖర్చవుతాయి.', saved: 'అనువాదం సేవ్ అయింది' },
  mr: { title: 'अनुवाद जोडा', intro: 'तुमचे ॲप ज्या भाषांमध्ये उपलब्ध आहे त्या भाषा भरा. तुम्ही मागितल्याशिवाय काहीही अनुवादित होत नाही.', translateTab: 'हा टॅब अनुवादित करा', translateAllTabs: 'सर्व टॅब अनुवादित करा', translating: 'अनुवाद करत आहे…', saveOne: 'हा अनुवाद जतन करा', saving: 'जतन करत आहे…', savedMark: 'जतन झाले', skip: 'आत्तासाठी वगळा', close: 'बंद करा', hint: 'पृष्ठ डिझाइन करत आहात आणि अंतिम ठरलेले नाही? अनुवाद वगळा. नोंद तुम्ही ज्या भाषेत काम करता त्यातच राहते; मांडणी ठरल्यानंतर बाकीच्या भाषा जोडा — मसुद्याचा अनुवाद केल्यास तुम्ही पुन्हा लिहिणार असलेल्या मजकूरावर वेळ आणि टोकन्स खर्च होतात.', saved: 'अनुवाद जतन झाला' },
  kn: { title: 'ಅನುವಾದಗಳನ್ನು ಸೇರಿಸಿ', intro: 'ನಿಮ್ಮ ಆಪ್ ಒಳಗೊಂಡಿರುವ ಭಾಷೆಗಳನ್ನು ಸೇರಿಸಿ. ನೀವು ಕೇಳುವವರೆಗೆ ಯಾವುದೂ ಅನುವಾದವಾಗದು.', translateTab: 'ಈ ಟ್ಯಾಬ್ ಅನ್ನು ಅನುವಾದಿಸಿ', translateAllTabs: 'ಎಲ್ಲಾ ಟ್ಯಾಬ್‌ಗಳನ್ನು ಅನುವಾದಿಸಿ', translating: 'ಅನುವಾದಿಸುತ್ತಿದೆ…', saveOne: 'ಈ ಅನುವಾದವನ್ನು ಉಳಿಸಿ', saving: 'ಉಳಿಸುತ್ತಿದೆ…', savedMark: 'ಉಳಿಸಲಾಗಿದೆ', skip: 'ಈಗಕ್ಕೆ ಬಿಟ್ಟುಬಿಡಿ', close: 'ಮುಚ್ಚಿ', hint: 'ಪುಟವನ್ನು ವಿನ್ಯಾಸಗೊಳಿಸುತ್ತಿದ್ದೀರಿ, ಅಂತಿಮವೇ ಎಂದು ಖಚಿತವಿಲ್ಲವೇ? ಅನುವಾದಗಳನ್ನು ಈಗ ಬಿಡಿ. ನೀವು ಕೆಲಸ ಮಾಡುತ್ತಿರುವ ಭಾಷೆಯಲ್ಲೇ ದಾಖಲೆ ಉಳಿಯುತ್ತದೆ; ಪದಪ್ರಯೋಗ ಸ್ಥಿರವಾದ ಮೇಲೆ ಉಳಿದುದನ್ನು ಸೇರಿಸಿ — ಕರಡು ಅನುವಾದಿಸುವುದು ನೀವು ಮರಳಿ ಬರೆಯಲಿರುವ ಪಠ್ಯಕ್ಕೆ ಸಮಯ ಮತ್ತು ಟೋಕನ್‌ಗಳನ್ನು ಖರ್ಚುಮಾಡುತ್ತದೆ.', saved: 'ಅನುವಾದ ಉಳಿಸಲಾಗಿದೆ' },
  gu: { title: 'અનુવાદો ઉમેરો', intro: 'તમારું ઍપ જે ભાષાઓમાં આવે છે, તે ઉમેરો. તમે કહો ત્યાં સુધી કંઈનું અનુવાદ થતું નથી.', translateTab: 'આ ટૅબનો અનુવાદ કરો', translateAllTabs: 'બધા ટૅબ્સનો અનુવાદ કરો', translating: 'અનુવાદ થઈ રહ્યો છે…', saveOne: 'આ અનુવાદ સાચવો', saving: 'સાચવાઈ રહ્યું છે…', savedMark: 'સાચવાયું', skip: 'હાલ માટે છોડો', close: 'બંધ કરો', hint: 'પેજ ડિઝાઇન કરી રહ્યા છો અને અંતિમ છે કે નહીં ખાતરી નથી? અનુવાદો હાલ છોડો. રેકોર્ડ તે ભાષામાં જ રહેશે જેમાં તમે કામ કરો છો, અને શબ્દરચના સ્થિર થાય પછી બાકી ઉમેરશો — ડ્રાફ્ટનું અનુવાદ કરવાથી તમે જે લખાણ ફરી લખવાના છો उसमें સમય અને ટોકન્સ ખર્ચાય છે.', saved: 'અનુવાદ સાચવાયો' },
  ml: { title: 'പരിഭാഷകൾ ചേർക്കുക', intro: 'നിങ്ങളുടെ ആപ്പ് നൽകുന്ന ഭാഷകൾ പൂരിപ്പിക്കുക. നിങ്ങൾ ആവശ്യപ്പെടുന്നതുവരെ ഒന്നും പരിഭാഷപ്പെടുത്തുകയില്ല.', translateTab: 'ഈ ടാബ് പരിഭാഷപ്പെടുത്തുക', translateAllTabs: 'എല്ലാ ടാബുകളും പരിഭാഷപ്പെടുത്തുക', translating: 'പരിഭാഷപ്പെടുത്തുന്നു…', saveOne: 'ഈ പരിഭാഷ സംരക്ഷിക്കുക', saving: 'സംരക്ഷിക്കുന്നു…', savedMark: 'സംരക്ഷിച്ചു', skip: 'ഇപ്പോൾ ഒഴിവാക്കുക', close: 'അടയ്ക്കുക', hint: 'ഒരു പേജ് ഡിസൈൻ ചെയ്യുകയാണോ, അന്തിമമാണെന്ന് ഉറപ്പില്ലേ? പരിഭാഷകൾ ഒഴിവാക്കുക. നിങ്ങൾ പ്രവർത്തിക്കുന്ന ഭാഷയിലാണ് രേഖ നിലനിൽക്കുന്നത്; വാചകം അന്തിമമായാൽ ശേഷമുള്ളത് ചേർക്കാം — കരട് പരിഭാഷപ്പെടുത്തുന്നത് ഉടൻ തന്നെ പുനർരചിക്കാനിരിക്കുന്ന എഴുത്തിന് സമയംയും ടോക്കണുകളും ചെലവാക്കും.', saved: 'പരിഭാഷ സംരക്ഷിച്ചു' },
  ta: { title: 'மொழிபெயர்ப்புகளைச் சேர்க்கவும்', intro: 'உங்கள் செயலி வழங்கும் மொழிகளை நிரப்பவும். நீங்கள் கேட்கும் வரை எதுவும் மொழிபெயர்க்கப்படாது.', translateTab: 'இந்த தாவலை மொழிபெயர்க்கவும்', translateAllTabs: 'அனைத்து தாவல்களையும் மொழிபெயர்க்கவும்', translating: 'மொழிபெயர்க்கிறது…', saveOne: 'இந்த மொழிபெயர்ப்பை சேமிக்கவும்', saving: 'சேமிக்கிறது…', savedMark: 'சேமிக்கப்பட்டது', skip: 'இப்போது தவிர்க்கவும்', close: 'மூடு', hint: 'ஒரு பக்கத்தை வடிவமைத்து, இது இறுதியா என்பது உறுதியாக இல்லையா? மொழிபெயர்ப்புகளைத் தவிர்க்கவும். பதிவு நீங்கள் பணிபுரியும் மொழியில்தான் இருக்கும்; உரை உறுதியாகிய பிறகு மற்றவற்றைச் சேர்க்கலாம் — வரைவை இப்போது மொழிபெயர்த்தால், பின்னர் மாற்றப் போகும் உரைக்காக நேரமும் டோக்கன்களும் செலவாகும்.', saved: 'மொழிபெயர்ப்பு சேமிக்கப்பட்டது' },
  ne: { title: 'अनुवाद थप्नुहोस्', intro: 'एप पठाइने भाषाहरू भर्नुहोस्। तपाईंले अनुरोध नगरेसम्म केही पनि अनुवाद हुँदैन।', translateTab: 'यो ट्याब अनुवाद गर्नुहोस्', translateAllTabs: 'सबै ट्याबहरू अनुवाद गर्नुहोस्', translating: 'अनुवाद गर्दै…', saveOne: 'यो अनुवाद सेभ गर्नुहोस्', saving: 'सेभ गर्दै…', savedMark: 'सेभ भयो', skip: 'अहिलेलाई छोड्नुहोस्', close: 'बन्द गर्नुहोस्', hint: 'पेज डिजाइन गर्दै हुनुहुन्छ र अन्तिम होइन जस्तो लाग्छ? अनुवादहरू छोड्नुहोस्। रेकर्ड तपाईं काम गरिरहेको भाषामै बस्छ, शब्द टुंगिएपछि बाँकी थप्नुहोस् — ड्राफ्ट अनुवाद गर्दा फेरि लेख्नै पर्ने पाठमा समय र टोकन खर्चिन्छ।', saved: 'अनुवाद सेभ भयो' },
  vi: { title: 'Thêm bản dịch', intro: 'Thiết lập các ngôn ngữ ứng dụng của bạn phát hành kèm. Chưa có gì được dịch cho đến khi bạn yêu cầu.', translateTab: 'Dịch tab này', translateAllTabs: 'Dịch tất cả các tab', translating: 'Đang dịch…', saveOne: 'Lưu bản dịch này', saving: 'Đang lưu…', savedMark: 'đã lưu', skip: 'Tạm bỏ qua', close: 'Đóng', hint: 'Đang thiết kế trang và chưa chắc đã là bản cuối? Hãy bỏ qua phần dịch. Bản ghi dùng ngôn ngữ bạn đang làm việc; bạn thêm các ngôn ngữ khác khi câu chữ đã ổn — dịch bản nháp sẽ tốn thời gian và token cho nội dung bạn sắp viết lại.', saved: 'Đã lưu bản dịch' },
  th: { title: 'เพิ่มคำแปล', intro: 'เพิ่มภาษาที่แอปของคุณรองรับ จะไม่มีการแปลจนกว่าคุณจะสั่ง', translateTab: 'แปลแท็บนี้', translateAllTabs: 'แปลทุกแท็บ', translating: 'กำลังแปล…', saveOne: 'บันทึกคำแปลนี้', saving: 'กำลังบันทึก…', savedMark: 'บันทึกแล้ว', skip: 'ข้ามไปก่อน', close: 'ปิด', hint: 'กำลังออกแบบหน้าและยังไม่แน่ใจว่าลงตัวหรือยัง? ข้ามการแปลไปก่อนได้ รายการจะอยู่ในภาษาที่คุณกำลังทำงานอยู่ และคุณค่อยเพิ่มส่วนที่เหลือเมื่อถ้อยคำลงตัว — การแปลฉบับร่างจะใช้ทั้งเวลาและโทเค็นกับข้อความที่คุณกำลังจะเขียนใหม่', saved: 'บันทึกคำแปลแล้ว' },
  id: { title: 'Tambah terjemahan', intro: 'Tambahkan bahasa yang disertakan aplikasi Anda. Tidak ada yang diterjemahkan sebelum Anda memintanya.', translateTab: 'Terjemahkan tab ini', translateAllTabs: 'Terjemahkan semua tab', translating: 'Menerjemahkan…', saveOne: 'Simpan terjemahan ini', saving: 'Menyimpan…', savedMark: 'tersimpan', skip: 'Lewati dulu', close: 'Tutup', hint: 'Sedang merancang halaman dan belum yakin sudah final? Lewati terjemahannya. Catatan tetap berada dalam bahasa yang Anda gunakan, dan Anda bisa menambahkan sisanya saat redaksinya sudah mantap — menerjemahkan draf menghabiskan waktu dan token untuk teks yang akan Anda tulis ulang.', saved: 'Terjemahan disimpan' },
  ms: { title: 'Tambah terjemahan', intro: 'Isi bahasa yang disokong aplikasi anda. Tiada yang diterjemah sehingga anda memintanya.', translateTab: 'Terjemah tab ini', translateAllTabs: 'Terjemah semua tab', translating: 'Menterjemah…', saveOne: 'Simpan terjemahan ini', saving: 'Menyimpan…', savedMark: 'disimpan', skip: 'Langkau buat masa ini', close: 'Tutup', hint: 'Sedang mereka bentuk halaman dan belum pasti versi akhirnya? Langkau terjemahan. Rekod kekal dalam bahasa yang anda sedang gunakan, dan anda boleh menambah selebihnya apabila ayat dimuktamadkan — menterjemah draf membazirkan masa dan token pada teks yang bakal anda ubah semula.', saved: 'Terjemahan disimpan' },
  tl: { title: 'Magdagdag ng mga salin', intro: 'Punan ang mga wikang kasama sa app mo. Walang isasalin hanggang hilingin mo.', translateTab: 'Isalin ang tab na ito', translateAllTabs: 'Isalin ang lahat ng tab', translating: 'Isinasalin…', saveOne: 'I-save ang salin na ito', saving: 'Nagse-save…', savedMark: 'naka-save', skip: 'Laktawan muna', close: 'Isara', hint: 'Nagdidisenyo ka ng pahina at hindi sigurado kung final na? Laktawan muna ang mga salin. Mananatili ang record sa wikang ginagamit mo, at idagdag mo na lang ang iba kapag napinal na ang teksto — ang pagsasalin ng draft ay nag-aaksaya ng oras at mga token sa tekstong babaguhin mo rin.', saved: 'Na-save ang salin' },
  my: { title: 'ဘာသာပြန်ချက်များ ထည့်ပါ', intro: 'သင့်အက်ပ် ထုတ်ဝေမည့် ဘာသာစကားများကို ဖြည့်ပါ။ သင်တောင်းဆိုမချင်း ဘာမှ ဘာသာမပြန်ပါ။', translateTab: 'ဤတැබ်ကို ဘာသာပြန်ပါ', translateAllTabs: 'တැබ်များ အားလုံးကို ဘာသာပြန်ပါ', translating: 'ဘာသာပြန်နေသည်…', saveOne: 'ဤဘာသာပြန်ချက်ကို သိမ်းပါ', saving: 'သိမ်းဆည်းနေသည်…', savedMark: 'သိမ်းပြီး', skip: 'ယခုအတွက် ကျော်ပါ', close: 'ပိတ်ပါ', hint: 'စာမျက်နှာတစ်ခုကို ဒီဇိုင်းဆွဲနေပြီး အပြီးသတ် ဖြစ်မဖြစ် မသေချာသေးလား? ဘာသာပြန်ခြင်းကို အရင် ကျော်ထားပါ။ သင် လုပ်နေသော ဘာသာစကားတွင်ပဲ မှတ်တမ်းက ရှိနေပါမယ်၊ စာသား တည်ငြိမ်လာပြီးမှ ကျန်သော ဘာသာများကို ထပ်ထည့်နိုင်ပါတယ် — မူကြမ်းကို ဘာသာပြန်လိုက်ရင် မကြာခဏ ပြန်ရေးမည့် စာအတွက် အချိန်နဲ့ တိုကင်များ ဆုံးသွားနိုင်ပါတယ်။', saved: 'ဘာသာပြန်ချက် သိမ်းပြီး' },
  km: { title: 'បន្ថែមការបកប្រែ', intro: 'បញ្ចូលភាសាដែលកម្មវិធីរបស់អ្នកផ្តល់ជូន។ អ្វីៗមិនត្រូវបានបកប្រែទេ ទាល់តែអ្នកស្នើសុំ។', translateTab: 'បកប្រែផ្ទាំងនេះ', translateAllTabs: 'បកប្រែផ្ទាំងទាំងអស់', translating: 'កំពុងបកប្រែ…', saveOne: 'រក្សាទុកការបកប្រែនេះ', saving: 'កំពុងរក្សាទុក…', savedMark: 'បានរក្សាទុក', skip: 'រំលងសិន', close: 'បិទ', hint: 'កំពុងរចនាទំព័រ ហើយមិនប្រាកដថាជាចុងក្រោយទេ? រំលងការបកប្រែសិន។ កំណត់ត្រានឹងនៅជាភាសាដែលអ្នកកំពុងធ្វើការ ហើយអ្នកអាចបន្ថែមភាសាផ្សេងៗនៅពេលអត្ថបទបានច្បាស់លាស់។ ការបកប្រែសេចក្តីព្រាងអាចខ្ជះខ្ជាយពេលវេលា និង tokens លើអត្ថបទដែលអ្នកនឹងកែសរសេរ។', saved: 'បានរក្សាទុកការបកប្រែ' },
  lo: { title: 'ເພີ່ມຄຳແປ', intro: 'ລະບຸພາສາທີ່ແອັບຂອງທ່ານຮອງຮັບ. ຈະບໍ່ມີການແປຈົນກວ່າທ່ານຮ້ອງຂໍ.', translateTab: 'ແປແທັບນີ້', translateAllTabs: 'ແປທຸກແທັບ', translating: 'ກຳລັງແປ…', saveOne: 'ບັນທຶກການແປນີ້', saving: 'ກຳລັງບັນທຶກ…', savedMark: 'ບັນທຶກແລ້ວ', skip: 'ຂ້າມໄປກ່ອນ', close: 'ປິດ', hint: 'ກຳລັງອອກແບບໜ້າ ແລະຍັງບໍ່ແນ່ໃຈວ່າສຸດທ້າຍບໍ? ຂ້າມການແປໄປກ່ອນ. ລາຍການຈະຢູ່ໃນພາສາທີ່ທ່ານກຳລັງໃຊ້ງານ ແລະທ່ານຈະເພີ່ມພາສາອື່ນໄດ້ເມື່ອຂໍ້ຄວາມກຳນົດແນ່. ການແປຮ່າງເປັນການເສຍເວລາ ແລະໃຊ້ໂຕເຄນກັບຂໍ້ຄວາມທີ່ຈະຂຽນໃໝ່.', saved: 'ບັນທຶກການແປແລ້ວ' },
}

export function translationsUi(lang: string): TranslationsUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
