// ─────────────────────────────────────────────────────────────────────────────
// parser-fs — ONE universal, config-driven post-list generator.
//
// Why this exists: posts (news/documentation/…) are co-located static route
// folders (page.tsx + _components + _data). The index/router page of each tab
// needs a list of its posts, but Turbopack (webpack is prohibited here) needs
// STATICALLY resolvable imports — so the list can't be discovered at runtime.
// This script discovers posts at BUILD time by scanning the filesystem and
// GENERATES a plain `_list.generated.ts` (static imports + a POSTS array). The
// runtime stays 100% static / no-JS; nobody hand-maintains a list.
//
// Reuse for any new tab: add one entry to COLLECTIONS below (the tab's posts must
// already be co-located, i.e. each post folder has _data/index.ts). Run via npm
// prebuild/predev (see package.json). The generated files are gitignored.
//
// Node ESM, zero deps — runs with bare `node lib/parser-fs.mjs` on any Node.
// ─────────────────────────────────────────────────────────────────────────────

import { readdirSync, existsSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

// Each collection = one tab whose posts are co-located. `type`/`typeModule` are
// the post-data type the tab's _data/index.ts exports as `data`.
const COLLECTIONS = [
  { dir: 'app/[lang]/blog',          type: 'BlogData',       typeModule: './_lib/post' },
]

// A post folder = a direct child dir that is not Next-private (`_`) / dynamic
// (`[`) and that contains `_data/index.ts`.
function findPostSlugs(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter(name => !name.startsWith('_') && !name.startsWith('[') && !name.startsWith('.'))
    .filter(name => statSync(join(dir, name)).isDirectory())
    .filter(name => existsSync(join(dir, name, '_data', 'index.ts')))
    .sort() // deterministic import order; runtime sorts by date anyway
}

function generate({ dir, type, typeModule }) {
  const slugs = findPostSlugs(dir)
  const imports = slugs.map((slug, i) => `import { data as p${i} } from './${slug}/_data'`).join('\n')
  const arr = slugs.map((_, i) => `p${i}`).join(', ')
  const body = `// AUTO-GENERATED by lib/parser-fs.mjs — DO NOT EDIT.
// Regenerated on every build/dev (npm prebuild/predev). Gitignored.
// Lists every post folder under this collection that has _data/index.ts.
import type { ${type} } from '${typeModule}'
${imports}

export const POSTS: ${type}[] = [${arr}]
`
  const out = join(dir, '_list.generated.ts')
  writeFileSync(out, body, 'utf8')
  return { out, count: slugs.length }
}

let total = 0
for (const c of COLLECTIONS) {
  const { out, count } = generate(c)
  total += count
  console.log(`parser-fs: ${out} (${count} posts)`)
}
console.log(`parser-fs: generated ${COLLECTIONS.length} list(s), ${total} posts total`)
