// ОБЩИЙ СЛОВАРЬ СПИСКА ТОВАРОВ — колонки, тулбар, пагинация, состояния.
//
// 🔒 ПОЧЕМУ ОН ОДИН НА ЧЕТЫРЕ СЛОЯ. Эти двадцать слов принадлежат не странице, а
// ТАБЛИЦЕ, которая стоит во всех четырёх слоях прав: «Цена» одинакова у
// менеджера, бухгалтера, администратора и покупателя. Скопированные в четыре
// словаря, они дают четыре места правки одного слова — и четыре повода
// разойтись. Хуже того: на 82 языках это была бы четырёхкратная оплата одного и
// того же перевода.
//
// 🔒 82 ЯЗЫКА, потому что общий предок четырёх слоёв — это уже переиспользуемая
// часть продукта: любой проект на этом стартере, где есть список чего угодно,
// получает эти слова целиком. Отличительные строки каждого слоя (заголовок,
// объяснение его единственного права, его тосты) остались при своих страницах.
//
// Языки и их порядок — тот же список, что у ящика аккаунта и корзины.

export type ProductListUi = {
  /** Колонки таблицы. */
  colPhoto: string
  colName: string
  colPrice: string
  colId: string
  /** Состояния. */
  empty: string
  loading: string
  failed: string
  /** Счётчик: `{count}`. */
  count: string
  /** Тулбар. */
  tableTitle: string
  reveal: string
  revealHint: string
  searchPlaceholder: string
  find: string
  reset: string
  /** Пагинация. */
  perPage: string
  prev: string
  next: string
  /** `{page}` из `{pages}`. */
  pageOf: string
  first: string
  last: string
}

const UI: Record<string, ProductListUi> = {
  en: { colPhoto: "Photo", colName: "Product", colPrice: "Price", colId: "ID", empty: "The catalogue is empty.", loading: "Loading…", failed: "Could not do that. Try again.", count: "{count} products", tableTitle: "Catalogue", reveal: "Show products", revealHint: "Nothing is requested until you ask — the page opens instantly and costs the database nothing.", searchPlaceholder: "Search by name…", find: "Find", reset: "Reset", perPage: "Per page", prev: "Back", next: "Forward", pageOf: "Page {page} of {pages}", first: "First", last: "Last" },
  fr: { colPhoto: "Photo", colName: "Produit", colPrice: "Prix", colId: "ID", empty: "Le catalogue est vide.", loading: "Chargement…", failed: "Échec. Réessayez.", count: "{count} produits", tableTitle: "Catalogue", reveal: "Afficher les produits", revealHint: "Rien n’est demandé tant que vous ne le demandez pas — la page s’ouvre aussitôt et ne coûte rien à la base.", searchPlaceholder: "Rechercher par nom…", find: "Chercher", reset: "Réinitialiser", perPage: "Par page", prev: "Précédent", next: "Suivant", pageOf: "Page {page} sur {pages}", first: "Première", last: "Dernière" },
  es: { colPhoto: "Foto", colName: "Producto", colPrice: "Precio", colId: "ID", empty: "El catálogo está vacío.", loading: "Cargando…", failed: "No se pudo. Inténtelo de nuevo.", count: "{count} productos", tableTitle: "Catálogo", reveal: "Mostrar productos", revealHint: "No se pide nada hasta que lo solicite: la página se abre al instante y no cuesta nada a la base de datos.", searchPlaceholder: "Buscar por nombre…", find: "Buscar", reset: "Restablecer", perPage: "Por página", prev: "Atrás", next: "Adelante", pageOf: "Página {page} de {pages}", first: "Primera", last: "Última" },
  pt: { colPhoto: "Foto", colName: "Produto", colPrice: "Preço", colId: "ID", empty: "O catálogo está vazio.", loading: "Carregando…", failed: "Não deu certo. Tente de novo.", count: "{count} produtos", tableTitle: "Catálogo", reveal: "Mostrar produtos", revealHint: "Nada é solicitado até você pedir — a página abre na hora e não custa nada ao banco.", searchPlaceholder: "Buscar por nome…", find: "Buscar", reset: "Redefinir", perPage: "Por página", prev: "Voltar", next: "Avançar", pageOf: "Página {page} de {pages}", first: "Primeira", last: "Última" },
  de: { colPhoto: "Foto", colName: "Produkt", colPrice: "Preis", colId: "ID", empty: "Der Katalog ist leer.", loading: "Wird geladen…", failed: "Hat nicht geklappt. Erneut versuchen.", count: "{count} Produkte", tableTitle: "Katalog", reveal: "Produkte anzeigen", revealHint: "Nichts wird abgefragt, bis Sie es verlangen — die Seite öffnet sofort und kostet die Datenbank nichts.", searchPlaceholder: "Nach Namen suchen…", find: "Suchen", reset: "Zurücksetzen", perPage: "Pro Seite", prev: "Zurück", next: "Weiter", pageOf: "Seite {page} von {pages}", first: "Erste", last: "Letzte" },
  it: { colPhoto: "Foto", colName: "Prodotto", colPrice: "Prezzo", colId: "ID", empty: "Il catalogo è vuoto.", loading: "Caricamento…", failed: "Non è riuscito. Riprova.", count: "{count} prodotti", tableTitle: "Catalogo", reveal: "Mostra i prodotti", revealHint: "Non viene chiesto nulla finché non lo chiedi: la pagina si apre subito e non costa nulla al database.", searchPlaceholder: "Cerca per nome…", find: "Cerca", reset: "Reimposta", perPage: "Per pagina", prev: "Indietro", next: "Avanti", pageOf: "Pagina {page} di {pages}", first: "Prima", last: "Ultima" },
  nl: { colPhoto: "Foto", colName: "Product", colPrice: "Prijs", colId: "ID", empty: "De catalogus is leeg.", loading: "Laden…", failed: "Het lukte niet. Probeer opnieuw.", count: "{count} producten", tableTitle: "Catalogus", reveal: "Producten tonen", revealHint: "Er wordt niets opgevraagd tot u erom vraagt — de pagina opent meteen en kost de database niets.", searchPlaceholder: "Zoek op naam…", find: "Zoeken", reset: "Herstellen", perPage: "Per pagina", prev: "Terug", next: "Verder", pageOf: "Pagina {page} van {pages}", first: "Eerste", last: "Laatste" },
  sv: { colPhoto: "Foto", colName: "Produkt", colPrice: "Pris", colId: "ID", empty: "Katalogen är tom.", loading: "Laddar…", failed: "Det gick inte. Försök igen.", count: "{count} produkter", tableTitle: "Katalog", reveal: "Visa produkter", revealHint: "Ingenting hämtas förrän du ber om det — sidan öppnas direkt och kostar databasen ingenting.", searchPlaceholder: "Sök på namn…", find: "Sök", reset: "Återställ", perPage: "Per sida", prev: "Bakåt", next: "Framåt", pageOf: "Sida {page} av {pages}", first: "Första", last: "Sista" },
  no: { colPhoto: "Foto", colName: "Produkt", colPrice: "Pris", colId: "ID", empty: "Katalogen er tom.", loading: "Laster…", failed: "Det gikk ikke. Prøv igjen.", count: "{count} produkter", tableTitle: "Katalog", reveal: "Vis produkter", revealHint: "Ingenting hentes før du ber om det — siden åpnes med en gang og koster databasen ingenting.", searchPlaceholder: "Søk på navn…", find: "Søk", reset: "Nullstill", perPage: "Per side", prev: "Tilbake", next: "Framover", pageOf: "Side {page} av {pages}", first: "Første", last: "Siste" },
  da: { colPhoto: "Foto", colName: "Produkt", colPrice: "Pris", colId: "ID", empty: "Kataloget er tomt.", loading: "Indlæser…", failed: "Det lykkedes ikke. Prøv igen.", count: "{count} produkter", tableTitle: "Katalog", reveal: "Vis produkter", revealHint: "Intet hentes, før du beder om det — siden åbner straks og koster databasen ingenting.", searchPlaceholder: "Søg på navn…", find: "Søg", reset: "Nulstil", perPage: "Per side", prev: "Tilbage", next: "Frem", pageOf: "Side {page} af {pages}", first: "Første", last: "Sidste" },
  fi: { colPhoto: "Kuva", colName: "Tuote", colPrice: "Hinta", colId: "Tunnus", empty: "Luettelo on tyhjä.", loading: "Ladataan…", failed: "Ei onnistunut. Yritä uudelleen.", count: "{count} tuotetta", tableTitle: "Luettelo", reveal: "Näytä tuotteet", revealHint: "Mitään ei haeta ennen kuin pyydät — sivu avautuu heti eikä maksa tietokannalle mitään.", searchPlaceholder: "Etsi nimellä…", find: "Etsi", reset: "Nollaa", perPage: "Sivulla", prev: "Takaisin", next: "Eteenpäin", pageOf: "Sivu {page} / {pages}", first: "Ensimmäinen", last: "Viimeinen" },
  is: { colPhoto: "Mynd", colName: "Vara", colPrice: "Verð", colId: "Auðkenni", empty: "Vörulistinn er tómur.", loading: "Hleð…", failed: "Það tókst ekki. Reyndu aftur.", count: "{count} vörur", tableTitle: "Vörulisti", reveal: "Sýna vörur", revealHint: "Ekkert er sótt fyrr en þú biður um það — síðan opnast strax og kostar gagnagrunninn ekkert.", searchPlaceholder: "Leita eftir heiti…", find: "Leita", reset: "Endurstilla", perPage: "Á síðu", prev: "Til baka", next: "Áfram", pageOf: "Síða {page} af {pages}", first: "Fyrsta", last: "Síðasta" },
  el: { colPhoto: "Φωτογραφία", colName: "Προϊόν", colPrice: "Τιμή", colId: "Αναγνωριστικό", empty: "Ο κατάλογος είναι άδειος.", loading: "Φόρτωση…", failed: "Δεν έγινε. Δοκιμάστε ξανά.", count: "{count} προϊόντα", tableTitle: "Κατάλογος", reveal: "Εμφάνιση προϊόντων", revealHint: "Τίποτα δεν ζητείται μέχρι να το ζητήσετε — η σελίδα ανοίγει αμέσως και δεν κοστίζει τίποτα στη βάση.", searchPlaceholder: "Αναζήτηση με όνομα…", find: "Αναζήτηση", reset: "Επαναφορά", perPage: "Ανά σελίδα", prev: "Πίσω", next: "Μπροστά", pageOf: "Σελίδα {page} από {pages}", first: "Πρώτη", last: "Τελευταία" },
  pl: { colPhoto: "Zdjęcie", colName: "Produkt", colPrice: "Cena", colId: "Identyfikator", empty: "Katalog jest pusty.", loading: "Ładowanie…", failed: "Nie udało się. Spróbuj ponownie.", count: "Produktów: {count}", tableTitle: "Katalog", reveal: "Pokaż produkty", revealHint: "Nic nie jest pobierane, dopóki nie poprosisz — strona otwiera się od razu i nic nie kosztuje bazy.", searchPlaceholder: "Szukaj po nazwie…", find: "Szukaj", reset: "Wyczyść", perPage: "Na stronie", prev: "Wstecz", next: "Dalej", pageOf: "Strona {page} z {pages}", first: "Pierwsza", last: "Ostatnia" },
  cs: { colPhoto: "Foto", colName: "Produkt", colPrice: "Cena", colId: "Identifikátor", empty: "Katalog je prázdný.", loading: "Načítám…", failed: "Nepovedlo se. Zkuste to znovu.", count: "Produktů: {count}", tableTitle: "Katalog", reveal: "Zobrazit produkty", revealHint: "Nic se nenačítá, dokud si neřeknete — stránka se otevře hned a databázi nic nestojí.", searchPlaceholder: "Hledat podle názvu…", find: "Hledat", reset: "Vymazat", perPage: "Na stránku", prev: "Zpět", next: "Dál", pageOf: "Stránka {page} z {pages}", first: "První", last: "Poslední" },
  sk: { colPhoto: "Foto", colName: "Produkt", colPrice: "Cena", colId: "Identifikátor", empty: "Katalóg je prázdny.", loading: "Načítavam…", failed: "Nepodarilo sa. Skúste znova.", count: "Produktov: {count}", tableTitle: "Katalóg", reveal: "Zobraziť produkty", revealHint: "Nič sa nenačítava, kým si nepoviete — stránka sa otvorí hneď a databázu nič nestojí.", searchPlaceholder: "Hľadať podľa názvu…", find: "Hľadať", reset: "Vymazať", perPage: "Na stránku", prev: "Späť", next: "Ďalej", pageOf: "Stránka {page} z {pages}", first: "Prvá", last: "Posledná" },
  hu: { colPhoto: "Fotó", colName: "Termék", colPrice: "Ár", colId: "Azonosító", empty: "A katalógus üres.", loading: "Betöltés…", failed: "Nem sikerült. Próbálja újra.", count: "{count} termék", tableTitle: "Katalógus", reveal: "Termékek megjelenítése", revealHint: "Semmi sem töltődik be, amíg nem kéri — az oldal azonnal megnyílik, és semmibe sem kerül az adatbázisnak.", searchPlaceholder: "Keresés név szerint…", find: "Keresés", reset: "Alaphelyzet", perPage: "Oldalanként", prev: "Vissza", next: "Előre", pageOf: "{page}. oldal / {pages}", first: "Első", last: "Utolsó" },
  ro: { colPhoto: "Foto", colName: "Produs", colPrice: "Preț", colId: "Identificator", empty: "Catalogul este gol.", loading: "Se încarcă…", failed: "Nu a mers. Încercați din nou.", count: "{count} produse", tableTitle: "Catalog", reveal: "Arată produsele", revealHint: "Nimic nu se cere până nu cereți dumneavoastră — pagina se deschide imediat și nu costă nimic baza de date.", searchPlaceholder: "Căutare după nume…", find: "Caută", reset: "Resetează", perPage: "Pe pagină", prev: "Înapoi", next: "Înainte", pageOf: "Pagina {page} din {pages}", first: "Prima", last: "Ultima" },
  hr: { colPhoto: "Fotografija", colName: "Proizvod", colPrice: "Cijena", colId: "Identifikator", empty: "Katalog je prazan.", loading: "Učitavanje…", failed: "Nije uspjelo. Pokušajte ponovno.", count: "Proizvoda: {count}", tableTitle: "Katalog", reveal: "Prikaži proizvode", revealHint: "Ništa se ne dohvaća dok ne zatražite — stranica se otvara odmah i bazu ne stoji ništa.", searchPlaceholder: "Traži po nazivu…", find: "Traži", reset: "Poništi", perPage: "Po stranici", prev: "Natrag", next: "Naprijed", pageOf: "Stranica {page} od {pages}", first: "Prva", last: "Zadnja" },
  sl: { colPhoto: "Fotografija", colName: "Izdelek", colPrice: "Cena", colId: "Identifikator", empty: "Katalog je prazen.", loading: "Nalaganje…", failed: "Ni uspelo. Poskusite znova.", count: "Izdelkov: {count}", tableTitle: "Katalog", reveal: "Pokaži izdelke", revealHint: "Nič se ne zahteva, dokler ne zahtevate vi — stran se odpre takoj in bazo ne stane nič.", searchPlaceholder: "Iskanje po imenu…", find: "Išči", reset: "Ponastavi", perPage: "Na stran", prev: "Nazaj", next: "Naprej", pageOf: "Stran {page} od {pages}", first: "Prva", last: "Zadnja" },
  et: { colPhoto: "Foto", colName: "Toode", colPrice: "Hind", colId: "Tunnus", empty: "Kataloog on tühi.", loading: "Laadin…", failed: "Ei õnnestunud. Proovige uuesti.", count: "{count} toodet", tableTitle: "Kataloog", reveal: "Näita tooteid", revealHint: "Midagi ei päritа enne, kui te seda palute — leht avaneb kohe ega maksa andmebaasile midagi.", searchPlaceholder: "Otsi nime järgi…", find: "Otsi", reset: "Lähtesta", perPage: "Lehel", prev: "Tagasi", next: "Edasi", pageOf: "Lehekülg {page} / {pages}", first: "Esimene", last: "Viimane" },
  lv: { colPhoto: "Foto", colName: "Prece", colPrice: "Cena", colId: "Identifikators", empty: "Katalogs ir tukšs.", loading: "Ielādē…", failed: "Neizdevās. Mēģiniet vēlreiz.", count: "Preču: {count}", tableTitle: "Katalogs", reveal: "Rādīt preces", revealHint: "Nekas netiek pieprasīts, kamēr jūs to nelūdzat — lapa atveras uzreiz un datubāzei neko nemaksā.", searchPlaceholder: "Meklēt pēc nosaukuma…", find: "Meklēt", reset: "Atiestatīt", perPage: "Lapā", prev: "Atpakaļ", next: "Uz priekšu", pageOf: "{page}. lappuse no {pages}", first: "Pirmā", last: "Pēdējā" },
  lt: { colPhoto: "Nuotrauka", colName: "Prekė", colPrice: "Kaina", colId: "Identifikatorius", empty: "Katalogas tuščias.", loading: "Įkeliama…", failed: "Nepavyko. Bandykite dar kartą.", count: "Prekių: {count}", tableTitle: "Katalogas", reveal: "Rodyti prekes", revealHint: "Niekas neužklausiama, kol nepaprašote — puslapis atsidaro iškart ir duomenų bazei nieko nekainuoja.", searchPlaceholder: "Ieškoti pagal pavadinimą…", find: "Ieškoti", reset: "Atstatyti", perPage: "Puslapyje", prev: "Atgal", next: "Pirmyn", pageOf: "{page} puslapis iš {pages}", first: "Pirmas", last: "Paskutinis" },
  mt: { colPhoto: "Ritratt", colName: "Prodott", colPrice: "Prezz", colId: "Identifikatur", empty: "Il-katalgu huwa vojt.", loading: "Qed jitgħabba…", failed: "Ma rnexxiex. Erġa’ pprova.", count: "{count} prodotti", tableTitle: "Katalgu", reveal: "Uri l-prodotti", revealHint: "Xejn ma jintalab qabel ma titlob int — il-paġna tinfetaħ mill-ewwel u ma tiswa xejn lid-database.", searchPlaceholder: "Fittex bl-isem…", find: "Fittex", reset: "Irrisettja", perPage: "F’kull paġna", prev: "Lura", next: "Il-quddiem", pageOf: "Paġna {page} minn {pages}", first: "L-ewwel", last: "L-aħħar" },
  ca: { colPhoto: "Foto", colName: "Producte", colPrice: "Preu", colId: "Identificador", empty: "El catàleg és buit.", loading: "Carregant…", failed: "No ha anat bé. Torneu-ho a provar.", count: "{count} productes", tableTitle: "Catàleg", reveal: "Mostra els productes", revealHint: "No es demana res fins que ho demaneu: la pàgina s’obre a l’instant i no costa res a la base de dades.", searchPlaceholder: "Cerca pel nom…", find: "Cerca", reset: "Reinicia", perPage: "Per pàgina", prev: "Enrere", next: "Endavant", pageOf: "Pàgina {page} de {pages}", first: "Primera", last: "Última" },
  gl: { colPhoto: "Foto", colName: "Produto", colPrice: "Prezo", colId: "Identificador", empty: "O catálogo está baleiro.", loading: "Cargando…", failed: "Non foi posible. Ténteo de novo.", count: "{count} produtos", tableTitle: "Catálogo", reveal: "Amosar produtos", revealHint: "Non se pide nada ata que o solicite: a páxina ábrese ao instante e non custa nada á base de datos.", searchPlaceholder: "Buscar polo nome…", find: "Buscar", reset: "Restablecer", perPage: "Por páxina", prev: "Atrás", next: "Adiante", pageOf: "Páxina {page} de {pages}", first: "Primeira", last: "Última" },
  cy: { colPhoto: "Llun", colName: "Cynnyrch", colPrice: "Pris", colId: "Dynodydd", empty: "Mae’r catalog yn wag.", loading: "Yn llwytho…", failed: "Methodd. Rhowch gynnig arall arni.", count: "{count} cynnyrch", tableTitle: "Catalog", reveal: "Dangos cynnyrch", revealHint: "Ni ofynnir am ddim byd nes i chi ofyn — mae’r dudalen yn agor ar unwaith ac nid yw’n costio dim i’r gronfa ddata.", searchPlaceholder: "Chwilio yn ôl enw…", find: "Chwilio", reset: "Ailosod", perPage: "Fesul tudalen", prev: "Yn ôl", next: "Ymlaen", pageOf: "Tudalen {page} o {pages}", first: "Cyntaf", last: "Olaf" },
  ga: { colPhoto: "Grianghraf", colName: "Táirge", colPrice: "Praghas", colId: "Aitheantóir", empty: "Tá an chatalóg folamh.", loading: "Á lódáil…", failed: "Níor éirigh leis. Bain triail eile as.", count: "{count} táirge", tableTitle: "Catalóg", reveal: "Taispeáin táirgí", revealHint: "Ní iarrtar aon rud go dtí go n-iarrann tú é — osclaíonn an leathanach láithreach agus ní chosnaíonn sé aon rud ar an mbunachar.", searchPlaceholder: "Cuardaigh de réir ainm…", find: "Cuardaigh", reset: "Athshocraigh", perPage: "In aghaidh an leathanaigh", prev: "Ar ais", next: "Ar aghaidh", pageOf: "Leathanach {page} as {pages}", first: "An chéad cheann", last: "An ceann deireanach" },
  eu: { colPhoto: "Argazkia", colName: "Produktua", colPrice: "Prezioa", colId: "Identifikatzailea", empty: "Katalogoa hutsik dago.", loading: "Kargatzen…", failed: "Ez du funtzionatu. Saiatu berriro.", count: "{count} produktu", tableTitle: "Katalogoa", reveal: "Erakutsi produktuak", revealHint: "Ez da ezer eskatzen zuk eskatu arte: orria berehala irekitzen da eta ez dio ezer kostatzen datu-baseari.", searchPlaceholder: "Bilatu izenaren arabera…", find: "Bilatu", reset: "Berrezarri", perPage: "Orriko", prev: "Atzera", next: "Aurrera", pageOf: "{page}. orria {pages}-tik", first: "Lehena", last: "Azkena" },
  ru: { colPhoto: "Фото", colName: "Товар", colPrice: "Цена", colId: "Идентификатор", empty: "Каталог пуст.", loading: "Загружаю…", failed: "Не получилось. Повторите.", count: "Товаров: {count}", tableTitle: "Каталог", reveal: "Показать товары", revealHint: "Пока не попросите, ничего не запрашивается — страница открывается мгновенно и не стоит базе ничего.", searchPlaceholder: "Поиск по названию…", find: "Найти", reset: "Сбросить", perPage: "На странице", prev: "Назад", next: "Вперёд", pageOf: "Страница {page} из {pages}", first: "Первая", last: "Последняя" },
  uk: { colPhoto: "Фото", colName: "Товар", colPrice: "Ціна", colId: "Ідентифікатор", empty: "Каталог порожній.", loading: "Завантажую…", failed: "Не вийшло. Повторіть.", count: "Товарів: {count}", tableTitle: "Каталог", reveal: "Показати товари", revealHint: "Поки не попросите, нічого не запитується — сторінка відкривається миттєво й нічого не коштує базі.", searchPlaceholder: "Пошук за назвою…", find: "Знайти", reset: "Скинути", perPage: "На сторінці", prev: "Назад", next: "Уперед", pageOf: "Сторінка {page} з {pages}", first: "Перша", last: "Остання" },
  be: { colPhoto: "Фота", colName: "Тавар", colPrice: "Цана", colId: "Ідэнтыфікатар", empty: "Каталог пусты.", loading: "Загружаю…", failed: "Не атрымалася. Паўтарыце.", count: "Тавараў: {count}", tableTitle: "Каталог", reveal: "Паказаць тавары", revealHint: "Пакуль не папросіце, нічога не запытваецца — старонка адкрываецца імгненна і нічога не каштуе базе.", searchPlaceholder: "Пошук па назве…", find: "Знайсці", reset: "Скінуць", perPage: "На старонцы", prev: "Назад", next: "Наперад", pageOf: "Старонка {page} з {pages}", first: "Першая", last: "Апошняя" },
  bg: { colPhoto: "Снимка", colName: "Продукт", colPrice: "Цена", colId: "Идентификатор", empty: "Каталогът е празен.", loading: "Зареждам…", failed: "Не се получи. Опитайте отново.", count: "Продукти: {count}", tableTitle: "Каталог", reveal: "Покажи продуктите", revealHint: "Нищо не се заявява, докато не поискате — страницата се отваря веднага и не струва нищо на базата.", searchPlaceholder: "Търсене по име…", find: "Търси", reset: "Изчисти", perPage: "На страница", prev: "Назад", next: "Напред", pageOf: "Страница {page} от {pages}", first: "Първа", last: "Последна" },
  sr: { colPhoto: "Фотографија", colName: "Производ", colPrice: "Цена", colId: "Идентификатор", empty: "Каталог је празан.", loading: "Учитавам…", failed: "Није успело. Покушајте поново.", count: "Производа: {count}", tableTitle: "Каталог", reveal: "Прикажи производе", revealHint: "Ништа се не тражи док ви не затражите — страница се отвара одмах и бази не кошта ништа.", searchPlaceholder: "Претрага по називу…", find: "Тражи", reset: "Поништи", perPage: "По страници", prev: "Назад", next: "Напред", pageOf: "Страница {page} од {pages}", first: "Прва", last: "Последња" },
  bs: { colPhoto: "Fotografija", colName: "Proizvod", colPrice: "Cijena", colId: "Identifikator", empty: "Katalog je prazan.", loading: "Učitavam…", failed: "Nije uspjelo. Pokušajte ponovo.", count: "Proizvoda: {count}", tableTitle: "Katalog", reveal: "Prikaži proizvode", revealHint: "Ništa se ne traži dok vi ne zatražite — stranica se otvara odmah i bazu ne košta ništa.", searchPlaceholder: "Pretraga po nazivu…", find: "Traži", reset: "Poništi", perPage: "Po stranici", prev: "Nazad", next: "Naprijed", pageOf: "Stranica {page} od {pages}", first: "Prva", last: "Zadnja" },
  mk: { colPhoto: "Фотографија", colName: "Производ", colPrice: "Цена", colId: "Идентификатор", empty: "Каталогот е празен.", loading: "Вчитувам…", failed: "Не успеа. Обидете се повторно.", count: "Производи: {count}", tableTitle: "Каталог", reveal: "Прикажи производи", revealHint: "Ништо не се бара додека вие не побарате — страницата се отвора веднаш и не чини ништо на базата.", searchPlaceholder: "Барај по име…", find: "Барај", reset: "Ресетирај", perPage: "По страница", prev: "Назад", next: "Напред", pageOf: "Страница {page} од {pages}", first: "Прва", last: "Последна" },
  sq: { colPhoto: "Foto", colName: "Produkt", colPrice: "Çmim", colId: "Identifikues", empty: "Katalogu është bosh.", loading: "Po ngarkoj…", failed: "Nuk u arrit. Provoni sërish.", count: "{count} produkte", tableTitle: "Katalog", reveal: "Shfaq produktet", revealHint: "Asgjë nuk kërkohet derisa ta kërkoni ju — faqja hapet menjëherë dhe nuk i kushton asgjë bazës.", searchPlaceholder: "Kërko sipas emrit…", find: "Kërko", reset: "Rivendos", perPage: "Për faqe", prev: "Prapa", next: "Përpara", pageOf: "Faqja {page} nga {pages}", first: "E para", last: "E fundit" },
  kk: { colPhoto: "Сурет", colName: "Тауар", colPrice: "Бағасы", colId: "Идентификатор", empty: "Каталог бос.", loading: "Жүктеп жатырмын…", failed: "Болмады. Қайталаңыз.", count: "Тауарлар: {count}", tableTitle: "Каталог", reveal: "Тауарларды көрсету", revealHint: "Сұрамағаныңызша ештеңе сұралмайды — бет бірден ашылады және дерекқорға ештеңе тұрмайды.", searchPlaceholder: "Атауы бойынша іздеу…", find: "Табу", reset: "Тазалау", perPage: "Бетте", prev: "Артқа", next: "Алға", pageOf: "{pages} беттің {page}-беті", first: "Бірінші", last: "Соңғы" },
  uz: { colPhoto: "Surat", colName: "Mahsulot", colPrice: "Narxi", colId: "Identifikator", empty: "Katalog bo‘sh.", loading: "Yuklanmoqda…", failed: "Bo‘lmadi. Qayta urinib ko‘ring.", count: "Mahsulotlar: {count}", tableTitle: "Katalog", reveal: "Mahsulotlarni ko‘rsatish", revealHint: "Siz so‘ramaguningizcha hech narsa so‘ralmaydi — sahifa darhol ochiladi va ma’lumotlar bazasiga hech narsa turmaydi.", searchPlaceholder: "Nomi bo‘yicha qidirish…", find: "Topish", reset: "Tozalash", perPage: "Sahifada", prev: "Orqaga", next: "Oldinga", pageOf: "{pages} sahifadan {page}-si", first: "Birinchi", last: "Oxirgi" },
  ky: { colPhoto: "Сүрөт", colName: "Товар", colPrice: "Баасы", colId: "Идентификатор", empty: "Каталог бош.", loading: "Жүктөлүүдө…", failed: "Болбоду. Кайталаңыз.", count: "Товарлар: {count}", tableTitle: "Каталог", reveal: "Товарларды көрсөтүү", revealHint: "Сурамайынча эч нерсе суралбайт — барак заматта ачылат жана базага эч нерсе турбайт.", searchPlaceholder: "Аты боюнча издөө…", find: "Табуу", reset: "Тазалоо", perPage: "Бетте", prev: "Артка", next: "Алдыга", pageOf: "{pages} беттин {page}-бети", first: "Биринчи", last: "Акыркы" },
  tg: { colPhoto: "Акс", colName: "Мол", colPrice: "Нарх", colId: "Идентификатор", empty: "Феҳрист холӣ аст.", loading: "Бор мекунам…", failed: "Нашуд. Такрор кунед.", count: "Молҳо: {count}", tableTitle: "Феҳрист", reveal: "Молҳоро нишон додан", revealHint: "То нахоҳед, чизе дархост намешавад — саҳифа фавран кушода мешавад ва ба пойгоҳ чизе намеарзад.", searchPlaceholder: "Ҷустуҷӯ аз рӯи ном…", find: "Ёфтан", reset: "Тоза кардан", perPage: "Дар саҳифа", prev: "Бозгашт", next: "Пеш", pageOf: "Саҳифаи {page} аз {pages}", first: "Аввалин", last: "Охирин" },
  tk: { colPhoto: "Surat", colName: "Haryt", colPrice: "Bahasy", colId: "Kesgitleýji", empty: "Katalog boş.", loading: "Ýüklenýär…", failed: "Bolmady. Gaýtadan synanyşyň.", count: "Harytlar: {count}", tableTitle: "Katalog", reveal: "Harytlary görkez", revealHint: "Siz soramasaňyz hiç zat soralmaýar — sahypa şobada açylýar we maglumat binýadyna hiç zat durmaýar.", searchPlaceholder: "Ady boýunça gözle…", find: "Tap", reset: "Arassala", perPage: "Sahypada", prev: "Yza", next: "Öňe", pageOf: "{pages} sahypadan {page}-si", first: "Birinji", last: "Soňky" },
  az: { colPhoto: "Şəkil", colName: "Məhsul", colPrice: "Qiymət", colId: "İdentifikator", empty: "Kataloq boşdur.", loading: "Yüklənir…", failed: "Alınmadı. Yenidən cəhd edin.", count: "Məhsullar: {count}", tableTitle: "Kataloq", reveal: "Məhsulları göstər", revealHint: "Siz istəməyincə heç nə sorğulanmır — səhifə dərhal açılır və bazaya heç nə baş vermir.", searchPlaceholder: "Ada görə axtar…", find: "Tap", reset: "Sıfırla", perPage: "Səhifədə", prev: "Geri", next: "İrəli", pageOf: "{pages} səhifədən {page}-si", first: "Birinci", last: "Sonuncu" },
  hy: { colPhoto: "Լուսանկար", colName: "Ապրանք", colPrice: "Գին", colId: "Նույնացուցիչ", empty: "Ցանկը դատարկ է։", loading: "Բեռնվում է…", failed: "Չստացվեց։ Կրկնեք։", count: "Ապրանքներ՝ {count}", tableTitle: "Ցանկ", reveal: "Ցույց տալ ապրանքները", revealHint: "Մինչև չխնդրեք, ոչինչ չի հարցվում — էջը բացվում է ակնթարթորեն և բազային ոչինչ չարժե։", searchPlaceholder: "Որոնում ըստ անվան…", find: "Գտնել", reset: "Զրոյացնել", perPage: "Էջում", prev: "Հետ", next: "Առաջ", pageOf: "Էջ {page} {pages}-ից", first: "Առաջին", last: "Վերջին" },
  ka: { colPhoto: "ფოტო", colName: "პროდუქტი", colPrice: "ფასი", colId: "იდენტიფიკატორი", empty: "კატალოგი ცარიელია.", loading: "იტვირთება…", failed: "ვერ მოხერხდა. სცადეთ ხელახლა.", count: "პროდუქტები: {count}", tableTitle: "კატალოგი", reveal: "პროდუქტების ჩვენება", revealHint: "სანამ არ მოითხოვთ, არაფერი იკითხება — გვერდი მყისვე იხსნება და ბაზას არაფერი უჯდება.", searchPlaceholder: "ძებნა სახელით…", find: "პოვნა", reset: "გასუფთავება", perPage: "გვერდზე", prev: "უკან", next: "წინ", pageOf: "გვერდი {page} / {pages}", first: "პირველი", last: "ბოლო" },
  mn: { colPhoto: "Зураг", colName: "Бараа", colPrice: "Үнэ", colId: "Танигч", empty: "Каталог хоосон байна.", loading: "Ачаалж байна…", failed: "Болсонгүй. Дахин оролдоно уу.", count: "Бараа: {count}", tableTitle: "Каталог", reveal: "Бараа харуулах", revealHint: "Та хүсэх хүртэл юу ч татахгүй — хуудас тэр даруй нээгдэж, өгөгдлийн санд юу ч зарцуулахгүй.", searchPlaceholder: "Нэрээр хайх…", find: "Олох", reset: "Цэвэрлэх", perPage: "Хуудсанд", prev: "Буцах", next: "Урагш", pageOf: "{pages}-с {page}-р хуудас", first: "Эхний", last: "Сүүлийн" },
  ar: { colPhoto: "صورة", colName: "المنتج", colPrice: "السعر", colId: "المعرّف", empty: "الكتالوج فارغ.", loading: "جارٍ التحميل…", failed: "لم ينجح. حاول مرة أخرى.", count: "المنتجات: {count}", tableTitle: "الكتالوج", reveal: "إظهار المنتجات", revealHint: "لا يُطلب شيء حتى تطلب أنت — تفتح الصفحة فورًا ولا تكلّف قاعدة البيانات شيئًا.", searchPlaceholder: "بحث بالاسم…", find: "بحث", reset: "إعادة تعيين", perPage: "في الصفحة", prev: "رجوع", next: "تقدّم", pageOf: "صفحة {page} من {pages}", first: "الأولى", last: "الأخيرة" },
  tr: { colPhoto: "Fotoğraf", colName: "Ürün", colPrice: "Fiyat", colId: "Kimlik", empty: "Katalog boş.", loading: "Yükleniyor…", failed: "Olmadı. Tekrar deneyin.", count: "{count} ürün", tableTitle: "Katalog", reveal: "Ürünleri göster", revealHint: "Siz istemeden hiçbir şey sorgulanmaz — sayfa anında açılır ve veritabanına hiçbir şeye mal olmaz.", searchPlaceholder: "Ada göre ara…", find: "Bul", reset: "Sıfırla", perPage: "Sayfa başına", prev: "Geri", next: "İleri", pageOf: "Sayfa {page} / {pages}", first: "İlk", last: "Son" },
  he: { colPhoto: "תמונה", colName: "מוצר", colPrice: "מחיר", colId: "מזהה", empty: "הקטלוג ריק.", loading: "טוען…", failed: "לא הצליח. נסו שוב.", count: "{count} מוצרים", tableTitle: "קטלוג", reveal: "הצג מוצרים", revealHint: "דבר אינו נטען עד שתבקשו — הדף נפתח מיד ואינו עולה למסד הנתונים דבר.", searchPlaceholder: "חיפוש לפי שם…", find: "חפש", reset: "איפוס", perPage: "בעמוד", prev: "אחורה", next: "קדימה", pageOf: "עמוד {page} מתוך {pages}", first: "ראשון", last: "אחרון" },
  fa: { colPhoto: "عکس", colName: "محصول", colPrice: "قیمت", colId: "شناسه", empty: "فهرست خالی است.", loading: "در حال بارگذاری…", failed: "نشد. دوباره تلاش کنید.", count: "محصولات: {count}", tableTitle: "فهرست", reveal: "نمایش محصولات", revealHint: "تا وقتی نخواهید چیزی درخواست نمی‌شود — صفحه فوراً باز می‌شود و برای پایگاه داده هزینه‌ای ندارد.", searchPlaceholder: "جستجو بر اساس نام…", find: "یافتن", reset: "بازنشانی", perPage: "در هر صفحه", prev: "بازگشت", next: "جلو", pageOf: "صفحه {page} از {pages}", first: "نخست", last: "آخر" },
  ku: { colPhoto: "Wêne", colName: "Berhem", colPrice: "Biha", colId: "Nasname", empty: "Katalog vala ye.", loading: "Tê barkirin…", failed: "Nebû. Dîsa biceribîne.", count: "{count} berhem", tableTitle: "Katalog", reveal: "Berheman nîşan bide", revealHint: "Heta tu nexwazî tiştek nayê xwestin — rûpel yekser vedibe û ji danegehê tiştekî nabe.", searchPlaceholder: "Li gorî navî bigere…", find: "Bibîne", reset: "Ji nû ve", perPage: "Di rûpelê de", prev: "Paş", next: "Pêş", pageOf: "Rûpel {page} ji {pages}", first: "Yekem", last: "Dawî" },
  af: { colPhoto: "Foto", colName: "Produk", colPrice: "Prys", colId: "Identifiseerder", empty: "Die katalogus is leeg.", loading: "Laai…", failed: "Dit het nie gewerk nie. Probeer weer.", count: "{count} produkte", tableTitle: "Katalogus", reveal: "Wys produkte", revealHint: "Niks word gevra voordat jy vra nie — die bladsy open dadelik en kos die databasis niks.", searchPlaceholder: "Soek op naam…", find: "Soek", reset: "Herstel", perPage: "Per bladsy", prev: "Terug", next: "Vorentoe", pageOf: "Bladsy {page} van {pages}", first: "Eerste", last: "Laaste" },
  sw: { colPhoto: "Picha", colName: "Bidhaa", colPrice: "Bei", colId: "Kitambulisho", empty: "Katalogi ni tupu.", loading: "Inapakia…", failed: "Haikufanikiwa. Jaribu tena.", count: "Bidhaa: {count}", tableTitle: "Katalogi", reveal: "Onyesha bidhaa", revealHint: "Hakuna kinachoombwa hadi uombe — ukurasa hufunguka mara moja na haugharimu hifadhidata chochote.", searchPlaceholder: "Tafuta kwa jina…", find: "Tafuta", reset: "Weka upya", perPage: "Kwa ukurasa", prev: "Nyuma", next: "Mbele", pageOf: "Ukurasa {page} kati ya {pages}", first: "Wa kwanza", last: "Wa mwisho" },
  ha: { colPhoto: "Hoto", colName: "Kaya", colPrice: "Farashi", colId: "Mai ganewa", empty: "Katalog babu komai.", loading: "Ana lodi…", failed: "Bai yi ba. Sake gwadawa.", count: "Kaya: {count}", tableTitle: "Katalog", reveal: "Nuna kaya", revealHint: "Ba a nema komai sai ka nema — shafin yana buɗewa nan take kuma bai ci wa bayanai komai ba.", searchPlaceholder: "Nemo da suna…", find: "Nemo", reset: "Sake saitawa", perPage: "A kowane shafi", prev: "Baya", next: "Gaba", pageOf: "Shafi {page} na {pages}", first: "Na farko", last: "Na ƙarshe" },
  yo: { colPhoto: "Fọ́tò", colName: "Ọjà", colPrice: "Iye", colId: "Ìdámọ̀", empty: "Àkójọ ṣofo.", loading: "Ń ṣíṣẹ́…", failed: "Kò ṣiṣẹ́. Tún gbìyànjú.", count: "Ọjà: {count}", tableTitle: "Àkójọ", reveal: "Fi ọjà hàn", revealHint: "Kò sí ohun tí a béèrè títí ìwọ yóò fi béèrè — ojú-ìwé ṣí lẹ́sẹ̀kẹsẹ̀, kò sì ná ibùdó ìwífún ohunkóhun.", searchPlaceholder: "Wá pẹ̀lú orúkọ…", find: "Wá", reset: "Tún bẹ̀rẹ̀", perPage: "Ní ojú-ìwé", prev: "Padà", next: "Síwájú", pageOf: "Ojú-ìwé {page} nínú {pages}", first: "Àkọ́kọ́", last: "Ìkẹyìn" },
  ig: { colPhoto: "Foto", colName: "Ngwaahịa", colPrice: "Ọnụahịa", colId: "Njirimara", empty: "Katalọgụ tọgbọrọ chakoo.", loading: "Na-ebu…", failed: "Ọ gaghị. Nwaa ọzọ.", count: "Ngwaahịa: {count}", tableTitle: "Katalọgụ", reveal: "Gosi ngwaahịa", revealHint: "Ọ dịghị ihe a na-arịọ tutu ị rịọ — ibe na-emeghe ozugbo, ọ naghịkwa efu nchekwa data ihe ọ bụla.", searchPlaceholder: "Chọọ site n’aha…", find: "Chọta", reset: "Tọghata", perPage: "N’ibe", prev: "Azụ", next: "N’ihu", pageOf: "Ibe {page} nke {pages}", first: "Nke mbụ", last: "Nke ikpeazụ" },
  am: { colPhoto: "ፎቶ", colName: "ምርት", colPrice: "ዋጋ", colId: "መለያ", empty: "ዝርዝሩ ባዶ ነው።", loading: "በመጫን ላይ…", failed: "አልተሳካም። እንደገና ይሞክሩ።", count: "ምርቶች፦ {count}", tableTitle: "ዝርዝር", reveal: "ምርቶችን አሳይ", revealHint: "እስክትጠይቁ ድረስ ምንም አይጠየቅም — ገጹ ወዲያውኑ ይከፈታል፣ ለመረጃ ቋቱም ምንም አያስወጣም።", searchPlaceholder: "በስም ፈልግ…", find: "ፈልግ", reset: "አጽዳ", perPage: "በገጽ", prev: "ወደኋላ", next: "ወደፊት", pageOf: "ገጽ {page} ከ{pages}", first: "የመጀመሪያ", last: "የመጨረሻ" },
  zu: { colPhoto: "Isithombe", colName: "Umkhiqizo", colPrice: "Intengo", colId: "Isikhombi", empty: "Uhlu alunalutho.", loading: "Iyalayisha…", failed: "Akuphumelelanga. Zama futhi.", count: "Imikhiqizo: {count}", tableTitle: "Uhlu", reveal: "Bonisa imikhiqizo", revealHint: "Akukho okuceliwe uze ucele — ikhasi livuleka masinyane futhi alibizi lutho kusizindalwazi.", searchPlaceholder: "Sesha ngegama…", find: "Thola", reset: "Setha kabusha", perPage: "Ekhasini", prev: "Emuva", next: "Phambili", pageOf: "Ikhasi {page} kwangu-{pages}", first: "Elokuqala", last: "Elokugcina" },
  xh: { colPhoto: "Ifoto", colName: "Imveliso", colPrice: "Ixabiso", colId: "Isalathisi", empty: "Uluhlu luze.", loading: "Iyalayisha…", failed: "Ayiphumelelanga. Zama kwakhona.", count: "Iimveliso: {count}", tableTitle: "Uluhlu", reveal: "Bonisa iimveliso", revealHint: "Akukho nto iceliweyo ude ucele — iphepha livuleka ngoko nangoko yaye alibizi nto kwisiseko sedatha.", searchPlaceholder: "Khangela ngegama…", find: "Fumana", reset: "Misela kwakhona", perPage: "Ephepheni", prev: "Umva", next: "Phambili", pageOf: "Iphepha {page} kwangama-{pages}", first: "Elokuqala", last: "Elokugqibela" },
  rw: { colPhoto: "Ifoto", colName: "Igicuruzwa", colPrice: "Igiciro", colId: "Ikiranga", empty: "Urutonde ni ubusa.", loading: "Biratangira…", failed: "Ntibyakunze. Ongera ugerageze.", count: "Ibicuruzwa: {count}", tableTitle: "Urutonde", reveal: "Erekana ibicuruzwa", revealHint: "Nta kintu gisabwa mbere y’uko ubisaba — urupapuro rufungura ako kanya kandi ntacyo rutwara ububiko.", searchPlaceholder: "Shakisha ukoresheje izina…", find: "Shaka", reset: "Subiramo", perPage: "Ku rupapuro", prev: "Inyuma", next: "Imbere", pageOf: "Urupapuro {page} kuri {pages}", first: "Urwa mbere", last: "Urwa nyuma" },
  so: { colPhoto: "Sawir", colName: "Alaab", colPrice: "Qiimo", colId: "Aqoonsi", empty: "Liiska waa madhan yahay.", loading: "Waa la soo dejinayaa…", failed: "Ma shaqeynin. Isku day mar kale.", count: "Alaabta: {count}", tableTitle: "Liis", reveal: "Muuji alaabta", revealHint: "Waxba lama codsado ilaa aad codsato — boggu wuxuu furmaa isla markiiba, kaydkana waxba kama qaadanayo.", searchPlaceholder: "Ku raadi magaca…", find: "Raadi", reset: "Dib u deji", perPage: "Bogga", prev: "Dib", next: "Hore", pageOf: "Bogga {page} ee {pages}", first: "Kii ugu horreeyay", last: "Kii ugu dambeeyay" },
  zh: { colPhoto: "图片", colName: "商品", colPrice: "价格", colId: "标识", empty: "目录为空。", loading: "加载中…", failed: "没有成功，请重试。", count: "商品 {count} 件", tableTitle: "目录", reveal: "显示商品", revealHint: "在你开口之前什么都不请求——页面立即打开，对数据库毫无消耗。", searchPlaceholder: "按名称搜索…", find: "查找", reset: "重置", perPage: "每页", prev: "上一页", next: "下一页", pageOf: "第 {page} 页，共 {pages} 页", first: "首页", last: "末页" },
  ja: { colPhoto: "写真", colName: "商品", colPrice: "価格", colId: "ID", empty: "カタログは空です。", loading: "読み込み中…", failed: "うまくいきませんでした。もう一度お試しください。", count: "商品 {count} 件", tableTitle: "カタログ", reveal: "商品を表示", revealHint: "求められるまで何も取得しません — ページはすぐ開き、データベースに負荷をかけません。", searchPlaceholder: "名前で検索…", find: "検索", reset: "リセット", perPage: "1ページあたり", prev: "戻る", next: "進む", pageOf: "{pages} ページ中 {page} ページ", first: "最初", last: "最後" },
  ko: { colPhoto: "사진", colName: "상품", colPrice: "가격", colId: "식별자", empty: "카탈로그가 비어 있습니다.", loading: "불러오는 중…", failed: "실패했습니다. 다시 시도하세요.", count: "상품 {count}개", tableTitle: "카탈로그", reveal: "상품 보기", revealHint: "요청하기 전에는 아무것도 조회하지 않습니다 — 페이지는 즉시 열리고 데이터베이스에 부담을 주지 않습니다.", searchPlaceholder: "이름으로 검색…", find: "찾기", reset: "초기화", perPage: "페이지당", prev: "이전", next: "다음", pageOf: "{pages}쪽 중 {page}쪽", first: "처음", last: "마지막" },
  hi: { colPhoto: "फ़ोटो", colName: "उत्पाद", colPrice: "मूल्य", colId: "पहचानकर्ता", empty: "सूची खाली है।", loading: "लोड हो रहा है…", failed: "नहीं हो सका। फिर से प्रयास करें।", count: "उत्पाद: {count}", tableTitle: "सूची", reveal: "उत्पाद दिखाएँ", revealHint: "जब तक आप न कहें, कुछ नहीं माँगा जाता — पृष्ठ तुरंत खुलता है और डेटाबेस पर कोई भार नहीं डालता।", searchPlaceholder: "नाम से खोजें…", find: "खोजें", reset: "रीसेट", perPage: "प्रति पृष्ठ", prev: "पीछे", next: "आगे", pageOf: "पृष्ठ {page} / {pages}", first: "पहला", last: "अंतिम" },
  ur: { colPhoto: "تصویر", colName: "مصنوعات", colPrice: "قیمت", colId: "شناخت", empty: "فہرست خالی ہے۔", loading: "لوڈ ہو رہا ہے…", failed: "نہیں ہو سکا۔ دوبارہ کوشش کریں۔", count: "مصنوعات: {count}", tableTitle: "فہرست", reveal: "مصنوعات دکھائیں", revealHint: "جب تک آپ نہ کہیں کچھ طلب نہیں کیا جاتا — صفحہ فوراً کھلتا ہے اور ڈیٹابیس پر کوئی بوجھ نہیں ڈالتا۔", searchPlaceholder: "نام سے تلاش کریں…", find: "تلاش", reset: "دوبارہ ترتیب", perPage: "فی صفحہ", prev: "پیچھے", next: "آگے", pageOf: "صفحہ {page} از {pages}", first: "پہلا", last: "آخری" },
  bn: { colPhoto: "ছবি", colName: "পণ্য", colPrice: "দাম", colId: "শনাক্তকারী", empty: "তালিকা খালি।", loading: "লোড হচ্ছে…", failed: "হলো না। আবার চেষ্টা করুন।", count: "পণ্য: {count}", tableTitle: "তালিকা", reveal: "পণ্য দেখান", revealHint: "আপনি না চাইলে কিছুই চাওয়া হয় না — পাতা সঙ্গে সঙ্গে খোলে এবং ডেটাবেসের কোনো খরচ নেই।", searchPlaceholder: "নাম দিয়ে খুঁজুন…", find: "খুঁজুন", reset: "রিসেট", perPage: "প্রতি পাতায়", prev: "পেছনে", next: "সামনে", pageOf: "পাতা {page} / {pages}", first: "প্রথম", last: "শেষ" },
  te: { colPhoto: "ఫోటో", colName: "ఉత్పత్తి", colPrice: "ధర", colId: "గుర్తింపు", empty: "జాబితా ఖాళీగా ఉంది.", loading: "లోడ్ అవుతోంది…", failed: "కాలేదు. మళ్లీ ప్రయత్నించండి.", count: "ఉత్పత్తులు: {count}", tableTitle: "జాబితా", reveal: "ఉత్పత్తులను చూపు", revealHint: "మీరు అడిగే వరకు ఏదీ అడగబడదు — పేజీ వెంటనే తెరుచుకుంటుంది, డేటాబేస్‌కు ఖర్చు ఉండదు.", searchPlaceholder: "పేరుతో వెతకండి…", find: "వెతుకు", reset: "రీసెట్", perPage: "ప్రతి పేజీకి", prev: "వెనక్కి", next: "ముందుకు", pageOf: "{pages}లో {page}వ పేజీ", first: "మొదటి", last: "చివరి" },
  mr: { colPhoto: "फोटो", colName: "उत्पादन", colPrice: "किंमत", colId: "ओळखकर्ता", empty: "यादी रिकामी आहे.", loading: "लोड होत आहे…", failed: "जमले नाही. पुन्हा प्रयत्न करा.", count: "उत्पादने: {count}", tableTitle: "यादी", reveal: "उत्पादने दाखवा", revealHint: "तुम्ही मागेपर्यंत काहीही मागवले जात नाही — पान लगेच उघडते आणि डेटाबेसला काहीच खर्च नाही.", searchPlaceholder: "नावाने शोधा…", find: "शोधा", reset: "रीसेट", perPage: "प्रति पान", prev: "मागे", next: "पुढे", pageOf: "पान {page} / {pages}", first: "पहिले", last: "शेवटचे" },
  kn: { colPhoto: "ಫೋಟೋ", colName: "ಉತ್ಪನ್ನ", colPrice: "ಬೆಲೆ", colId: "ಗುರುತು", empty: "ಪಟ್ಟಿ ಖಾಲಿಯಿದೆ.", loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…", failed: "ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", count: "ಉತ್ಪನ್ನಗಳು: {count}", tableTitle: "ಪಟ್ಟಿ", reveal: "ಉತ್ಪನ್ನಗಳನ್ನು ತೋರಿಸು", revealHint: "ನೀವು ಕೇಳುವವರೆಗೆ ಏನೂ ಕೇಳಲಾಗುವುದಿಲ್ಲ — ಪುಟ ತಕ್ಷಣ ತೆರೆಯುತ್ತದೆ, ಡೇಟಾಬೇಸ್‌ಗೆ ಖರ್ಚಿಲ್ಲ.", searchPlaceholder: "ಹೆಸರಿನಿಂದ ಹುಡುಕಿ…", find: "ಹುಡುಕು", reset: "ಮರುಹೊಂದಿಸು", perPage: "ಪ್ರತಿ ಪುಟಕ್ಕೆ", prev: "ಹಿಂದೆ", next: "ಮುಂದೆ", pageOf: "{pages}ರಲ್ಲಿ {page}ನೇ ಪುಟ", first: "ಮೊದಲ", last: "ಕೊನೆಯ" },
  gu: { colPhoto: "ફોટો", colName: "ઉત્પાદન", colPrice: "કિંમત", colId: "ઓળખકર્તા", empty: "યાદી ખાલી છે.", loading: "લોડ થઈ રહ્યું છે…", failed: "થયું નહીં. ફરી પ્રયાસ કરો.", count: "ઉત્પાદનો: {count}", tableTitle: "યાદી", reveal: "ઉત્પાદનો બતાવો", revealHint: "તમે ન કહો ત્યાં સુધી કશું માગવામાં આવતું નથી — પાનું તરત ખૂલે છે અને ડેટાબેઝને કોઈ ખર્ચ નથી.", searchPlaceholder: "નામથી શોધો…", find: "શોધો", reset: "રીસેટ", perPage: "પ્રતિ પાનું", prev: "પાછળ", next: "આગળ", pageOf: "પાનું {page} / {pages}", first: "પ્રથમ", last: "છેલ્લું" },
  ml: { colPhoto: "ഫോട്ടോ", colName: "ഉൽപ്പന്നം", colPrice: "വില", colId: "തിരിച്ചറിയൽ", empty: "പട്ടിക ശൂന്യമാണ്.", loading: "ലോഡ് ചെയ്യുന്നു…", failed: "നടന്നില്ല. വീണ്ടും ശ്രമിക്കുക.", count: "ഉൽപ്പന്നങ്ങൾ: {count}", tableTitle: "പട്ടിക", reveal: "ഉൽപ്പന്നങ്ങൾ കാണിക്കുക", revealHint: "നിങ്ങൾ ചോദിക്കുന്നതുവരെ ഒന്നും ചോദിക്കുന്നില്ല — പേജ് ഉടനെ തുറക്കുന്നു, ഡാറ്റാബേസിന് ചെലവില്ല.", searchPlaceholder: "പേരുകൊണ്ട് തിരയുക…", find: "കണ്ടെത്തുക", reset: "പുനഃസജ്ജമാക്കുക", perPage: "ഓരോ പേജിലും", prev: "പിന്നോട്ട്", next: "മുന്നോട്ട്", pageOf: "{pages}-ൽ {page}-ാം പേജ്", first: "ആദ്യത്തേത്", last: "അവസാനത്തേത്" },
  ta: { colPhoto: "புகைப்படம்", colName: "பொருள்", colPrice: "விலை", colId: "அடையாளம்", empty: "பட்டியல் காலியாக உள்ளது.", loading: "ஏற்றுகிறது…", failed: "முடியவில்லை. மீண்டும் முயற்சிக்கவும்.", count: "பொருட்கள்: {count}", tableTitle: "பட்டியல்", reveal: "பொருட்களைக் காட்டு", revealHint: "நீங்கள் கேட்கும் வரை எதுவும் கோரப்படுவதில்லை — பக்கம் உடனே திறக்கிறது, தரவுத்தளத்திற்குச் செலவில்லை.", searchPlaceholder: "பெயரால் தேடு…", find: "தேடு", reset: "மீட்டமை", perPage: "ஒரு பக்கத்திற்கு", prev: "பின்", next: "முன்", pageOf: "{pages}ல் {page}ஆம் பக்கம்", first: "முதல்", last: "கடைசி" },
  ne: { colPhoto: "फोटो", colName: "उत्पादन", colPrice: "मूल्य", colId: "परिचायक", empty: "सूची खाली छ।", loading: "लोड हुँदैछ…", failed: "भएन। फेरि प्रयास गर्नुहोस्।", count: "उत्पादनहरू: {count}", tableTitle: "सूची", reveal: "उत्पादनहरू देखाउनुहोस्", revealHint: "तपाईंले नमागेसम्म केही मागिँदैन — पृष्ठ तुरुन्तै खुल्छ र डाटाबेसलाई केही खर्च हुँदैन।", searchPlaceholder: "नामबाट खोज्नुहोस्…", find: "खोज्नुहोस्", reset: "रिसेट", perPage: "प्रति पृष्ठ", prev: "पछाडि", next: "अगाडि", pageOf: "पृष्ठ {page} / {pages}", first: "पहिलो", last: "अन्तिम" },
  vi: { colPhoto: "Ảnh", colName: "Sản phẩm", colPrice: "Giá", colId: "Định danh", empty: "Danh mục trống.", loading: "Đang tải…", failed: "Không được. Hãy thử lại.", count: "{count} sản phẩm", tableTitle: "Danh mục", reveal: "Hiện sản phẩm", revealHint: "Không có gì được truy vấn cho tới khi bạn yêu cầu — trang mở ngay và không tốn gì của cơ sở dữ liệu.", searchPlaceholder: "Tìm theo tên…", find: "Tìm", reset: "Đặt lại", perPage: "Mỗi trang", prev: "Lùi", next: "Tiến", pageOf: "Trang {page} / {pages}", first: "Đầu", last: "Cuối" },
  th: { colPhoto: "รูป", colName: "สินค้า", colPrice: "ราคา", colId: "ตัวระบุ", empty: "รายการว่างเปล่า", loading: "กำลังโหลด…", failed: "ไม่สำเร็จ ลองอีกครั้ง", count: "สินค้า {count} รายการ", tableTitle: "รายการ", reveal: "แสดงสินค้า", revealHint: "จะไม่มีการเรียกข้อมูลจนกว่าคุณจะขอ — หน้าเปิดทันทีและไม่กินทรัพยากรฐานข้อมูล", searchPlaceholder: "ค้นหาด้วยชื่อ…", find: "ค้นหา", reset: "ล้าง", perPage: "ต่อหน้า", prev: "ย้อนกลับ", next: "ถัดไป", pageOf: "หน้า {page} จาก {pages}", first: "แรก", last: "สุดท้าย" },
  id: { colPhoto: "Foto", colName: "Produk", colPrice: "Harga", colId: "Pengenal", empty: "Katalog kosong.", loading: "Memuat…", failed: "Tidak berhasil. Coba lagi.", count: "{count} produk", tableTitle: "Katalog", reveal: "Tampilkan produk", revealHint: "Tidak ada yang diminta sampai Anda meminta — halaman terbuka seketika dan tidak membebani basis data.", searchPlaceholder: "Cari berdasarkan nama…", find: "Cari", reset: "Atur ulang", perPage: "Per halaman", prev: "Kembali", next: "Maju", pageOf: "Halaman {page} dari {pages}", first: "Pertama", last: "Terakhir" },
  ms: { colPhoto: "Foto", colName: "Produk", colPrice: "Harga", colId: "Pengecam", empty: "Katalog kosong.", loading: "Memuatkan…", failed: "Tidak berjaya. Cuba lagi.", count: "{count} produk", tableTitle: "Katalog", reveal: "Tunjukkan produk", revealHint: "Tiada apa-apa diminta sehingga anda meminta — halaman terbuka serta-merta dan tidak membebankan pangkalan data.", searchPlaceholder: "Cari mengikut nama…", find: "Cari", reset: "Set semula", perPage: "Setiap halaman", prev: "Kembali", next: "Ke hadapan", pageOf: "Halaman {page} daripada {pages}", first: "Pertama", last: "Terakhir" },
  tl: { colPhoto: "Larawan", colName: "Produkto", colPrice: "Presyo", colId: "Pagkakakilanlan", empty: "Walang laman ang katalogo.", loading: "Naglo-load…", failed: "Hindi umubra. Subukan muli.", count: "{count} produkto", tableTitle: "Katalogo", reveal: "Ipakita ang mga produkto", revealHint: "Walang hinihingi hangga’t hindi ka humihingi — agad bumubukas ang pahina at walang gastos sa database.", searchPlaceholder: "Maghanap ayon sa pangalan…", find: "Hanapin", reset: "I-reset", perPage: "Bawat pahina", prev: "Balik", next: "Sulong", pageOf: "Pahina {page} ng {pages}", first: "Una", last: "Huli" },
  my: { colPhoto: "ဓာတ်ပုံ", colName: "ကုန်ပစ္စည်း", colPrice: "ဈေးနှုန်း", colId: "အမှတ်အသား", empty: "စာရင်း ဗလာဖြစ်နေသည်။", loading: "ဖွင့်နေသည်…", failed: "မအောင်မြင်ပါ။ ထပ်ကြိုးစားပါ။", count: "ကုန်ပစ္စည်း {count} ခု", tableTitle: "စာရင်း", reveal: "ကုန်ပစ္စည်းများ ပြရန်", revealHint: "သင်မတောင်းမချင်း ဘာမှ မတောင်းပါ — စာမျက်နှာ ချက်ချင်းပွင့်ပြီး ဒေတာဘေ့စ်ကို ဝန်မပေးပါ။", searchPlaceholder: "အမည်ဖြင့် ရှာရန်…", find: "ရှာရန်", reset: "ပြန်လည်သတ်မှတ်", perPage: "စာမျက်နှာလျှင်", prev: "နောက်သို့", next: "ရှေ့သို့", pageOf: "စာမျက်နှာ {page} / {pages}", first: "ပထမ", last: "နောက်ဆုံး" },
  km: { colPhoto: "រូបភាព", colName: "ផលិតផល", colPrice: "តម្លៃ", colId: "អត្តសញ្ញាណ", empty: "បញ្ជីទទេ។", loading: "កំពុងផ្ទុក…", failed: "មិនបានសម្រេច។ សាកល្បងម្តងទៀត។", count: "ផលិតផល៖ {count}", tableTitle: "បញ្ជី", reveal: "បង្ហាញផលិតផល", revealHint: "គ្មានអ្វីត្រូវបានស្នើសុំទេ រហូតដល់អ្នកស្នើ — ទំព័របើកភ្លាមៗ ហើយមិនចំណាយអ្វីលើមូលដ្ឋានទិន្នន័យ។", searchPlaceholder: "ស្វែងរកតាមឈ្មោះ…", find: "ស្វែងរក", reset: "កំណត់ឡើងវិញ", perPage: "ក្នុងមួយទំព័រ", prev: "ថយក្រោយ", next: "ទៅមុខ", pageOf: "ទំព័រ {page} នៃ {pages}", first: "ដំបូង", last: "ចុងក្រោយ" },
  lo: { colPhoto: "ຮູບ", colName: "ສິນຄ້າ", colPrice: "ລາຄາ", colId: "ຕົວລະບຸ", empty: "ລາຍການວ່າງເປົ່າ.", loading: "ກຳລັງໂຫຼດ…", failed: "ບໍ່ສຳເລັດ. ລອງໃໝ່.", count: "ສິນຄ້າ: {count}", tableTitle: "ລາຍການ", reveal: "ສະແດງສິນຄ້າ", revealHint: "ຈະບໍ່ມີການຮ້ອງຂໍຫຍັງຈົນກວ່າທ່ານຈະຂໍ — ໜ້າເປີດທັນທີ ແລະ ບໍ່ເສຍຄ່າຫຍັງກັບຖານຂໍ້ມູນ.", searchPlaceholder: "ຄົ້ນຫາດ້ວຍຊື່…", find: "ຄົ້ນຫາ", reset: "ຕັ້ງຄືນ", perPage: "ຕໍ່ໜ້າ", prev: "ກັບຄືນ", next: "ໄປໜ້າ", pageOf: "ໜ້າ {page} ຈາກ {pages}", first: "ທຳອິດ", last: "ສຸດທ້າຍ" },
}

export function productListUi(lang: string): ProductListUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
