// СООБЩЕНИЯ ОБ ОТКАЗАХ ПЛАТФОРМЫ — 82 языка, одно место на весь проект.
//
// 🔒 ПОЧЕМУ ОДИН ФАЙЛ, А НЕ КОПИЯ В КАЖДОЙ ВОЗМОЖНОСТИ. «Нет ключа OpenAI» —
// один и тот же отказ для голосового ввода, перевода полей и любой будущей
// думающей части. Копии расходятся, и расходятся именно в редких языках, где
// этого никто не заметит до жалобы пользователя.
//
// 🔒 ПОЧЕМУ 82, А НЕ ДЕСЯТЬ. Набор языков приложения выбирает владелец, и
// выбрать он может любой из 82. Строка на десяти языках для остальных молча
// становится английской — ровно в тот момент, когда у человека что-то сломалось
// и он читает объяснение. Правило `/code/CLAUDE.md` §4д.
//
// 🔒 ЭТОТ МОДУЛЬ НЕ ИМПОРТИРУЕТСЯ ИЗ КЛИЕНТА. 82 языка в браузер — это
// мегабайты на каждой странице. Серверный компонент зовёт `platformErrors(lang)`
// и передаёт результат островку пропсами; тот же закон, что у панели.
//
// ТЕКСТЫ КОРОТКИЕ НАМЕРЕННО: это тост, а не статья. Каждое сообщение говорит,
// ЧТО случилось и КУДА идти; сама ссылка — рядом, отдельным элементом.

export type PlatformErrors = {
  /** Ключа нет вовсе. */
  noKey: string
  /** Ключ есть, но OpenAI его не принял. */
  badKey: string
  /** Кончились средства на балансе. */
  noFunds: string
  /** Слишком часто — ограничение частоты. */
  rateLimit: string
  /** Ответа не было. */
  upstream: string
  /** Подпись ссылки на страницу ключа в панели. */
  keyLink: string
  /** Подпись ссылки на баланс OpenAI. */
  fundsLink: string
}

const E: Record<string, PlatformErrors> = {
  en: { noKey: "No OpenAI key — add it in the control panel.", badKey: "OpenAI rejected the key — check it in the control panel.", noFunds: "Not enough funds on the OpenAI balance — top it up.", rateLimit: "OpenAI is limiting requests — wait a few seconds.", upstream: "OpenAI did not answer — try again.", keyLink: "OpenAI settings", fundsLink: "OpenAI billing" },
  fr: { noKey: "Aucune clé OpenAI — ajoutez-la dans le panneau.", badKey: "OpenAI a refusé la clé — vérifiez-la dans le panneau.", noFunds: "Solde OpenAI insuffisant — rechargez-le.", rateLimit: "OpenAI limite les requêtes — patientez quelques secondes.", upstream: "OpenAI n’a pas répondu — réessayez.", keyLink: "Réglages OpenAI", fundsLink: "Facturation OpenAI" },
  es: { noKey: "No hay clave de OpenAI — añádela en el panel.", badKey: "OpenAI rechazó la clave — revísala en el panel.", noFunds: "Saldo insuficiente en OpenAI — recárgalo.", rateLimit: "OpenAI limita las peticiones — espera unos segundos.", upstream: "OpenAI no respondió — inténtalo de nuevo.", keyLink: "Ajustes de OpenAI", fundsLink: "Facturación de OpenAI" },
  pt: { noKey: "Sem chave OpenAI — adicione no painel.", badKey: "A OpenAI recusou a chave — verifique no painel.", noFunds: "Saldo insuficiente na OpenAI — recarregue.", rateLimit: "A OpenAI está limitando as requisições — aguarde alguns segundos.", upstream: "A OpenAI não respondeu — tente de novo.", keyLink: "Configurações da OpenAI", fundsLink: "Faturamento da OpenAI" },
  de: { noKey: "Kein OpenAI-Schlüssel — im Panel hinterlegen.", badKey: "OpenAI hat den Schlüssel abgelehnt — im Panel prüfen.", noFunds: "Zu wenig Guthaben bei OpenAI — bitte aufladen.", rateLimit: "OpenAI drosselt die Anfragen — ein paar Sekunden warten.", upstream: "OpenAI hat nicht geantwortet — erneut versuchen.", keyLink: "OpenAI-Einstellungen", fundsLink: "OpenAI-Abrechnung" },
  it: { noKey: "Manca la chiave OpenAI — aggiungila nel pannello.", badKey: "OpenAI ha rifiutato la chiave — controllala nel pannello.", noFunds: "Credito OpenAI insufficiente — ricaricalo.", rateLimit: "OpenAI limita le richieste — attendi qualche secondo.", upstream: "OpenAI non ha risposto — riprova.", keyLink: "Impostazioni OpenAI", fundsLink: "Fatturazione OpenAI" },
  nl: { noKey: "Geen OpenAI-sleutel — voeg hem toe in het paneel.", badKey: "OpenAI weigerde de sleutel — controleer hem in het paneel.", noFunds: "Onvoldoende saldo bij OpenAI — vul het aan.", rateLimit: "OpenAI beperkt de verzoeken — wacht enkele seconden.", upstream: "OpenAI antwoordde niet — probeer opnieuw.", keyLink: "OpenAI-instellingen", fundsLink: "OpenAI-facturering" },
  sv: { noKey: "Ingen OpenAI-nyckel — lägg till den i panelen.", badKey: "OpenAI avvisade nyckeln — kontrollera den i panelen.", noFunds: "För lite saldo hos OpenAI — fyll på.", rateLimit: "OpenAI begränsar förfrågningarna — vänta några sekunder.", upstream: "OpenAI svarade inte — försök igen.", keyLink: "OpenAI-inställningar", fundsLink: "OpenAI-fakturering" },
  no: { noKey: "Ingen OpenAI-nøkkel — legg den til i panelet.", badKey: "OpenAI avviste nøkkelen — sjekk den i panelet.", noFunds: "For lite saldo hos OpenAI — fyll på.", rateLimit: "OpenAI begrenser forespørslene — vent noen sekunder.", upstream: "OpenAI svarte ikke — prøv igjen.", keyLink: "OpenAI-innstillinger", fundsLink: "OpenAI-fakturering" },
  da: { noKey: "Ingen OpenAI-nøgle — tilføj den i panelet.", badKey: "OpenAI afviste nøglen — tjek den i panelet.", noFunds: "For lidt saldo hos OpenAI — fyld op.", rateLimit: "OpenAI begrænser forespørgslerne — vent et par sekunder.", upstream: "OpenAI svarede ikke — prøv igen.", keyLink: "OpenAI-indstillinger", fundsLink: "OpenAI-fakturering" },
  fi: { noKey: "Ei OpenAI-avainta — lisää se hallintapaneelissa.", badKey: "OpenAI hylkäsi avaimen — tarkista se paneelissa.", noFunds: "OpenAI-saldo ei riitä — lataa lisää.", rateLimit: "OpenAI rajoittaa pyyntöjä — odota muutama sekunti.", upstream: "OpenAI ei vastannut — yritä uudelleen.", keyLink: "OpenAI-asetukset", fundsLink: "OpenAI-laskutus" },
  is: { noKey: "Enginn OpenAI-lykill — bættu honum við í stjórnborðinu.", badKey: "OpenAI hafnaði lyklinum — athugaðu hann í stjórnborðinu.", noFunds: "Ekki næg innistæða hjá OpenAI — fylltu á.", rateLimit: "OpenAI takmarkar beiðnir — bíddu í nokkrar sekúndur.", upstream: "OpenAI svaraði ekki — reyndu aftur.", keyLink: "OpenAI-stillingar", fundsLink: "OpenAI-reikningar" },
  el: { noKey: "Δεν υπάρχει κλειδί OpenAI — προσθέστε το στον πίνακα.", badKey: "Το OpenAI απέρριψε το κλειδί — ελέγξτε το στον πίνακα.", noFunds: "Ανεπαρκές υπόλοιπο OpenAI — ανανεώστε το.", rateLimit: "Το OpenAI περιορίζει τα αιτήματα — περιμένετε λίγα δευτερόλεπτα.", upstream: "Το OpenAI δεν απάντησε — δοκιμάστε ξανά.", keyLink: "Ρυθμίσεις OpenAI", fundsLink: "Χρεώσεις OpenAI" },
  pl: { noKey: "Brak klucza OpenAI — dodaj go w panelu.", badKey: "OpenAI odrzuciło klucz — sprawdź go w panelu.", noFunds: "Za mało środków w OpenAI — doładuj.", rateLimit: "OpenAI ogranicza żądania — poczekaj kilka sekund.", upstream: "OpenAI nie odpowiedziało — spróbuj ponownie.", keyLink: "Ustawienia OpenAI", fundsLink: "Rozliczenia OpenAI" },
  cs: { noKey: "Chybí klíč OpenAI — přidejte jej v panelu.", badKey: "OpenAI klíč odmítlo — zkontrolujte jej v panelu.", noFunds: "Nedostatek prostředků u OpenAI — dobijte je.", rateLimit: "OpenAI omezuje požadavky — počkejte pár sekund.", upstream: "OpenAI neodpovědělo — zkuste to znovu.", keyLink: "Nastavení OpenAI", fundsLink: "Fakturace OpenAI" },
  sk: { noKey: "Chýba kľúč OpenAI — pridajte ho v paneli.", badKey: "OpenAI kľúč odmietlo — skontrolujte ho v paneli.", noFunds: "Nedostatok prostriedkov v OpenAI — dobite ich.", rateLimit: "OpenAI obmedzuje požiadavky — počkajte pár sekúnd.", upstream: "OpenAI neodpovedalo — skúste to znova.", keyLink: "Nastavenia OpenAI", fundsLink: "Fakturácia OpenAI" },
  hu: { noKey: "Nincs OpenAI-kulcs — adja hozzá a vezérlőpulton.", badKey: "Az OpenAI elutasította a kulcsot — ellenőrizze a vezérlőpulton.", noFunds: "Nincs elég egyenleg az OpenAI-nál — töltse fel.", rateLimit: "Az OpenAI korlátozza a kéréseket — várjon néhány másodpercet.", upstream: "Az OpenAI nem válaszolt — próbálja újra.", keyLink: "OpenAI-beállítások", fundsLink: "OpenAI-számlázás" },
  ro: { noKey: "Nu există cheie OpenAI — adăugați-o în panou.", badKey: "OpenAI a respins cheia — verificați-o în panou.", noFunds: "Sold insuficient la OpenAI — reîncărcați-l.", rateLimit: "OpenAI limitează cererile — așteptați câteva secunde.", upstream: "OpenAI nu a răspuns — încercați din nou.", keyLink: "Setări OpenAI", fundsLink: "Facturare OpenAI" },
  hr: { noKey: "Nema OpenAI ključa — dodajte ga u ploči.", badKey: "OpenAI je odbio ključ — provjerite ga u ploči.", noFunds: "Nedovoljno sredstava na OpenAI računu — nadopunite.", rateLimit: "OpenAI ograničava zahtjeve — pričekajte nekoliko sekundi.", upstream: "OpenAI nije odgovorio — pokušajte ponovno.", keyLink: "Postavke OpenAI", fundsLink: "Naplata OpenAI" },
  sl: { noKey: "Ni ključa OpenAI — dodajte ga v nadzorni plošči.", badKey: "OpenAI je zavrnil ključ — preverite ga v nadzorni plošči.", noFunds: "Premalo sredstev pri OpenAI — dopolnite jih.", rateLimit: "OpenAI omejuje zahteve — počakajte nekaj sekund.", upstream: "OpenAI ni odgovoril — poskusite znova.", keyLink: "Nastavitve OpenAI", fundsLink: "Obračun OpenAI" },
  et: { noKey: "OpenAI võtit pole — lisage see juhtpaneelil.", badKey: "OpenAI lükkas võtme tagasi — kontrollige seda juhtpaneelil.", noFunds: "OpenAI saldo ei ole piisav — täiendage seda.", rateLimit: "OpenAI piirab päringuid — oodake mõni sekund.", upstream: "OpenAI ei vastanud — proovige uuesti.", keyLink: "OpenAI seaded", fundsLink: "OpenAI arveldus" },
  lv: { noKey: "Nav OpenAI atslēgas — pievienojiet to panelī.", badKey: "OpenAI noraidīja atslēgu — pārbaudiet to panelī.", noFunds: "Nepietiek līdzekļu OpenAI kontā — papildiniet.", rateLimit: "OpenAI ierobežo pieprasījumus — pagaidiet dažas sekundes.", upstream: "OpenAI neatbildēja — mēģiniet vēlreiz.", keyLink: "OpenAI iestatījumi", fundsLink: "OpenAI norēķini" },
  lt: { noKey: "Nėra OpenAI rakto — pridėkite jį skydelyje.", badKey: "OpenAI atmetė raktą — patikrinkite jį skydelyje.", noFunds: "Nepakanka lėšų OpenAI sąskaitoje — papildykite.", rateLimit: "OpenAI riboja užklausas — palaukite kelias sekundes.", upstream: "OpenAI neatsakė — bandykite dar kartą.", keyLink: "OpenAI nustatymai", fundsLink: "OpenAI atsiskaitymai" },
  mt: { noKey: "M’hemmx ċavetta OpenAI — żidha fil-pannell.", badKey: "OpenAI ċaħad iċ-ċavetta — iċċekkjaha fil-pannell.", noFunds: "Bilanċ OpenAI insuffiċjenti — irrikarkah.", rateLimit: "OpenAI qed jillimita t-talbiet — stenna ftit sekondi.", upstream: "OpenAI ma weġibx — erġa’ pprova.", keyLink: "Issettjar OpenAI", fundsLink: "Fatturazzjoni OpenAI" },
  ca: { noKey: "No hi ha clau d’OpenAI — afegeix-la al tauler.", badKey: "OpenAI ha rebutjat la clau — revisa-la al tauler.", noFunds: "Saldo insuficient a OpenAI — recarrega’l.", rateLimit: "OpenAI limita les peticions — espera uns segons.", upstream: "OpenAI no ha respost — torna-ho a provar.", keyLink: "Configuració d’OpenAI", fundsLink: "Facturació d’OpenAI" },
  gl: { noKey: "Non hai clave de OpenAI — engádea no panel.", badKey: "OpenAI rexeitou a clave — revísaa no panel.", noFunds: "Saldo insuficiente en OpenAI — recárgao.", rateLimit: "OpenAI limita as peticións — agarda uns segundos.", upstream: "OpenAI non respondeu — téntao de novo.", keyLink: "Axustes de OpenAI", fundsLink: "Facturación de OpenAI" },
  cy: { noKey: "Dim allwedd OpenAI — ychwanegwch hi yn y panel.", badKey: "Gwrthododd OpenAI yr allwedd — gwiriwch hi yn y panel.", noFunds: "Dim digon o gredyd OpenAI — ychwanegwch ato.", rateLimit: "Mae OpenAI yn cyfyngu ar y ceisiadau — arhoswch ychydig eiliadau.", upstream: "Ni atebodd OpenAI — rhowch gynnig arall.", keyLink: "Gosodiadau OpenAI", fundsLink: "Bilio OpenAI" },
  ga: { noKey: "Níl eochair OpenAI ann — cuir leis sa phainéal í.", badKey: "Dhiúltaigh OpenAI don eochair — seiceáil sa phainéal í.", noFunds: "Níl go leor creidmheasa ag OpenAI — cuir leis.", rateLimit: "Tá OpenAI ag teorannú na n-iarratas — fan cúpla soicind.", upstream: "Níor fhreagair OpenAI — bain triail eile as.", keyLink: "Socruithe OpenAI", fundsLink: "Billeáil OpenAI" },
  eu: { noKey: "Ez dago OpenAI gakorik — gehitu panelean.", badKey: "OpenAI-k gakoa baztertu du — egiaztatu panelean.", noFunds: "OpenAI saldoa ez da nahikoa — kargatu ezazu.", rateLimit: "OpenAI-k eskaerak mugatzen ditu — itxaron segundo batzuk.", upstream: "OpenAI-k ez du erantzun — saiatu berriro.", keyLink: "OpenAI ezarpenak", fundsLink: "OpenAI fakturazioa" },
  ru: { noKey: "Нет ключа OpenAI — добавьте его в панели управления.", badKey: "OpenAI отклонил ключ — проверьте его в панели управления.", noFunds: "Недостаточно средств на балансе OpenAI — пополните его.", rateLimit: "OpenAI ограничивает частоту запросов — подождите несколько секунд.", upstream: "OpenAI не ответил — повторите попытку.", keyLink: "Настройки OpenAI", fundsLink: "Баланс OpenAI" },
  uk: { noKey: "Немає ключа OpenAI — додайте його в панелі керування.", badKey: "OpenAI відхилив ключ — перевірте його в панелі керування.", noFunds: "Недостатньо коштів на балансі OpenAI — поповніть його.", rateLimit: "OpenAI обмежує частоту запитів — зачекайте кілька секунд.", upstream: "OpenAI не відповів — повторіть спробу.", keyLink: "Налаштування OpenAI", fundsLink: "Баланс OpenAI" },
  be: { noKey: "Няма ключа OpenAI — дадайце яго ў панэлі кіравання.", badKey: "OpenAI адхіліў ключ — праверце яго ў панэлі кіравання.", noFunds: "Недастаткова сродкаў на балансе OpenAI — папоўніце яго.", rateLimit: "OpenAI абмяжоўвае частату запытаў — пачакайце некалькі секунд.", upstream: "OpenAI не адказаў — паўтарыце спробу.", keyLink: "Налады OpenAI", fundsLink: "Баланс OpenAI" },
  bg: { noKey: "Няма ключ за OpenAI — добавете го в панела.", badKey: "OpenAI отхвърли ключа — проверете го в панела.", noFunds: "Недостатъчна наличност в OpenAI — заредете я.", rateLimit: "OpenAI ограничава заявките — изчакайте няколко секунди.", upstream: "OpenAI не отговори — опитайте отново.", keyLink: "Настройки на OpenAI", fundsLink: "Плащания в OpenAI" },
  sr: { noKey: "Нема OpenAI кључа — додајте га у панелу.", badKey: "OpenAI је одбио кључ — проверите га у панелу.", noFunds: "Недовољно средстава на OpenAI рачуну — допуните.", rateLimit: "OpenAI ограничава захтеве — сачекајте неколико секунди.", upstream: "OpenAI није одговорио — покушајте поново.", keyLink: "Подешавања OpenAI", fundsLink: "Наплата OpenAI" },
  bs: { noKey: "Nema OpenAI ključa — dodajte ga u panelu.", badKey: "OpenAI je odbio ključ — provjerite ga u panelu.", noFunds: "Nedovoljno sredstava na OpenAI računu — dopunite.", rateLimit: "OpenAI ograničava zahtjeve — sačekajte nekoliko sekundi.", upstream: "OpenAI nije odgovorio — pokušajte ponovo.", keyLink: "Postavke OpenAI", fundsLink: "Naplata OpenAI" },
  mk: { noKey: "Нема OpenAI клуч — додајте го во панелот.", badKey: "OpenAI го одби клучот — проверете го во панелот.", noFunds: "Недоволно средства на OpenAI — дополнете ги.", rateLimit: "OpenAI ги ограничува барањата — почекајте неколку секунди.", upstream: "OpenAI не одговори — обидете се повторно.", keyLink: "Поставки на OpenAI", fundsLink: "Наплата на OpenAI" },
  sq: { noKey: "Nuk ka çelës OpenAI — shtojeni në panel.", badKey: "OpenAI e refuzoi çelësin — kontrollojeni në panel.", noFunds: "Bilanc i pamjaftueshëm në OpenAI — rimbusheni.", rateLimit: "OpenAI po kufizon kërkesat — prisni disa sekonda.", upstream: "OpenAI nuk u përgjigj — provoni sërish.", keyLink: "Cilësimet e OpenAI", fundsLink: "Faturimi i OpenAI" },
  kk: { noKey: "OpenAI кілті жоқ — оны басқару панелінде қосыңыз.", badKey: "OpenAI кілтті қабылдамады — панельден тексеріңіз.", noFunds: "OpenAI балансында қаражат жеткіліксіз — толтырыңыз.", rateLimit: "OpenAI сұраныстарды шектеп жатыр — бірнеше секунд күтіңіз.", upstream: "OpenAI жауап бермеді — қайталап көріңіз.", keyLink: "OpenAI параметрлері", fundsLink: "OpenAI балансы" },
  uz: { noKey: "OpenAI kaliti yo‘q — uni boshqaruv panelida qo‘shing.", badKey: "OpenAI kalitni rad etdi — uni panelda tekshiring.", noFunds: "OpenAI balansida mablag‘ yetarli emas — to‘ldiring.", rateLimit: "OpenAI so‘rovlarni cheklamoqda — bir necha soniya kuting.", upstream: "OpenAI javob bermadi — qayta urinib ko‘ring.", keyLink: "OpenAI sozlamalari", fundsLink: "OpenAI balansi" },
  ky: { noKey: "OpenAI ачкычы жок — аны башкаруу панелинде кошуңуз.", badKey: "OpenAI ачкычты кабыл албады — панелден текшериңиз.", noFunds: "OpenAI балансында каражат жетишсиз — толтуруңуз.", rateLimit: "OpenAI сурамдарды чектеп жатат — бир нече секунд күтүңүз.", upstream: "OpenAI жооп бербеди — кайра аракет кылыңыз.", keyLink: "OpenAI жөндөөлөрү", fundsLink: "OpenAI балансы" },
  tg: { noKey: "Калиди OpenAI нест — онро дар панел илова кунед.", badKey: "OpenAI калидро рад кард — онро дар панел санҷед.", noFunds: "Маблағ дар OpenAI кофӣ нест — пур кунед.", rateLimit: "OpenAI дархостҳоро маҳдуд мекунад — чанд сония интизор шавед.", upstream: "OpenAI ҷавоб надод — боз кӯшиш кунед.", keyLink: "Танзимоти OpenAI", fundsLink: "Тавозуни OpenAI" },
  tk: { noKey: "OpenAI açary ýok — ony panelde goşuň.", badKey: "OpenAI açary kabul etmedi — panelde barlaň.", noFunds: "OpenAI balansynda serişde ýeterlik däl — dolduryň.", rateLimit: "OpenAI haýyşlary çäklendirýär — birnäçe sekunt garaşyň.", upstream: "OpenAI jogap bermedi — gaýtadan synanyşyň.", keyLink: "OpenAI sazlamalary", fundsLink: "OpenAI balansy" },
  az: { noKey: "OpenAI açarı yoxdur — onu idarə panelində əlavə edin.", badKey: "OpenAI açarı rədd etdi — onu paneldə yoxlayın.", noFunds: "OpenAI balansında vəsait çatmır — artırın.", rateLimit: "OpenAI sorğuları məhdudlaşdırır — bir neçə saniyə gözləyin.", upstream: "OpenAI cavab vermədi — yenidən cəhd edin.", keyLink: "OpenAI parametrləri", fundsLink: "OpenAI balansı" },
  hy: { noKey: "OpenAI բանալի չկա — ավելացրեք այն վահանակում։", badKey: "OpenAI-ն մերժեց բանալին — ստուգեք այն վահանակում։", noFunds: "OpenAI-ի հաշվեկշիռը բավարար չէ — համալրեք այն։", rateLimit: "OpenAI-ն սահմանափակում է հարցումները — սպասեք մի քանի վայրկյան։", upstream: "OpenAI-ն չպատասխանեց — կրկին փորձեք։", keyLink: "OpenAI-ի կարգավորումներ", fundsLink: "OpenAI-ի հաշիվ" },
  ka: { noKey: "OpenAI გასაღები არ არის — დაამატეთ პანელში.", badKey: "OpenAI-მ გასაღები არ მიიღო — შეამოწმეთ პანელში.", noFunds: "OpenAI-ის ბალანსი არასაკმარისია — შეავსეთ.", rateLimit: "OpenAI ზღუდავს მოთხოვნებს — დაელოდეთ რამდენიმე წამს.", upstream: "OpenAI არ უპასუხა — სცადეთ თავიდან.", keyLink: "OpenAI-ის პარამეტრები", fundsLink: "OpenAI-ის ბალანსი" },
  mn: { noKey: "OpenAI түлхүүр алга — удирдлагын самбарт нэмнэ үү.", badKey: "OpenAI түлхүүрийг хүлээж авсангүй — самбараас шалгана уу.", noFunds: "OpenAI үлдэгдэл хүрэлцэхгүй байна — цэнэглэнэ үү.", rateLimit: "OpenAI хүсэлтийг хязгаарлаж байна — хэдэн секунд хүлээнэ үү.", upstream: "OpenAI хариу өгсөнгүй — дахин оролдоно уу.", keyLink: "OpenAI тохиргоо", fundsLink: "OpenAI үлдэгдэл" },
  ar: { noKey: "لا يوجد مفتاح OpenAI — أضفه من لوحة التحكم.", badKey: "رفض OpenAI المفتاح — تحقق منه في لوحة التحكم.", noFunds: "الرصيد في OpenAI غير كافٍ — قم بشحنه.", rateLimit: "يحدّ OpenAI من الطلبات — انتظر بضع ثوانٍ.", upstream: "لم يستجب OpenAI — حاول مرة أخرى.", keyLink: "إعدادات OpenAI", fundsLink: "فوترة OpenAI" },
  tr: { noKey: "OpenAI anahtarı yok — panelden ekleyin.", badKey: "OpenAI anahtarı reddetti — panelden kontrol edin.", noFunds: "OpenAI bakiyesi yetersiz — yükleme yapın.", rateLimit: "OpenAI istekleri sınırlıyor — birkaç saniye bekleyin.", upstream: "OpenAI yanıt vermedi — tekrar deneyin.", keyLink: "OpenAI ayarları", fundsLink: "OpenAI faturalandırma" },
  he: { noKey: "אין מפתח OpenAI — הוסיפו אותו בלוח הבקרה.", badKey: "OpenAI דחה את המפתח — בדקו אותו בלוח הבקרה.", noFunds: "אין מספיק יתרה ב-OpenAI — טענו אותה.", rateLimit: "OpenAI מגביל את הבקשות — המתינו כמה שניות.", upstream: "OpenAI לא הגיב — נסו שוב.", keyLink: "הגדרות OpenAI", fundsLink: "חיוב OpenAI" },
  fa: { noKey: "کلید OpenAI وجود ندارد — آن را در پنل اضافه کنید.", badKey: "OpenAI کلید را نپذیرفت — آن را در پنل بررسی کنید.", noFunds: "موجودی OpenAI کافی نیست — آن را شارژ کنید.", rateLimit: "OpenAI درخواست‌ها را محدود می‌کند — چند ثانیه صبر کنید.", upstream: "OpenAI پاسخ نداد — دوباره تلاش کنید.", keyLink: "تنظیمات OpenAI", fundsLink: "صورتحساب OpenAI" },
  ku: { noKey: "Kilîla OpenAI tune — wê di panelê de zêde bike.", badKey: "OpenAI kilîl red kir — wê di panelê de kontrol bike.", noFunds: "Balansa OpenAI têrê nake — wê dagire.", rateLimit: "OpenAI daxwazan sînordar dike — çend saniyeyan bisekine.", upstream: "OpenAI bersiv neda — dîsa biceribîne.", keyLink: "Mîhengên OpenAI", fundsLink: "Fatûreya OpenAI" },
  af: { noKey: "Geen OpenAI-sleutel nie — voeg dit in die paneel by.", badKey: "OpenAI het die sleutel verwerp — kontroleer dit in die paneel.", noFunds: "Nie genoeg fondse by OpenAI nie — laai dit aan.", rateLimit: "OpenAI beperk die versoeke — wag ’n paar sekondes.", upstream: "OpenAI het nie geantwoord nie — probeer weer.", keyLink: "OpenAI-instellings", fundsLink: "OpenAI-fakturering" },
  sw: { noKey: "Hakuna ufunguo wa OpenAI — uweke katika paneli.", badKey: "OpenAI imekataa ufunguo — uangalie katika paneli.", noFunds: "Salio la OpenAI halitoshi — liongeze.", rateLimit: "OpenAI inapunguza maombi — subiri sekunde chache.", upstream: "OpenAI haikujibu — jaribu tena.", keyLink: "Mipangilio ya OpenAI", fundsLink: "Malipo ya OpenAI" },
  ha: { noKey: "Babu mabuɗin OpenAI — ƙara shi a cikin panel.", badKey: "OpenAI ya ƙi mabuɗin — duba shi a cikin panel.", noFunds: "Ma’aunin OpenAI bai isa ba — cika shi.", rateLimit: "OpenAI yana iyakance buƙatun — jira ’yan daƙiƙu.", upstream: "OpenAI bai amsa ba — sake gwadawa.", keyLink: "Saitunan OpenAI", fundsLink: "Biyan kuɗi na OpenAI" },
  yo: { noKey: "Kò sí kọ́kọ́rọ́ OpenAI — fi kún un nínú pánẹ́lì.", badKey: "OpenAI kọ kọ́kọ́rọ́ náà — ṣàyẹ̀wò rẹ̀ nínú pánẹ́lì.", noFunds: "Owó OpenAI kò tó — kún un.", rateLimit: "OpenAI ń dín ìbéèrè kù — dúró fún ìṣẹ́jú díẹ̀.", upstream: "OpenAI kò dáhùn — gbìyànjú lẹ́ẹ̀kansi.", keyLink: "Ètò OpenAI", fundsLink: "Ìsanwó OpenAI" },
  ig: { noKey: "Enweghị igodo OpenAI — tinye ya na panel.", badKey: "OpenAI jụrụ igodo ahụ — lelee ya na panel.", noFunds: "Ego OpenAI ezughi — tinyekwuo.", rateLimit: "OpenAI na-amachi arịrịọ — chere sekọnd ole na ole.", upstream: "OpenAI azaghị — nwaa ọzọ.", keyLink: "Ntọala OpenAI", fundsLink: "Ụgwọ OpenAI" },
  am: { noKey: "የOpenAI ቁልፍ የለም — በመቆጣጠሪያ ሰሌዳው ውስጥ ያክሉት።", badKey: "OpenAI ቁልፉን ውድቅ አድርጎታል — በሰሌዳው ውስጥ ያረጋግጡት።", noFunds: "የOpenAI ቀሪ ሂሳብ በቂ አይደለም — ይሙሉት።", rateLimit: "OpenAI ጥያቄዎችን እየገደበ ነው — ጥቂት ሰከንዶች ይጠብቁ።", upstream: "OpenAI አልመለሰም — እንደገና ይሞክሩ።", keyLink: "የOpenAI ቅንብሮች", fundsLink: "የOpenAI ክፍያ" },
  zu: { noKey: "Awukho ukhiye we-OpenAI — wufake kuphaneli.", badKey: "I-OpenAI yenqabe ukhiye — hlola kuphaneli.", noFunds: "Ibhalansi ye-OpenAI ayanele — yigcwalise.", rateLimit: "I-OpenAI ikhawulela izicelo — linda imizuzwana embalwa.", upstream: "I-OpenAI ayiphendulanga — zama futhi.", keyLink: "Izilungiselelo ze-OpenAI", fundsLink: "Ukukhokha kwe-OpenAI" },
  xh: { noKey: "Akukho siqhoboshi se-OpenAI — sifake kwiphaneli.", badKey: "I-OpenAI yasala isiqhoboshi — sijonge kwiphaneli.", noFunds: "Ibhalansi ye-OpenAI ayonelanga — yizalise.", rateLimit: "I-OpenAI ithintela izicelo — linda imizuzwana embalwa.", upstream: "I-OpenAI ayiphendulanga — zama kwakhona.", keyLink: "Iisetingi ze-OpenAI", fundsLink: "Ityala le-OpenAI" },
  rw: { noKey: "Nta rufunguzo rwa OpenAI — rwongere ku ipaneli.", badKey: "OpenAI yanze urufunguzo — rugenzure ku ipaneli.", noFunds: "Amafaranga kuri OpenAI ntahagije — yongere.", rateLimit: "OpenAI iragabanya ibyifuzo — tegereza amasegonda make.", upstream: "OpenAI ntiyasubije — ongera ugerageze.", keyLink: "Igenamiterere rya OpenAI", fundsLink: "Kwishyura kwa OpenAI" },
  so: { noKey: "Ma jiro furaha OpenAI — ku dar guddiga.", badKey: "OpenAI wuu diiday furaha — ka hubi guddiga.", noFunds: "Hadhaaga OpenAI kuma filna — buuxi.", rateLimit: "OpenAI wuxuu xaddidayaa codsiyada — sug dhawr ilbiriqsi.", upstream: "OpenAI ma jawaabin — mar kale isku day.", keyLink: "Dejinta OpenAI", fundsLink: "Lacag-bixinta OpenAI" },
  zh: { noKey: "没有 OpenAI 密钥 — 请在控制面板中添加。", badKey: "OpenAI 拒绝了该密钥 — 请在控制面板中检查。", noFunds: "OpenAI 余额不足 — 请充值。", rateLimit: "OpenAI 正在限制请求 — 请稍等几秒。", upstream: "OpenAI 没有响应 — 请重试。", keyLink: "OpenAI 设置", fundsLink: "OpenAI 账单" },
  ja: { noKey: "OpenAI キーがありません — 管理パネルで追加してください。", badKey: "OpenAI がキーを拒否しました — 管理パネルで確認してください。", noFunds: "OpenAI の残高が不足しています — チャージしてください。", rateLimit: "OpenAI がリクエストを制限しています — 数秒お待ちください。", upstream: "OpenAI が応答しませんでした — もう一度お試しください。", keyLink: "OpenAI の設定", fundsLink: "OpenAI の請求" },
  ko: { noKey: "OpenAI 키가 없습니다 — 관리 패널에서 추가하세요.", badKey: "OpenAI가 키를 거부했습니다 — 관리 패널에서 확인하세요.", noFunds: "OpenAI 잔액이 부족합니다 — 충전하세요.", rateLimit: "OpenAI가 요청을 제한하고 있습니다 — 몇 초 기다리세요.", upstream: "OpenAI가 응답하지 않았습니다 — 다시 시도하세요.", keyLink: "OpenAI 설정", fundsLink: "OpenAI 결제" },
  hi: { noKey: "OpenAI कुंजी नहीं है — इसे कंट्रोल पैनल में जोड़ें।", badKey: "OpenAI ने कुंजी अस्वीकार की — इसे कंट्रोल पैनल में जाँचें।", noFunds: "OpenAI बैलेंस पर्याप्त नहीं — इसे भरें।", rateLimit: "OpenAI अनुरोध सीमित कर रहा है — कुछ सेकंड प्रतीक्षा करें।", upstream: "OpenAI ने उत्तर नहीं दिया — फिर से प्रयास करें।", keyLink: "OpenAI सेटिंग्स", fundsLink: "OpenAI बिलिंग" },
  ur: { noKey: "OpenAI کلید موجود نہیں — اسے کنٹرول پینل میں شامل کریں۔", badKey: "OpenAI نے کلید مسترد کر دی — اسے پینل میں جانچیں۔", noFunds: "OpenAI بیلنس ناکافی ہے — اسے بھریں۔", rateLimit: "OpenAI درخواستیں محدود کر رہا ہے — چند سیکنڈ انتظار کریں۔", upstream: "OpenAI نے جواب نہیں دیا — دوبارہ کوشش کریں۔", keyLink: "OpenAI ترتیبات", fundsLink: "OpenAI بلنگ" },
  bn: { noKey: "OpenAI কী নেই — কন্ট্রোল প্যানেলে যোগ করুন।", badKey: "OpenAI কী প্রত্যাখ্যান করেছে — প্যানেলে যাচাই করুন।", noFunds: "OpenAI ব্যালেন্স যথেষ্ট নয় — রিচার্জ করুন।", rateLimit: "OpenAI অনুরোধ সীমিত করছে — কয়েক সেকেন্ড অপেক্ষা করুন।", upstream: "OpenAI সাড়া দেয়নি — আবার চেষ্টা করুন।", keyLink: "OpenAI সেটিংস", fundsLink: "OpenAI বিলিং" },
  te: { noKey: "OpenAI కీ లేదు — కంట్రోల్ ప్యానెల్‌లో జోడించండి.", badKey: "OpenAI కీని తిరస్కరించింది — ప్యానెల్‌లో తనిఖీ చేయండి.", noFunds: "OpenAI బ్యాలెన్స్ సరిపోదు — రీఛార్జ్ చేయండి.", rateLimit: "OpenAI అభ్యర్థనలను పరిమితం చేస్తోంది — కొన్ని సెకన్లు వేచి ఉండండి.", upstream: "OpenAI స్పందించలేదు — మళ్లీ ప్రయత్నించండి.", keyLink: "OpenAI సెట్టింగ్‌లు", fundsLink: "OpenAI బిల్లింగ్" },
  mr: { noKey: "OpenAI की नाही — ती कंट्रोल पॅनेलमध्ये जोडा.", badKey: "OpenAI ने की नाकारली — पॅनेलमध्ये तपासा.", noFunds: "OpenAI शिल्लक पुरेशी नाही — भरा.", rateLimit: "OpenAI विनंत्या मर्यादित करत आहे — काही सेकंद थांबा.", upstream: "OpenAI ने उत्तर दिले नाही — पुन्हा प्रयत्न करा.", keyLink: "OpenAI सेटिंग्ज", fundsLink: "OpenAI बिलिंग" },
  kn: { noKey: "OpenAI ಕೀ ಇಲ್ಲ — ನಿಯಂತ್ರಣ ಫಲಕದಲ್ಲಿ ಸೇರಿಸಿ.", badKey: "OpenAI ಕೀಯನ್ನು ತಿರಸ್ಕರಿಸಿದೆ — ಫಲಕದಲ್ಲಿ ಪರಿಶೀಲಿಸಿ.", noFunds: "OpenAI ಬಾಕಿ ಸಾಕಾಗಿಲ್ಲ — ತುಂಬಿಸಿ.", rateLimit: "OpenAI ವಿನಂತಿಗಳನ್ನು ಮಿತಿಗೊಳಿಸುತ್ತಿದೆ — ಕೆಲವು ಸೆಕೆಂಡು ಕಾಯಿರಿ.", upstream: "OpenAI ಉತ್ತರಿಸಲಿಲ್ಲ — ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", keyLink: "OpenAI ಸೆಟ್ಟಿಂಗ್‌ಗಳು", fundsLink: "OpenAI ಬಿಲ್ಲಿಂಗ್" },
  gu: { noKey: "OpenAI કી નથી — તેને કંટ્રોલ પેનલમાં ઉમેરો.", badKey: "OpenAI એ કી નકારી — પેનલમાં તપાસો.", noFunds: "OpenAI બેલેન્સ પૂરતું નથી — ભરો.", rateLimit: "OpenAI વિનંતીઓ મર્યાદિત કરે છે — થોડી સેકંડ રાહ જુઓ.", upstream: "OpenAI એ જવાબ આપ્યો નથી — ફરી પ્રયાસ કરો.", keyLink: "OpenAI સેટિંગ્સ", fundsLink: "OpenAI બિલિંગ" },
  ml: { noKey: "OpenAI കീ ഇല്ല — കൺട്രോൾ പാനലിൽ ചേർക്കുക.", badKey: "OpenAI കീ നിരസിച്ചു — പാനലിൽ പരിശോധിക്കുക.", noFunds: "OpenAI ബാലൻസ് മതിയാകുന്നില്ല — റീചാർജ് ചെയ്യുക.", rateLimit: "OpenAI അഭ്യർത്ഥനകൾ പരിമിതപ്പെടുത്തുന്നു — കുറച്ച് സെക്കൻഡ് കാത്തിരിക്കുക.", upstream: "OpenAI പ്രതികരിച്ചില്ല — വീണ്ടും ശ്രമിക്കുക.", keyLink: "OpenAI ക്രമീകരണങ്ങൾ", fundsLink: "OpenAI ബില്ലിംഗ്" },
  ta: { noKey: "OpenAI விசை இல்லை — கட்டுப்பாட்டு பலகத்தில் சேர்க்கவும்.", badKey: "OpenAI விசையை நிராகரித்தது — பலகத்தில் சரிபார்க்கவும்.", noFunds: "OpenAI இருப்பு போதவில்லை — நிரப்பவும்.", rateLimit: "OpenAI கோரிக்கைகளை வரம்பிடுகிறது — சில வினாடிகள் காத்திருங்கள்.", upstream: "OpenAI பதிலளிக்கவில்லை — மீண்டும் முயலவும்.", keyLink: "OpenAI அமைப்புகள்", fundsLink: "OpenAI கட்டணம்" },
  ne: { noKey: "OpenAI कुञ्जी छैन — नियन्त्रण प्यानलमा थप्नुहोस्।", badKey: "OpenAI ले कुञ्जी अस्वीकार गर्‍यो — प्यानलमा जाँच्नुहोस्।", noFunds: "OpenAI ब्यालेन्स अपुग — पुनः भर्नुहोस्।", rateLimit: "OpenAI अनुरोध सीमित गर्दैछ — केही सेकेन्ड पर्खनुहोस्।", upstream: "OpenAI ले जवाफ दिएन — फेरि प्रयास गर्नुहोस्।", keyLink: "OpenAI सेटिङ", fundsLink: "OpenAI बिलिङ" },
  vi: { noKey: "Không có khóa OpenAI — hãy thêm trong bảng điều khiển.", badKey: "OpenAI từ chối khóa — hãy kiểm tra trong bảng điều khiển.", noFunds: "Số dư OpenAI không đủ — hãy nạp thêm.", rateLimit: "OpenAI đang giới hạn yêu cầu — chờ vài giây.", upstream: "OpenAI không phản hồi — hãy thử lại.", keyLink: "Cài đặt OpenAI", fundsLink: "Thanh toán OpenAI" },
  th: { noKey: "ไม่มีคีย์ OpenAI — เพิ่มในแผงควบคุม", badKey: "OpenAI ปฏิเสธคีย์ — ตรวจสอบในแผงควบคุม", noFunds: "ยอดเงิน OpenAI ไม่พอ — เติมเงิน", rateLimit: "OpenAI กำลังจำกัดคำขอ — รอสักครู่", upstream: "OpenAI ไม่ตอบสนอง — ลองอีกครั้ง", keyLink: "การตั้งค่า OpenAI", fundsLink: "การเรียกเก็บเงิน OpenAI" },
  id: { noKey: "Tidak ada kunci OpenAI — tambahkan di panel kontrol.", badKey: "OpenAI menolak kunci — periksa di panel kontrol.", noFunds: "Saldo OpenAI tidak cukup — isi ulang.", rateLimit: "OpenAI membatasi permintaan — tunggu beberapa detik.", upstream: "OpenAI tidak menjawab — coba lagi.", keyLink: "Pengaturan OpenAI", fundsLink: "Penagihan OpenAI" },
  ms: { noKey: "Tiada kunci OpenAI — tambahkannya di panel kawalan.", badKey: "OpenAI menolak kunci — semak di panel kawalan.", noFunds: "Baki OpenAI tidak mencukupi — tambah nilai.", rateLimit: "OpenAI mengehadkan permintaan — tunggu beberapa saat.", upstream: "OpenAI tidak menjawab — cuba lagi.", keyLink: "Tetapan OpenAI", fundsLink: "Pengebilan OpenAI" },
  tl: { noKey: "Walang OpenAI key — idagdag ito sa control panel.", badKey: "Tinanggihan ng OpenAI ang key — suriin ito sa control panel.", noFunds: "Kulang ang balanse sa OpenAI — mag-load muli.", rateLimit: "Nililimitahan ng OpenAI ang mga kahilingan — maghintay ng ilang segundo.", upstream: "Hindi sumagot ang OpenAI — subukan muli.", keyLink: "Mga setting ng OpenAI", fundsLink: "Pagsingil ng OpenAI" },
  my: { noKey: "OpenAI ကီး မရှိပါ — ထိန်းချုပ်မှုပန်နယ်တွင် ထည့်ပါ။", badKey: "OpenAI က ကီးကို ငြင်းပယ်ခဲ့သည် — ပန်နယ်တွင် စစ်ဆေးပါ။", noFunds: "OpenAI လက်ကျန်ငွေ မလုံလောက်ပါ — ဖြည့်ပါ။", rateLimit: "OpenAI က တောင်းဆိုမှုများကို ကန့်သတ်နေသည် — စက္ကန့်အနည်းငယ် စောင့်ပါ။", upstream: "OpenAI က မဖြေကြားပါ — ထပ်စမ်းကြည့်ပါ။", keyLink: "OpenAI ဆက်တင်များ", fundsLink: "OpenAI ငွေတောင်းခံမှု" },
  km: { noKey: "គ្មានសោ OpenAI — បន្ថែមវានៅក្នុងផ្ទាំងបញ្ជា។", badKey: "OpenAI បានបដិសេធសោ — ពិនិត្យវានៅក្នុងផ្ទាំងបញ្ជា។", noFunds: "សមតុល្យ OpenAI មិនគ្រប់គ្រាន់ — សូមបញ្ចូលទឹកប្រាក់។", rateLimit: "OpenAI កំពុងកំណត់សំណើ — សូមរង់ចាំពីរបីវិនាទី។", upstream: "OpenAI មិនបានឆ្លើយតប — សូមព្យាយាមម្តងទៀត។", keyLink: "ការកំណត់ OpenAI", fundsLink: "វិក្កយបត្រ OpenAI" },
  lo: { noKey: "ບໍ່ມີກະແຈ OpenAI — ເພີ່ມມັນໃນແຜງຄວບຄຸມ.", badKey: "OpenAI ປະຕິເສດກະແຈ — ກວດສອບໃນແຜງຄວບຄຸມ.", noFunds: "ຍອດເງິນ OpenAI ບໍ່ພຽງພໍ — ເຕີມເງິນ.", rateLimit: "OpenAI ກຳລັງຈຳກັດຄຳຂໍ — ລໍຖ້າສອງສາມວິນາທີ.", upstream: "OpenAI ບໍ່ຕອບ — ລອງໃໝ່.", keyLink: "ການຕັ້ງຄ່າ OpenAI", fundsLink: "ການເອີ້ນເກັບເງິນ OpenAI" },
}

/** Прямая ссылка на баланс — одна на весь продукт. */
export const OPENAI_BILLING_URL = "https://platform.openai.com/settings/organization/billing/overview"

/** Сообщения на языке страницы; неизвестный язык честно падает на английский. */
export function platformErrors(lang: string): PlatformErrors {
  return E[lang] ?? E[lang.slice(0, 2)] ?? E.en
}
