// Слова диалога отказа в доступе — 82 языка (`/code/CLAUDE.md` §4д).
//
// Это единственный экран, на котором человек встретит продукт в самом
// раздражённом состоянии: его не пустили. Объяснение на чужом языке в такую
// минуту читается как безразличие, поэтому здесь полный набор языков, а не
// десять.
//
// 🔒 СЕРВЕРНЫЙ РЕЗОЛВ — как и у остальных словарей: клиентский компонент
// получает строки пропсами, а не импортом.
//
// Языки, кроме английского, переведены моделью 2026-08-11. Подстановка
// `{roles}` сохранена во всех языках — её заменяет перечень требуемых ролей.

export type AccessGateUi = {
  /** Заголовок диалога. */
  title: string
  /** Строка с перечислением ролей; `{roles}` подставляется. */
  needRoles: string
  /** Что делать, если доступ должен быть. */
  haveAccess: string
  /** Что делать, если человек попал сюда случайно. */
  wrongPlace: string
  /** Кнопка «у меня есть доступ» → авторизация. */
  signIn: string
  /** Кнопка «вернуться на главную». */
  goHome: string
  /** Кнопка «отмена» → предыдущая страница. */
  cancel: string
  /** Пока идёт проверка. */
  checking: string
}

const UI: Record<string, AccessGateUi> = {
  en: { title: 'This page is not open to you', needRoles: 'It requires one of these roles: {roles}.', haveAccess: 'If you should have access, sign in — you will come straight back here.', wrongPlace: 'If you landed here by accident, go back or return to the home page.', signIn: 'I have access — sign in', goHome: 'Go to the home page', cancel: 'Cancel', checking: 'Checking access…' },
  fr: { title: 'Cette page ne vous est pas accessible', needRoles: 'Il faut l’un de ces rôles : {roles}.', haveAccess: 'Si vous devez y avoir accès, connectez-vous — vous reviendrez directement ici.', wrongPlace: 'Si vous êtes arrivé ici par erreur, revenez en arrière ou retournez à la page d’accueil.', signIn: 'J’ai accès — me connecter', goHome: 'Aller à la page d’accueil', cancel: 'Annuler', checking: 'Vérification de l’accès…' },
  es: { title: 'No tienes acceso a esta página', needRoles: 'Se requiere uno de estos roles: {roles}.', haveAccess: 'Si deberías tener acceso, inicia sesión: volverás aquí enseguida.', wrongPlace: 'Si llegaste aquí por error, vuelve atrás o regresa a la página de inicio.', signIn: 'Tengo acceso — Iniciar sesión', goHome: 'Ir a la página de inicio', cancel: 'Cancelar', checking: 'Comprobando acceso…' },
  pt: { title: 'Esta página não está disponível para si', needRoles: 'Requer uma destas funções: {roles}.', haveAccess: 'Se deveria ter acesso, inicie sessão — voltará diretamente aqui.', wrongPlace: 'Se chegou aqui por engano, volte ou regresse à página inicial.', signIn: 'Tenho acesso — iniciar sessão', goHome: 'Ir para a página inicial', cancel: 'Cancelar', checking: 'A verificar o acesso…' },
  de: { title: 'Kein Zugriff auf diese Seite', needRoles: 'Du brauchst eine dieser Rollen: {roles}.', haveAccess: 'Solltest du Zugriff haben, melde dich an — du kommst direkt hierher zurück.', wrongPlace: 'Wenn du versehentlich hier gelandet bist, geh zurück oder kehre zur Startseite zurück.', signIn: 'Ich habe Zugriff — anmelden', goHome: 'Zur Startseite', cancel: 'Abbrechen', checking: 'Zugriff wird geprüft…' },
  it: { title: 'Non puoi accedere a questa pagina', needRoles: 'Richiede uno di questi ruoli: {roles}.', haveAccess: 'Se dovessi avere accesso, accedi — tornerai subito qui.', wrongPlace: 'Se sei arrivato qui per errore, torna indietro o torna alla home page.', signIn: 'Ho accesso — accedi', goHome: 'Vai alla home page', cancel: 'Annulla', checking: 'Verifica dell’accesso…' },
  nl: { title: 'Je hebt geen toegang tot deze pagina', needRoles: 'Je hebt een van deze rollen nodig: {roles}.', haveAccess: 'Als je toegang zou moeten hebben, meld je dan aan — je komt direct terug op deze pagina.', wrongPlace: 'Ben je hier per ongeluk terechtgekomen? Ga terug of ga naar de startpagina.', signIn: 'Ik heb toegang — inloggen', goHome: 'Ga naar de startpagina', cancel: 'Annuleren', checking: 'Toegang controleren…' },
  sv: { title: 'Du har inte åtkomst till den här sidan', needRoles: 'Det krävs en av följande roller: {roles}.', haveAccess: 'Om du borde ha åtkomst, logga in — du kommer direkt tillbaka hit.', wrongPlace: 'Om du hamnade här av misstag, gå tillbaka eller gå till startsidan.', signIn: 'Jag har åtkomst — logga in', goHome: 'Gå till startsidan', cancel: 'Avbryt', checking: 'Kontrollerar åtkomst…' },
  no: { title: 'Du har ikke tilgang til denne siden', needRoles: 'Krever en av disse rollene: {roles}.', haveAccess: 'Hvis du skal ha tilgang, logg inn — du kommer rett tilbake hit.', wrongPlace: 'Hvis du havnet her ved en feil, gå tilbake eller gå til startsiden.', signIn: 'Jeg har tilgang — logg inn', goHome: 'Gå til startsiden', cancel: 'Avbryt', checking: 'Sjekker tilgang…' },
  da: { title: 'Denne side er ikke tilgængelig for dig', needRoles: 'Det kræver en af disse roller: {roles}.', haveAccess: 'Hvis du har adgang, så log ind — du kommer direkte tilbage hertil.', wrongPlace: 'Hvis du er landet her ved en fejl, gå tilbage eller gå til forsiden.', signIn: 'Jeg har adgang — log ind', goHome: 'Gå til forsiden', cancel: 'Annuller', checking: 'Kontrollerer adgang…' },
  fi: { title: 'Sinulla ei ole pääsyä tälle sivulle', needRoles: 'Tarvitset jonkin näistä rooleista: {roles}.', haveAccess: 'Jos sinulla pitäisi olla pääsy, kirjaudu sisään — palaat suoraan tänne.', wrongPlace: 'Jos päädyit tänne vahingossa, palaa takaisin tai siirry etusivulle.', signIn: 'Minulla on pääsy — kirjaudu sisään', goHome: 'Siirry etusivulle', cancel: 'Peruuta', checking: 'Tarkistetaan pääsyä…' },
  is: { title: 'Þú hefur ekki aðgang að þessari síðu', needRoles: 'Þú þarft eitt af þessum hlutverkum: {roles}.', haveAccess: 'Ef þú átt að hafa aðgang, skráðu þig inn — þú kemur beint hingað aftur.', wrongPlace: 'Ef þú lendir hér fyrir mistök, farðu til baka eða á forsíðuna.', signIn: 'Ég hef aðgang — skrá mig inn', goHome: 'Fara á forsíðuna', cancel: 'Hætta við', checking: 'Athuga aðgang…' },
  el: { title: 'Δεν έχετε πρόσβαση σε αυτή τη σελίδα', needRoles: 'Απαιτεί έναν από αυτούς τους ρόλους: {roles}.', haveAccess: 'Αν δικαιούστε πρόσβαση, συνδεθείτε — θα επιστρέψετε αμέσως εδώ.', wrongPlace: 'Αν βρεθήκατε εδώ κατά λάθος, γυρίστε πίσω ή επιστρέψτε στην αρχική σελίδα.', signIn: 'Έχω πρόσβαση — σύνδεση', goHome: 'Μετάβαση στην αρχική σελίδα', cancel: 'Άκυρο', checking: 'Έλεγχος πρόσβασης…' },
  pl: { title: 'Brak dostępu do tej strony', needRoles: 'Wymagana jest jedna z tych ról: {roles}.', haveAccess: 'Jeśli przysługuje ci dostęp, zaloguj się — wrócisz prosto tutaj.', wrongPlace: 'Jeśli jesteś tu przez pomyłkę, wróć lub przejdź na stronę główną.', signIn: 'Mam dostęp — zaloguj się', goHome: 'Przejdź do strony głównej', cancel: 'Anuluj', checking: 'Sprawdzanie dostępu…' },
  cs: { title: 'Na tuto stránku nemáte přístup', needRoles: 'Vyžaduje jednu z těchto rolí: {roles}.', haveAccess: 'Pokud máte mít přístup, přihlaste se — vrátíte se rovnou sem.', wrongPlace: 'Pokud jste se sem dostali omylem, vraťte se nebo přejděte na domovskou stránku.', signIn: 'Mám přístup — přihlásit se', goHome: 'Přejít na domovskou stránku', cancel: 'Zrušit', checking: 'Ověřujeme přístup…' },
  sk: { title: 'Nemáte prístup k tejto stránke', needRoles: 'Vyžaduje niektorú z týchto rolí: {roles}.', haveAccess: 'Ak by ste mali mať prístup, prihláste sa — hneď sa vrátite sem.', wrongPlace: 'Ak ste sa sem dostali omylom, vráťte sa alebo prejdite na domovskú stránku.', signIn: 'Mám prístup — prihlásiť sa', goHome: 'Prejsť na domovskú stránku', cancel: 'Zrušiť', checking: 'Kontrolujeme prístup…' },
  hu: { title: 'Nincs hozzáférésed ehhez az oldalhoz', needRoles: 'Ehhez az alábbi szerepkörök egyikére van szükség: {roles}.', haveAccess: 'Ha jogosult vagy, jelentkezz be — azonnal visszakerülsz ide.', wrongPlace: 'Ha véletlenül kerültél ide, lépj vissza, vagy menj a kezdőlapra.', signIn: 'Van hozzáférésem — bejelentkezem', goHome: 'Ugrás a kezdőlapra', cancel: 'Mégse', checking: 'Hozzáférés ellenőrzése…' },
  ro: { title: 'Nu ai acces la această pagină', needRoles: 'Necesită unul dintre aceste roluri: {roles}.', haveAccess: 'Dacă ar trebui să ai acces, autentifică-te — vei reveni direct aici.', wrongPlace: 'Dacă ai ajuns aici din greșeală, mergi înapoi sau revino la pagina principală.', signIn: 'Am acces — autentifică-mă', goHome: 'Mergi la pagina principală', cancel: 'Anulează', checking: 'Se verifică accesul…' },
  hr: { title: 'Ova stranica vam nije dostupna', needRoles: 'Potrebna je jedna od ovih uloga: {roles}.', haveAccess: 'Ako biste trebali imati pristup, prijavite se — odmah ćete se vratiti ovamo.', wrongPlace: 'Ako ste ovdje slučajno, vratite se ili idite na početnu stranicu.', signIn: 'Imam pristup — prijavite se', goHome: 'Idite na početnu stranicu', cancel: 'Odustanite', checking: 'Provjera pristupa…' },
  sl: { title: 'Do te strani nimate dostopa.', needRoles: 'Potrebna je ena od teh vlog: {roles}.', haveAccess: 'Če bi morali imeti dostop, se prijavite — takoj se boste vrnili sem.', wrongPlace: 'Če ste sem prišli po pomoti, pojdite nazaj ali se vrnite na domačo stran.', signIn: 'Imam dostop — prijavite se', goHome: 'Na domačo stran', cancel: 'Prekliči', checking: 'Preverjanje dostopa…' },
  et: { title: 'See leht pole teile avatud', needRoles: 'Vajalik on üks neist rollidest: {roles}.', haveAccess: 'Kui teil peaks olema juurdepääs, logige sisse — teid suunatakse kohe siia tagasi.', wrongPlace: 'Kui sattusite siia kogemata, minge tagasi või naaske avalehele.', signIn: 'Mul on juurdepääs — logi sisse', goHome: 'Mine avalehele', cancel: 'Tühista', checking: 'Kontrollin juurdepääsu…' },
  lv: { title: 'Šī lapa jums nav pieejama', needRoles: 'Nepieciešama viena no šīm lomām: {roles}.', haveAccess: 'Ja jums pienākas piekļuve, pierakstieties — uzreiz atgriezīsieties šeit.', wrongPlace: 'Ja šeit nonācāt nejauši, dodieties atpakaļ vai atgriezieties sākumlapā.', signIn: 'Man ir piekļuve — pierakstīties', goHome: 'Doties uz sākumlapu', cancel: 'Atcelt', checking: 'Pārbauda piekļuvi…' },
  lt: { title: 'Šis puslapis jums neprieinamas', needRoles: 'Reikalinga viena iš šių rolių: {roles}.', haveAccess: 'Jei manote, kad turite prieigą, prisijunkite — grįšite tiesiai čia.', wrongPlace: 'Jei čia patekote netyčia, grįžkite atgal arba eikite į pagrindinį puslapį.', signIn: 'Turiu prieigą — prisijungti', goHome: 'Eiti į pagrindinį puslapį', cancel: 'Atšaukti', checking: 'Tikrinama prieiga…' },
  mt: { title: 'Din il-paġna mhix miftuħa għalik', needRoles: 'Teħtieġ waħda minn dawn ir-rwoli: {roles}.', haveAccess: 'Jekk suppost għandek aċċess, idħol — terġa’ lura hawn mill-ewwel.', wrongPlace: 'Jekk spiċċajt hawn bi żball, mur lura jew erġa’ lura lejn il-paġna ewlenija.', signIn: 'Għandi aċċess — idħol', goHome: 'Mur fil-paġna ewlenija', cancel: 'Ikkanċella', checking: 'Qed nivverifikaw l-aċċess…' },
  ca: { title: 'No tens accés a aquesta pàgina', needRoles: 'Cal un d’aquests rols: {roles}.', haveAccess: 'Si hi has de tenir accés, inicia sessió — tornaràs directament aquí.', wrongPlace: 'Si has arribat aquí per error, torna enrere o ves a la pàgina d’inici.', signIn: 'Tinc accés — inicia sessió', goHome: 'Vés a la pàgina d’inici', cancel: 'Cancel·la', checking: 'Comprovant l’accés…' },
  gl: { title: 'Non tes acceso a esta páxina', needRoles: 'Precisas un destes roles: {roles}.', haveAccess: 'Se deberías ter acceso, inicia sesión — volverás directamente aquí.', wrongPlace: 'Se chegaches aquí por erro, volve atrás ou vai á páxina de inicio.', signIn: 'Teño acceso — iniciar sesión', goHome: 'Ir á páxina de inicio', cancel: 'Cancelar', checking: 'Comprobando o acceso…' },
  cy: { title: 'Nid yw’r dudalen hon ar gael i chi', needRoles: 'Mae’n gofyn am un o’r rolau hyn: {roles}.', haveAccess: 'Os dylai fod gennych fynediad, mewngofnodwch — byddwch yn dod yn ôl yma ar unwaith.', wrongPlace: 'Os daethoch yma ar ddamwain, ewch yn ôl neu ewch i’r hafan.', signIn: 'Mae gen i fynediad — mewngofnodwch', goHome: 'Ewch i’r hafan', cancel: 'Canslo', checking: 'Wrthi’n gwirio mynediad…' },
  ga: { title: 'Níl rochtain agat ar an leathanach seo', needRoles: 'Tá ceann de na róil seo de dhíth: {roles}.', haveAccess: 'Má ba chóir go mbeadh rochtain agat, logáil isteach — tabharfar ar ais go díreach anseo thú.', wrongPlace: 'Má tháinig tú anseo de thaisme, téigh siar nó fill ar an leathanach baile.', signIn: 'Tá rochtain agam — logáil isteach', goHome: 'Téigh go dtí an leathanach baile', cancel: 'Cealaigh', checking: 'Rochtain á seiceáil…' },
  eu: { title: 'Ez duzu orri honetarako sarbiderik', needRoles: 'Honako rol hauetako bat behar da: {roles}.', haveAccess: 'Sarbidea baduzula uste baduzu, hasi saioa — berehala itzuliko zara hona.', wrongPlace: 'Hona ustekabean iritsi bazara, itzuli atzera edo joan hasierako orrira.', signIn: 'Sarbidea dut — hasi saioa', goHome: 'Joan hasierako orrira', cancel: 'Ezeztatu', checking: 'Sarbidea egiaztatzen…' },
  ru: { title: 'Эта страница вам недоступна', needRoles: 'Требуется одна из этих ролей: {roles}.', haveAccess: 'Если считаете, что у вас есть доступ, войдите — вы сразу вернётесь сюда.', wrongPlace: 'Если вы попали сюда случайно, вернитесь назад или перейдите на главную страницу.', signIn: 'У меня есть доступ — войти', goHome: 'На главную', cancel: 'Отмена', checking: 'Проверяем доступ…' },
  uk: { title: 'Ця сторінка вам недоступна', needRoles: 'Потрібна одна з цих ролей: {roles}.', haveAccess: 'Якщо у вас має бути доступ, увійдіть — ви одразу повернетеся сюди.', wrongPlace: 'Якщо ви потрапили сюди випадково, поверніться назад або на головну сторінку.', signIn: 'Маю доступ — увійти', goHome: 'Перейти на головну', cancel: 'Скасувати', checking: 'Перевірка доступу…' },
  be: { title: 'Гэтая старонка вам недаступная', needRoles: 'Патрабуецца адна з гэтых роляў: {roles}.', haveAccess: 'Калі ў вас павінен быць доступ, увайдзіце — вы адразу вернецеся сюды.', wrongPlace: 'Калі вы трапілі сюды выпадкова, вярніцеся назад або на галоўную старонку.', signIn: 'У мяне ёсць доступ — увайсці', goHome: 'Перайсці на галоўную старонку', cancel: 'Адмяніць', checking: 'Правяраем доступ…' },
  bg: { title: 'Нямате достъп до тази страница', needRoles: 'Изисква една от следните роли: {roles}.', haveAccess: 'Ако смятате, че трябва да имате достъп, влезте — ще се върнете направо тук.', wrongPlace: 'Ако сте попаднали тук по погрешка, върнете се назад или отидете на началната страница.', signIn: 'Имам достъп — Вход', goHome: 'Към началната страница', cancel: 'Отказ', checking: 'Проверка на достъпа…' },
  sr: { title: 'Ova stranica ti nije dostupna', needRoles: 'Potrebna je jedna od ovih uloga: {roles}.', haveAccess: 'Ako treba da imaš pristup, prijavi se — odmah se vraćaš ovde.', wrongPlace: 'Ako si ovde greškom, vrati se ili idi na početnu stranicu.', signIn: 'Imam pristup — prijavi se', goHome: 'Idi na početnu stranicu', cancel: 'Otkaži', checking: 'Provera pristupa…' },
  bs: { title: 'Ova stranica vam nije dostupna', needRoles: 'Potrebna je jedna od ovih uloga: {roles}.', haveAccess: 'Ako biste trebali imati pristup, prijavite se — odmah ćete se vratiti ovdje.', wrongPlace: 'Ako ste ovdje slučajno, vratite se ili idite na početnu stranicu.', signIn: 'Imam pristup — prijavite se', goHome: 'Idite na početnu stranicu', cancel: 'Otkaži', checking: 'Provjera pristupa…' },
  mk: { title: 'Оваа страница не ви е достапна', needRoles: 'Потребна е една од овие улоги: {roles}.', haveAccess: 'Ако треба да имате пристап, најавете се — ќе се вратите директно овде.', wrongPlace: 'Ако сте тука по грешка, вратете се назад или одете на почетната страница.', signIn: 'Имам пристап — најавете се', goHome: 'Одете на почетната страница', cancel: 'Откажи', checking: 'Проверуваме пристап…' },
  sq: { title: 'Nuk keni qasje në këtë faqe', needRoles: 'Kërkon një nga këto role: {roles}.', haveAccess: 'Nëse duhet të keni qasje, hyni — do të ktheheni menjëherë këtu.', wrongPlace: 'Nëse keni ardhur këtu gabimisht, kthehuni mbrapa ose shkoni te faqja kryesore.', signIn: 'Kam qasje — hyni', goHome: 'Shkoni te faqja kryesore', cancel: 'Anulo', checking: 'Po kontrollohet qasja…' },
  kk: { title: 'Бұл бет сізге қолжетімді емес', needRoles: 'Осы рөлдердің біреуі қажет: {roles}.', haveAccess: 'Егер сізде рұқсат болуы керек болса, кіріңіз — бірден осында қайта ораласыз.', wrongPlace: 'Кездейсоқ осында түсіп қалсаңыз, артқа қайтыңыз немесе басты бетке өтіңіз.', signIn: 'Менде рұқсат бар — кіру', goHome: 'Басты бетке өту', cancel: 'Бас тарту', checking: 'Рұқсат тексерілуде…' },
  uz: { title: 'Bu sahifa sizga ochiq emas', needRoles: 'Quyidagi rollardan biri kerak: {roles}.', haveAccess: 'Agar sizda kirish bo‘lsa, tizimga kiring — darhol shu yerga qaytasiz.', wrongPlace: 'Agar bu yerga tasodifan tushib qolsangiz, ortga qayting yoki bosh sahifaga o‘ting.', signIn: 'Menda kirish bor — tizimga kirish', goHome: 'Bosh sahifaga o‘tish', cancel: 'Bekor qilish', checking: 'Kirish tekshirilmoqda…' },
  ky: { title: 'Бул бет сизге ачык эмес', needRoles: 'Бул ролдордун бирөөсү талап кылынат: {roles}.', haveAccess: 'Эгер сизде кирүү укугу болушу керек болсо, системага кириңиз — түз эле ушул бетке кайтып келесиз.', wrongPlace: 'Кокусунан бул бетке келип калсаңыз, артка кайтыңыз же башкы бетке өтүңүз.', signIn: 'Менде укук бар — системага кирүү', goHome: 'Башкы бетке өтүү', cancel: 'Болтурбоо', checking: 'Кирүү укугу текшерилүүдө…' },
  tg: { title: 'Ин саҳифа барои шумо дастрас нест', needRoles: 'Яке аз ин нақшҳо лозим аст: {roles}.', haveAccess: 'Агар дастрасӣ доред, ворид шавед — бевосита ба ин ҷо бармегардед.', wrongPlace: 'Агар ба ин ҷо тасодуфан омадед, ба қафо баргардед ё ба саҳифаи асосӣ равед.', signIn: 'Дастрасӣ дорам — ворид шавам', goHome: 'Ба саҳифаи асосӣ равед', cancel: 'Бекор', checking: 'Санҷиши дастрасӣ…' },
  tk: { title: 'Bu sahypa size açyk däl', needRoles: 'Şu rollardan birini talap edýär: {roles}.', haveAccess: 'Giriş hukugyňyz bar bolsa, giriň — göni bu ýere dolanarsyňyz.', wrongPlace: 'Tötänlikden şu ýere düşen bolsaňyz, yza gaýdyň ýa-da baş sahypa dolanyň.', signIn: 'Mende giriş hukugy bar — giriň', goHome: 'Baş sahypa geçiň', cancel: 'Ýatyr', checking: 'Giriş barlanýar…' },
  az: { title: 'Bu səhifə sizə açıq deyil', needRoles: 'Bu rollardan biri tələb olunur: {roles}.', haveAccess: 'Əgər giriş hüququnuz varsa, daxil olun — birbaşa buraya qayıdacaqsınız.', wrongPlace: 'Təsadüfən bura düşmüsünüzsə, geri qayıdın və ya ana səhifəyə dönün.', signIn: 'Girişim var — daxil olun', goHome: 'Ana səhifəyə keçin', cancel: 'Ləğv edin', checking: 'Giriş yoxlanılır…' },
  hy: { title: 'Այս էջը ձեզ համար հասանելի չէ', needRoles: 'Պահանջվում է այս դերերից մեկը՝ {roles}։', haveAccess: 'Եթե պետք է մուտք ունեք, մուտք գործեք — անմիջապես կվերադառնաք այստեղ։', wrongPlace: 'Եթե պատահմամբ այստեղ եք հայտնվել, վերադարձեք նախորդ էջ կամ անցեք գլխավոր էջ։', signIn: 'Մուտք ունեմ — մուտք գործել', goHome: 'Անցնել գլխավոր էջ', cancel: 'Չեղարկել', checking: 'Մուտքի ստուգում…' },
  ka: { title: 'ამ გვერდზე წვდომა არ გაქვთ', needRoles: 'საჭიროა ამ როლებიდან ერთ-ერთი: {roles}.', haveAccess: 'თუ უნდა გქონდეთ წვდომა, შედით — მაშინვე აქ დაბრუნდებით.', wrongPlace: 'თუ აქ შემთხვევით მოხვდით, დაბრუნდით უკან ან გადადით მთავარ გვერდზე.', signIn: 'მაქვს წვდომა — შესვლა', goHome: 'მთავარ გვერდზე გადასვლა', cancel: 'გაუქმება', checking: 'წვდომის შემოწმება…' },
  mn: { title: 'Энэ хуудас танд нээлттэй биш', needRoles: 'Дараах эрхийн аль нэг шаардлагатай: {roles}.', haveAccess: 'Танд эрх байх ёстой бол нэвтэрнэ үү — шууд буцаад энд ирнэ.', wrongPlace: 'Санаандгүй энд орсон бол буцна уу, эсвэл нүүр хуудас руу очно уу.', signIn: 'Надад эрх бий — нэвтрэх', goHome: 'Нүүр хуудас руу очих', cancel: 'Цуцлах', checking: 'Эрхийг шалгаж байна…' },
  ar: { title: 'هذه الصفحة غير متاحة لك', needRoles: 'يتطلب الوصول أحد هذه الأدوار: {roles}.', haveAccess: 'إن كان من المفترض أن تملك صلاحية الوصول، سجّل الدخول — ستعود مباشرةً إلى هنا.', wrongPlace: 'إن وصلت إلى هنا عن طريق الخطأ، ارجع أو عد إلى الصفحة الرئيسية.', signIn: 'لديّ صلاحية الوصول — سجّل الدخول', goHome: 'الانتقال إلى الصفحة الرئيسية', cancel: 'إلغاء', checking: 'جارٍ التحقق من صلاحية الوصول…' },
  tr: { title: 'Bu sayfa size açık değil', needRoles: 'Şu rollerden birini gerektirir: {roles}.', haveAccess: 'Erişiminiz olması gerekiyorsa oturum açın — doğrudan buraya döneceksiniz.', wrongPlace: 'Buraya yanlışlıkla geldiyseniz, geri gidin veya ana sayfaya dönün.', signIn: 'Erişimim var — oturum aç', goHome: 'Ana sayfaya git', cancel: 'İptal', checking: 'Erişim kontrol ediliyor…' },
  he: { title: 'אין לכם גישה לדף הזה', needRoles: 'נדרש אחד מהתפקידים הבאים: {roles}.', haveAccess: 'אם אמורה להיות לכם גישה, התחברו — תחזרו לכאן מיד.', wrongPlace: 'אם הגעתם לכאן בטעות, חזרו אחורה או עברו לדף הבית.', signIn: 'יש לי גישה — התחברות', goHome: 'לדף הבית', cancel: 'ביטול', checking: 'בודקים גישה…' },
  fa: { title: 'این صفحه برای شما در دسترس نیست', needRoles: 'به یکی از این نقش‌ها نیاز دارید: {roles}.', haveAccess: 'اگر باید دسترسی داشته باشید، وارد شوید — مستقیماً به همین‌جا برمی‌گردید.', wrongPlace: 'اگر تصادفی به اینجا آمده‌اید، برگردید یا به صفحهٔ اصلی بروید.', signIn: 'دسترسی دارم — ورود', goHome: 'رفتن به صفحهٔ اصلی', cancel: 'انصراف', checking: 'در حال بررسی دسترسی…' },
  ku: { title: 'Ev rûpel ji te re vekirî nîne', needRoles: 'Pêdivî ye yek ji van rolan hebe: {roles}.', haveAccess: 'Heke divê te gihîştin hebe, têkeve — dê vegerî vir.', wrongPlace: 'Heke bi xeletî hatî vir, vegere an herê rûpela sereke.', signIn: 'Gihîştina min heye — têkeve', goHome: 'Here rûpela sereke', cancel: 'Betal bike', checking: 'Piştrastkirina gihîştinê…' },
  af: { title: 'Hierdie bladsy is nie vir jou oop nie', needRoles: 'Dit vereis een van hierdie rolle: {roles}.', haveAccess: 'As jy toegang behoort te hê, meld aan — jy kom dadelik weer hierheen.', wrongPlace: 'As jy per ongeluk hier beland het, gaan terug of gaan na die tuisblad.', signIn: 'Ek het toegang — meld aan', goHome: 'Gaan na die tuisblad', cancel: 'Kanselleer', checking: 'Kontroleer toegang…' },
  sw: { title: 'Huna ruhusa kufikia ukurasa huu', needRoles: 'Inahitaji moja ya majukumu haya: {roles}.', haveAccess: 'Ikiwa unapaswa kuwa na ruhusa, ingia — utarudishwa moja kwa moja hapa.', wrongPlace: 'Ikiwa umefika hapa kimakosa, rudi nyuma au nenda kwenye ukurasa wa nyumbani.', signIn: 'Nina ruhusa — ingia', goHome: 'Nenda kwenye ukurasa wa nyumbani', cancel: 'Ghairi', checking: 'Inakagua ruhusa…' },
  ha: { title: 'Ba ka da izini ga wannan shafi', needRoles: 'Ana buƙatar ɗaya daga cikin waɗannan matsayi: {roles}.', haveAccess: 'Idan ya kamata ka sami izini, shiga — za a dawo da kai nan kai tsaye.', wrongPlace: 'Idan ka zo nan ba da gangan ba, koma baya ko koma shafin farko.', signIn: 'Ina da izini — shiga', goHome: 'Je shafin farko', cancel: 'Soke', checking: 'Ana duba izini…' },
  yo: { title: 'Ojú-ìwé yìí kò ṣí fún ọ', needRoles: 'Ó nílò ọ̀kan nínú àwọn ìpò wọ̀nyí: {roles}.', haveAccess: 'Bí o bá yẹ kí o ní ìwọlé, buwọlé — ìwọ yóò padà síbí lẹ́sẹ̀kẹsẹ̀.', wrongPlace: 'Bí o bá dé síbí ní aṣìṣe, padà sẹ́yìn tàbí lọ sí ojú-ìwé ilé.', signIn: 'Mo ní ìwọlé — buwọlé', goHome: 'Lọ sí ojú-ìwé ilé', cancel: 'Fagilé', checking: 'Ṣàyẹ̀wò ìwọlé…' },
  ig: { title: 'Ibe a emegheghị maka gị', needRoles: 'Ọ na-achọ otu n’ime ọkwa ndị a: {roles}.', haveAccess: 'Ọ bụrụ na ị kwesịrị inwe ohere, banye — ị ga-alaghachi ebe a ozugbo.', wrongPlace: 'Ọ bụrụ na ị rutere ebe a n’emehie, laghachi azụ ma ọ bụ lọta na ibe ụlọ.', signIn: 'Enwere m ohere — banye', goHome: 'Gaa na ibe ụlọ', cancel: 'Kagbuo', checking: 'Na-enyocha ohere…' },
  am: { title: 'ይህ ገጽ ለእርስዎ ክፍት አይደለም', needRoles: 'ከእነዚህ ሚናዎች አንዱ ያስፈልጋል: {roles}.', haveAccess: 'መዳረሻ ካለዎት ይግቡ — በቀጥታ ወደዚህ ይመለሳሉ.', wrongPlace: 'በስህተት እዚህ ካደረሱ ከሆነ ወደኋላ ይመለሱ ወይም ወደ መነሻ ገጽ ይመለሱ.', signIn: 'መዳረሻ አለኝ — ይግቡ', goHome: 'ወደ መነሻ ገጽ ይሂዱ', cancel: 'ይቋረጡ', checking: 'መዳረሻን በመፈተሽ ላይ…' },
  zu: { title: 'Leli khasi alivunyelwe kuwe', needRoles: 'Kudingeka eyodwa yalezi zindima: {roles}.', haveAccess: 'Uma kufanele ube nokufinyelela, ngena — uzobuyela lapha ngqo.', wrongPlace: 'Uma ufike lapha ngephutha, buyela emuva noma ubuyele ekhasini lasekhaya.', signIn: 'Nginokufinyelela — ngena', goHome: 'Iya ekhasini lasekhaya', cancel: 'Hoxisa', checking: 'Kuhlolwa ukufinyelela…' },
  xh: { title: 'Eli khasi alivulelekanga kuwe', needRoles: 'Kufuneka ube nenye yezi ndima: {roles}.', haveAccess: 'Ukuba umele ube nokufikelela, ngena — uya kubuya ngqo apha.', wrongPlace: 'Ukuba ufike apha ngempazamo, buyela umva okanye ubuyele kwikhasi lasekhaya.', signIn: 'Ndinofikelelo — ngena', goHome: 'Yiya kwikhasi lasekhaya', cancel: 'Rhoxisa', checking: 'Kujongwa ukufikelela…' },
  rw: { title: 'Ntikwemerewe kureba iyi paji', needRoles: 'Bisaba imwe muri izi nshingano: {roles}.', haveAccess: 'Niba ukwiriye kugira uburenganzira, injira — uzahita usubizwa hano.', wrongPlace: 'Niba waje hano utabishaka, subira inyuma cyangwa usubire ku ipaji y\'itangiriro.', signIn: 'Mfite uburenganzira — injira', goHome: 'Jya ku ipaji y\'itangiriro', cancel: 'Kureka', checking: 'Iri gusuzuma uburenganzira…' },
  so: { title: 'Boggan kuma furna', needRoles: 'Waxaa looga baahan yahay mid ka mid ah doorarkan: {roles}.', haveAccess: 'Haddii aad haysato gelitaan, soo gal — isla markiiba halkan ayaad ku soo laabanaysaa.', wrongPlace: 'Haddii si kama\' ah halkan u timid, dib u noqo ama ku laabo bogga hore.', signIn: 'Waxaan leeyahay gelitaan — soo gal', goHome: 'Tag bogga hore', cancel: 'Jooji', checking: 'Gelitaanka ayaa la hubinayaa…' },
  zh: { title: '您无权访问此页面', needRoles: '需要以下任一角色：{roles}。', haveAccess: '如果您应当有权限，请登录—您将直接回到此页。', wrongPlace: '如果误入此处，请返回上一页或返回首页。', signIn: '我有权限—登录', goHome: '返回首页', cancel: '取消', checking: '正在检查权限…' },
  ja: { title: 'このページにはアクセスできません', needRoles: '次のいずれかのロールが必要です：{roles}。', haveAccess: 'アクセスできるはずなら、サインインしてください。すぐにここへ戻ります。', wrongPlace: '誤ってここに来た場合は、戻るかホームに戻ってください。', signIn: 'アクセスできる方はサインイン', goHome: 'ホームに戻る', cancel: 'キャンセル', checking: 'アクセスを確認しています…' },
  ko: { title: '이 페이지에 접근할 수 없습니다', needRoles: '다음 역할 중 하나가 필요합니다: {roles}.', haveAccess: '접근 권한이 있으면 로그인하세요 — 바로 여기로 돌아옵니다.', wrongPlace: '실수로 도착하셨다면 뒤로 가거나 홈 페이지로 돌아가세요.', signIn: '접근 권한이 있습니다 — 로그인', goHome: '홈 페이지로 가기', cancel: '취소', checking: '접근 권한 확인 중…' },
  hi: { title: 'यह पेज आपके लिए उपलब्ध नहीं है', needRoles: 'इसके लिए इन भूमिकाओं में से किसी एक की आवश्यकता है: {roles}.', haveAccess: 'अगर आपको एक्सेस होना चाहिए, तो साइन इन करें — आप सीधे यहीं वापस आ जाएंगे।', wrongPlace: 'यदि आप यहाँ गलती से आ गए हैं, तो पीछे जाएँ या होम पेज पर लौटें।', signIn: 'मेरे पास एक्सेस है — साइन इन करें', goHome: 'होम पेज पर जाएँ', cancel: 'रद्द करें', checking: 'एक्सेस की जाँच हो रही है…' },
  ur: { title: 'یہ صفحہ آپ کے لیے دستیاب نہیں', needRoles: 'اس کے لیے ان میں سے کسی ایک رول کی ضرورت ہے: {roles}۔', haveAccess: 'اگر آپ کو رسائی ہونی چاہیے تو سائن ان کریں — آپ سیدھا یہیں واپس آ جائیں گے۔', wrongPlace: 'اگر آپ یہاں غلطی سے آ گئے ہیں، تو پیچھے جائیں یا ہوم پیج پر جائیں۔', signIn: 'مجھے رسائی ہے — سائن ان کریں', goHome: 'ہوم پیج پر جائیں', cancel: 'منسوخ کریں', checking: 'رسائی چیک ہو رہی ہے…' },
  bn: { title: 'এই পেজটি আপনার জন্য খোলা নয়', needRoles: 'এটির জন্য এই ভূমিকাগুলোর যেকোনো একটি প্রয়োজন: {roles}.', haveAccess: 'আপনার অ্যাক্সেস থাকার কথা হলে, সাইন ইন করুন — আপনি সরাসরি এখানেই ফিরে আসবেন।', wrongPlace: 'ভুলবশত এখানে এলে, পেছনে যান বা হোম পেজে ফিরে যান।', signIn: 'আমার অ্যাক্সেস আছে — সাইন ইন করুন', goHome: 'হোম পেজে যান', cancel: 'বাতিল', checking: 'অ্যাক্সেস যাচাই করা হচ্ছে…' },
  te: { title: 'ఈ పేజీ మీకు అందుబాటులో లేదు', needRoles: 'దీనికి ఈ పాత్రల్లో కనీసం ఒకటి అవసరం: {roles}.', haveAccess: 'మీకు యాక్సెస్ ఉండాలని భావిస్తే, సైన్ ఇన్ చేయండి — మీరు వెంటనే ఇక్కడికే తిరిగి వస్తారు.', wrongPlace: 'ఇక్కడికి పొరపాటున వచ్చి ఉంటే, వెనక్కి వెళ్లండి లేదా హోమ్ పేజీకి వెళ్లండి.', signIn: 'నాకు యాక్సెస్ ఉంది — సైన్ ఇన్', goHome: 'హోమ్ పేజీకి వెళ్లండి', cancel: 'రద్దు', checking: 'యాక్సెస్‌ను తనిఖీ చేస్తున్నాం…' },
  mr: { title: 'हे पृष्ठ तुमच्यासाठी उपलब्ध नाही', needRoles: 'यासाठी यापैकी एखादी भूमिका आवश्यक आहे: {roles}.', haveAccess: 'तुम्हाला प्रवेश असायला हवा असल्यास, साइन इन करा — तुम्ही थेट इथे परत याल.', wrongPlace: 'चुकून इथे आलात तर मागे जा किंवा मुखपृष्ठावर परत जा.', signIn: 'मला प्रवेश आहे — साइन इन करा', goHome: 'मुखपृष्ठावर जा', cancel: 'रद्द करा', checking: 'प्रवेश तपासत आहोत…' },
  kn: { title: 'ಈ ಪುಟ ನಿಮಗೆ ಲಭ್ಯವಿಲ್ಲ', needRoles: 'ಈ ಪಾತ್ರಗಳಲ್ಲಿ ಯಾವುದಾದರೂ ಒಂದು ಬೇಕು: {roles}.', haveAccess: 'ನಿಮಗೆ ಪ್ರವೇಶ ಇದ್ದರೆ, ಸೈನ್ ಇನ್ ಮಾಡಿ — ನೀವು ನೇರವಾಗಿ ಇಲ್ಲಿಗೆ ಹಿಂದಿರುಗುತ್ತೀರಿ.', wrongPlace: 'ತಪ್ಪಾಗಿ ಇಲ್ಲಿ ಬಂದಿದ್ದರೆ, ಹಿಂದಿರುಗಿ ಅಥವಾ ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ.', signIn: 'ನನಗೆ ಪ್ರವೇಶ ಇದೆ — ಸೈನ್ ಇನ್ ಮಾಡಿ', goHome: 'ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ', cancel: 'ರದ್ದುಮಾಡಿ', checking: 'ಪ್ರವೇಶ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…' },
  gu: { title: 'આ પૃષ્ઠ તમારા માટે ઉપલબ્ધ નથી', needRoles: 'આ માટે આમાંથી કોઈ એક ભૂમિકા જોઈએ: {roles}.', haveAccess: 'જો તમને પ્રવેશ હોવો જોઈએ, તો સાઇન ઇન કરો — તમે સીધા અહીં પાછા આવશો.', wrongPlace: 'જો તમે અહીં ભૂલથી આવ્યા હો, તો પાછા જાઓ અથવા મુખ્ય પૃષ્ઠ પર પરત ફરો.', signIn: 'મને પ્રવેશ છે — સાઇન ઇન કરો', goHome: 'મુખ્ય પૃષ્ઠ પર જાઓ', cancel: 'રદ કરો', checking: 'પ્રવેશ તપાસી રહ્યા છીએ…' },
  ml: { title: 'ഈ പേജ് നിങ്ങൾക്ക് ലഭ്യമല്ല', needRoles: 'ഈ റോളുകളിൽ ഏതെങ്കിലും ഒന്ന് ആവശ്യമാണ്: {roles}.', haveAccess: 'നിങ്ങൾക്ക് ആക്സസ് ഉണ്ടാകേണ്ടതാണെങ്കിൽ, സൈൻ ഇൻ ചെയ്യുക — നിങ്ങൾ നേരെ ഇവിടേക്കു മടങ്ങിയെത്തും.', wrongPlace: 'തെറ്റിച്ച് ഇവിടെ എത്തിയതാണെങ്കിൽ, തിരികെ പോകുക അല്ലെങ്കിൽ ഹോം പേജിലേക്ക് മടങ്ങുക.', signIn: 'എനിക്ക് ആക്സസ് ഉണ്ട് — സൈൻ ഇൻ ചെയ്യുക', goHome: 'ഹോം പേജിലേക്ക് പോകുക', cancel: 'റദ്ദാക്കുക', checking: 'ആക്സസ് പരിശോധിക്കുന്നു…' },
  ta: { title: 'இந்தப் பக்கத்துக்கு உங்களுக்கு அணுகல் இல்லை', needRoles: 'இதற்கு இவற்றில் ஏதேனும் ஒரு பங்கு தேவை: {roles}.', haveAccess: 'உங்களுக்கு அணுகல் இருக்க வேண்டும் என்றால், உள்நுழையுங்கள் — நீங்கள் உடனே இங்கே திரும்புவீர்கள்.', wrongPlace: 'நீங்கள் தவறுதலாக இங்கே வந்திருந்தால், பின் செல்லுங்கள் அல்லது முகப்புப் பக்கத்திற்கு திரும்புங்கள்.', signIn: 'எனக்கு அணுகல் உள்ளது — உள்நுழையவும்', goHome: 'முகப்புப் பக்கத்திற்கு செல்லுங்கள்', cancel: 'ரத்து', checking: 'அணுகலைச் சரிபார்க்கிறது…' },
  ne: { title: 'यो पृष्ठ तपाईंका लागि खुला छैन', needRoles: 'यी भूमिकामध्ये कुनै एक चाहिन्छ: {roles}.', haveAccess: 'यदि तपाईंलाई पहुँच हुनुपर्ने हो भने, साइन इन गर्नुहोस् — तपाईं सिधै यतै फर्कनुहुनेछ.', wrongPlace: 'यदि तपाईं यहाँ गल्तीले आइपुग्नुभयो भने, पछाडि जानुहोस् वा गृहपृष्ठमा फर्किनुहोस्.', signIn: 'मसँग पहुँच छ — साइन इन गर्नुहोस्', goHome: 'गृहपृष्ठमा जानुहोस्', cancel: 'रद्द', checking: 'पहुँच जाँच्दै…' },
  vi: { title: 'Bạn không có quyền truy cập trang này', needRoles: 'Cần một trong các vai trò sau: {roles}.', haveAccess: 'Nếu bạn có quyền truy cập, hãy đăng nhập — bạn sẽ quay lại đây ngay.', wrongPlace: 'Nếu bạn vào đây nhầm, hãy quay lại hoặc về trang chủ.', signIn: 'Tôi có quyền truy cập — đăng nhập', goHome: 'Về trang chủ', cancel: 'Hủy', checking: 'Đang kiểm tra quyền truy cập…' },
  th: { title: 'คุณไม่มีสิทธิ์เข้าถึงหน้านี้', needRoles: 'ต้องมีหนึ่งในบทบาทเหล่านี้: {roles}.', haveAccess: 'ถ้าคุณควรเข้าถึงได้ ให้ลงชื่อเข้าใช้ — คุณจะกลับมาที่นี่ทันที.', wrongPlace: 'ถ้ามาถึงที่นี่โดยบังเอิญ ให้ย้อนกลับหรือไปที่หน้าแรก.', signIn: 'ฉันมีสิทธิ์ — ลงชื่อเข้าใช้', goHome: 'ไปที่หน้าแรก', cancel: 'ยกเลิก', checking: 'กำลังตรวจสอบสิทธิ์การเข้าถึง…' },
  id: { title: 'Anda tidak dapat mengakses halaman ini', needRoles: 'Diperlukan salah satu peran berikut: {roles}.', haveAccess: 'Jika Anda seharusnya memiliki akses, masuk — Anda akan langsung kembali ke sini.', wrongPlace: 'Jika Anda tiba di sini tanpa sengaja, kembali atau buka halaman beranda.', signIn: 'Saya memiliki akses — masuk', goHome: 'Ke beranda', cancel: 'Batal', checking: 'Memeriksa akses…' },
  ms: { title: 'Halaman ini tidak tersedia untuk anda', needRoles: 'Memerlukan salah satu peranan berikut: {roles}.', haveAccess: 'Jika anda sepatutnya mempunyai akses, log masuk — anda akan kembali terus ke sini.', wrongPlace: 'Jika anda tiba di sini secara tidak sengaja, kembali atau pergi ke laman utama.', signIn: 'Saya ada akses — log masuk', goHome: 'Pergi ke laman utama', cancel: 'Batal', checking: 'Menyemak akses…' },
  tl: { title: 'Wala kang access sa pahinang ito', needRoles: 'Kailangan ang isa sa mga role na ito: {roles}.', haveAccess: 'Kung dapat may access ka, mag-sign in — babalik ka agad dito.', wrongPlace: 'Kung napunta ka rito nang hindi sinasadya, bumalik o pumunta sa home page.', signIn: 'May access ako — mag-sign in', goHome: 'Pumunta sa home page', cancel: 'Kanselahin', checking: 'Sinusuri ang access…' },
  my: { title: 'This page is not open to you', needRoles: 'It requires one of these roles: {roles}.', haveAccess: 'If you should have access, sign in — you will come straight back here.', wrongPlace: 'If you landed here by accident, go back or return to the home page.', signIn: 'I have access — sign in', goHome: 'Go to the home page', cancel: 'Cancel', checking: 'Checking access…' },
  km: { title: 'អ្នកមិនមានសិទ្ធិមើលទំព័រនេះទេ', needRoles: 'ត្រូវការតួនាទីណាមួយក្នុងចំណោមទាំងនេះ: {roles}.', haveAccess: 'បើអ្នកគួរមានសិទ្ធិ សូមចូល — អ្នកនឹងត្រឡប់មកទីនេះភ្លាមៗ។', wrongPlace: 'បើអ្នកបានមកទីនេះដោយចៃដន្យ សូមត្រឡប់ក្រោយ ឬទៅទំព័រដើម។', signIn: 'ខ្ញុំមានសិទ្ធិ — ចូល', goHome: 'ទៅទំព័រដើម', cancel: 'បោះបង់', checking: 'កំពុងពិនិត្យសិទ្ធិ…' },
  lo: { title: 'ໜ້ານີ້ບໍ່ໃຫ້ທ່ານເຂົ້າເຖິງ', needRoles: 'ຕ້ອງມີໜຶ່ງໃນບົດບາດເຫຼົ່ານີ້: {roles}.', haveAccess: 'ຖ້າທ່ານຄວນມີສິດ, ເຂົ້າລະບົບ — ຈະກັບມາທີ່ນີ້ທັນທີ.', wrongPlace: 'ຖ້າມາຮອດນີ້ໂດຍບັງເອີນ, ກັບຄືນ ຫຼື ກັບໄປໜ້າຫຼັກ.', signIn: 'ຂ້ອຍມີສິດ — ເຂົ້າລະບົບ', goHome: 'ໄປທີ່ໜ້າຫຼັກ', cancel: 'ຍົກເລີກ', checking: 'ກຳລັງກວດສອບສິດ…' },
}

export function accessGateUi(lang: string): AccessGateUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
